- src/condor_tests/test_xfer_stats_overflow_regression.py
> HTCONDOR-1772: Fix xfer stats overflow test failure

- docs/admin-manual/configuration-macros.rst
- docs/version-history/lts-versions-10-0.rst
- src/condor_examples/condor_config.generic.debian.patch
- src/condor_examples/condor_config.generic.rpm.patch
- src/condor_master.V6/master.cpp
- src/condor_utils/param_info.in
> HTCONDOR-1757 scitokens cache

- src/condor_scripts/CheckOutputFormats.pm
- src/condor_tests/cmd_drain_scavenging.run
- src/condor_tests/test_allowed_job_duration.py
- src/condor_tests/test_condor_now.py
- src/condor_tests/test_custom_machine_resource.py
- src/condor_tests/test_custom_machine_resource_instances.py
- src/condor_utils/print_format_tables.cpp
> Backport Test fixes

- docs/version-history/feature-versions-10-x.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_starter.V6.1/vanilla_proc.h
> HTCONDOR-1775-cgroup-v2-32bit

- docs/version-history/feature-versions-10-x.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_starter.V6.1/vanilla_proc.h
> HTCONDOR-1775-cgroup-v2-32bit (10.5.0 cherry-pick)

- src/python-bindings/classad_python_user.cpp
> HTCONDOR-1777-remove-py-set-programname

- docs/version-history/feature-versions-10-x.rst
- src/condor_utils/condor_regex.cpp
> HTCONDOR-1774: CE audit plugin fix

- src/python-bindings/classad_parsers.cpp
- src/python-bindings/credd.cpp
> HTCONDOR-1768 fix python warnings

- docs/version-history/lts-versions-10-0.rst
- src/python-bindings/negotiator.cpp
> HTCONDOR-1780 python acct ads

- src/condor_schedd.V6/schedd.cpp
- src/condor_tools/qusers.cpp
> HTCONDOR-1768 fix warnings

- docs/version-history/feature-versions-10-x.rst
- src/condor_schedd.V6/schedd.cpp
- src/condor_tools/qusers.cpp
- src/condor_tools/ssh_to_job.cpp
> V10_6-HTCONDOR-1782-no-control-master-for-ssh-to-job

- src/condor_unit_tests/FTEST_your_string.cpp
- src/condor_unit_tests/unit_test_utils.cpp
- src/condor_unit_tests/unit_test_utils.h
- src/condor_utils/test_user_mapping.cpp
> HTCONDOR-1768-cleanup-tests

- docs/version-history/feature-versions-10-x.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_utils/proc_family_direct_cgroup_v1.cpp
> HTCONDOR-1786-no-blkio-cgroup

- docs/admin-manual/configuration-macros.rst
- docs/version-history/lts-versions-10-0.rst
- src/condor_io/condor_auth_ssl.cpp
- src/condor_utils/param_info.in
> HTCONDOR-1781 ssl-proxy

- docs/admin-manual/configuration-macros.rst
- docs/version-history/lts-versions-10-0.rst
- src/condor_io/condor_auth_ssl.cpp
- src/condor_utils/param_info.in
> HTCONDOR-1781 ssl proxy

- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_ft-gahp/io_loop.cpp
- src/condor_io/condor_crypt.cpp
- src/condor_io/condor_secman.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_utils/AWSv4-utils.cpp
- src/condor_utils/data_reuse.cpp
Mostly replacing sprintf with snprintf and initializing classad attribute lookup locals
> V10_6-HTCONDOR-1768-fix-clang-warnings

- build/cmake/CondorConfigure.cmake
- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-10-x.rst
- src/arc_gahp/io_loop_pthread.cpp
- src/condor_gridmanager/arcjob.cpp
- src/condor_gridmanager/arcjob.h
- src/condor_gridmanager/arcresource.cpp
- src/condor_gridmanager/arcresource.h
- src/condor_gridmanager/gahp-client.h
- src/condor_includes/config.h.cmake
- src/condor_utils/param_info.in
> HTCONDOR-1778 arc-gahp-memory-leak

- src/condor_tests/test_activation_metrics.py
By polling and retrying if the job ad attribute CompletionDate is missing
> HTCONDOR-1773-test_activation_metrics

- docs/version-history/feature-versions-10-x.rst
- src/condor_starter.V6.1/starter.cpp
being written into the sandbox
> HTCONDOR-1794-sandbox-job-ad

- src/condor_starter.V6.1/starter.cpp
being written into the sandbox
> HTCONDOR-1737 Fix bug that prevented .job.ad and .machine.ad files

- docs/version-history/lts-versions-10-0.rst
> HTCONDOR-1658: version history

- src/condor_tests/test_condor_history.py
> HTCONDOR-1788: Fix condor_history test

- docs/version-history/feature-versions-10-x.rst
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_utils/proc_family_direct_cgroup_v1.cpp
> HTCONDOR-1801 cgroup v1 on el7

- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_utils/proc_family_direct_cgroup_v1.cpp
> HTCONDOR-1801: Cherry-pick back to 10.5.0 branch

- docs/version-history/lts-versions-10-0.rst
- src/condor_utils/condor_scitokens.cpp
- src/condor_utils/param_info.in
> HTCONDOR-1757 scitokens cache config

- docs/version-history/lts-versions-10-0.rst
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_json_toe_when.py
- src/condor_utils/ToE.cpp
> HTCONDOR-1763  Make ToE.When an integer even in JSON

- src/condor_utils/proc_family_proxy.cpp
> HTCONDOR-1808-ssh-to-docker-uni

- src/condor_utils/proc_family_proxy.cpp
> HTCONDOR-1808 Fix recent regression with ssh-to-job and docker universe

- src/condor_tests/cmd_submit_factory_regress_dry.run
- src/condor_tests/cmd_submit_regress_dry.run
So they don't clobber each other
> HTCONDOR-1811 give cmd_submit-regress tests their own scratch dirs

- src/gpu/cuda_device_enumeration.h
- src/gpu/cuda_header_doc.h
And give us a better chance of working on ppc, arm and other architectures with stricter alignment requirements
> HTCONDOR-1768 fix clang alignment warning

- bindings/python/htcondor/__init__.py
- docs/version-history/lts-versions-10-0.rst
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_python_bindings_version.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1813
> HTCONDOR-1813 Fix htcondor.__version__

- .github/pull_request_template.md
> Add documentation build logs link to PR template

- src/condor_utils/cred_dir.h
> HTCONDOR-1453 fix-creddata

- docs/codes-other-values/glossary.rst
- docs/index.rst
> HTCONDOR-1802 First pass at adding limited glossary to manual

- src/condor_scripts/upgrade9to10checks.py
> HTCONDOR-1658: Final reviews for upgrade checking script

- src/classad/xmlSource.cpp
- src/condor_io/sock.cpp
- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_utils/file_transfer.cpp
- src/condor_utils/xform_utils.cpp
- src/gpu/cuda_device_enumeration.cpp
- src/gpu/simulated_device_enumeration.cpp
> HTCONDOR-1768-sprintf-rm

- src/condor_tests/test_checkpoint_destination.py
By allowing .update.ad.tmp to be a valid file in the checkpoint dir
> HTCONDOR-1815-fix-test-checkpoint-dest

- src/condor_tests/test_condor_history.py
> HTCONDOR-1768: test_condor_history reconfig schedd only

- src/condor_dagman/dagman_classad.cpp
- src/condor_gridmanager/gahp-client.h
- src/condor_job_router/submit_job.cpp
- src/condor_prio/prio.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_tools/config_val.cpp
- src/gpu/cuda_device_enumeration.cpp
- src/gpu/simulated_device_enumeration.cpp
> HTCONDOR-1768 more-coverity

- src/condor_includes/condor_commands.h
replace with const int.  Ultimately, should namespaces these.
> HTCONDOR-1818-replace-pound-defines

- src/condor_q.V6/queue.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_sysapi/idle_time.cpp
- src/condor_tests/x_complete_params.cpp
- src/condor_tests/x_job_mem_checker.c
- src/condor_utils/access_euid.unix.cpp
- src/condor_utils/submit_utils.cpp
- src/gangliad/gangliad.cpp
- src/gangliad/gangliad.h
> HTCONDOR-1768-sprintf-warnings

- src/condor_startd.V6/command.cpp
> HTCONDOR-1768 fix recently introduced unused variable warning

- docs/version-history/feature-versions-10-x.rst
- src/blahp/src/scripts/slurm_ping.sh
> HTCONDOR-1826 slurm squeue me

- src/condor_utils/compat_classad.cpp
- src/condor_utils/test_classad_funcs.cpp
> HTCONDOR-1817 fix merge conflicts

- src/condor_daemon_core.V6/pipe.WINDOWS.cpp
> HTCONDOR-1834-better-pipe-debugging

- docs/users-manual/container-universe-jobs.rst
- docs/version-history/feature-versions-10-x.rst
- src/condor_tests/test_container_img_declares_universe.py
- src/condor_utils/submit_utils.cpp
- src/condor_utils/submit_utils.h
> HTCONDOR-1820 container uni xfer

- docs/man-pages/condor_submit.rst
- docs/version-history/feature-versions-10-x.rst
- src/condor_utils/submit_utils.cpp
> HTCONDOR-1836 add new submit file macro $(JobId)

- src/condor_scripts/condor_upgrade_check
-Fixed bug in PCRE2 check where the python split() would split
up regular expressions with spaces and only hand over part of
the regex.
-Made it so that using -ce only checks the HTCONDOR-CE system
-Made it possible for script flags to use - or --
> HTCONDOR-1840: 9 to 10 incompatibilities script issues

- docs/version-history/lts-versions-10-0.rst
- src/condor_ft-gahp/io_loop.cpp
- src/condor_gridmanager/infnbatchjob.cpp
- src/condor_gridmanager/infnbatchjob.h
> HTCONDOR-1560 blahp remote iwd 2

- src/condor_sysapi/processor_flags.cpp
- src/condor_utils/condor_snutils.cpp
- src/condor_utils/config.cpp
- src/condor_utils/file_transfer.cpp
- src/condor_utils/file_transfer.h
- src/condor_utils/make_printmask.cpp
- src/condor_utils/proc_family_interface.cpp
- src/condor_utils/ranger.cpp
> HTCONDOR-1768 remove sprintfs to make mac compiler happy

- docs/man-pages/condor_qusers.rst
- docs/version-history/feature-versions-10-x.rst
- src/condor_includes/condor_attributes.h
- src/condor_includes/condor_qmgr.h
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/qmgmt.h
- src/condor_schedd.V6/qmgmt_receivers.cpp
- src/condor_schedd.V6/qmgmt_send_stubs.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_submit.V6/submit.cpp
- src/condor_submit.V6/submit_internal.h
- src/condor_submit.V6/submit_simulate.cpp
- src/condor_tools/qusers.cpp
- src/condor_utils/CondorError.cpp
- src/condor_utils/submit_protocol.cpp
- src/condor_utils/submit_protocol.h
> HTCONDOR-1835 branch

- docs/version-history/lts-versions-10-0.rst
- src/condor_examples/condor-annex-ec2.service
- src/condor_examples/condor.service
> HTCONDOR-1829: Backport systemd waits for SSSD

- docs/admin-manual/configuration-macros.rst
- docs/version-history/stable-release-series-90.rst
- src/condor_io/condor_auth_ssl.cpp
- src/condor_utils/param_info.in
> HTCONDOR-1848 x509 proxy ssl auth

- src/condor_submit.V6/submit_simulate.cpp
- src/condor_utils/dprintf.cpp
> HTCONDOR-1856-fix-warnings

- docs/version-history/lts-versions-10-0.rst
- src/condor_io/condor_auth_ssl.cpp
> HTCONDOR-1866 ssl-proxy-identity

- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/schedd.cpp
> HTCONDOR-1865 Knobs to control if OwnerCheck is fully qualified

- src/condor_tests/test_checkpoint_destination.py
We see intermittent failures in the test_checkpoint_destination test. Turns out this is because we run cp -a . {save_directory} in the execute scratch dir, and this cp command occasionally fails with
/bin/cp: cannot stat './.update.ad.tmp': No such file or directory
This is because there is a race condition with the startd which writes to .update.ad.tmp, and renames it, and cp -a is a two pass algorithm. We then see unexpected output in stderr, which breaks the test.  Let’s fix the test by just redirecting the stderr of the cp command to /dev/null
- If the pull request is approved, …
> HTCONDOR-1871 fix race condition in test_checkpoint_destination

- src/condor_daemon_core.V6/pipe.WINDOWS.cpp
> HTCONDOR-1872 fix hang in windows pipe code when far side closes

- docs/version-history/feature-versions-10-x.rst
- src/condor_tools/preen.cpp
> HTCONDOR-1874 preen no rm offline ads

- src/condor_tests/config_validate_policy_templates.run
tests
to be consistent with other test timeouts.
(Still disturbingly too high).
> HTCONDOR-1877-increase-personal-condor-startup-timeout-in-test

- src/condor_utils/classadHistory.cpp
- src/condor_utils/proc_family_interface.cpp
> HTCONDOR-1856 warnings

- docs/version-history/lts-versions-10-0.rst
- src/condor_io/condor_auth_passwd.cpp
> HTCONDOR-1776 idtokens-logging

- docs/version-history/lts-versions-10-0.rst
- src/condor_tools/preen.cpp
> HTCONDOR-1874 preen should not remove $(COLLECTOR_PERSISTENT_ADS)

- src/condor_starter.V6.1/os_proc.cpp
- src/condor_starter.V6.1/os_proc.h
- src/condor_starter.V6.1/sshd_proc.h
- src/condor_tests/cmd_ssh_to_job_van.run
> HTCONDOR-1227 fix condor_ssh_to_job with condor_exec.exe renaming

- docs/version-history/lts-versions-10-0.rst
- src/condor_scripts/condor_remote_cluster
Let curl print error messages for the user to see.
> HTCONDOR-1884 Improve error messages for condor_remote_cluster

- src/condor_tools/htcondor_cli/eventlog.py
> HTCONDOR-1849 Added groupby flag

- docs/man-pages/condor_config_val.rst
- docs/version-history/lts-versions-10-0.rst
- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_includes/condor_config.h
- src/condor_tools/config_val.cpp
- src/condor_utils/condor_config.cpp
> HTCONDOR-1879 add remote query support to condor_config_val -summary

- bindings/python/htcondor/__init__.py
- bindings/python/htcondor/_deprecation.py
- src/condor_tests/test_htcondor_cli.py
- src/condor_tools/htcondor_cli/job.py
This actually branched from `V10_7-HTCONDOR-1868-branch`, but should merge cleanly to `main` after that branch is merged.
> HTCONDOR-1887 Remove deprecated calls in htcondor_cli.

- bindings/python/htcondor/__init__.py
- bindings/python/htcondor/_deprecation.py
- src/condor_tests/test_htcondor_cli.py
> HTCONDOR-1868 Add in-code deprecation warnings for newly-documented deprecations.

- docs/classads/classad-mechanism.rst
- docs/version-history/feature-versions-10-x.rst
> HTCONDOR-1817 docs for stringListSubsetMatch

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/daemoncore.rst
- docs/admin-manual/policy-configuration.rst
- docs/admin-manual/security.rst
- docs/admin-manual/setting-up-special-environments.rst
- docs/classad-attributes/job-classad-attributes.rst
- docs/classad-attributes/machine-classad-attributes.rst
- docs/codes-other-values/condor_shadow-exit-codes.rst
- docs/codes-other-values/job-event-log-codes.rst
- docs/man-pages/condor_drain.rst
- docs/man-pages/condor_off.rst
- docs/man-pages/condor_submit.rst
- docs/man-pages/condor_userlog.rst
- docs/man-pages/condor_vacate.rst
- docs/platform-specific/microsoft-windows.rst
- docs/users-manual/managing-a-job.rst
- docs/users-manual/matchmaking-with-classads.rst
- docs/users-manual/submitting-a-job.rst
- docs/version-history/feature-versions-10-x.rst
> HTCONDOR-1839  Remove standard-universe checkpointing refernces from the manual.

- docs/version-history/feature-versions-10-x.rst
> HTCONDOR-1821: version history

- src/condor_tools/htcondor_cli/eventlog.py
> Htcondor 1849

- src/condor_utils/submit_utils.cpp
> HTCONDOR-1820 container_universe submit requirements generation

- src/condor_daemon_core.V6/daemon_core.cpp
> HTCONDOR-1898 Better WIndows shutdown logging and debugging

- src/condor_tests/job_core_niceuser_van.run
> HTCONDOR-1853 Before restarting the negotiator, verify all submitter ads

- build/cmake/CondorConfigure.cmake
- src/condor_gridmanager/arcjob.cpp
- src/condor_includes/config.h.cmake
Also fix up the use of CURL_USES_NSS in the C++ code.
> HTCONDOR-1778 Move CURL_USES_NSS test to linux block in cmake

- docs/version-history/lts-versions-10-0.rst
- src/condor_tools/preen.cpp
> V10_0-HTCONDOR-1906-preen-no-rm-lost-found

- docs/users-manual/quick-start-guide.rst
> HTCONDOR-1870 add job nature docs

- docs/users-manual/quick-start-guide.rst
> HTCONDOR-1870  Even better job nature docs

- src/condor_tests/test_htcondor_736.py
> HTCONDOR-1905-fix-test-htcondor-736

- src/condor_tools/htcondor_cli/eventlog.py
> V10 7 htcondor 1886 htcondor cli eventlog second merge

- src/condor_utils/condor_config.cpp
> HTCONDOR-1907 fix for int truncation of param table default values

- src/blahp/src/CMakeLists.txt
- src/condor_examples/CMakeLists.txt
- src/condor_scripts/CMakeLists.txt
> HTCONDOR-1911 only set execute permission bits on files that need them

- docs/admin-manual/configuration-macros.rst
- docs/classad-attributes/scheduler-classad-attributes.rst
- docs/extensions/macro.py
- docs/man-pages/condor_dagman.rst
- docs/man-pages/condor_submit_dag.rst
- src/condor_dagman/condor_submit_dag.cpp
- src/condor_dagman/dagman_main.cpp
> HTCONDOR-1893 update DAGMan command docs branch

- docs/version-history/feature-versions-10-x.rst
- src/condor_utils/proc_family_direct_cgroup_v1.cpp
> HTCONDOR-1920-cgroup-v1-cpu-usage

- src/condor_gridmanager/arcjob.cpp
- src/condor_gridmanager/arcresource.cpp
- src/condor_gridmanager/azurejob.cpp
- src/condor_gridmanager/azureresource.cpp
- src/condor_gridmanager/basejob.cpp
- src/condor_gridmanager/basejob.h
- src/condor_gridmanager/baseresource.cpp
- src/condor_gridmanager/baseresource.h
- src/condor_gridmanager/condorjob.cpp
- src/condor_gridmanager/condorresource.cpp
- src/condor_gridmanager/ec2job.cpp
- src/condor_gridmanager/ec2resource.cpp
- src/condor_gridmanager/gcejob.cpp
- src/condor_gridmanager/gceresource.cpp
- src/condor_gridmanager/gridmanager.cpp
- src/condor_includes/condor_attributes.h
- src/condor_negotiator.V6/matchmaker.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_schedd.V6/schedd_negotiate.cpp
- src/condor_tests/cmd_submit_regress_dry.expect
- src/condor_utils/submit_utils.cpp
> HTCONDOR-1925 remove-grid-matchmaking

- docs/admin-manual/configuration-macros.rst
> HTCONDOR-1876 document START_VANILLA_UNIVERSE

- docs/codes-other-values/glossary.rst
> HTCONDOR-1928-add-workflow-to-glossary

- docs/version-history/feature-versions-10-x.rst
- src/condor_tools/preen.cpp
> HTCONDOR-1933-preen-preserve-offlinelog

- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_ft_plugin_testing.py
Ornithology test to show correct functionality of file transfer plugin testing mode and updates to 'condor_starter -classad' output.
> HTCONDOR-1709 Created test for file transfer plugin testing

- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_utils/perf_counter.linux.cpp
- src/condor_utils/perf_counter.linux.h
> HTCONDOR-1925 fix warnings

- src/condor_tests/test_singularity_sif.py
> HTCONDOR-1944-robustify-test-singularity

- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/ResMgr.h
- src/condor_startd.V6/Resource.cpp
- src/condor_startd.V6/Starter.cpp
- src/condor_startd.V6/claim.cpp
- src/condor_startd.V6/claim.h
- src/condor_startd.V6/command.cpp
> HTCONDOR-1925 claim-client-cleanup

- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_daemon_core.V6/daemon_core_main.cpp
> HTCONDOR-1943 better DaemonCore handling of exited but unreaped children

- docs/version-history/lts-versions-10-0.rst
- src/condor_schedd.V6/transfer_queue.cpp
- src/condor_schedd.V6/transfer_queue.h
> V10_0-HTCONDOR-1937-no-xfer-queue-spam

- docs/version-history/feature-versions-10-x.rst
- src/condor_dagman/job.cpp
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_dagman_futile_nodes_efficiency.py
> HTCONDOR-1945: dag man futile nodes inefficiency branch

- src/condor_utils/email_cpp.cpp
> HTCONDOR-1947-job-email-notification-default

- docs/admin-manual/configuration-macros.rst
- docs/users-manual/file-transfer.rst
> HTCONDOR-1708: Documentation for file transfer plugin testing

- docs/version-history/feature-versions-10-x.rst
- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_schedd.V6/dedicated_scheduler.h
- src/condor_utils/condor_event.cpp
> HTCONDOR-1952-parallel-uni-assertion

- src/condor_schedd.V6/qmgr_lib_support.cpp
> HTCONDOR-1925-fix-warning

- build/packaging/rpm/condor.spec
> HTCONDOR-1953-remove-openstack-build-warning

- src/condor_utils/test_user_mapping.cpp
only seen with newer g++ versions
> V10_8-HTCONDOR-1925-fix-segfault-user-map-test

- docs/version-history/feature-versions-10-x.rst
- src/condor_dagman/dag.cpp
- src/condor_dagman/dag.h
- src/condor_dagman/dagman_main.cpp
> HTCONDOR-1950: DAGMan use condor_rm's reason flag

- docs/man-pages/condor_token_list.rst
> add -dir switch to documentation

- docs/version-history/feature-versions-10-x.rst
- src/condor_schedd.V6/schedd.cpp
- src/condor_utils/param_info.in
- src/condor_utils/write_user_log.cpp
- src/condor_utils/write_user_log.h
> HTCONDOR-1550-no-fsync-userlog

- docs/admin-manual/configuration-macros.rst
- docs/automated-workflows/dagman-job-ad-attrs.rst
- docs/full_conf.py
- docs/version-history/feature-versions-10-x.rst
- src/condor_dagman/parse.cpp
- src/condor_tests/test_dagman_proper_env.py
- src/condor_utils/dagman_utils.cpp
- src/condor_utils/dagman_utils.h
-Added ndew command (ENV) that can GET variables from the submit
time environment ot carry over into the DAGMan jobs env or SET
explicit key=value pairs of information into the DAGMan jobs env.
-Extended base list of getenv variables for the .condor.sub file
to include needed scitoken variables
- BEARER_TOKEN
- BEARER_TOKEN_FILE - XDG_RUNTIME_DIR -Expanded test_dagman_proper_env test to included testing new command
and know about the expanded base vars for getenv
-Also cleaned up code in dagman utils for processing the DAG file
for submit time commands
- If the pull request is …
> HTCONDOR-1955: Added new DAGMan ENV command

- docs/automated-workflows/dagman-interaction.rst
- docs/classad-attributes/job-classad-attributes.rst
- docs/version-history/feature-versions-10-x.rst
- src/condor_dagman/dagman_classad.cpp
- src/condor_includes/condor_attributes.h
- src/condor_tests/job_dagman_classad-node.pl
- src/condor_tools/htcondor_cli/__init__.py
- src/condor_tools/htcondor_cli/dagman.py
-Improved output for htcondor dag status command
-Added new DAGMan classad attribute DAG_AdUpdateTime that is
a timestamp of when the DAGMan job ad was last updated by the
DAGMan process
> HTCONDOR-1951: Improve htcondor dag status

- src/condor_tests/test_dagman_futile_nodes.py
> HTCONDOR-1925: Add assert to DAGMan futile nodes test

- docs/admin-manual/user-priorities-negotiation.rst
- docs/classad-attributes/scheduler-classad-attributes.rst
- docs/man-pages/condor_submit.rst
> seperate -> separate

- build/nmi-build/build-batlab-images.sh
- build/nmi-build/setup.sh
- build/packaging/rpm/condor.spec
- nmi_tools/glue/SubmitInfo.pm
- nmi_tools/nmi-build-platforms
> HTCONDOR-1854: Add Fedora 38

- src/condor_utils/docker-api.cpp
> HTCONDOR-1925 Fix typo in dprintf message

- docs/version-history/lts-versions-10-0.rst
- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_schedd.V6/dedicated_scheduler.h
> HTCONDOR-1959-backport-parallel-uni-changes

- src/condor_tests/cmd_status-compact.run
This test submits a job, polls condor_status -schedd until the JobsRunning attribute is non-zero, and analyzes the output of condor_status -schedd.
Then it removes the job
In a subsequent phase, it also submits a job, polls condor_status -schedd
until the the schedd ad reports nonzero JobsRunning, then runs condor_status again to verify.
There is a race condition here, where the first phase succeeds, and the test removes the job, but the schedd ad hasn't made it to the collector yet.  We submit the second job, and though it hasn't started, our polling of condor_status -schedd succeeds with the stale info.  Between that time and the next run of condor_status, the schedd updates its ad with 0 jobs running to the collector, and hasn't gotten around to starting the second job
In this case the …
> HTCONDOR-1925 Robustify cmd_status-compact test

- docs/version-history/feature-versions-10-x.rst
- src/condor_submit.V6/submit.cpp
- src/condor_tools/store_cred_main.cpp
- src/condor_utils/store_cred.cpp
- src/condor_utils/store_cred.h
- src/condor_utils/uids.windows.credd.cpp
- src/python-bindings/credd.cpp
> HTCONDOR-1587 store-cred-pool-passwd-2

- src/condor_tests/cmd_condor_submit_dashspool.run
cmd_condor_submit_dashspool test
by removing a superflous condor_submit that wasn't really testing much of anything
> HTCONDOR-1925 robustify intermittently failing

- src/condor_schedd.V6/ExampleClassAdLogPlugin.cpp
- src/condor_schedd.V6/ExampleScheddPlugin.cpp
- src/condor_schedd.V6/autocluster.cpp
- src/condor_schedd.V6/grid_universe.cpp
- src/condor_schedd.V6/ickpt_share.cpp
- src/condor_schedd.V6/job_transforms.cpp
- src/condor_schedd.V6/jobsets.cpp
- src/condor_schedd.V6/jobsets.h
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/qmgmt.h
- src/condor_schedd.V6/qmgmt_common.cpp
- src/condor_schedd.V6/qmgmt_factory.cpp
- src/condor_schedd.V6/qmgmt_receivers.cpp
- src/condor_schedd.V6/qmgmt_send_stubs.cpp
- src/condor_schedd.V6/qmgr_job_updater.cpp
- src/condor_schedd.V6/qmgr_lib_support.cpp
- src/condor_schedd.V6/schedd_cron_job_mgr.cpp
- src/condor_schedd.V6/schedd_main.cpp
- src/condor_schedd.V6/schedd_negotiate.cpp
- src/condor_schedd.V6/schedd_stats.cpp
- src/condor_schedd.V6/transfer_queue.cpp
- src/condor_schedd.V6/transfer_queue.h
Run clang-tidy on the schedd source files, but not schedd.cpp or ded_sched yet. This
Replaces NULL with nullptr
Initializes all locals with sensible values
Uses range based for loops where appropriate
const-ifies things that could be const
> HTCONDOR-1925 clang-tidy schedd helper sources

- docs/version-history/lts-versions-10-0.rst
- src/condor_scripts/adstash/interfaces/elasticsearch.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1930 as reported by @astroclark.
Cherry-picks 98ec502e81267d3f18eb43b89d8b09c8aeabeabf from https://github.com/htcondor/htcondor/pull/1628, fixes some additional, related buggy code, and adds version history. Thanks again @mschnepf!
> HTCONDOR-1930 Fix unexpected keyword argument in adstash

- docs/version-history/lts-versions-10-0.rst
- src/condor_scripts/adstash/interfaces/elasticsearch.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1964
Cherry-picks dc92674976be6c4002cb5df0ce169c07e1e82963 from https://github.com/htcondor/htcondor/pull/1628 and adds version history. Thanks @mschnepf!
> HTCONDOR-1964 Fix version check for older ES libraries

- docs/version-history/lts-versions-10-0.rst
- src/condor_scripts/adstash/interfaces/registry.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1965
Cherry-picks 48e1474f5e2c195180ef3a982c861fe805218738 from https://github.com/htcondor/htcondor/pull/1628 and adds version history. Thanks @mschnepf!
> HTCONDOR-1965 Fix OpenSearch import in adstash

- docs/version-history/feature-versions-10-x.rst
- src/condor_status.V6/prettyPrint.cpp
- src/condor_status.V6/prettyPrint.h
- src/condor_status.V6/setflags.cpp
- src/condor_status.V6/status.cpp
- src/condor_tests/CheckOutputFormats.pm
- src/condor_tests/cmd_status-compact.run
- src/condor_tests/cmd_status-transform.run
- src/condor_tests/testoverride.not
- src/condor_utils/ad_printmask.h
- src/condor_utils/generic_query.cpp
- src/condor_utils/generic_query.h
- src/condor_utils/status_types.h
- src/condor_utils/totals.cpp
- src/condor_utils/totals.h
> HTCONDOR-1958 Add -gpus option to condor_status

- src/condor_scripts/get_htcondor
> HTCONDOR-1962 get-htcondor-bugs

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-10-x.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_utils/param_info.in
> HTCONDOR-1974 make CGROUP_MEMORY_LIMIT_POLICY = hard the default

- src/condor_starter.V6.1/NTsenders.cpp
- src/condor_starter.V6.1/NTsenders.h
- src/condor_starter.V6.1/io_proxy_handler.cpp
- src/condor_starter.V6.1/jic_shadow.cpp
> HTCONDOR-1925 starter-except

- docs/version-history/feature-versions-10-x.rst
- src/condor_schedd.V6/schedd.cpp
- src/condor_shadow.V6.1/remoteresource.cpp
- src/condor_startd.V6/Starter.cpp
> V10_8-HTCONDOR-1979-fix-ssh_to_job

- src/condor_shadow.V6.1/ShadowHookMgr.h
- src/condor_tests/test_shadow_hook.py
> HTCONDOR-1915: fixed bug with shadow hook keyword in config file

- build/packaging/debian/control.in
- build/packaging/debian/htcondor-dev.install
- build/packaging/debian/htcondor.install.in
- build/packaging/debian/libclassad-dev.install
- build/packaging/debian/libclassad16.install
- build/packaging/rpm/condor.spec
- src/blahp/config/CMakeLists.txt
- src/classad/CMakeLists.txt
- src/classad/how_to_edit_classad_version.txt
> HTCONDOR-1981: Fold classad library into main package

- build/packaging/rpm/condor.spec
- src/blahp/config/CMakeLists.txt
> HTCONDOR-1981: Simplify RPM (fold in blahp, procd)

- .gitignore
- docs/classads/classad-mechanism.rst
- src/condor_tests/ornithology-docs/source/guides/getting-started.rst
> V10 8 htcondor 1925 minor typos

- src/condor_scripts/CMakeLists.txt
> HTCONDOR-1984  This should fix the problem.

- src/blahp/CMakeLists.txt
- src/blahp/config/CMakeLists.txt
- src/blahp/doc/CMakeLists.txt
- src/blahp/src/CMakeLists.txt
> HTCONDOR-1925 remove cmake warnings by upping minimum to 3.16 in blahp

- docs/version-history/lts-versions-10-0.rst
- src/condor_procd/proc_family.cpp
- src/condor_starter.V6.1/cgroup.linux.cpp
- src/condor_starter.V6.1/cgroup_limits.cpp
> HTCONDOR-1985: remove cgroup v1 blkio

- docs/man-pages/condor_adstash.rst
- docs/man-pages/condor_check_password.rst
- docs/man-pages/condor_configure.rst
- docs/man-pages/condor_install.rst
- docs/man-pages/condor_qusers.rst
- docs/man-pages/condor_submit.rst
- docs/man-pages/condor_updates_stats.rst
- docs/man-pages/get_htcondor.rst
> HTCONDOR-1986 fix double dash options

- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_includes/basename.h
- src/condor_includes/sock.h
- src/condor_io/sock.cpp
- src/condor_sysapi/arch.cpp
- src/condor_utils/basename.cpp
- src/condor_utils/compat_classad.cpp
- src/condor_utils/compat_classad.h
- src/condor_utils/compat_classad_util.cpp
- src/condor_utils/compat_classad_util.h
- src/condor_utils/condor_pidenvid.cpp
> HTCONDOR-1925 TRUE is true

- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_schedd.V6/dedicated_scheduler.h
> HTCONDOR-1925 clang-tidy ded sched

- docs/man-pages/htcondor.rst
and tidy up this man page in general
> HTCONDOR-1889 document htcondor eventlog

- src/condor_tests/test_job_token_transfer.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1972
Differences:
1. Cleaned up unnecessary import statements and added some logging statements.
2. Changed the test to a script that uses `$_CONDOR_CREDS` instead of looking in `.condor_creds` (which required file transfer) but otherwise does the same thing as before.
3. Added local universe tests (and made vanilla universe tests explicit).
> HTCONDOR-1972 Expand token test to other universes

- src/condor_dagman/jobstate_log.cpp
> HTCONDOR-1992 fix dagman warning -- if we check for a nullptr

- src/condor_starter.V6.1/jic_shadow.cpp
> HTCONDOR-1992 when shutting down starter, don't call daemonCore methods

- src/condor_starter.V6.1/vm_proc.cpp
- src/condor_starter.V6.1/vm_proc.h
> HTCONDOR-1992 don't pass a possible-but-unlikely nullptr to dprintf

- src/condor_tests/test_checkpoint_ct.py
itermittently on our slower, emulated platforms
> HTCONDOR-1992 add more timing slop to this test which is failing

- src/condor_q.V6/queue.cpp
- src/condor_schedd.V6/qmgmt_receivers.cpp
> HTCONDOR-1992 schedd leak

- src/condor_collector.V6/collector_engine.cpp
- src/condor_q.V6/jobmatch.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_utils/compat_classad_util.cpp
- src/condor_utils/compat_classad_util.h
- src/condor_utils/condor_query.cpp
This change is future proofing against expected changes of MyType for Startd ads.
> HTCONDOR-1997 remove comparison of TargetType for classad matchmaking

- docs/version-history/lts-versions-10-0.rst
- src/condor_utils/store_cred.cpp
> HTCONDOR-1998 user-password-delete

- src/annex/BulkRequest.cpp
- src/annex/GetFunction.cpp
- src/annex/OnDemandRequest.cpp
- src/annex/PutRule.cpp
- src/annex/PutTargets.cpp
- src/annex/UploadFile.cpp
- src/condor_unit_tests/OTEST_HashTable.cpp
- src/condor_utils/dprintf.cpp
But the warnings only show up on ppc gcc (?)
> HTCONDOR-1992 fix warnings

- build/packaging/debian/control.in
- build/packaging/rpm/condor.spec
> HTCONDOR-1981: Add RPM Provides: for Obsolete packages

- src/condor_gridmanager/gahp-client.cpp
> HTCONDOR-1992 fix initialized variable read

- src/condor_utils/MapFile.cpp
- src/condor_utils/MapFile.h
- src/condor_utils/test_user_mapping.cpp
This PR allows us to use map files to match against the longest prefix first, instead of just exact matches and regular expressions.
> (HTCONDOR-1999)  Add longest-prefix-first as an option for map files.

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/singularity-support.rst
> HTCONDOR-1996 document SINGULARTY_EXTRA_ARGUMENTS MY and TARGET

- build/nmi-build/build-batlab-images.sh
- docs/apis/python-bindings/install.rst
- docs/getting-htcondor/from-our-repositories.rst
- docs/getting-htcondor/index.rst
- docs/version-history/feature-versions-23-x.rst
- nmi_tools/nmi-build-platforms
> HTCONDOR-1990: Drop EL7

- docs/version-history/lts-versions-23-0.rst
- src/blahp/src/scripts/lsf_ping.sh
> HTCONDOR-2003 blahp lsf bhist

- docs/man-pages/condor_remote_cluster.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_gridmanager/remote_gahp
- src/condor_scripts/condor_remote_cluster
> HTCONDOR-2002 remote-cluster-ssh-port

- src/condor_scripts/condor_upgrade_check
> HTCONDOR-2004: Backport checks for going to V23 from HTCONDOR-1960

- docs/getting-htcondor/from-our-repositories.rst
Just a minor documentation update
> Update repolist to include Debian 12 in the title

- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_includes/condor_pidenvid.h
- src/condor_utils/condor_pidenvid.cpp
> HTCONDOR-1925 fix warnings from previous bool fix

- src/condor_utils/submit_utils.cpp
- src/condor_utils/xform_utils.cpp
- src/condor_utils/xform_utils.h
> HTCONDOR-1992 fix warnings about const/non-const param string_value type

- externals/bundles/scitokens-cpp/1.0.0/CMakeLists.txt
> HTCONDOR-1992 Update SciTokens external to 1.0.2

- docs/users-manual/submitting-a-job.rst
There seems to be a typo in line number 354.
Changed from \$(SUBMIT_FILE) to \$(SUBMIT_TIME)
> Update submitting-a-job.rst in line number 354

- src/condor_had/AbstractReplicatorStateMachine.cpp
- src/condor_includes/condor_debug.h
- src/condor_utils/dprintf_common.cpp
> HTCONDOR-1992 remove obsolete D_CKPT, D_PROC and D_NFS

- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_daemon_core.V6/timer_manager.cpp
> HTCONDOR-1922 less d_daemoncore chatttude

- src/condor_tests/test_job_token_transfer.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1972
> HTCONDOR-1972 Add permissions check for credential files

- docs/version-history/feature-versions-10-x.rst
> HTCONDOR-1984  Belated release note.

- CMakeLists.txt
- build/nmi-build/setup.sh
- nmi_tools/glue/build/make-tarball-from-debs
- nmi_tools/glue/build/make-tarball-from-rpms
- nmi_tools/nmi-build-platforms
- src/condor_tests/x_conditional_params.cpp
> HTCONDOR-1993: Linux externals

- src/condor_daemon_core.V6/daemon_command.cpp
Make daemons less chatty about DC_SEC_QUERY
> HTCONDOR-1992 sec-query-dprintf

- src/arc_gahp/io_loop_pthread.cpp
- src/arc_gahp/io_loop_pthread.h
- src/condor_includes/condor_accountant.h
- src/condor_negotiator.V6/Accountant.cpp
- src/condor_tools/give_interactive.cpp
- src/condor_tools/tool.cpp
- src/condor_utils/check_events.cpp
- src/condor_utils/check_events.h
- src/condor_utils/condor_id.cpp
- src/condor_utils/condor_id.h
- src/condor_utils/directory.WINDOWS.cpp
- src/condor_utils/passwd_cache.unix.cpp
- src/condor_utils/passwd_cache.unix.h
- src/condor_utils/proc_family_direct.cpp
- src/condor_utils/proc_family_direct.h
- src/condor_utils/remote_close.WINDOWS.cpp
- src/condor_utils/setenv.cpp
- src/condor_utils/system_info.WINDOWS.cpp
- src/condor_utils/system_info.WINDOWS.h
- src/ec2_gahp/io_loop_pthread.cpp
- src/ec2_gahp/io_loop_pthread.h
- src/gce_gahp/io_loop_pthread.cpp
- src/gce_gahp/io_loop_pthread.h
- src/openstack_gahp/io_loop_pthread.cpp
- src/openstack_gahp/io_loop_pthread.h
> HTCONDOR-1994 maps

- src/condor_starter.V6.1/jic_shadow.cpp
- src/condor_utils/file_transfer.cpp
> V23_0-HTCONDOR-2010-better-file-xfer-message

- src/condor_tools/preen.cpp
> (HTCONDOR-2007)  Preen now includes program name, core file date, and core file size.

- docs/version-history/feature-versions-10-x.rst
> HTCONDOR-1981, HTCONDOR-1987: Packaging reorg version history

- src/condor_tests/CMakeLists.txt
platforms.  Let's just not run them there.
> HTCONDOR-1992 checkpoint tests intermittantly failing on emulated

- docs/version-history/lts-versions-23-0.rst
- src/condor_daemon_client/daemon_types.cpp
- src/condor_daemon_client/daemon_types.h
- src/condor_includes/condor_adtypes.h
- src/condor_submit.V6/submit.cpp
- src/condor_utils/condor_adtypes.cpp
- src/python-bindings/collector.cpp
- src/python-bindings/dc_tool.cpp
- src/python-bindings/secman.cpp
> HTCONDOR-2014 Print the output of SEC_CREDENTIAL_STORER script on -dry-run

- src/condor_daemon_client/daemon_types.cpp
- src/condor_daemon_client/daemon_types.h
- src/condor_includes/condor_adtypes.h
- src/condor_utils/condor_adtypes.cpp
- src/python-bindings/collector.cpp
- src/python-bindings/dc_tool.cpp
- src/python-bindings/secman.cpp
and replace with AdTypeStringToDaemonType
remove DT_STORK and DT_GRIDMANAGER to daemon_t enum
> HTCONDOR-1992 cleanup AdType and daemon_t,  remove stringToAdType lookup

- src/condor_scripts/condor_upgrade_check
-Added check for systems using fragmented desktop policy macros -Added warning for deprecation of old job router config syntax
slated for removal in V23 feature series lifetime
> HTCONDOR-2004: Add checks for upgrading to V23

- build/packaging/rpm/condor.spec
- nmi_tools/glue/build/build_uw_rpm.sh
> HTCONDOR-1981: RPM provides blahp to smooth upgrades

- src/condor_utils/param_info.in
> HTCONDOR-2011-curb-matchmaking-when-lots-uploading

- bindings/python/htcondor/htchirp/htchirp.py
- docs/version-history/lts-versions-10-0.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2012
> HTCONDOR-2012 Fix HTChirp to use _CONDOR_CHIRP_CONFIG

- docs/version-history/lts-versions-23-0.rst
- src/condor_vm-gahp/xen_type.linux.cpp
> HTCONDOR-2009 vm-gahp-test

- docs/version-history/lts-versions-23-0.rst
- src/condor_tools/preen.cpp
> HTCONDOR-2019 preen offline ads

- build/packaging/debian/rules
- build/packaging/rpm/condor.spec
> HTCONDOR-2020 build debian with -O2

- docs/version-history/lts-versions-23-0.rst
- src/condor_startd.V6/Starter.cpp
> HTCONDOR-2016  startd should never fail to contact its own live starter

- docs/version-history/feature-versions-10-x.rst
- src/condor_scripts/condor_remote_cluster
> HTCONDOR-2023 bosco nfs

- nmi_tools/glue/build/remote_pre.pl
> HTCONDOR-1992 Make date in condor_verion string identical on all

- src/condor_utils/MapFile.cpp
- src/condor_utils/check_events.cpp
- src/condor_utils/condor_config.cpp
- src/condor_utils/hashkey.cpp
- src/condor_utils/hashkey.h
- src/condor_utils/passwd_cache.unix.cpp
- src/condor_utils/read_multiple_logs.h
- src/condor_utils/submit_glob.cpp
- src/ec2_gahp/io_loop_pthread.cpp
- src/gce_gahp/io_loop_pthread.cpp
- src/openstack_gahp/io_loop_pthread.cpp
> HTCONDOR-1994 remove unused header includes

- src/condor_includes/condor_secman.h
- src/condor_io/condor_secman.cpp
- src/condor_tools/ping.cpp
- src/python-bindings/schedd.cpp
- src/python-bindings/secman.cpp
> HTCONDOR-1994 map with code review changes

- docs/version-history/lts-versions-23-0.rst
- src/condor_startd.V6/command.cpp
> HTCONDOR-2032 startd-draining-crash

- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_negotiator.V6/Accountant.cpp
- src/condor_utils/d_format_time.cpp
- src/condor_utils/format_time.cpp
- src/condor_utils/history_utils.h
- src/python-bindings/classad.cpp
> HTCONDOR-1994 use std::ignore instead of cast-to-void

- docs/version-history/lts-versions-23-0.rst
- src/condor_tests/test_container_img_declares_universe.py
- src/condor_utils/submit_utils.cpp
- src/condor_utils/submit_utils.h
> HTCONDOR-2031 Fix container universe for late materialization

- src/condor_scripts/condor_upgrade_check
> HTCONDOR-2004: pslot default check branch

- src/condor_daemon_client/daemon.cpp
- src/condor_daemon_client/daemon.h
- src/condor_daemon_client/daemon_list.cpp
- src/condor_daemon_client/dc_collector.cpp
- src/condor_daemon_client/dc_master.cpp
- src/condor_daemon_client/dc_schedd.cpp
- src/condor_daemon_client/dc_shadow.cpp
- src/condor_daemon_client/dc_startd.cpp
- src/condor_daemon_client/dc_starter.cpp
- src/condor_daemon_client/dc_transfer_queue.cpp
> HTCONDOR-1994 daemon

- build/packaging/debian/control.in
- build/packaging/rpm/condor.spec
> HTCONDOR-2004: Generic package description for condor-upgrade-checks

- docs/apis/python-bindings/api/htcondor.rst
- docs/man-pages/condor_test_token.rst
- docs/version-history/lts-versions-23-0.rst
- src/condor_tests/test_condor_history.py
- src/condor_tests/test_condor_history_reads_epochs.py
- src/python-bindings/history_iterator.h
- src/python-bindings/schedd.cpp
- src/python-bindings/startd.cpp
> HTCONDOR-2036: python bindings query epoch history branch

- CMakeLists.txt
> HTCONDOR-1994 fix CMake warning about mis-matched if/endif comments

- docs/version-history/lts-versions-23-0.rst
- src/condor_starter.V6.1/jic_shadow.cpp
> HTCONDOR-2034 don't hold job if checkpoint transfer fails

- src/condor_daemon_client/daemon.cpp
> HTCONDOR-1994 Fix exception in daemon lookup recently introduced

- .readthedocs.yaml
- docs/requirements.txt
> HTCONDOR-2000: Update per read the docs requirements

- docs/version-history/lts-versions-23-0.rst
- src/condor_starter.V6.1/docker_proc.cpp
> HTCONDOR-2041 Fix CommittedTime attribute for DockerUni checkpointing

- docs/version-history/lts-versions-23-0.rst
- src/condor_includes/condor_config.h
- src/condor_io/condor_secman.cpp
- src/condor_utils/condor_config.cpp
- src/condor_utils/config.cpp
- src/condor_utils/param_info.cpp
- src/condor_utils/param_info.in
> HTCONDOR-2047 put SEC_DEFAULT_AUTHENTICATION_METHODS into param table

- src/condor_tests/test_pcre.py
> HTCONDOR-2047 make CLAIMTOBE explict for read in pcre test

- docs/version-history/upgrading-from-10-0-to-23-0-versions.rst
> HTCONDOR-2053: document missing gotchs branch

- src/condor_startd.V6/ResAttributes.cpp
- src/condor_startd.V6/ResAttributes.h
- src/condor_startd.V6/Resource.cpp
- src/condor_startd.V6/Resource.h
- src/condor_startd.V6/Starter.cpp
- src/condor_startd.V6/slot_builder.cpp
- src/condor_startd.V6/slot_builder.h
> HTCONDOR-2055 proper fix for negative SlotTypeId

- docs/version-history/upgrading-from-10-0-to-23-0-versions.rst
> HTCONDOR-1993: add new features list to v23 release docs

- src/condor_utils/dprintf.cpp
- src/condor_utils/dprintf_config.cpp
> HTCONDOR-2054 Don't sigprocmask around every dprinf call

- src/condor_tests/CheckOutputFormats.pm
- src/condor_tests/cmd_status-transform.run
> HTCONDOR-2059 fix cmd_status-transform for ctest

- docs/version-history/lts-versions-23-0.rst
- src/condor_shadow.V6.1/baseshadow.cpp
…t write an epoch ad to history
> HTCONDOR-2060: Fix bug internally held jobs didnt write epoch ads

- docs/version-history/lts-versions-23-0.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
> HTCONDOR-2061 don't check for oom on  windows

- docs/version-history/feature-versions-23-x.rst
- src/condor_utils/proc_family_direct_cgroup_v2.cpp
> V23_1-HTCONDOR-2058-cgroup-v2-delegation

- docs/version-history/feature-versions-23-x.rst
- src/condor_master.V6/masterDaemon.cpp
> HTCONDOR-2064-set-TZ

- build/packaging/rpm/condor.spec
- docs/conf.py
This PR modifies the build and distribution of the manual for `classads`; this isn't a user command so shouldn't be in section 1.
I selected section 7 as per <https://man7.org/linux/man-pages/man7/man-pages.7.html>.
> Use man section 7 for classads doc

- docs/admin-manual/monitoring.rst
- src/condor_utils/param_info.in
> HTCONDOR-2049 Improve monitoring docs

- build/nmi-build/setup.sh
- docs/full_conf.py
- docs/requirements.txt
Does this also put it into the container we use for rtd?
> HTCONDOR-2049 add mermaid to build containers

- docs/version-history/introduction-version-history.rst
> Explain release version compatibility

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/monitoring.rst
- docs/admin-manual/power-management.rst
This config knob has been decprecated for over a decade.
> HTCONDOR-2062 Remove mention of OFFLINE_LOG in the manual

- docs/version-history/lts-versions-23-0.rst
- src/condor_gridmanager/arcjob.cpp
> HTCONDOR-2068 arc-times

- docs/version-history/lts-versions-23-0.rst
- src/condor_gridmanager/condorjob.cpp
- src/condor_job_router/VanillaToGrid.cpp
> HTCONDOR-2069 grid resouces provisioned

- build/packaging/debian/condor.postinst
- docs/version-history/lts-versions-23-0.rst
> HTCONDOR-2074: Ensure /var/lib/condor exists on Debian

- src/condor_submit.V6/factory_test.cpp
> HTCONDOR-1994 fix warning about incomplete type and failure to delete

- INSTALL.md
> HTCONDOR-1992 Clarify that we only support building in out-of-source

- docs/version-history/lts-versions-23-0.rst
- src/condor_shadow.V6.1/parallelshadow.cpp
> HTCONDOR-2070 fix race condition in parallel universe condor_rm

- src/condor_tests/test_dagman_service_nodes.py
> HTCONDOR-1994: increase service node test timeout

- docs/admin-manual/introduction-admin-manual.rst
- docs/admin-manual/policy-configuration.rst
- docs/automated-workflows/dagman-using-other-dags.rst
- docs/man-pages/index.rst
- docs/users-manual/index.rst
> V23_1-HTCONDOR-2049-more-mermaid-docs

- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_schedd.V6/prio_rec.h
- src/condor_starter.V6.1/jic_local.cpp
- src/condor_starter.V6.1/jic_local_file.cpp
- src/condor_starter.V6.1/jic_shadow.cpp
- src/condor_tools/give_interactive.cpp
> HTCONDOR-1992  string of 0 when empty

- docs/automated-workflows/dagman-using-other-dags.rst
> HTCONDOR-2049 finish replacing dagman images with mermaid diagrams

- docs/man-pages/classad_eval.rst
- docs/man-pages/classads.rst
- docs/man-pages/condor_evicted_files.rst
- docs/man-pages/condor_ssl_fingerprint.rst
- docs/man-pages/condor_token_create.rst
- docs/man-pages/condor_token_fetch.rst
- docs/man-pages/condor_token_list.rst
- docs/man-pages/condor_token_request.rst
- docs/man-pages/condor_token_request_approve.rst
- docs/man-pages/condor_token_request_auto_approve.rst
- docs/man-pages/condor_token_request_list.rst
> HTCONDOR-2049 no man page copyrights

- src/condor_utils/generic_stats.cpp
- src/condor_utils/generic_stats.h
This reduces string copies of stat names, improving performance.
> HTCONDOR-2072 generic-stats-reorg

- src/condor_utils/MapFile.cpp
> HTCONDOR-2091-branch

- src/condor_utils/proc_family_direct_cgroup_v2.cpp
> HTCONDOR-2081-cgroup-v2-delegation-cleanup

- docs/classad-attributes/machine-classad-attributes.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_includes/condor_attributes.h
- src/condor_startd.V6/ResAttributes.cpp
> HTCONDOR-2085 rotational scratch

- docs/admin-manual/cm-configuration.rst
- docs/admin-manual/configuration-macros.rst
> HTCONDOR-2097 fixup broken links in manual

- docs/version-history/lts-versions-23-0.rst
- src/condor_userlog/userlog.cpp
> HTCONDOR-2099 userlog dbz

- docs/admin-manual/configuration-macros.rst
> HTCONDOR-2097: Replace Knob :index: with :macro:

- src/condor_q.V6/queue.cpp
- src/condor_tools/advertise.cpp
- src/condor_utils/compat_classad.cpp
- src/condor_utils/condor_config.cpp
- src/condor_utils/write_user_log.cpp
> V23_2-HTCONDOR-2098-win-binary-files

- docs/version-history/feature-versions-23-x.rst
> HTCONDOR-2098 win-binary-files

- INSTALL.md
> HTCONDOR-2097 Add INSTALL.md docs for building native packages

- docs/users-manual/time-scheduling-for-job-execution.rst
> HTCONDOR-2097 fix broken ref ligo tripped over

- docs/admin-manual/cm-configuration.rst
- docs/admin-manual/configuration-templates.rst
- docs/admin-manual/ep-policy-configuration.rst
- docs/admin-manual/hooks.rst
- docs/admin-manual/installation-startup-shutdown-reconfiguration.rst
- docs/admin-manual/introduction-admin-manual.rst
- docs/admin-manual/introduction-to-configuration.rst
- docs/admin-manual/logging.rst
- docs/admin-manual/networking.rst
- docs/classad-attributes/defrag-classad-attributes.rst
- docs/classad-attributes/job-classad-attributes.rst
- docs/classad-attributes/machine-classad-attributes.rst
- docs/classad-attributes/scheduler-classad-attributes.rst
- docs/classads/classad-mechanism.rst
- docs/cloud-computing/annex-configuration.rst
- docs/cloud-computing/annex-customization-guide.rst
- docs/cloud-computing/annex-users-guide.rst
> HTCONDOR-2097: Replace more instances of knob :index: with :macro:

- docs/admin-manual/cm-configuration.rst
- docs/automated-workflows/dagman-introduction.rst
- docs/automated-workflows/index.rst
- docs/classads/index.rst
> HTCONDOR-2097 As recommended by a user, add video links to manual

- docs/version-history/lts-versions-23-0.rst
- src/condor_ft-gahp/io_loop.cpp
- src/condor_gridmanager/infnbatchjob.cpp
> HTCONDOR-2073 bosco-sandbox-leak

- docs/version-history/lts-versions-23-0.rst
- src/condor_gridmanager/remote_gahp
> HTCONDOR-2118 ssh-agent

- src/condor_negotiator.V6/matchmaker.cpp
- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_shadow.V6.1/remoteresource.cpp
> HTCONDOR-2119 Fix how we log messages about security sessions

- docs/version-history/feature-versions-23-x.rst
- src/condor_shadow.V6.1/baseshadow.cpp
- src/condor_utils/condor_event.cpp
> HTCONDOR-2101 Add walltime to eventlog as per RCF requests

- docs/man-pages/condor_submit.rst
- docs/users-manual/automatic-job-management.rst
- docs/users-manual/choosing-an-htcondor-universe.rst
- docs/users-manual/container-universe-jobs.rst
- docs/users-manual/docker-universe-applications.rst
- docs/users-manual/file-transfer.rst
- docs/users-manual/java-applications.rst
- docs/users-manual/job-sets.rst
- docs/users-manual/managing-a-job.rst
- docs/users-manual/matchmaking-with-classads.rst
- docs/users-manual/parallel-applications.rst
- docs/users-manual/priorities-and-preemption.rst
- docs/users-manual/quick-start-guide.rst
- docs/users-manual/self-checkpointing-applications.rst
- docs/users-manual/services-for-jobs.rst
- docs/users-manual/special-environment-considerations.rst
- docs/users-manual/submitting-a-job.rst
- docs/users-manual/time-scheduling-for-job-execution.rst
- docs/users-manual/virtual-machine-applications.rst
> HTCONDOR-2097 use :subcom: macro in sphinx documentation

- docs/extensions/subcom.py
- docs/users-manual/submitting-a-job.rst
-:subcom:`foo` will now just make a ref to the foo command
declaration
-:subcom:`foo<example>` will create a ref to the foo command
declaration and create a ref in the index table called 'example'
-Improved the index to be targetid to be foo-example-n
> HTCONDOR-2097: Improve auto indexing for subcom extension

- docs/version-history/lts-versions-23-0.rst
> HTCONDOR-2084 add version history

- docs/STYLE.md
- docs/users-manual/choosing-an-htcondor-universe.rst
- docs/users-manual/docker-universe-applications.rst
- docs/users-manual/file-transfer.rst
- docs/users-manual/java-applications.rst
- docs/users-manual/managing-a-job.rst
- docs/users-manual/parallel-applications.rst
- docs/users-manual/services-for-jobs.rst
- docs/users-manual/special-environment-considerations.rst
- docs/users-manual/submitting-a-job.rst
- docs/users-manual/time-scheduling-for-job-execution.rst
- docs/users-manual/virtual-machine-applications.rst
> HTCONDOR-2097 Add STYLE.md and use new subcom macros in docs

- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_bogus_collector.py
- src/condor_tests/test_broken_hash_bang.py
- src/condor_tests/test_classad_eval.py
- src/condor_tests/test_concurrency_limits.py
- src/condor_tests/test_ft_plugin_stuff.py
- src/condor_tests/test_hpc_annex_require_job.py
- src/condor_tests/test_htcondor_993.py
- src/condor_tests/test_job_env.py
- src/condor_tests/test_manifest.py
- src/condor_tests/test_parallel_uni.py
- src/condor_tests/test_shadow_hook.py
- src/condor_tests/test_singularity_sif.py
While I'm poking around in here...
> (HTCONDOR-2107)  Clean up infelicities in the test suite.

- docs/version-history/lts-versions-23-0.rst
- src/condor_negotiator.V6/matchmaker.cpp
> HTCONDOR-2115 negotiator private addr

- docs/STYLE.md
- docs/admin-manual/ap-policy-configuration.rst
- docs/admin-manual/configuration-macros.rst
- docs/extensions/classad-attribute.py
- docs/extensions/htc_helpers.py
- docs/extensions/macro-def.py
- docs/extensions/macro.py
- docs/extensions/subcom-def.py
- docs/extensions/subcom.py
> HTCONDOR-2097: improve custom sphinx roles branch

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/introduction-to-configuration.rst
- docs/man-pages/condor_submit.rst
- docs/users-manual/docker-universe-applications.rst
- docs/users-manual/submitting-a-job.rst
> HTCONDOR-2097 Fix up first entries in index to not look awful

- src/classad/xmlSink.cpp
> HTCONDOR-2072 fix warning introduced by earlier commit

- docs/admin-manual/configuration-macros.rst
- docs/extensions/macro-def.py
> HTCONDOR-2097: Add Indexing group option for :macro-def: declaration

- docs/STYLE.md
- docs/apis/python-bindings/api/classad.rst
- docs/apis/python-bindings/api/htchirp.rst
- docs/apis/python-bindings/api/htcondor.rst
- docs/apis/python-bindings/api/personal.rst
- docs/users-manual/services-for-jobs.rst
they look messy, and the reference docs are the best place to find these.
> HTCONDOR-2097 don't generate index entries for python APIs

- docs/STYLE.md
> HTCONDOR-2097: Update style guide for macro-def sectioning

- docs/apis/python-bindings/api/classad.rst
- docs/apis/python-bindings/api/dags.rst
- docs/apis/python-bindings/api/htchirp.rst
- docs/apis/python-bindings/api/htcondor.rst
- docs/apis/python-bindings/api/personal.rst
- docs/users-manual/time-scheduling-for-job-execution.rst
> HTCONDOR-2079 :nonindex: the rest of the bindings

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/introduction-admin-manual.rst
- docs/classad-attributes/job-classad-attributes.rst
- docs/users-manual/choosing-an-htcondor-universe.rst
> HTCONDOR-2079 Fix index issues and turn small diagrams to sidebars

- docs/admin-manual/ep-policy-configuration.rst
> HTCONDOR-2097: Improve LVM disk enforcement docs

- src/condor_dagman/condor_submit_dag.cpp
- src/condor_dagman/dagman_main.cpp
- src/condor_dagman/dagman_submit.cpp
- src/condor_utils/dagman_utils.cpp
- src/condor_utils/dagman_utils.h
- src/python-bindings/schedd.cpp
Useful for version 2 of the Python bindings.
As of a952cfe958b2edee5a070b10d38b8d3ef07259c8, not all options use the new-style code.  I have to discuss with ColeB if there are any options that shouldn't be made available, or perhaps made available but left undocumented.
See the ticket for a brief introduction to the design.
> (HTCONDOR-2116)  Try to make DagmanSubmit[Deep|Shallow]Options suck less.

- docs/admin-manual/configuration-macros.rst
- docs/extensions/macro-def.py
> HTCONDOR-2097 fixup macro sections when multiple macro-def's on one line

- docs/admin-manual/configuration-macros.rst
- docs/cloud-computing/annex-configuration.rst
> HTCONDOR-2097 Properly index annex knobs

- docs/version-history/feature-versions-23-x.rst
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_master.V6/masterDaemon.cpp
- src/condor_utils/CMakeLists.txt
- src/condor_utils/largestOpenFD.cpp
- src/condor_utils/largestOpenFD.h
- src/condor_utils/my_popen.cpp
> HTCONDOR-2128 faster fd closing

- build/packaging/debian/rules
- build/packaging/rpm/condor.spec
- nmi_tools/glue/build/build_uw_deb.sh
- nmi_tools/glue/build/build_uw_rpm.sh
- nmi_tools/glue/build/check-tarball.pl
- nmi_tools/glue/build/make-tarball-from-debs
- nmi_tools/glue/build/make-tarball-from-rpms
- nmi_tools/glue/build/remote_task.pl
- src/condor_tools/CMakeLists.txt
> HTCONDOR-2072: Various build improvements

- src/condor_master.V6/master.cpp
- src/condor_master.V6/masterDaemon.cpp
- src/condor_status.V6/status.cpp
- src/condor_tools/ssl_fingerprint.cpp
> HTCONDOR-2072 remove unused includes

- docs/version-history/lts-versions-23-0.rst
- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.h
> HTCONDOR-2127 Add DISABLE_SWAP_FOR_JOB for cgroup v2

- build/packaging/debian/condor-test.install
- build/packaging/debian/condor.install
- build/packaging/rpm/condor.spec
Without `condor_manifest`, jobs which set a checkpoint destination can't be cleaned up after.
> (HTCONDOR-2130)  Move `condor_manifest` from the test tarball to the primary tarball.

- docs/version-history/feature-versions-23-x.rst
- src/condor_scripts/condor_remote_cluster
> HTCONDOR-2125 bosco-rhel7

- build/cmake/macros/CloneInstall.cmake
> V23_2-HTCONDOR-2129-fix-clone-install

- src/condor_collector.V6/collector.cpp
> HTCONDOR-2072 fix warnings

- docs/version-history/lts-versions-23-0.rst
- src/condor_schedd.V6/qmgmt_factory.cpp
- src/condor_submit.V6/factory_test.cpp
- src/condor_submit.V6/submit.cpp
- src/condor_tests/cmd_submit_factory_regress_dry.run
- src/condor_utils/submit_utils.cpp
- src/condor_utils/submit_utils.h
test_job_factory.exe was also revised to use the actual late materialization code from the schedd
> HTCONDOR-2092 fix for bug with late materialization and initialdir

- src/python-bindings/JobEventLog.cpp
A user remarked that they'd found this confusing.
> HTCONDOR-2083 Improve JobEventLog documentation

- docs/version-history/lts-versions-23-0.rst
- src/condor_credd/condor_credmon_oauth/condor_credmon_oauth
- src/condor_credd/condor_credmon_oauth/condor_credmon_oauth.wsgi
- src/condor_credd/condor_credmon_oauth/condor_credmon_vault
- src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/AbstractCredentialMonitor.py
- src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/OAuthCredmonWebserver/OAuthCredmonWebserver.py
- src/condor_credd/condor_credmon_oauth/credmon/utils/utils.py
Addresses [HTCONDOR-2013](https://opensciencegrid.atlassian.net/browse/HTCONDOR-2013) by switching from using the Python `logging` library to using HTCondor's logging functionality built into the Python bindings.
[HTCONDOR-2013]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-2013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> HTCONDOR-2013 Make credmons use HTCondor logging

- src/condor_tests/shadow_mem_usage-basic.run
> V23_2-HTCONDOR-2132-Fedora-39

- docs/_static/css/htcondor-manual.css
- docs/admin-manual/ep-policy-configuration.rst
> HTCONDOR-2097 Replace the startd big activity diagram with mermaid

- externals/bundles/scitokens-cpp/1.0.0/CMakeLists.txt
> HTCONDOR-2135 Update SciTokens external to 1.1.0

- src/bash_completion.d/condor
> HTCONDOR-2139 htcondor-cli completions

- src/arc_gahp/arcCommands.cpp
- src/condor_daemon_client/daemon.cpp
- src/condor_daemon_client/dc_collector.cpp
- src/condor_daemon_client/dc_schedd.cpp
- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_io/condor_auth_passwd.cpp
- src/condor_io/condor_auth_ssl.cpp
- src/condor_negotiator.V6/matchmaker.cpp
> HTCONDOR-2140 use join instead of open coded stringstream loops

- src/condor_daemon_core.V6/pipe.WINDOWS.h
> HTCONDOR-2140 Subclasses ReadPipeEnd and WritePipeEnd need virtual dtors

- src/classad/classad.cpp
- src/condor_collector.V6/collector_engine.h
- src/condor_daemon_client/daemon.cpp
- src/condor_daemon_client/daemon.h
- src/condor_daemon_client/daemon_types.cpp
- src/condor_daemon_client/daemon_types.h
- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_includes/condor_adtypes.h
- src/condor_includes/condor_config.h
- src/condor_master.V6/masterDaemon.cpp
- src/condor_schedd.V6/checkpoint_cleanup.cpp
- src/condor_status.V6/status.cpp
- src/condor_tools/transform_ads.cpp
- src/condor_utils/MapFile.h
- src/condor_utils/compat_classad.h
- src/condor_utils/config.cpp
- src/condor_utils/submit_utils.h
- src/condor_utils/subsystem_info.cpp
- src/condor_utils/subsystem_info.h
To aid code review, pull out just the lines that aren't in new files (or refer to those files).
> (HTCONDOR-1598)  Changes to the rest of the code only.

- docs/version-history/feature-versions-23-x.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.cpp
> V23_3-HTCONDOR-1533-better-oom-hold-message

- src/condor_had/AbstractReplicatorStateMachine.cpp
- src/condor_had/AbstractReplicatorStateMachine.h
- src/condor_had/BaseReplicaTransferer.cpp
- src/condor_had/BaseReplicaTransferer.h
- src/condor_had/DownloadReplicaTransferer.cpp
- src/condor_had/DownloadReplicaTransferer.h
- src/condor_had/ReplicatorStateMachine.cpp
- src/condor_had/StateMachine.cpp
- src/condor_had/StateMachine.h
- src/condor_had/Transferer.cpp
- src/condor_had/UploadReplicaTransferer.cpp
- src/condor_had/UploadReplicaTransferer.h
- src/condor_had/Utils.cpp
- src/condor_had/Utils.h
- src/condor_includes/condor_auth_kerberos.h
- src/condor_io/authentication.cpp
- src/condor_io/ca_utils.cpp
- src/condor_io/condor_auth_kerberos.cpp
- src/condor_io/condor_auth_passwd.cpp
- src/condor_io/condor_auth_ssl.cpp
- src/condor_io/condor_ipverify.cpp
- src/condor_io/condor_ipverify.h
- src/condor_io/shared_port_endpoint.cpp
- src/condor_io/shared_port_server.cpp
- src/condor_io/sock.cpp
- src/condor_utils/condor_sinful.cpp
- src/condor_utils/condor_sinful.h
- src/condor_utils/sinful-tool.cpp
- src/condor_utils/test_sinful.cpp
> HTCONDOR-2140 cleanup

- docs/version-history/feature-versions-23-x.rst
> HTCONDOR-1851 version history for prepare job args

- docs/version-history/feature-versions-23-x.rst
> HTCONDOR-2081-version-history

- src/python-bindings/schedd.cpp
> (HTCONDOR-2143)  Improve Python bindings documentation

- src/condor_scripts/get_htcondor
The names to use for CentOS Stream 8 and macOS were wrong.
> HTCONDOR-2148 get-htcondor-download

- docs/version-history/lts-versions-23-0.rst
- src/condor_daemon_core.V6/daemon_core.cpp
> HTCONDOR-1698 better-enoent-when-root

- docs/version-history/feature-versions-23-x.rst
> HTCONDOR-2100: Version history for Pelican file transfer plugin

- docs/version-history/stable-release-series-90.rst
- src/condor_includes/condor_auth_ssl.h
- src/condor_io/condor_auth_ssl.cpp
- src/condor_utils/param_info.in
> HTCONDOR-2145 ssl-mapping-fallback

- docs/admin-manual/configuration-macros.rst
- docs/classads/classad-mechanism.rst
- docs/extensions/classad-attribute-def.py
- docs/extensions/htc_helpers.py
- docs/extensions/macro-def.py
- docs/extensions/subcom-def.py
> HTCONDOR-2141: add headerlink functionality to extentsion defs

- docs/version-history/lts-versions-23-0.rst
- src/condor_submit.V6/submit.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2078
Reverts #1739
> HTCONDOR-2078 Stream output of SEC_CREDENTIAL_STORER, revert HTCONDOR-2014

- src/condor_filetransfer_plugins/multifile_curl_plugin.cpp
- src/condor_starter.V6.1/starter_v61_main.cpp
- src/condor_utils/file_transfer.cpp
- src/condor_utils/file_transfer.h
We run the file-transfer plug-ins with `-classad` when the startd first starts up to find out which protocols/schemas they support.  They should also tell us which proxy or proxies (or cache or caches) they will be using.  This PR adds the EP infrastructure and updates the curl plug-in.
> HTCONDOR-2144 Advertise what proxies the file-transfer plug-ins tell us about.

- src/condor_scripts/CondorPersonal.pm
- src/condor_scripts/CondorUtils.pm
> HTCONDOR-2152 don't use threads to pull stdout/stderr from runcmd

- src/condor_utils/file_transfer.cpp
- src/condor_utils/file_transfer.h
- src/condor_utils/stl_string_utils.h
> HTCONDOR-268 better file transfer exception list handling

- docs/version-history/feature-versions-23-x.rst
- src/condor_starter.V6.1/singularity.cpp
- src/condor_utils/submit_utils.cpp
> HTCONDOR-1329 Allow container universe jobs to work with

- src/condor_schedd.V6/qmgmt.cpp
> HTCONDOR-2155 clarify *which* owner is over MAX_JOBS_PER_OWNER in

- bindings/python/htcondor/htchirp/htchirp.py
- docs/version-history/lts-versions-23-0.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2142
> HTCONDOR-2142 Fix HTChirp max line limit and catch large requests

- src/classad/classad/common.h
- src/classad/classad/util.h
- src/classad/lexer.cpp
- src/classad/literals.cpp
- src/classad/xmlSource.cpp
> HTCONDOR-2140 use std::from_chars instead of strtol in classads

- src/condor_startd.V6/ResAttributes.cpp
- src/condor_startd.V6/ResAttributes.h
- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/ResMgr.h
- src/condor_startd.V6/Resource.cpp
- src/condor_startd.V6/Resource.h
- src/condor_startd.V6/command.cpp
- src/condor_status.V6/status.cpp
also advertise resources-in-use values for both primary and backfill resources in the daemon ad
> HTCONDOR-2154 deduct active primary slot resources from advertised backfill p-slot

- src/condor_tests/appendmsg.cpp
> HTCONDOR-1095 update test program appendmsg.cpp to build x64

- docs/man-pages/condor_drain.rst
- docs/version-history/lts-versions-23-0.rst
- src/condor_tools/drain.cpp
> HTCONDOR-2164 add -reconfig-on-completion to condor_drain usage

- src/condor_tests/sleep.cpp
- src/condor_tests/tiny_winapi.h
> HTCONDOR-1095 update windows test program sleep.cpp to build x64

- src/annex/GetInstances.cpp
- src/annex/OnDemandRequest.cpp
- src/condor_gridmanager/ec2-gahp-client.cpp
- src/condor_gridmanager/ec2job.cpp
- src/condor_gridmanager/ec2job.h
- src/condor_gridmanager/ec2resource.cpp
- src/condor_gridmanager/gahp-client.h
- src/condor_gridmanager/gcejob.cpp
> HTCONDOR-2140 gridmanager-lists

- src/condor_tests/test_classads.py
- src/condor_tests/test_schedd_submit.py
This PR does not target main or a stable branch, because it makes no sense without the PR it does target. The plan is not to merge this until https://github.com/htcondor/htcondor/pull/1964 (the PR for the target branch) is merged to main, and then re-target this PR to main.
> (HTCONDOR-1598)  Expanded testing.

- bindings/python/htcondor2/_job_event.py
- bindings/python/htcondor2/_job_event_log.py
- bindings/python/htcondor2/_job_event_type.py
- src/python-bindings/htcondor2/job_event_log.cpp
This PR does not target main or a stable branch, because it makes no sense without the PR it does target. The plan is not to merge this until https://github.com/htcondor/htcondor/pull/1964 (the PR for the target branch) is merged to main, and then re-target this PR to main.
> (HTCONDOR-1598)  Implement JobEventLog and company.

- bindings/python/htcondor2/_collector.py
- src/python-bindings/htcondor2/collector.cpp
This PR does not target main or a stable branch, because it makes no sense without the PR it does target. The plan is not to merge this until #1964  (the PR for the target branch) is merged to main, and then re-target this PR to main.
> (HTCONDOR-1598)  Implement htcondor2.Collector.

- src/condor_tests/test_htcondor_cli.py
> HTCONDOR-1890 Add smoke test for htcondor eventlog read

- src/condor_q.V6/queue.cpp
- src/condor_status.V6/status.cpp
- src/condor_tools/history.cpp
- src/condor_tools/qusers.cpp
- src/condor_tools/user_prio.cpp
- src/condor_who/who.cpp
> HTCONDOR-903 Fix "at last one" --> "at least one" typo

- docs/man-pages/condor_q.rst
The documentation had obsolete link to ClassAd description without any meaningful information. I updated the link to `:latest` doc page about ClassAd.
> Updated ClassAd link to latest documentation

- docs/version-history/feature-versions-23-x.rst
- src/condor_utils/cron_job.cpp
> HTCONDOR-1012 reduce startd cron log spam

- docs/version-history/lts-versions-23-0.rst
- src/condor_scripts/adstash/adstash.py
- src/condor_scripts/condor_adstash
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2166
> HTCONDOR-2166 Adstash now uses multiprocessing spawn method

- nmi_tools/condor_nmi_submit
> HTCONDOR-2137: Use 9GiB for builds

- docs/admin-manual/ep-policy-configuration.rst
- docs/classad-attributes/machine-classad-attributes.rst
- src/classad/lexer.cpp
- src/classad/literals.cpp
> HTCONDOR-2140 fix warnings

- bindings/python/htcondor2/__init__.py
- bindings/python/htcondor2/_param.py
- bindings/python/htcondor2/_startd.py
- src/python-bindings/htcondor2/loose_functions.cpp
- src/python-bindings/htcondor2/param.cpp
- src/python-bindings/htcondor2/startd.cpp
- src/python-bindings/htcondor2_impl.cpp
This PR depends on the previous 10 PRs, and needs all of them merged to build cleanly.  The target branch generates the relevant diff, but we'll leave this PR in draft until it can be rebased into a buildable state.
> (HTCONDOR-1598)  Miscellany

- src/condor_utils/docker-api.cpp
> HTCONDOR-1471 Don't try to run docker test if no docker on system

- bindings/python/classad2/_class_ad.py
- bindings/python/htcondor2/__init__.py
- bindings/python/htcondor2/_daemon_type.py
- bindings/python/htcondor2/_job_event_log.py
- bindings/python/htcondor2/_param.py
- bindings/python/htcondor2/_startd.py
- src/condor_collector.V6/collector_engine.cpp
- src/condor_dagman/dagman_main.cpp
- src/python-bindings/classad2/classad.cpp
- src/python-bindings/classad2_impl.cpp
- src/python-bindings/common2/py_handle.cpp
- src/python-bindings/htcondor2/loose_functions.cpp
- src/python-bindings/htcondor2/param.cpp
- src/python-bindings/htcondor2/startd.cpp
- src/python-bindings/htcondor2/submit.cpp
- src/python-bindings/htcondor2_impl.cpp
- src/python-bindings/schedd.cpp
> V23 3 htcondor 1598 refactor test branch

- src/python-bindings/htcondor2/collector.cpp
- src/python-bindings/htcondor2_impl.cpp
> (HTCONDOR-1598)  Update to use the new CollectorList API.

- src/condor_tests/test_startd_cron.py
- src/condor_utils/cron_job.cpp
I recommend viewing the first commit's diff with `-w`: https://github.com/htcondor/htcondor/compare/main...V23_3_0-HTCONDOR-2177-branch?w=1
> (HTCONDOR-2177)  Return to always processing cron job output.

- docs/STYLE.md
- docs/automated-workflows/dagman-file-paths.rst
- docs/conf.py
- docs/extensions/macro-def.py
- docs/extensions/macro.py
- docs/extensions/subcom-def.py
- docs/extensions/subcom.py
- docs/extensions/tool.py
- docs/full_conf.py
- docs/version-history/lts-versions-23-0.rst
> HTCONDOR-2173: add sphinx tool ref extension branch

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_utils/submit_utils.cpp
> HTCONDOR-1837-missing-submit-requests-warn-or-error

- build/packaging/rpm/condor.spec
- docs/conf.py
- docs/version-history/feature-versions-23-x.rst
- nmi_tools/nmi-build-platforms
> HTCONDOR-2194: Resurrect CentOS7 build

- src/condor_scripts/condor_remote_cluster
> HTCONDOR-2194: Disable using 23.0 tarballs with CentOS7 remote cluster

- src/condor_tests/job_late_materialize.run
> HTCONDOR-2196-speedup-late-materialize-test

- docs/users-manual/time-scheduling-for-job-execution.rst
and demote the assembly-language deferral to the end of the docs
> HTCONDOR-2181-add-crondor-example

- docs/version-history/introduction-version-history.rst
> HTCONDOR-2022: Add Support Life Cycle

- docs/version-history/feature-versions-23-x.rst
- src/condor_utils/classadHistory.cpp
> HTCONDOR-2027-assert-on-per-job-history-error

- src/condor_tests/job_core_crontab.run
By running every minute, not every other minute
> HTCONDOR-2196 speed up crondor test

- docs/users-manual/services-for-jobs.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_tests/lib_meta_knob.run
- src/condor_utils/param_info.in
> HTCONDOR-2189-export-NVIDIA_VISIBLE_DEVICES

- docs/version-history/lts-versions-23-0.rst
- src/condor_utils/file_transfer.cpp
> HTCONDOR-2203 Check for and handle file errors when writing file xfer

- docs/admin-manual/file-and-cred-transfer.rst
- docs/version-history/lts-versions-23-0.rst
- src/condor_utils/file_transfer.cpp
> HTCONDOR-2205 non zero file xfer exits are always an error

- src/condor_tests/test_allowed_execute_duration.py
> HTCONDOR-2196 increase condor_reschedule timeout in test for hardening

- build/nmi-build/setup.sh
> HTCONDOR-2156: Get build dependencies from spec file for openSUSE

- build/nmi-build/build-batlab-images.sh
> HTCONDOR-2173: Save time by pushing BaTLab Docker images in parallel

- src/condor_utils/condor_event.cpp
> HTCONDOR-1897 Messages from startd Hooks to userlog no longer "Warning",

- src/condor_tests/test_job_submit_method_recording.py
- src/condor_tools/htcondor_cli/job_set.py
> HTCONDOR-1422-htcondor-cli-no-jobset-enable-no-work

- docs/version-history/lts-versions-23-0.rst
- src/condor_dagman/parse.cpp
- src/condor_tests/test_job_submit_method_recording.py
> HTCONDOR-2184: fix dag inline submit desc job submit method recording branch

- src/condor_tests/test_job_submit_method_recording.py
> HTCONDOR-2196: Fix job submit method test by only using one condor

- docs/admin-manual/configuration-macros.rst
- docs/codes-other-values/glossary.rst
- docs/users-manual/job-sets.rst
and start docs with fully functional example
> HTCONDOR-2196 Fixup jobsets docs to reflect reality,

- src/condor_dagman/parse.cpp
- src/condor_tests/job_dagman_subdag-A-upper.dag
> HTCONDOR-2173: DAGMan fail if SUBDAG declared via JOB command

- src/condor_tests/test_late_materialization.py
It submit 10 jobs with max materialize of 5, and checks that exactly five jobs run concurrently.  On very slow machines we can't get up to fix.  So only run with 3 instead of five. Also knocks almost a minute off of the test run.
> HTCONDOR-2196 speedup and harden test_late_materialization

- src/condor_utils/condor_config.cpp
not D_ALWAYS.  Avoids pre-banner spam
> HTCONDOR-2173 Missing config.d should dprintf at D_FULLDEBUG,

- docs/conf.py
- docs/man-pages/condor_upgrade_check.rst
- docs/man-pages/index.rst
- docs/version-history/lts-versions-23-0.rst
- src/condor_scripts/condor_upgrade_check
> HTCONDOR-2168: first class condor upgrade check branch

- build/packaging/rpm/condor.spec
> HTCONDOR-2173: fix rpm packaging for upgrade check branch

- build/packaging/debian/README.Debian
- build/packaging/debian/TODO
- build/packaging/debian/condor-test.install.in
- build/packaging/debian/control.in
- build/packaging/debian/copyright
- build/packaging/debian/copyright.in
- build/packaging/debian/prepare-build-files.sh
- build/packaging/debian/rules.in
- build/packaging/debian/upstream/metadata
> HTCONDOR-2172: Update Debian Copyright file

- build/packaging/rpm/condor.spec
- src/classad/CMakeLists.txt
- src/classad/classad.cpp
- src/classad/classad/classad.h
- src/classad/classad/classad_flat_map.h
- src/condor_collector.V6/collector_engine.cpp
- src/condor_daemon_client/dc_schedd.cpp
- src/condor_gridmanager/condorjob.cpp
- src/condor_gridmanager/infnbatchjob.cpp
- src/condor_shadow.V6.1/parallelshadow.cpp
- src/condor_startd.V6/startd_named_classad.cpp
- src/condor_tests/test_classad_eval.py
- src/condor_tools/user_prio.cpp
> HTCONDOR-2158-classads-use-sorted-vector

- src/condor_startd.V6/startd_named_classad.cpp
- src/condor_tests/libcmr.py
> HTCONDOR-2196 robustify custom machine resources tests

- docs/admin-manual/security.rst
> HTCONDOR-1805 minor clarifications to security docs

- src/condor_tests/test_checkpoint_preen.py
empiricism.  "Trust, but verify"
> HTCONDOR-2196 Robustify test_checkpoint_preen by removing crass

- src/condor_tests/test_checkpoint_ct.py
- src/condor_tests/test_checkpoint_destination.py
The Checkpoint tests look for the job's output files immediately after the userlog says the job is done, but sometimes file transfer hasn't finished yet.  Let's poll a couple of times to be sure the files are there.
> HTCONDOR-2196 Robustify checkpoint tests

- docs/getting-htcondor/install-windows-as-administrator.rst
- docs/platform-specific/windows-installer.rst
> HTCONDOR-2042 Escape asterisk in sphinx docs

- build/cmake/CondorConfigure.cmake
> HTCONDOR-2173 replace deprecated cmake exec_program with execute_process

- src/condor_tests/test_startd_cron.py
By checking to see that startd cron has completed and is in collector before checking to see if the stderr has hit the dprintf log.
> HTCONDOR-2196 Robustify test-startd-cron

- docs/getting-htcondor/from-our-repositories.rst
- docs/getting-htcondor/index.rst
> HTCONDOR-2156: Add in openSUSE platform and clean up others

- build/packaging/debian/condor.lintian-overrides
- build/packaging/debian/copyright.in
- build/packaging/debian/source/lintian-overrides
- nmi_tools/glue/build/remote_task.pl
> HTCONDOR-2199: Deal with lintian errors and copyright

- src/condor_scripts/get_htcondor
> HTCONDOR-2173: Make get_htcondor work for amzn2023 (no EPEL needed)

- docs/admin-manual/cm-configuration.rst
- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/ep-policy-configuration.rst
- docs/admin-manual/installation-startup-shutdown-reconfiguration.rst
- docs/admin-manual/networking.rst
- docs/admin-manual/security.rst
- docs/man-pages/condor_submit.rst
- docs/users-manual/priorities-and-preemption.rst
- docs/users-manual/special-environment-considerations.rst
- docs/users-manual/submitting-a-job.rst
other minor changes, and move some admin-related info from user manual to admin manual.
> HTCONDOR-2181 spruce up manifest documentation

- src/condor_tests/test_get_htcondor.py
Instead of doing a lot of work to have a single fixture that spawns all the containers concurrently and then rewriting the whole test to pull container results out of that fixture, let's just add a `main()`-equivalent that runs `pytest -k` on itself once for each image.  If that's fast enough, we can come back later and add do once per image-and-branch, or whatever.
> (HTCONDOR-2207)  This is a hack, but it's better than waiting for a clean fix.

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_utils/param_info.in
- src/condor_utils/submit_utils.cpp
> HTCONDOR-2204 condor-c-reqs

- src/condor_tests/test_checkpoint_ct.py
- src/condor_tests/test_late_materialization.py
> V23_0-HTCONDOR-2208-backport-test-fixes

- bindings/python/classad/__init__.py
- bindings/python/htcondor/__init__.py
- docs/version-history/lts-versions-23-0.rst
- src/condor_tools/htcondor_cli/job_set.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2212
> HTCONDOR-2212 Fix SyntaxWarnings in Python binding scripts for Python 3.12

- bindings/python/classad/__init__.py
- bindings/python/htcondor/__init__.py
- bindings/python/htcondor2/_schedd.py
- docs/version-history/lts-versions-23-0.rst
- src/condor_tools/htcondor_cli/job_set.py
*ONLY MERGE AFTER #2094 IS MERGED UP THROUGH `main`*
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2212
No feature branch version history added here since it's (a) already covered by the LTS version history and (b) only affects undocumented code.
> HTCONDOR-2212 Fix SyntaxWarnings in v2 Python binding script for Python 3.12

- build/nmi-build/build-batlab-images.sh
- nmi_tools/glue/SubmitInfo.pm
- nmi_tools/glue/build/make-tarball-from-rpms
- nmi_tools/nmi-build-platforms
> HTCONDOR-2172: Add Fedora 39

- src/condor_scripts/get_htcondor
- src/condor_tests/test_get_htcondor.py
> HTCONDOR-2137: Add SUSE to get_htcondor

- src/condor_tests/test_singularity_sif.py
So that if user namespaces are broken, we don't fail the test
> HTCONDOR-2215-verify-singularity-test-preconditions

- src/condor_examples/filetransfer_example_plugin.py
- src/condor_shadow.V6.1/remoteresource.cpp
- src/condor_starter.V6.1/CMakeLists.txt
- src/condor_starter.V6.1/filter.cpp
- src/condor_starter.V6.1/filter.h
- src/condor_starter.V6.1/jic_shadow.cpp
- src/condor_starter.V6.1/jic_shadow.h
- src/condor_tools/history.cpp
- src/condor_utils/file_transfer.cpp
- src/condor_utils/file_transfer.h
- src/condor_utils/file_transfer_stats.cpp
- src/condor_utils/job_ad_instance_recording.cpp
- src/condor_utils/job_ad_instance_recording.h
- src/condor_utils/stl_string_utils.cpp
- src/condor_utils/stl_string_utils.h
I'd like to merge this PR to give Pelican something to start testing against / working with, not because I believe the ticket is complete.  For that reason, this PR shouldn't have any documentation in the manual.
We should discuss if a release note is necessary due to the change in the (totally undocumented) syntax of the transfer log.
This PR has two goals, both related to the ads in the output file produced by a multi-file transfer plug-in:
*  forwarding those ads to the slot ad;
*  writing those ads to the epoch log.
In addition, this PR:
* filters the ads in the output file (to enforce the type-safety of the schema);
* pre-allocates the output file (which both prevents accidental re-use and makes space available for an error message if the disk fills up for some);
* writes the slot ad …
> (HTCONDOR-2122)  propagate structured data from file transfer plug-in results

- build/packaging/rpm/condor.spec
- docs/version-history/lts-versions-23-0.rst
- src/condor_scripts/condor_gather_info
> HTCONDOR-2094: condor_gather_info updates

- docs/version-history/lts-versions-23-0.rst
- src/condor_utils/submit_utils.cpp
> HTCONDOR-2201 disallow some likely request_gpus_* mistakes in submit

- src/condor_tools/htcondor_cli/eventlog.py
Added ability for `htcondor eventlog read` to take multiple log files as arguments from the cli
> Read multiple log files

- docs/version-history/lts-versions-23-0.rst
- src/condor_scripts/adstash/interfaces/elasticsearch.py
- src/condor_scripts/adstash/interfaces/opensearch.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2167
> HTCONDOR-2167 Improve search engine timeouts in condor_adstash

- docs/man-pages/htcondor.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_tools/htcondor_cli/eventlog.py
> HTCONDOR-2200  htcondor cli eventlog read many

- src/condor_credd/condor_credmon_oauth/condor_vault_storer
- src/condor_submit.V6/submit.cpp
- src/condor_utils/submit_utils.cpp
> HTCONDOR-2096 cred-storer-opts

- docs/STYLE.md
- docs/automated-workflows/dagman-introduction.rst
- docs/conf.py
- docs/extensions/ad-attr.py
- docs/extensions/htc_helpers.py
- docs/full_conf.py
> HTCONDOR-2221: New :ad-attr: extension

- src/condor_utils/read_user_log.cpp
> HTCONDOR-2223 Better dprintf levels for read_user_log

- docs/conf.py
> HTCONDOR-2228: Fix classad-attribute-def on el7

- docs/classads/print-formats.rst
- src/condor_utils/make_printmask.cpp
> HTCONDOR-2229-fix-descending-spelling

- docs/admin-manual/ap-policy-configuration.rst
- docs/admin-manual/cm-configuration.rst
- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/ep-policy-configuration.rst
- docs/admin-manual/file-and-cred-transfer.rst
- docs/classad-attributes/classad-types.rst
- docs/classad-attributes/collector-classad-attributes.rst
- docs/classad-attributes/daemon-core-statistics-attributes.rst
- docs/classad-attributes/daemon-master-classad-attributes.rst
- docs/classad-attributes/job-classad-attributes.rst
- docs/classad-attributes/machine-classad-attributes.rst
- docs/classad-attributes/negotiator-classad-attributes.rst
- docs/classad-attributes/scheduler-classad-attributes.rst
- docs/classads/classad-mechanism.rst
- docs/classads/transforms.rst
- docs/cloud-computing/annex-customization-guide.rst
- docs/cloud-computing/annex-users-guide.rst
- docs/cloud-computing/condor-in-the-cloud.rst
- docs/cloud-computing/introduction-cloud-computing.rst
- docs/cloud-computing/using-annex-first-time.rst
> HTCONDOR-2233 spell check manual

- src/classad/classad.cpp
> HTCONDOR-2234 Fix memory leak in classad introduced in HTCONDOR-2158

- src/condor_had/AbstractReplicatorStateMachine.cpp
- src/condor_had/AbstractReplicatorStateMachine.h
- src/condor_had/ReplicatorStateMachine.cpp
- src/condor_had/ReplicatorStateMachine.h
- src/condor_had/StateMachine.cpp
- src/condor_had/StateMachine.h
- src/condor_had/Utils.h
> HTCONDOR-2237 had-lists

- src/condor_daemon_client/dc_schedd.cpp
- src/condor_tools/qusers.cpp
- src/condor_utils/dprintf.cpp
> HTCONDOR-2235 fix warnings

- docs/version-history/lts-versions-23-0.rst
- src/condor_dagman/dag.cpp
> HTCONDOR-2240: Prevent retry node that got an abort event from setting descendants to futile state

- src/condor_collector.V6/collector_engine.cpp
- src/condor_collector.V6/collector_engine.h
- src/condor_q.V6/queue.cpp
- src/condor_status.V6/prettyPrint.cpp
- src/condor_status.V6/prettyPrint.h
- src/condor_status.V6/status.cpp
- src/condor_tools/history.cpp
- src/condor_utils/classad_oldnew.cpp
- src/condor_utils/compat_classad.cpp
- src/condor_utils/compat_classad.h
- src/condor_utils/read_multiple_logs.cpp
- src/condor_utils/read_multiple_logs.h
- src/condor_utils/stl_string_utils.cpp
> HTCONDOR-2237 remove-stringlists

- src/classad/classad/classad.h
> HTCONDOR-2234 fix classad memory leak introduced in HTCONDOR-2158

- docs/version-history/lts-versions-23-0.rst
- src/condor_starter.V6.1/starter.cpp
> HTCONDOR-2242 set NVIDIA_VISIBLE_DEVICES env var to full gpu uuid

- build/nmi-build/build-batlab-images.sh
- build/nmi-build/setup.sh
- Use apt-get instead of apt
- Use preferred repository key management
- Push images to Docker hub in parallel
> HTCONDOR-2244: Improvements to building NMI Docker images

- docs/version-history/feature-versions-23-x.rst
- src/condor_collector.V6/collector.cpp
> HTCONDOR-2245 fix bug where NEGOTIATOR_SLOT_CONSTRAINT was ignored

- build/nmi-build/setup.sh
- Install released HTCondor on openSUSE (not from test repo)
- Supply apt-utils to suppress warnings on ubuntu:focal
> HTCONDOR-2244: Minor NMI build image fixes

- docs/version-history/lts-versions-23-0.rst
- src/condor_utils/config.cpp
This also eliminates extra copies of here-file contents.
> HTCONDOR-2249 config-crash

- docs/grid-computing/job-router.rst
> HTCONDOR-2062 router-docs

- src/condor_scripts/get_htcondor
> HTCONDOR-2235: Use preferred (non-deprecated) method for debian repo key

- src/classad/classad/exprTree.h
- src/classad/exprTree.cpp
- src/condor_starter.V6.1/filter.cpp
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_filter.cpp
- src/condor_tests/test_filter.py
This reverts commit dec9cef5f161c5c593c48a447cb2a85a53f071f0.
> (HTCONDOR-2122)  Now with more C++20.

- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_negotiator_slot_const.py
> HTCONDOR-2250-add-negotiator-slot-const-test

- docs/version-history/feature-versions-23-x.rst
- src/condor_tools/wait.cpp
- src/condor_utils/condor_event.cpp
- src/condor_utils/condor_event.h
- src/condor_utils/data_reuse.cpp
- src/condor_utils/file_modified_trigger.cpp
- src/condor_utils/file_modified_trigger.h
- src/condor_utils/read_user_log.cpp
- src/condor_utils/read_user_log.h
- src/condor_utils/read_user_log_state.h
- src/condor_utils/write_user_log.cpp
- src/python-bindings/event.cpp
by having it always read lines and have less need to seek to recover from short reads.
> HTCONDOR-2254 Improve eventlog reader reliability

- src/condor_startd.V6/ResAttributes.cpp
> HTCONDOR-2235 Only warn once in dprintf log about rotational detection

- src/condor_daemon_core.V6/daemon_core.cpp
> HTCONDOR-2235: Don't warn about mysin len 0 in DAGMan

- build/nmi-build/setup.sh
- build/packaging/debian/condor-test.install.in
- build/packaging/debian/control.in
- build/packaging/debian/copyright.in
- build/packaging/debian/prepare-build-files.sh
- build/packaging/debian/rules.in
- nmi_tools/glue/build/build_uw_deb.sh
- nmi_tools/glue/build/make-tarball-from-debs
- nmi_tools/glue/build/remote_post.pl
- perpare-build-files default path matches most recent Debian
- Migrate to new debug symbols
- Account for Ubuntu putting symbols in ddeb files
> HTCONDOR-2261: Update Debian build files

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_utils/CMakeLists.txt
- src/condor_utils/nvidia_utils.cpp
- src/condor_utils/nvidia_utils.h
- src/condor_utils/param_info.in
- src/condor_utils/proc_family_direct_cgroup_v1.cpp
- src/condor_utils/proc_family_direct_cgroup_v1.h
> HTCONDOR-1152: isolate GPUs with cgroups v1

- bindings/python/htcondor2/_submit.py
- src/condor_dagman/condor_submit_dag.cpp
- src/condor_dagman/dagman_main.cpp
- src/condor_utils/dagman_utils.cpp
- src/condor_utils/dagman_utils.h
- src/python-bindings/htcondor2/submit.cpp
- src/python-bindings/htcondor2_impl.cpp
> HTCONDOR-2238 mechanical dagman options display and parse

- build/packaging/debian/copyright.in
- docs/conf.py
> HTCONDOR-2235 bump copyright in manual to 2024

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_startd.V6/ResAttributes.cpp
- src/condor_tests/lib_meta_knob.run
- src/condor_utils/param_info.in
> HTCONDOR-2264 Enable GPUs custom resource by default

- docs/version-history/feature-versions-23-x.rst
- src/condor_shadow.V6.1/remoteresource.cpp
> HTCONDOR-2265 no log bogus execute duration

- src/condor_tests/disable_owner_test.run
> HTCONDOR-2268 robustify disable_owner_test

- src/condor_dagman/dagman_main.cpp
> HTCONDOR-2235 disable classad cache for dagman

- docs/admin-manual/file-and-cred-transfer.rst
> HTCONDOR-1881 First cut at documenting krb5 job ticket workflow

- src/condor_tests/test_parallel_uni.py
> HTCONDOR-2235 Robustify parallel universe test

- src/condor_dagman/dagman_main.cpp
- src/condor_utils/dagman_utils.cpp
- src/condor_utils/dagman_utils.h
- src/python-bindings/schedd.cpp
-Fixed extend() to internally call set() to reduce code
duplication and possible future functionality skew
-Updated GetFromEnv option to be a string list rather than
single string to remove unneeded special case code. Updated
appropriate call sites to call extend() rather than removed
append()
-Removed obsolete append()
-Moved AutoParse() map of bool options to used flags to be a class
member rather that local static variable
-Added handling for AutoParse to use addDAGFile() for -Dag flag
used by DAGMan main
- …
> HTCONDOR-2235: Minor DAGMan options cleanup

- docs/version-history/lts-versions-23-0.rst
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_master.V6/masterDaemon.cpp
- src/condor_utils/CMakeLists.txt
- src/condor_utils/largestOpenFD.cpp
- src/condor_utils/largestOpenFD.h
- src/condor_utils/my_popen.cpp
> HTCONDOR-2270 backport fd closing faster

- src/condor_includes/proc.h
- src/condor_q.V6/queue.cpp
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_tests/ornithology/jobs.py
- src/condor_utils/condor_q.cpp
- src/condor_utils/history_utils.h
- src/condor_utils/print_format_tables.cpp
- src/condor_utils/proc.cpp
> HTCONDOR-2035 render potential future job states in condor_q

- src/condor_tests/lib_meta_knob.run
- src/condor_utils/param_info.in
rely on the code to set it properly
> HTCONDOR-2271 Remove NVIDIA_VISIBLE_DEVICES from param table

- docs/version-history/lts-versions-23-0.rst
- src/condor_io/condor_secman.cpp
> HTCONDOR-2272 ec key macos

- docs/users-manual/automatic-job-management.rst
Observation that it is confusing to use 2 hours in example when 2 is also a job status.
> HTCONDOR-2235 changes per rcfs

- src/condor_tests/test_negotiator_slot_const.py
- src/condor_unit_tests/OTEST_Directory.cpp
> HTCONDOR-2235 robustify tests

- build/packaging/rpm/condor.spec
- docs/version-history/feature-versions-23-x.rst
- src/condor_tests/CMakeLists.txt
- src/condor_utils/CMakeLists.txt
> HTCONDOR-2278 remove libcondorapi

- docs/admin-manual/configuration-macros.rst
- docs/automated-workflows/dagman-resubmit-failed.rst
- docs/automated-workflows/node-pass-or-fail.rst
- src/condor_dagman/condor_submit_dag.cpp
- src/condor_dagman/dagman_main.cpp
> HTCONDOR-2279 deprecate DAGMan full rescue files

- src/condor_tests/job_dagman_node_status.cmd
- src/condor_tests/job_dagman_node_status.pl
> HTCONDOR-2235: Changes for job_dagman_node_status test

- docs/classad-attributes/scheduler-classad-attributes.rst
> HTCONDOR-2077: Document missing Transfer Queue Attributes in Schedd Ad

- build/cmake/CondorConfigure.cmake
- build/packaging/debian/rules.in
- build/packaging/rpm/condor.spec
- docs/version-history/feature-versions-23-x.rst
- nmi_tools/condor_nmi_submit
- nmi_tools/glue/build/build_uw_rpm.sh
- nmi_tools/glue/build/pre_all
- nmi_tools/glue/build/remote_declare.pl
- nmi_tools/glue/build/remote_pre.pl
- src/condor_tools/version.cpp
- src/condor_utils/condor_version.cpp
> HTCONDOR-532: Add GitSHA to Version String

- docs/users-manual/submitting-a-job.rst
> HTCONDOR-2067 better vault/scitoken docs

- docs/version-history/lts-versions-23-0.rst
- src/condor_filetransfer_plugins/multifile_curl_plugin.cpp
> HTCONDOR-2273 ftp file xfer plugin

- src/condor_scripts/run_test.pl
> HTCONDOR-2287 remove NVIDIA_VISIBLE_DEVICES env var from testing env

- docs/version-history/lts-versions-23-0.rst
- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_gridmanager/gahp-client.cpp
> HTCONDOR-2286 gahp-orphans

- docs/version-history/lts-versions-23-0.rst
- src/condor_dagman/job.cpp
- src/condor_dagman/parse.cpp
> HTCONDOR-2291: Don't allow the provisioner node to have parent nodes

- docs/version-history/feature-versions-23-x.rst
- src/condor_utils/docker-api.cpp
> HTCONDOR-2294-docker-host-network

- docs/version-history/lts-versions-23-0.rst
- src/condor_shadow.V6.1/NTreceivers.cpp
>  HTCONDOR-2292 no-terminate

- src/condor_includes/condor_attributes.h
- src/condor_utils/job_ad_instance_recording.cpp
> HTCONDOR-2289: Rename epoch write attribute from *Time to *Date

- src/condor_q.V6/jobmatch.cpp
- src/condor_startd.V6/ResAttributes.cpp
- src/condor_startd.V6/ResAttributes.h
- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/ResMgr.h
- src/condor_startd.V6/Resource.cpp
- src/condor_startd.V6/Resource.h
- src/condor_startd.V6/command.cpp
- src/condor_startd.V6/slot_builder.cpp
- src/condor_starter.V6.1/jic_shadow.cpp
- src/condor_starter.V6.1/starter.cpp
- src/condor_starter.V6.1/starter.h
- src/condor_utils/expr_analyze.cpp
- src/condor_utils/expr_analyze.h
- src/condor_utils/file_transfer.cpp
- src/condor_utils/file_transfer.h
New statistics to count claims, activations, and dslots that don't match when created. Added match analysis to StartLog for dslots that don't match when created.
> HTCONDOR-2257 p-slots handle mismatch in backfill vs. primary resources.

- docs/admin-manual/ap-policy-configuration.rst
> HTCONDOR-2284 Add performance tuning of the AP to docs

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
> HTCONDOR-2290 Docs for ETC param knob

- src/condor_schedd.V6/checkpoint_cleanup.cpp
- src/condor_scripts/cleanup_locally_mounted_checkpoint
- src/condor_shadow.V6.1/pseudo_ops.cpp
- src/condor_shadow.V6.1/remoteresource.cpp
- src/condor_starter.V6.1/filter.cpp
- src/condor_starter.V6.1/jic_shadow.cpp
- src/condor_starter.V6.1/jic_shadow.h
- src/condor_starter.V6.1/job_info_communicator.h
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_starter.V6.1/vanilla_proc.h
- src/condor_tests/CMakeLists.txt
- src/condor_tests/conftest.py
- src/condor_tests/test_checkpoint_destination_two.py
- src/condor_tools/manifest.cpp
- src/condor_utils/file_transfer.cpp
- src/condor_utils/manifest.cpp
- src/condor_utils/manifest.h
The starter will now name all checkpoint upload attempts, and notify the shadow when one fails.  The shadow renames the failed upload's MANIFEST file to a FAILURE file, so that if its attempt at clean-up fails, `condor_preen` will know that it's OK if some of the files named in the FAILURE file don't exist (and therefore can't be removed).  This is achieved by a new '-ignore-missing-files' flag, which the shadow then uses to try to clean the failed checkpoint up immediately.
In order to make sure that errors in uploading a checkpoint from the starter don't result in the corresponding MANIFEST file being deleted on the shadow side, we delay reporting the error on the shadow side until after the corresponding download loop is done.  This (currently) implies that we don't log the transfer …
> (HTCONDOR-2178)  Clean up after failured checkpoint uploads.

- src/condor_tests/job_test_logrotation.run
> HTCONDOR-2235 speedup job_test_logrotation

- src/condor_io/condor_auth_ssl.cpp
- src/condor_utils/globus_utils.cpp
> HTCONDOR-2256 voms ssl fixes

- docs/classad-attributes/job-classad-attributes.rst
- docs/man-pages/condor_submit.rst
> HTCONDOR-2062 Minor doc corrections for streaming and container universe

- docs/admin-manual/ep-policy-configuration.rst
- docs/faq/admins/breadth-first.rst
- docs/faq/admins/index.rst
- docs/faq/index.rst
- docs/faq/users/index.rst
- docs/faq/users/prefer-gpu-to-cpu.rst
In contrast to GregT's effort (#2165).
> HTCONDOR-2200  First pass at an FAQ/recipe/example section.

- docs/admin-manual/configuration-macros.rst
- docs/man-pages/condor_ssh_to_job.rst
> HTCONDOR-2284 Improve ssh_to_job docs

- src/condor_tests/conftest.py
> HTCONDOR-2301 fix python error in some pytest versions in conftest.py

- docs/automated-workflows/dagman-using-other-dags.rst
> HTCONDOR-2284: DAGMan doc reorg| DAG w/ DAGs cleanup

- docs/version-history/lts-versions-23-0.rst
- msconfig/WiX/xml/win.xsl.in
> HTCONDOR-2302 Windows MSI installer fix for install dir with spaces

- src/annex/annex.cpp
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_dagman/dagman_main.cpp
- src/condor_io/cedar.t.unix.cpp
- src/condor_negotiator.V6/matchmaker.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_startd.V6/vmuniverse_mgr.cpp
- src/condor_starter.V6.1/starter.cpp
- src/condor_tools/config_val.cpp
- src/condor_tools/give_interactive.cpp
- src/condor_tools/preen.cpp
- src/condor_tools/test_auth.cpp
- src/condor_tools/transfer_data.cpp
- src/condor_utils/file_transfer.cpp
- src/condor_utils/simple_arg.cpp
- src/condor_utils/userlog_to_classads.cpp
- src/condor_utils/write_user_log.cpp
- src/condor_who/who.cpp
> HTCONDOR-2284 Remove duplicate #include in any given file

- build/docker/services/build-images
we don't use it and it's going to go away.
> HTCONDOR-2313: Remove alias for the deprecated "dockerreg.chtc.wisc.edu" registry

- docs/admin-manual/configuration-macros.rst
> HTCONDOR-2284 fix missing backtick in docs

- src/condor_startd.V6/CMakeLists.txt
- src/condor_startd.V6/ResMgr.cpp
> HTCONDOR-2288 fix warnings

- docs/version-history/feature-versions-23-x.rst
- src/condor_io/condor_auth_passwd.cpp
- src/condor_unit_tests/FTEST_stl_string_utils.cpp
- src/condor_utils/stl_string_utils.cpp
- src/condor_utils/stl_string_utils.h
> HTCONDOR-232 token perms

- src/condor_scripts/get_htcondor
> HTCONDOR-505: Invoke apt-get in noninteractive mode in get_htcondor

- docs/version-history/lts-versions-23-0.rst
- src/condor_starter.V6.1/user_proc.cpp
doing so causes the event log parser to become confused.
> HTCONDOR-2305  Don't pass newlines from the job wrapper into the error message;

- docs/admin-manual/file-and-cred-transfer.rst
> HTCONDOR-2284 Touch up krb5 admin docs

- docs/version-history/feature-versions-23-x.rst
- src/condor_tools/htcondor_cli/eventlog.py
eventlog reader to avoid leap year issues
> HTCONDOR-2318 Use years when parsing eventlog in htcondor cli

- docs/full_conf.py
> HTCONDOR-2284 improve doc code block config regex for use statements

- src/condor_utils/largestOpenFD.cpp
- src/condor_utils/nvidia_utils.cpp
- src/condor_utils/proc_family_direct_cgroup_v1.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.cpp
> HTCONDOR-2288 use non-throwing version of stdfs::directory_iterator

- docs/version-history/feature-versions-23-x.rst
> HTCONDOR-2284 fix jira: --> :jira: in version history

- src/condor_scripts/adstash/ad_sources/registry.py
> HTCONDOR-2316 fix typo in adstash

- docs/classads/transforms.rst
- docs/grid-computing/job-router.rst
Make command syntax clearer, matching the style in the general transform docs.
> HTCONDOR-2062 Improve docs for Job Router route syntax

- docs/classad-attributes/job-classad-attributes.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_includes/condor_attributes.h
- src/condor_tests/cmd_q_protocols.run
- src/condor_utils/submit_utils.cpp
> HTCONDOR-2319 job attr submit file

- build/packaging/debian/control.in
- build/packaging/rpm/condor.spec
- docs/version-history/feature-versions-23-x.rst
> HTCONDOR-2295: Weak dependency for Pelican OSDF file transfer plugin

- src/condor_utils/log_transaction.cpp
- src/condor_utils/log_transaction.h
> HTCONDOR-2288 replace List with std::vector in LogTransaction

- docs/admin-manual/networking.rst
- docs/faq/users/prefer-gpu-to-cpu.rst
> HTCONDOR-2284 fixup recipe example as per RCF feedback

- src/condor_starter.V6.1/os_proc.cpp
- src/condor_starter.V6.1/parallel_proc.cpp
- src/condor_starter.V6.1/remote_proc.cpp
- src/condor_starter.V6.1/script_proc.cpp
- src/condor_starter.V6.1/sshd_proc.cpp
- src/condor_starter.V6.1/tool_daemon_proc.cpp
- src/condor_starter.V6.1/user_proc.cpp
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_starter.V6.1/vm_proc.cpp
> HTCONDOR-2288 Quiet non-useful dprintf D_FULLDEBUGs in starter

- src/condor_dagman/dagman_metrics.cpp
- src/condor_dagman/dagman_metrics.h
> HTCONDOR-2288: Remove dead code for in DAGMan metrics file

- docs/man-pages/condor_submit.rst
- docs/users-manual/env-of-job.rst
- src/condor_includes/condor_attributes.h
- src/condor_scripts/adstash/convert.py
- src/condor_tests/cmd_submit_regress_dry.expect
- src/condor_tests/cmd_submit_regress_dry.subs
- src/condor_utils/docker-api.cpp
- src/condor_utils/submit_utils.cpp
- src/condor_utils/submit_utils.h
> HTCONDOR-2321 docker entrypoint

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_dagman/dagman_main.cpp
- src/condor_utils/param_info.in
> HTCONDOR-2323: Change DAGMan default to not suppress email notifications

- src/condor_utils/condor_query.h
- src/condor_utils/generic_query.cpp
- src/condor_utils/generic_query.h
> HTCONDOR-2288 replace List with vector in generic_query

- docs/classad-attributes/machine-classad-attributes.rst
> HTCONDOR-2325 better loadavg docs

- build/packaging/debian/condor.postinst
- docs/version-history/lts-versions-23-0.rst
> HTCONDOR-2306: Debian install condor with multiple LDAP condor users

- src/condor_credd/condor_credmon_oauth/condor_vault_storer
- src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/VaultCredmon.py
This makes the following changes to the condor vault integration:
1. When `condor_vault_storer` is requested to do a token exchange with non-default scopes and/or audience, it now only calls `condor_store_cred` when the list has changed.  This can make a significant difference in the amount of requests to vault when there is a user that starts a lot of jobs with the same token.
2. It adds a new configuration variable `SEC_CREDENTIAL_VAULT_STORER_OPTS` to `condor_vault_storer` so anybody can pass in `-v` or `-d` options for debugging.  Previously that could be done by redefining `SEC_CREDENTIAL_STORER` but condor 23 now attempts to execute the whole value instead of parsing it at the blank and passing everything after the blank as an option.
3. It adds removal of vault credentials to …
> HTCONDOR-2232 Vault integration improvements

- docs/version-history/lts-versions-23-0.rst
> HTCONDOR-2232 vault-improvement-docs

- src/condor_filetransfer_plugins/multifile_curl_plugin.cpp
> (HTCONDOR-2310)  Add ProtocolVersion to the curl plug-in.

- docs/version-history/feature-versions-23-x.rst
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/scheduler.h
> HTCONDOR-2324 condor scratch dir in local uni

- build/packaging/debian/control.in
- build/packaging/rpm/condor.spec
Plus some comment updates to help my remember future work.
> HTCONDOR-2311: Weak dependency on bash-completion

- docs/version-history/feature-versions-23-x.rst
- src/condor_job_router/JobRouter.cpp
> HTCONDOR-2329 router-grid-resource-2

- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_schedd.V6/dedicated_scheduler.h
> HTCONDOR-2288 replace List with std::list in ded sched

- src/condor_schedd.V6/checkpoint_cleanup.cpp
- src/condor_shadow.V6.1/pseudo_ops.cpp
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_tests/test_checkpoint_destination.py
- src/condor_tests/test_checkpoint_destination_two.py
- src/condor_tools/manifest.cpp
- src/condor_utils/checkpoint_cleanup_utils.cpp
- src/condor_utils/checkpoint_cleanup_utils.h
- src/condor_utils/dc_coroutines.cpp
- src/condor_utils/dc_coroutines.h
- src/condor_utils/manifest.cpp
After successfully uploading a checkpoint, the starter now explicitly notifies the shadow.  The shadow looks at the MANIFEST and FAILURE files on disk and moves all but the most-recent _k_ (default 2) from the job's spool directory proper to the part of the spool where they can be cleaned up.  (The schedd creates and owns several directories between the SPOOL directory and the job's spool, and nothing but the schedd can safely remove those intermediate directories, so we can't clean them up from the checkpoint-cleanup script.)  It then runs the appropriate checkpoint clean-up script.
The test modifies the test from HTCONDOR-2178 to assert that only the two most-recent checkpoints survive.
- Hit the merge button if the pull request is approved and it is not a security patch (security …
> (HTCONDOR-2179)  Clean up successful checkpoints while the job is running.

- src/condor_includes/condor_attributes.h
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_failure_files.py
- src/condor_utils/file_transfer.cpp
> (HTCONDOR-2328)  Implement test and back-end for failure files.

- src/condor_status.V6/prettyPrint.cpp
- src/condor_status.V6/prettyPrint.h
- src/condor_status.V6/status.cpp
- src/condor_utils/ad_printmask.cpp
- src/condor_utils/ad_printmask.h
- src/condor_utils/make_printmask.cpp
- src/condor_who/who.cpp
> HTCONDOR-2288 Remove List from ad_mask, replace with vector

- docs/version-history/feature-versions-23-x.rst
- src/condor_sysapi/ncpus.cpp
- src/condor_tests/job_hyperthread_check.run
> HTCONDOR-727  startd reads omp num threads for cpus

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/ep-policy-configuration.rst
- docs/admin-manual/logging.rst
> HTCONDOR-1783: Remove warnings about LVM disk enforcement

- docs/version-history/upgrading-from-23-0-to-24-0-versions.tmpl
> HTCONDOR-2260 Add upgrade note for old job route syntax

- docs/admin-manual/configuration-macros.rst
> HTCONDOR-716 update job router docs

- docs/man-pages/htcondor.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_tools/htcondor_cli/job.py
> HTCONDOR-2182  htcondor cli out err log

- docs/version-history/feature-versions-23-x.rst
- src/condor_tools/token_list.cpp
> HTCONDOR-575 add -file option to condor_token_list

- docs/man-pages/condor_submit.rst
> HTCONDOR-2284  Remove example of deprecated use of multiple queue in

- docs/version-history/feature-versions-23-x.rst
- src/condor_sysapi/phys_mem.cpp
that amount of memory for jobs to use.
> HTCONDOR-727 If an EP starts in a cgroup with a memory limit, advertise

- docs/users-manual/env-of-job.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_starter.V6.1/starter.cpp
> HTCONDOR-2337 Set SINGULARITY_CACHEDIR and APPTAINER_CACHEDIR

- docs/users-manual/env-of-job.rst
> HTCONDOR-2337: Fix duplicated env variable in manual

- docs/classad-attributes/job-classad-attributes.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_includes/condor_attributes.h
- src/condor_schedd.V6/qmgr_job_updater.cpp
- src/condor_shadow.V6.1/baseshadow.cpp
> HTCONDOR-1896 save shadow exception in job ad

- docs/version-history/lts-versions-23-0.rst
- src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/LocalCredmon.py
- src/condor_credd/condor_credmon_oauth/examples/config/condor/40-oauth-credmon.conf
- src/condor_utils/param_info.in
> HTCONDOR-2285 properly name the locally issued scitokens "scitoken:2.0"

- src/classad/classad/classad.h
- src/condor_tests/test_classad_eval.py
> HTCONDOR-2327 Implement classad in memory storage as a flat map

- src/classad/fnCall.cpp
> HTCONDOR-2342 Port to pcre2 10.43

- src/ccb/ccb_listener.cpp
- src/condor_daemon_client/dc_collector.cpp
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_dagman/dagman_main.cpp
- src/condor_io/shared_port_endpoint.cpp
- src/condor_io/sock.cpp
- src/condor_master.V6/masterDaemon.cpp
- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_shadow.V6.1/remoteresource.cpp
- src/condor_shadow.V6.1/shadow.cpp
- src/condor_startd.V6/Starter.cpp
- src/condor_starter.V6.1/jic_shadow.cpp
- src/condor_starter.V6.1/starter.cpp
- src/condor_sysapi/processor_flags.cpp
- src/condor_tests/test_for_AwaitableDeadlineReaper.cpp
- src/condor_tools/testwritelog.cpp
- src/condor_utils/classadHistory.cpp
- src/condor_utils/condor_config.cpp
- src/condor_utils/dagman_utils.cpp
- src/condor_utils/wait_for_user_log.cpp
- src/gangliad/statsd.cpp
> HTCONDOR-2335 except-newlines

- src/condor_scripts/condor_remote_cluster
The OSPool will be using our blessed RCs from the update subdirectory of the tarball area. condor_remote_cluster needs to know about the update subdirectory for blessed RCs.
> HTCONDOR-2341: Take blessed RC tarball from update subdirectory

- src/condor_starter.V6.1/starter.cpp
- src/condor_starter.V6.1/starter.h
> HTCONDOR-2288 delist starter, replace with vector

- docs/admin-manual/configuration-macros.rst
- docs/extensions/macro.py
- docs/version-history/feature-versions-23-x.rst
- docs/version-history/lts-versions-23-0.rst
> HTCONDOR-2284 fix doc warnings

- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_daemon_core.V6/daemon_core.cpp
> HTCONDOR-2335 Remove List from DaemonCore

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_tools/preen.cpp
- src/condor_utils/param_info.in
- src/gangliad/gangliad.cpp
- src/gangliad/statsd.cpp
- src/gangliad/statsd.h
[See JIRA ticket.](https://opensciencegrid.atlassian.net/browse/HTCONDOR-2346)
> HTCONDOR-2346 Reset unpublished ganglia aggregate metrics back to zero

- src/condor_collector.V6/offline_plugin.cpp
- src/condor_submit.V6/submit.cpp
- src/condor_utils/submit_utils.cpp
- src/condor_utils/submit_utils.h
This PR `moves process_job_credentials()` from `condor_submit` to the submit utils.  This brought a few other functions along (that weren't called anywhere else and therefore didn't need to be exposed).  There were two other sets of changes: changes to remove dependencies on `condor_submit` globals, and changes to avoid calling `exit()` and instead report the error (because library code should probably never `exit()`).
To get a better sense of the changes, check out main and copy-and-paste the functions in the patch into a temporary files; then checkout the branch and do the same into a different file (the original files will be different); maintain the same order.  Then diff the two temporary files.
This PR does _not_ attempt to make the Python bindings (either version) or …
> (HTCONDOR-2293)  Refactor credential-handling code.

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/networking.rst
> HTCONDOR-2344 Add docs for TCP_FORWARDING_HOST

- docs/admin-manual/cm-configuration.rst
- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/ep-policy-configuration.rst
- docs/admin-manual/logging.rst
- docs/admin-manual/security.rst
- docs/extensions/ad-attr.py
- docs/extensions/config-template.py
- docs/extensions/dag-cmd.py
- docs/extensions/htc_helpers.py
- docs/extensions/macro.py
- docs/extensions/subcom.py
> HTCONDOR-2344 various doc improvements

- docs/admin-manual/cm-configuration.rst
- docs/admin-manual/configuration-macros.rst
> HTCONDOR-2344 fix doc warnings

- docs/version-history/lts-versions-23-0.rst
- src/condor_shadow.V6.1/baseshadow.cpp
- src/condor_starter.V6.1/user_proc.cpp
> HTCONDOR-2343 shadow exception msg

- src/condor_schedd.V6/schedd.cpp
> HTCONDOR-495 fix minor leak in schedd if MachineAttrs is doubled

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_includes/condor_cron_job.h
- src/condor_includes/condor_cron_job_list.h
- src/condor_includes/condor_cron_job_mgr.h
- src/condor_includes/condor_debug.h
- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/ResMgr.h
- src/condor_startd.V6/Resource.h
- src/condor_startd.V6/startd_bench_job_mgr.cpp
- src/condor_startd.V6/startd_cron_job.cpp
- src/condor_startd.V6/startd_cron_job_mgr.cpp
- src/condor_startd.V6/startd_main.cpp
- src/condor_startd.V6/startd_named_classad_list.cpp
- src/condor_utils/cron_job_list.cpp
- src/condor_utils/cron_job_mgr.cpp
- src/condor_utils/dprintf_common.cpp
- src/condor_utils/param_info.in
> HTCONDOR-2308 Use STARTD daemon ad to evaluate STARTD_CRON CONDITION

- bindings/python/CMakeLists.txt
- bindings/python/htcondor2/__init__.py
- bindings/python/htcondor2/_ad_type.py
- bindings/python/htcondor2/_daemon_command.py
- bindings/python/htcondor2/_loose_functions.py
- bindings/python/htcondor2/_schedd.py
- bindings/python/htcondor2/_submit_result.py
- docs/apis/python-bindings/api/version2/htcondor2/enums.rst
- docs/apis/python-bindings/api/version2/htcondor2/module.rst
- src/python-bindings/common2/py_util.cpp
- src/python-bindings/htcondor2/loose_functions.cpp
- src/python-bindings/htcondor2/schedd.cpp
- src/python-bindings/htcondor2_impl.cpp
> HTCONDOR-2309: New Python bindings, part 4.

- docs/version-history/lts-versions-23-0.rst
- src/condor_utils/submit_utils.h
- src/python-bindings/schedd.cpp
> HTCONDOR-2351: Fix DAGMan crash caused by queue for each data

- src/condor_c-gahp/schedd_client.cpp
- src/condor_daemon_client/dc_collector.cpp
- src/condor_daemon_client/dc_schedd.cpp
- src/condor_daemon_client/dc_schedd.h
- src/condor_daemon_client/dc_transfer_queue.cpp
- src/condor_gridmanager/gridmanager.cpp
- src/condor_includes/proc.h
- src/condor_job_router/submit_job.cpp
- src/condor_rm.V6/rm.cpp
- src/condor_schedd.V6/qmgr_job_updater.cpp
- src/python-bindings/htcondor2/schedd.cpp
- src/python-bindings/schedd.cpp
> HTCONDOR-2335 dc-schedd-stringlist

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/security.rst
- docs/version-history/feature-versions-10-x.rst
- docs/version-history/lts-versions-23-0.rst
> HTCONDOR-2344 fix warnings

- docs/STYLE.md
- docs/extensions/macro.py
> HTCONDOR-2344: all macro defs anywhere with correct refencing

- src/condor_startd.V6/startd_cron_job_mgr.cpp
> HTCONDOR-2335 fix warning with missing dprintf argument

- docs/version-history/lts-versions-23-0.rst
- src/condor_q.V6/jobmatch.cpp
- src/condor_utils/expr_analyze.cpp
> HTCONDOR-2355 Improve -better-analyze handling of ?: expressions

- docs/version-history/lts-versions-23-0.rst
- src/condor_utils/file_transfer.cpp
> HTCONDOR-2353  Don't create directories on AP when `output_destination` is set.

- docs/admin-manual/networking.rst
> HTCONDOR-2344 Add mermaid diagrams to ccb

- src/condor_who/who.cpp
> HTCONDOR-2355 remove List from condor_who

- docs/version-history/lts-versions-23-0.rst
- src/condor_daemon_core.V6/daemon_core.cpp
> HTCONDOR-2357 no shadow kill randos

- docs/admin-manual/configuration-macros.rst
> HTCONDOR-2344: Add missing DAGMan config definition and deverbosify

- src/condor_daemon_core.V6/daemon_core.cpp
> HTCONDOR-2335 Always dprintf when we ShutdownGraceful

- src/condor_daemon_core.V6/daemon_core_main.cpp
> HTCONDOR-2360 signal-source

- src/condor_tools/transform_ads.cpp
- src/condor_userlog/condor_check_userlogs.cpp
- src/condor_utils/env.cpp
- src/condor_utils/env.h
- src/condor_utils/java_config.cpp
- src/condor_utils/which.cpp
> HTCONDOR-2335 one-less-strlist

- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_shadow.V6.1/pseudo_ops.cpp
- src/condor_utils/checkpoint_cleanup_utils.cpp
- src/condor_utils/dc_coroutines.cpp
- src/condor_utils/dc_coroutines.h
- src/condor_utils/param_info.in
> (HTCONDOR-2359) Fix checkpoint clean-up code.

- src/condor_startd.V6/Resource.cpp
- src/condor_utils/compat_classad_util.cpp
> HTCONDOR-2335 fix warnings

- src/condor_utils/MyString.h
- src/condor_utils/classad_usermap.cpp
- src/condor_utils/compat_classad.cpp
- src/condor_utils/compat_classad_util.h
- src/condor_utils/test_macro_expand.cpp
- src/condor_utils/test_user_mapping.cpp
> HTCONDOR-2335 convert-string-lists

- docs/faq/admins/index.rst
- docs/faq/admins/slot-attrs.rst
> HTCONDOR-2344 Add example FAQ for slot-attrs

- src/condor_io/condor_auth_passwd.cpp
- src/condor_io/condor_crypt.cpp
- src/condor_io/condor_crypt_aesgcm.cpp
- src/condor_io/condor_secman.cpp
- src/condor_utils/get_random_num_secure.cpp
We didn't use to check this, so an assertion, while not perfect is at least better than where we were before
and replace a stringstring with a string while we are here.
> HTCONDOR-338 Assert if RAND_bytes returns an error

- src/condor_utils/submit_utils.cpp
> HTCONDOR-2315 never transfer interactive exe

- src/condor_utils/remote_close.WINDOWS.cpp
- src/condor_utils/system_info.WINDOWS.cpp
- src/condor_utils/system_info.WINDOWS.h
> HTCONDOR-2288 remove List from windows system_info

- src/condor_dagman/dagman_main.cpp
- src/condor_io/condor_auth_passwd.cpp
- src/condor_io/condor_auth_ssl.cpp
- src/condor_job_router/JobRouterHookMgr.cpp
- src/condor_startd.V6/StartdHookMgr.cpp
- src/condor_tools/config_val.cpp
- src/condor_unit_tests/FTEST_string_vector.cpp
- src/condor_utils/config.cpp
- src/condor_utils/read_multiple_logs.cpp
- src/condor_utils/stl_string_utils.cpp
- src/condor_utils/stl_string_utils.h
- src/condor_utils/xform_utils.cpp
This matches the default behavior of StringList and split(), and is usually what we want.
Update the trimming and delimiter settings of a few instances.
> HTCONDOR-2335 string-iterator-trim

- src/condor_includes/stream.h
- src/condor_io/cedar_no_ckpt.cpp
- src/condor_io/stream.cpp
> HTCONDOR-516 If a transfer_output_file doesn't exist, don't xfer it

- src/condor_c-gahp/schedd_client.h
- src/condor_gridmanager/gridmanager.h
- src/condor_schedd.V6/dedicated_scheduler.h
- src/condor_schedd.V6/scheduler.h
- src/condor_startd.V6/ResAttributes.cpp
- src/condor_startd.V6/ResAttributes.h
- src/condor_submit.V6/submit.cpp
- src/condor_submit.V6/submit_factory.cpp
- src/condor_submit.V6/submit_simulate.cpp
- src/condor_unit_tests/OTEST_StringList.cpp
- src/condor_utils/string_list.cpp
- src/condor_utils/string_list.h
- src/condor_utils/submit_glob.cpp
- src/condor_utils/submit_protocol.cpp
- src/condor_utils/submit_utils.cpp
- src/condor_utils/system_info.WINDOWS.h
- src/condor_utils/xform_utils.cpp
> HTCONDOR-2335 remove last (non-StringList) uses of List

- docs/version-history/feature-versions-23-x.rst
- src/condor_shadow.V6.1/parallelshadow.cpp
- src/condor_shadow.V6.1/shadow.cpp
> HTCONDOR-2362 Evaluate user policy expression during file xfer

- docs/man-pages/condor_submit.rst
> HTCONDOR-2344 Add subcom-def tag to periodic_vacate in submit man page

- src/condor_scripts/condor_remote_cluster
> HTCONDOR-2366: Unconditionally fetch update tarballs

- bindings/python/CMakeLists.txt
- bindings/python/htcondor2/__init__.py
- bindings/python/htcondor2/_remote_param.py
- bindings/python/htcondor2/_submit.py
- bindings/python/htcondor2/_submit_method.py
- docs/apis/python-bindings/api/version2/htcondor2/enums.rst
- docs/apis/python-bindings/api/version2/htcondor2/index.rst
- docs/apis/python-bindings/api/version2/htcondor2/remoteparam.rst
- src/python-bindings/htcondor2/remote_param.cpp
- src/python-bindings/htcondor2/submit.cpp
- src/python-bindings/htcondor2_impl.cpp
> (HTCONDOR-2227)  Implement `RemoteParm`

- docs/man-pages/condor_q.rst
- docs/version-history/feature-versions-23-x.rst
- src/classad/classad.cpp
- src/classad/classad/classad.h
- src/condor_daemon_client/dc_schedd.cpp
- src/condor_daemon_client/dc_schedd.h
- src/condor_includes/condor_attributes.h
- src/condor_q.V6/queue.cpp
- src/condor_schedd.V6/jobsets.cpp
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/qmgmt.h
- src/condor_schedd.V6/schedd.cpp
- src/condor_tools/preen.cpp
- src/condor_utils/compat_classad_util.h
- src/condor_utils/condor_q.cpp
- src/condor_utils/condor_q.h
- src/condor_utils/query_result_type.h
- src/python-bindings/htcondor2/schedd.cpp
- src/python-bindings/schedd.cpp
to query and display jobse ads.
> HTCONDOR-2358 Add condor_q -jobset option

- src/condor_schedd.V6/qmgmt.cpp
> HTCONDOR-2335 fix warning

- src/condor_includes/condor_attributes.h
- src/condor_tools/history.cpp
- src/condor_utils/history_queue.cpp
- src/python-bindings/common2/py_util.cpp
- src/python-bindings/htcondor2/collector.cpp
- src/python-bindings/htcondor2/schedd.cpp
- src/python-bindings/htcondor2_impl.cpp
- src/python-bindings/schedd.cpp
* Refactor common code for dealing with projection arguments.
The name parameter is presently useless, but I expect we'll be switching over to this function in other places as time goes by.
* `#define` a constant that someone else should have a long time ago.
* Pass the error stack's message along in two places where we didn't before.  (Untested.)
> (HTCONDOR-2368)  Fix some FIXMEs in the version 2 Python bindings.

- docs/users-manual/when-job-wont-run.rst
> /usr/log -> /var/log

- src/condor_dagman/dagman_main.cpp
- src/condor_io/condor_secman.cpp
- src/condor_utils/stl_string_utils.h
And add postfix increment.
These two changes allow us to use StringTokenIterator in C++ 20 range algorithms.
> HTCONDOR-2335 properly const-ify StringTokenIterator

- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_schedd.V6/job_transforms.cpp
- src/condor_shadow.V6.1/NTreceivers.cpp
- src/condor_shadow.V6.1/parallelshadow.cpp
- src/condor_shadow.V6.1/pseudo_ops.cpp
- src/condor_shadow.V6.1/remoteresource.cpp
- src/condor_shadow.V6.1/remoteresource.h
- src/condor_startd.V6/command.cpp
- src/condor_sysapi/idle_time.cpp
- src/condor_sysapi/reconfig.cpp
- src/condor_sysapi/sysapi_externs.h
- src/condor_tools/history.cpp
- src/condor_tools/manifest.cpp
- src/condor_tools/preen.cpp
- src/condor_tools/qedit.cpp
- src/condor_tools/qusers.cpp
- src/condor_tools/ssl_fingerprint.cpp
- src/condor_utils/condor_q.h
> HTCONDOR-2335 omit-needless-stringlists

- docs/users-manual/job-sets.rst
> HTCONDOR-2344 fixup jobset docs example

- docs/version-history/feature-versions-23-x.rst
- src/condor_collector.V6/collector.cpp
> HTCONDOR-1105 if collector's local-name is set but not NAME, use that

- src/condor_chirp/condor_chirp.cpp
- src/condor_dagman/debug.h
- src/condor_dagman/script.h
- src/condor_dagman/throttle_by_category.h
- src/condor_includes/condor_common.h
- src/condor_includes/condor_sockaddr.h
- src/condor_includes/condor_uid.h
- src/condor_includes/internet.h
- src/condor_includes/proc.h
- src/condor_io/condor_ipverify.h
- src/condor_master.V6/master.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_shadow.V6.1/baseshadow.cpp
- src/condor_startd.V6/ResAttributes.cpp
- src/condor_startd.V6/slot_builder.cpp
- src/condor_startd.V6/startd_main.cpp
- src/condor_sysapi/resource_limits.cpp
- src/condor_utils/CondorError.h
- src/condor_utils/condor_config.cpp
- src/condor_utils/condor_getcwd.h
- src/condor_utils/condor_regex.cpp
- src/condor_utils/condor_regex.h
- src/condor_utils/filesystem_remap.cpp
- src/condor_utils/my_hostname.cpp
- src/condor_utils/passwd_cache.unix.h
- src/condor_utils/read_multiple_logs.h
- src/condor_utils/status_string.cpp
- src/condor_utils/string_list.h
- src/condor_utils/system_info.WINDOWS.h
- src/ec2_gahp/amazonCommands.h
> HTCONDOR-2335 Don't include condor_syspai (recursively) in every include

- docs/full_conf.py
- docs/requirements.txt
> HTCONDOR-2344 Add a copy button to code blocks in the manual

- docs/classad-attributes/machine-classad-attributes.rst
> HTCONDOR-2344: Restore JobBusyTimeCount definition

- src/condor_sysapi/arch.cpp
This have no functional changes other than reporting the OpSys name in startd ads.
> HTCONDOR-2063 Add macOS 14.X (Sonoma) as known version

- src/classad/attrrefs.cpp
- src/classad/classad.cpp
- src/classad/classad/classadCache.h
- src/classad/classad/exprList.h
- src/classad/exprList.cpp
- src/classad/fnCall.cpp
- src/classad/operators.cpp
- src/classad/view.cpp
> HTCONDOR-2335 Replace ExprListIterator with stl iterators

- docs/version-history/feature-versions-23-x.rst
> HTCONDOR-2321 Version history

- docs/version-history/feature-versions-23-x.rst
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_schedd.V6/scheduler.h
- src/condor_tests/x_read_joblog.cpp
> HTCONDOR-2634 non-blocking remove of dependent dag jobs

- docs/classad-attributes/job-classad-attributes.rst
- docs/man-pages/condor_submit.rst
- docs/users-manual/env-of-job.rst
> HTCONDOR-2378 document transfer_container

- src/blahp/src/classad_binary_op_unwind.C
- src/blahp/src/classad_c_helper.C
- src/classad/classad.cpp
- src/classad/classad/exprTree.h
- src/classad/classad/literals.h
- src/classad/classad_unit_tester.cpp
- src/classad/exprTree.cpp
- src/classad/jsonSink.cpp
- src/classad/literals.cpp
- src/classad/sink.cpp
- src/classad/source.cpp
- src/classad/xmlSink.cpp
- src/condor_gridmanager/arcjob.cpp
- src/condor_negotiator.V6/matchmaker.cpp
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_shadow.V6.1/remoteresource.cpp
- src/condor_startd.V6/ResMgr.cpp
- src/condor_status.V6/status.cpp
- src/condor_utils/classad_oldnew.cpp
- src/condor_utils/compat_classad_util.cpp
- src/condor_utils/expr_analyze.cpp
- src/condor_utils/print_format_tables.cpp
- src/condor_utils/submit_utils.cpp
- src/python-bindings/classad.cpp
- src/python-bindings/classad2/classad.cpp
- src/python-bindings/classad2/exprtree.cpp
- src/python-bindings/classad_module_impl.cpp
This reduces collector footprint by about 10% and improves injestion performance simliarly.
> HTCONDOR-2374 Make classad::Literal an abstract base class

- docs/version-history/lts-versions-23-0.rst
- src/condor_tests/test_xfer_hold_codes.py
- src/condor_utils/file_transfer.cpp
- src/condor_utils/file_transfer.h
> HTCONDOR-2373 keep file xfer plugin exit code in subcode

- docs/faq/users/delta.rst
- docs/faq/users/index.rst
- src/condor_scripts/CMakeLists.txt
- src/condor_scripts/annex/delta.fragment
- src/condor_scripts/annex/hpc.sh
- src/condor_starter.V6.1/singularity.cpp
- src/condor_starter.V6.1/singularity.h
- src/condor_tools/htcondor_cli/annex_create.py
- src/condor_tools/htcondor_cli/annex_validate.py
Creating this PR early for Rynge's convenience.
> (HTCONDOR-2326)  Add support for Delta to `htcondor annex`.

- docs/full_conf.py
> HTCONDOR-2344 configure the copybutton sphinx code not to copy shell

- docs/version-history/feature-versions-23-x.rst
- src/gangliad/statsd.cpp
- src/gangliad/statsd.h
[<HTCONDOR-2394 Enhance condor_gangliad to use projections when querying the collector>](https://opensciencegrid.atlassian.net/browse/HTCONDOR-2394)
> HTCONDOR-2394 gangliad should use a projections to query the collector

- docs/version-history/lts-versions-23-0.rst
- src/condor_scripts/condor_upgrade_check
Applies to versions of python older than 3.8
> HTCONDOR-2393: Fix python argparser crash using extend action

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.h
> HTCONDOR-2392 Add cgroup v2 low memory limit

- src/condor_schedd.V6/transfer_queue.cpp
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_dont_queue_small_sandboxes.py
- src/condor_utils/file_transfer.cpp
Obviously still needs release notes, documentation, an entry in the param table, and some reason to believe it also works for uploads.
> (HTCONDOR-2388)  Don't queue small transfers.

- src/condor_io/condor_auth_ssl.cpp
> HTCONDOR-2396 client-ssl-dn

- docs/version-history/feature-versions-23-x.rst
- src/condor_io/condor_auth_passwd.cpp
> HTCONDOR-232 token-perms-readd

- build/cmake/CondorConfigure.cmake
- docs/admin-manual/configuration-macros.rst
- src/condor_utils/mk_cache_links.cpp
Also fix up the relevant docs.
> HTCONDOR-2389 http-public-files

- build/nmi-build/setup.sh
- docs/version-history/lts-versions-23-0.rst
> HTCONDOR-2397: Move apptainer to usr/libexec in the tarballs

- src/classad/classad/literals.h
- src/classad/classad/sink.h
- src/classad/sink.cpp
> HTCONDOR-2389 Use fewer temporaries to unparse classad expressions

- src/classad/source.cpp
- src/condor_utils/classad_oldnew.cpp
> HTCONDOR-2389 Parse classads with fewer temporary mallocations

- docs/admin-manual/configuration-macros.rst
- docs/classad-attributes/job-classad-attributes.rst
- docs/version-history/feature-versions-23-x.rst
> HTCONDOR-2389 fix doc typos

- docs/version-history/lts-versions-23-0.rst
- src/condor_gridmanager/gahp-client.cpp
> HTCONDOR-2398 ft gahp port

- src/classad/fnCall.cpp
> HTCONDOR-2389 fix warnings

- src/condor_tests/shadow_mem_usage-basic.run
> HTCONDOR-2404 Update Shadow Memory test for Fedora 40

- docs/_static/css/htcondor-manual.css
> HTCONDOR-2389: Replace docs search bar with condor color and logo

- docs/auto-redirect.html
- docs/faq/DAGMan/bagman-exit-at-percent-done.rst
- docs/faq/DAGMan/index.rst
- docs/faq/index.rst
> HTCONDOR-2336: Add example for DAG completion when percent done

- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_tests/lib_shared_port-check-ports_van.run
> HTCONDOR-2389 Always print RealUID in startup dprintf banner

- src/condor_schedd.V6/autocluster.cpp
- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_schedd.V6/dedicated_scheduler.h
- src/condor_schedd.V6/job_transforms.cpp
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_schedd.V6/schedd_negotiate.cpp
- src/condor_schedd.V6/scheduler.h
> HTCONDOR-2389 schedd-lists

- src/condor_schedd.V6/qmgmt_factory.cpp
- src/condor_submit.V6/submit.cpp
- src/condor_submit.V6/submit_factory.cpp
- src/condor_submit.V6/submit_internal.h
- src/condor_utils/ad_transforms.cpp
- src/condor_utils/submit_protocol.cpp
- src/condor_utils/submit_utils.cpp
- src/condor_utils/submit_utils.h
- src/condor_utils/xform_utils.cpp
- src/python-bindings/htcondor2/submit.cpp
- src/python-bindings/schedd.cpp
> HTCONDOR-2389 submit-string-lists

- build/nmi-build/build-batlab-images.sh
- build/nmi-build/setup.sh
- docs/version-history/lts-versions-23-0.rst
- nmi_tools/glue/SubmitInfo.pm
- nmi_tools/glue/build/build_uw_deb.sh
- nmi_tools/glue/build/make-tarball-from-debs
- nmi_tools/nmi-build-platforms
- src/condor_tests/shadow_mem_usage-basic.run
> HTCONDOR-2407: Add Ubuntu 24.04 (Noble Numbat)

- build/cmake/CondorConfigure.cmake
> HTCONDOR-2244 Fix warning about _FORTIFY_SOURCE redefinitions

- docs/man-pages/condor_submit.rst
> HTCONDOR-2405 clearify use of use_scitokens submit command

- docs/version-history/feature-versions-23-x.rst
- src/blahp/src/scripts/blah_common_submit_functions.sh
> HTCONDOR-2413 blahp-home

- docs/version-history/lts-versions-23-0.rst
- src/condor_scripts/condor_upgrade_check
> HTCONDOR-2372: token permissions upgrade check

- src/condor_shadow.V6.1/baseshadow.cpp
> HTCONDOR-2389 Fix warning

- build/cmake/CondorConfigure.cmake
warn incessantly.  Let's go back to FORITY_SOURCE=2 for our non-native builds.
> HTCONDOR-2389 EL8 platforms don't support FORTIFY_SOURCE=3, and

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_utils/param_info.in
- src/gangliad/statsd.cpp
See https://opensciencegrid.atlassian.net/browse/HTCONDOR-2416 for info about this PR.
> HTCONDOR-2416 fix gangliad projection, add config knob GANGLIAD_WANT_PROJECTION

- src/condor_examples/condor.service
> HTCONDOR-2420 Add DelegateSubgroup to systemd service

- docs/version-history/feature-versions-23-x.rst
- src/condor_daemon_client/daemon.cpp
- src/condor_daemon_client/daemon.h
- src/condor_starter.V6.1/jic_shadow.cpp
> HTCONDOR-2411 daemon-session

- docs/version-history/feature-versions-23-x.rst
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.h
- src/condor_utils/proc_family_interface.h
> HTCONDOR-2423 cgroup v2 creation race

- src/condor_dagman/dagman_submit.cpp
- src/condor_utils/submit_utils.h
- src/python-bindings/schedd.cpp
submit using v1 python bindings
> HTCONDOR-2429 fix dummy keys in submit digest from late materialzation

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_includes/reli_sock.h
- src/condor_io/reli_sock.cpp
- src/condor_starter.V6.1/jic_shadow.cpp
- src/condor_starter.V6.1/jic_shadow.h
- src/condor_utils/file_transfer.cpp
- src/condor_utils/file_transfer.h
- src/condor_utils/param_info.in
LIGO reports that the starter/shadow can hang forever when transferring to/from a down NFS server.  While we have a keep alive from the starter up to the startd, and the startd will kill a hung starter, input sandbox transfers are down with a forked child, so the main starter process is alive, while the child process is blocked, so the keepalive always runs, and we never kill the blocked process.
To address this, we add a callback into the ReliSock file transfer methods.  This callback fires every time through the read/network-send or network-read/write loops.  The Starter installs a callback to update a most recent time.  The Starter also installs a timer during file transfer to check this time, and if older than STARTER_FILE_XFER_STALL_TIMEOUT, we evict the job, and it can start again. …
> HTCONDOR-1395 timeout stalled xfers

- src/classad/classad_unit_tester.cpp
- src/classad/operators.cpp
> HTCONDOR-2423 classad array bound check

- build/docker/services/base/container-install-htcondor.sh
These are useful debugging tools and only add a few megs to the container
> HTCONDOR-973: Install ps, less, and nano into the images

- docs/version-history/feature-versions-23-x.rst
- src/condor_daemon_core.V6/daemon_command.cpp
- src/condor_io/sock.cpp
> HTCONDOR-2424 token-implied-auths

- docs/version-history/feature-versions-23-x.rst
- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_utils/file_transfer.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.h
- src/condor_utils/proc_family_interface.h
> HTCONDOR-2438 cgroup v2 submit i

- docs/admin-manual/introduction-admin-manual.rst
> HTCONDOR-2389 Add big mermaid architecture diagram

- docs/admin-manual/configuration-macros.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
> HTCONDOR-2440 local uni cgroup

- src/condor_tests/CMakeLists.txt
- src/condor_tests/ornithology/scripts/null_plugin.py
- src/condor_tests/test_epoch_attrs.py
- src/condor_utils/job_ad_instance_recording.cpp
- src/condor_utils/param_info.in
Implemented in a generic way because it didn't take any longer than being specific.
> (HTCONDOR-2431)  $(epoch-type)_JOB_ATTRS

- src/condor_utils/param_info.in
> HTCONDOR-2439: Revert DAGMAN_CHECK_QUEUE_INTERVAL to be enabled

- bindings/python/htcondor2/_schedd.py
> (HTCONDOR-2389)  Sphinx really can't deal with escape sequences.

- src/condor_dagman/dag.cpp
- src/condor_dagman/dag.h
- src/condor_dagman/dag_priority_q.h
- src/condor_dagman/dagman_classad.cpp
- src/condor_dagman/dagman_classad.h
- src/condor_dagman/dagman_main.cpp
- src/condor_dagman/dagman_main.h
- src/condor_dagman/dagman_submit.cpp
- src/condor_dagman/parse.cpp
- src/condor_dagman/parse.h
- src/condor_dagman/scriptQ.cpp
- src/condor_utils/dagman_utils.h
> HTCONDOR-2422: DAGMan utilize new dagman options class part 2

- src/condor_dagman/dag.cpp
- src/condor_dagman/dag.h
> HTCONDOR-2389 fix unused variable warning

- docs/version-history/lts-versions-23-0.rst
- src/condor_utils/process_control.WINDOWS.cpp
> HTCONDOR-2444: Don't except in windows suspension code

- docs/version-history/feature-versions-23-x.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
- src/condor_utils/proc_family_direct_cgroup_v2.cpp
> HTCONDOR-2445 cgroup v2 under starter cgroup

- src/condor_daemon_client/daemon_list.cpp
- src/condor_daemon_client/daemon_list.h
- src/condor_daemon_client/daemon_types.cpp
- src/condor_daemon_client/daemon_types.h
- src/condor_daemon_client/dc_collector.cpp
- src/condor_daemon_client/dc_collector.h
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_includes/condor_adtypes.h
- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/Resource.h
- src/condor_status.V6/prettyPrint.cpp
- src/condor_status.V6/status.cpp
- src/condor_status.V6/totals.cpp
- src/condor_status.V6/totals.h
- src/condor_utils/ad_printmask.h
The DCCollector object will now do a version check of the collector and refuse
to send StartD daemon ads to collectors where the version is unknown or
less than 23.2 unless ENABLE_STARTD_DAEMON_AD is set to TRUE
> HTCONDOR-2443 Implement the AUTO value of ENABLE_STARTD_DAEMON_AD

- src/annex/BulkRequest.cpp
- src/annex/OnDemandRequest.cpp
- src/annex/annex-create.cpp
- src/annex/annex.cpp
- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_includes/condor_cron_job_list.h
- src/condor_startd.V6/startd_bench_job_mgr.cpp
- src/condor_sysapi/sysapi.h
- src/condor_tools/config_val.cpp
- src/condor_utils/compat_classad.cpp
- src/condor_utils/condor_config.cpp
- src/condor_utils/condor_event.cpp
- src/condor_utils/config.cpp
- src/condor_utils/credmon_interface.cpp
- src/condor_utils/cron_job_list.cpp
Replace with StringTokenIterator or std::vector<std::string>.
> HTCONDOR-2389 convert-more-lists

- docs/_static/css/htcondor-manual.css
> HTCONDOR-2389: Improve documentation css

- src/condor_tests/test_epoch_attrs.py
> HTCONDOR-2389: Up test timeout for slower platforms

- src/condor_tests/test_condor_history.py
> HTCONDOR-2389: Add more test cases to condor_history test

- src/condor_master.V6/master.cpp
- src/condor_master.V6/master.h
- src/condor_master.V6/masterDaemon.cpp
> HTCONDOR-2389 Remove last StringLists from condor_master

- docs/man-pages/condor_ping.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_tools/ping.cpp
> HTCONDOR-2449 Add -long, -format and -af to condor_ping

- docs/admin-manual/cm-configuration.rst
- docs/man-pages/condor_submit.rst
> HTCONDOR-2389 Improve admin cm docs

- src/condor_starter.V6.1/starter.cpp
> HTCONDOR-2414: Improve LVM hold message per RCF input

- docs/version-history/feature-versions-23-x.rst
- src/condor_startd.V6/ResAttributes.cpp
> HTCONDOR-2462 Fixed bug in backfill pslots to reporting of Memory

- src/condor_daemon_client/dc_transfer_queue.cpp
- src/condor_job_router/VanillaToGrid.cpp
- src/condor_job_router/job_router_info.cpp
- src/condor_tools/testwritelog.cpp
- src/condor_utils/test_multi_log.cpp
- src/condor_utils/test_user_mapping.cpp
> HTCONDOR-2389 remove StringLists

- nmi_tools/glue/build/make-tarball-links
- src/condor_examples/condor_config.generic.debian.patch
- src/condor_examples/condor_config.generic.rpm.patch
- src/condor_utils/param_info.in
> HTCONDOR-2460: Update apptainer path in tarball

- src/condor_utils/config.cpp
> HTCONDOR-2465 double free bug in condor_transform_ads

- docs/version-history/feature-versions-23-x.rst
- src/condor_utils/file_transfer.cpp
> HTCONDOR-2464 File Transfer plugin now correctly check for all errors

- docs/man-pages/condor_qusers.rst
> HTCONDOR-2450 Fix typos in man page for condor_qusers

- docs/version-history/lts-versions-23-0.rst
- src/condor_startd.V6/startd_main.cpp
- src/condor_utils/docker-api.cpp
> HTCONDOR-2458 correctly write .startd_docker_images as user condor

- src/condor_tests/ctest_driver
> HTCONDOR-2389 Allow ctest to run test_singularity unit test

- docs/version-history/feature-versions-23-x.rst
> HTCONDOR-2389 misc doc clarifications

- docs/version-history/feature-versions-23-x.rst
- src/condor_utils/file_transfer.cpp
- src/condor_utils/file_transfer.h
> HTCONDOR-2400 file xfer missing plugin errors

- src/condor_dagman/dag.cpp
- src/condor_q.V6/queue.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_schedd.V6/scheduler.h
- src/condor_starter.V6.1/docker_proc.cpp
- src/condor_tools/condor_test_match.cpp
- src/condor_tools/history.cpp
- src/condor_tools/test_auth.cpp
- src/condor_unit_tests/unit_test_utils.cpp
- src/condor_unit_tests/unit_tests.cpp
- src/condor_utils/condor_q.cpp
- src/condor_utils/condor_q.h
- src/python-bindings/classad_python_user.cpp
- src/python-bindings/collector.cpp
- src/python-bindings/dc_tool.cpp
- src/python-bindings/htcondor2/schedd.cpp
- src/python-bindings/schedd.cpp
> HTCONDOR-2475 Remove StringLists

- docs/man-pages/condor_qusers.rst
- src/condor_tools/qusers.cpp
Also add -edit to man page, and remove -delete from usage
> HTCONDOR-2450 Improve condor_qusers arg parsing for -edit

- docs/version-history/lts-versions-23-0.rst
- src/condor_credd/credd.cpp
- src/condor_includes/condor_commands.h
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_startd.V6/command.cpp
- src/condor_utils/credmon_interface.cpp
- src/condor_utils/credmon_interface.h
> HTCONDOR-2467 cred cleanup
