- build/cmake/CondorConfigure.cmake
- src/classad/lexerSource.cpp
- src/condor_includes/condor_sys_linux.h
- src/python-bindings/bulk_query_iterator.cpp
- src/python-bindings/classad.cpp
- src/python-bindings/classad_module.cpp
- src/python-bindings/classad_parsers.cpp
- src/python-bindings/classad_python_user.cpp
- src/python-bindings/collector.cpp
- src/python-bindings/collector_plugin.cpp
- src/python-bindings/event.cpp
- src/python-bindings/exprtree_wrapper.h
- src/python-bindings/log_reader.cpp
- src/python-bindings/python_bindings_common.h
- src/python-bindings/schedd.cpp
- src/python-bindings/tests/classad_tests.py
- src/python-bindings/tests/delayed_update_tests.py
- src/python-bindings/tests/event_tests.py
- src/python-bindings/tests/htcondor_tests.py
- src/python-bindings/tests/htcondor_version_tests.py
- src/python-bindings/tests/log_reader_tests.py
This contains various fixes to get `src/python-bindings/tests/classad_tests.py` working when building against python3 (3.6.1 on fedora-26).
All tests for `classad_tests.py` still pass for python2 on RHEL 6.
> (#6326) python3 fixes for classad_tests.py

- src/condor_gridmanager/boincjob.cpp
Since the mechanism for querying the remote BOINC server for specific jobs is implemented, disable every other way for the condor state to transition from IDLE to RUNNING. This way we are certain that a job reported as RUNNING on the condor side is actually IN_PROGRESS on the boinc side.
> Report IN_PROGRESS only after querying the BOINC server

- doc/platforms/windows.tex
I've had a load of trouble getting the pool password set up on Windows, since I didn't have any authentication other than PASSWORD set up. By looking at the source code of condor_store_cred, I figured out that it can write the pool password directly to the registry *if run as SYSTEM*. 
I tried writing this done and adding it to the respective section of the condor documentation. Please let me know if my understanding here is incorrect, and I'll change it to match reality.
> More documentation on storing the pool password on Windows

- src/python-bindings/schedd.cpp
- Rename keyword argument from `from` to `itemdata`.
- Accept iterables in addition to iterators.
- Values provided to the method are converted to strings where possible.
> Improve usability of `queue_with_itemdata`. #7064

- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_includes/condor_auth_passwd.h
- src/condor_io/condor_auth_passwd.cpp
- src/condor_io/condor_secman.cpp
TOKEN auth is enabled by default _unless_ there are no tokens or credentials present.
TOKEN is always tried if explicitly set by the sysadmin.
> Enable TOKEN auth by default.  #7070

- src/condor_io/condor_auth_passwd.cpp
Prefer using the auto-generated token first for the corresponding
subsystem type (i.e., STARTD uses `startd_auto_generated_token`).
This way we avoid the startd using the schedd's auto-generated token
when utilizing a personal condor setup.
> Improve token location algorithm. #7092

- docs/misc-concepts/classad-mechanism.rst
Small documentation change:
- [https://htcondor.readthedocs.io/en/v8_9_2/misc-concepts/classad-mechanism.html](url)
`Example: A ClassAd is is a set to Example: A ClassAd is a set`
> Fix documentation grammatical error

- build/packaging/srpm/condor.spec
Without this, i get a `/bin/ld: cannot find -lstdc++` error for the `-static` targets.
Note the conditional section here is under `%if %uw_build || %std_univ`, so it may continue to be relevant after std_univ goes away.  (For static shadow?)
> bring in libstdc++-static for EL7 where libstdc++.a is needed

- build/packaging/srpm/condor.spec
apparently this was never actually required for the builds
> the blahp (build requirement) is a lie!

- src/python-bindings/classad.cpp
- src/python-bindings/classad_module_impl.cpp
- src/python-bindings/tests/classad_tests.py
- src/python-bindings/tests/htcondor_version_tests.py
The boolean coercion of `Value`, as it is a boost enum, defaulted to integer coercion.  Thus, `bool(classad.Value.Undefined)` returns `True` - a horribly surprising result.
It turns out that it is not overly difficult to overload operators for enums; it's just not well-advertised.  This does the overload in the case of boolean coercion.  Others may be reasonable in the future.
> Override boolean coercion of `Value` to do something reasonable.  #7109

- src/ccb/ccb_listener.cpp
- src/ccb/ccb_listener.h
- src/condor_daemon_client/daemon.cpp
- src/condor_daemon_client/daemon.h
- src/condor_daemon_client/daemon_list.cpp
- src/condor_daemon_client/daemon_list.h
- src/condor_daemon_client/dc_collector.cpp
- src/condor_daemon_client/dc_collector.h
- src/condor_daemon_client/dc_message.cpp
- src/condor_daemon_client/dc_message.h
- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_includes/condor_secman.h
- src/condor_io/condor_secman.cpp
- src/condor_negotiator.V6/matchmaker.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_schedd.V6/scheduler.h
- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/ResMgr.h
- src/condor_tools/token_create.cpp
- src/condor_tools/token_fetch.cpp
- src/condor_tools/token_request.cpp
- src/condor_utils/token_utils.cpp
- src/condor_utils/token_utils.h
This pulls common token request code from the schedd and startd into a single implementation inside DaemonCore.
It also refactors a number of calling interfaces to allow the entire token request workflow to become non-blocking.  This cleverly solves some memory management issues where the `Socket` the `DaemonList` held was no longer valid: the callbacks are instead invoked immediately after success/failure in the SecMan.
> Refactor (and re-enable) token requests #7093

- src/condor_utils/data_reuse.cpp
- src/condor_utils/data_reuse.h
It's not entirely clear whether the std::move would return a local reference; this replaces the usage of rvalue refs with RVO.
Also fix buffer sizing issues; it's not clear if these were actually able to trigger given the loop constraints.  Will trust the compiler's advice on that one, however.
> Fixup F27 warning. #7318

- build/packaging/srpm/condor.spec
- OSG explicitly does not want cream for RHEL7
- `scitokens-cpp-devel` is needed when not building the external (that is, when not doing a uw_build)
- if cream is not included, the Obsoletes is needed in order for yum to know it can remove an old installed `condor-cream-gahp` package, which otherwise breaks a yum upgrade
> some condor.spec updates to harmonize with osg (SOFTWARE-3929)

- docs/admin-manual/security.rst
You can see the bad formatting in the live manual here: https://htcondor.readthedocs.io/en/latest/admin-manual/security.html#token-authentication
> Fix command block formatting

- src/condor_utils/file_transfer.cpp
When `OutputPluginsOnlyOnExit` is set to `true` (the default value; there would have been no reason why someone would set the undocumented knob to this value either), output plugins were not being invoked on exit. This corrects the logic to ensure plugins are invoked on exit for all cases.
This additionally refactors the stageout logic as suggested in #7042 to make it simpler to read.
> Bugfix: invoke stageout plugin at job end.  #7078

- src/python-bindings/classad.cpp
- src/python-bindings/classad_expr_return_policy.h
- src/python-bindings/classad_module_impl.cpp
- src/python-bindings/classad_wrapper.h
This uses the boost call policies mechanism to ensure that the parent ClassAd both outlives the iterator and any values that the tuples may contain.
> Ensure lifetime of iterators and returned values. #6721

- src/condor_filetransfer_plugins/multifile_curl_plugin.cpp
- src/condor_filetransfer_plugins/multifile_curl_plugin.h
- src/condor_utils/file_transfer.cpp
This does a few things:
- Simplify the implementation of `ParseAds`.  Objects live on the stack;
we use smart pointers to manage lifetimes; safe_fopen variants are used.
More commentary is added about the function's purpose in the header.
- `ParseAds` is invoked next to other libcurl-related setup instead of in
the constructor.  It still can't fail, but groups logically-like things
together.
- Tidy up a few dprintf debug statements so they are only printed when the
corresponding functionality is used.
> Address code review for #6971.  #7079.

- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_master.V6/master.h
- src/condor_master.V6/masterDaemon.cpp
Similar to the startd and schedd logic, this causes the master to automatically request tokens if it cannot authenticate with the collector.  Also allows tokens for `ADVERTISE_MASTER` to be allowed for auto-approval.
> Auto-request tokens for condor_master. #7447

- src/condor_includes/condor_auth_passwd.h
- src/condor_io/condor_auth_passwd.cpp
- src/condor_utils/param_info.in
This allows the admin to set an expression, `SEC_TOKEN_BLACKLIST_EXPR`, which will reject any matching tokens (tokens are converted into ClassAds for the purpose of the blacklist evaluation).
> Add token blacklisting mechanism. #7449

- src/condor_tools/scitoken_exchange.cpp
- src/condor_tools/token_create.cpp
- src/condor_tools/token_fetch.cpp
- src/condor_tools/token_list.cpp
- src/condor_tools/token_request.cpp
- src/condor_tools/token_request_approve.cpp
- src/condor_tools/token_request_auto_approve.cpp
- src/condor_tools/token_request_list.cpp
This fixes the `-debug` flag for `condor_token_*` clients and one incorrect `-help` message.
> Fix `-debug` flag and other odds'n'ends for the `condor_token_*` clients. #7448

- src/condor_daemon_core.V6/daemon_command.cpp
- src/condor_io/sock.cpp
The behavior to add ALLOW permissions (introduced in #7006) was not carried over to the alternate permissions approach added in
> Implicitly add ALLOW permission to tokens. #7456

- src/condor_io/condor_auth_kerberos.cpp
Kerberos authentication fails to set the remote domain unless verbose debugging is on for `D_SECURITY`.
The cause is that the call to `setRemoteDomain()` in `Condor_Auth_Kerberos::map_domain_name()` is _inside_ the condition `if (IsDebugVerbose(D_SECURITY))`.
> Kerberos authentication fails to set remote domain

- docs/users-manual/submitting-a-job.rst
Undocumented condor feature, but the described syntax works in my experiments.
Example: "Queue from seq 7 9 |"
I think this should be documented (and I believe it used to be).
tried on:
$CondorVersion: 8.6.11 May 10 2018 BuildID: 440910 $
$CondorPlatform: x86_64_Ubuntu14 $
> Update doc: Queue from shell command using pipe

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/security.rst
This fixes a mix-up of `KERBEROS_SERVER_PRINCIPAL` and `KERBEROS_SERVER_SERVICE` in the docs.
> Fix documentation of KERBEROS_SERVER_SERVICE

- src/condor_io/authentication.cpp
- src/condor_io/condor_secman.cpp
In order to better distinguish `TOKEN` authentication from `SCITOKENS`, this provides an alias from `IDTOKENS` to `SCITOKENS` as well as accepting any variation of the singular / plural.
> Alias IDTOKENS to TOKEN. #7540

- src/condor_io/condor_auth_kerberos.cpp
This fixes the failing Kerberos authentication of a client daemon with a server daemon when `KERBEROS_SERVER_PRINCIPAL` is set.
The purpose of `Condor_Auth_Kerberos::init_server_info()` is to find out and store the Kerberos principal for the _server_ end of a connection. When invoked by a server daemon, this is the principal of the local host. In this case `KERBEROS_SERVER_PRINCIPAL` correctly overrides the default `host/<local-hostname>@<realm>`.
When invoked by a _client_ daemon,  the server principal is the one associated with the _remote_ end of the connection. The current code correctly derives this principal from the remote hostname by composing it into  `host/<remote-hostname>@<realm>`. However, when `KERBEROS_SERVER_PRINCIPAL` is set, its value is set as the principal for the …
> Fix daemon authentication when KERBEROS_SERVER_PRINCIPAL is set

- docs/admin-manual/user-priorities-negotiation.rst
This should fix the raw text seen here: https://htcondor.readthedocs.io/en/stable/admin-manual/user-priorities-negotiation.html#group-accounting
> Fix a code block formatting issue

- docs/man-pages/condor_prio.rst
Add text to to explain the ordering of job priority in the
condor_prio manpage.
Good to have this clear, as it is inverted compared to user priority
and UNIX nice values.
> In condor_prio manpage make ordering more prominent

- src/condor_includes/condor_secman.h
- src/condor_io/condor_auth_ssl.cpp
- src/condor_io/condor_secman.cpp
- src/condor_schedd.V6/qmgmt_receivers.cpp
Currently, clients and servers will advertise / request authentication methods that don't exist.
This PR centralizes the code for determining the list of valid authentication methods and ensures that we only send out methods that exist and are compiled in to our version of HTCondor.
> Filter authentication methods when possible

- src/condor_contrib/bosco/bosco_cluster
We're carrying this patch in the OSG for 8.8 (https://github.com/opensciencegrid/Software-Redhat/blob/trunk/condor/osg/bosco_https.patch). I imagine that this should be applied to 8.8 as well.
> Fix missing bosco/glite/libexec dir on the remote host

- src/condor_starter.V6.1/docker_proc.cpp
- src/condor_utils/docker-api.cpp
- src/condor_utils/docker-api.h
If condor admin configured CPU affinity (ASSIGN_CPU_AFFINITY for example), use this CPU affinity
for docker universe jobs running on those slots by using the --cpuset-cpus
option in Docker create cmd API.
Also, made this support mutuale exclusive with the CPU share configuration
(taking into account machineAD number of CPUs), as they should have the same effect.
@shohamd4
> condor_starter: Support of CPU affinity with docker

- src/condor_includes/condor_qmgr.h
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/qmgmt_receivers.cpp
- src/condor_schedd.V6/qmgmt_send_stubs.cpp
- src/condor_submit.V6/submit.cpp
For about 20 years, `condor_submit` has checked to see if it's being invoked as UID 0 or GID 0; if so, it refuses to even try to submit.
This seems to date back to a day where there was a strong correlation between the submitting UID and the `Owner` in HTCondor (arguably the GID check was always wrong...).  That's still a frequent case - but not always a safe assumption for remote submit.
This PR removes this check and relies on the schedd side; there's fundamentally no problem with running the client binary as `root` (but, of course, a problem with the schedd accepting jobs with the `Owner` attribute set to `root`).
In order to reasonably remove the safety check, the schedd must be able to give a reasonable message on failure.  The bulk of the PR is plumbing this through - and converting …
> Do not check for root Owner on client side

- src/condor_tools/condor_gpu_discovery.cpp
The conditional was originally added before `ConvertSMVer2Cores` contained mappings for Volta and later GPUs (which have since been added). However, even if they hadn't been added, the conditional is probably unnecessary since `ConvertSMVer2Cores` will default to returning the values for the last known generation (which is probably better than omitting the property entirely from `condor_gpu_discovery` output).
Might be worth a separate discussion about how best to alert the user if they are using a newer GPU than that accounted for in `ConvertSMVer2Cores`?
> Ensure condor_gpu_discovery reports CoresPerCU for Volta and later GPUs

- src/condor_tools/condor_gpu_discovery.cpp
Since the RuntimeVersion attribute is no longer output (following [#7413](https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=7413)), there is probably no need to include it in the simulated output.
> Remove remaining unused RuntimeVersion code

- src/condor_contrib/bosco/bosco_cluster
This helped us understand the nature of the SSH failures for the Clarkson Hosted CE
> Add "--debug" option to bosco_cluster

- src/condor_io/condor_secman.cpp
After we have successfully authenticated, we should clear out the error state object.  Otherwise, any prior authentication failure is included in the error stack resulting in a confusing error message for authorization failures.
Before, on a failed `condor_submit`:
```
ERROR: Failed to connect to local queue manager
SECMAN:2010:Received "DENIED" from server for user build@07a87ab21a6b using method FS.
AUTHENTICATE:1004:Failed to authenticate using KERBEROS
```
(Here, I had included `KERBEROS` as the first authentication protocol even though it is guaranteed to fail in my setup.)
After:
```
ERROR: Failed to connect to local queue manager
SECMAN:2010:Received "DENIED" from server for user build@07a87ab21a6b using method FS.
```
> Clear errstack after successful auth'n. #7774

- src/condor_io/condor_auth_passwd.cpp
This causes HTCondor to access the token as PRIV_CONDOR when running as a daemon _unless_ we are purposely impersonating a user.  To my knowledge, the latter only happens in various user-level flocking scenarios.
This was tested by forcing a shadow to use a CCB which requires `IDTOKENS` auth; because the shadow spends most of its life as `PRIV_USER`, before this patch it would try to read the daemon's token as the unprivileged user.  Fixes #7767, reported by an OSG user.
> Access token as PRIV_CONDOR when a daemon

- src/condor_negotiator.V6/matchmaker.cpp
- src/condor_negotiator.V6/matchmaker.h
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_schedd.V6/scheduler.h
- src/condor_tools/user_prio.cpp
- src/condor_utils/param_info.in
This PR adds the concept of an "accounting namespace" (realized via the `ACCOUNTING_DOMAIN` variable) and allows the negotiator to map submitter ads from a remote namespace into the local one.
Additionally, it allows the negotiator administrator to delegate the management of a groups prio factors (and only that!) to an identity that otherwise only has `WRITE` access.  Note this means the `setpriofactor` RPC has evolved, allowing the negotiator to return a status code and (if needed) error message.
> Add mapping capabilities for non-local accounting groups

- src/condor_contrib/bosco/bosco_cluster
Currently used in the OSG Hosted CEs:
https://opensciencegrid.atlassian.net/browse/SOFTWARE-4095
> Add the ability to specify a custom remote Bosco install dir

- docs/grid-computing/grid-universe.rst
The documentation could be extended by adding other batch systems as additional columns to the provided table.
I added the `--cpus-per-task` argument as unsupported, as opposed to leaving it out, as the patch to slurm_submit.sh to support this is [supposed](https://lists.cs.wisc.edu/archive/htcondor-users/2019-August/msg00104.shtml) to come to a future Condor version. (I can provide that PR for review too, if desired)
> Document how the batch GAHP maps job classad attributes to Slurm attributes

- build/docker/services/base/Dockerfile
Using the RedHat assigned UID/GID for the condor user
> Ensure that the condor user is the same across containers

- src/condor_gridmanager/remote_gahp
When connecting to some HPCs with "-o BatchMode yes", we get kicked to
a password or PIN prompt. This gives administrators an option of
disabling BatchMode
https://opensciencegrid.atlassian.net/browse/SOFTWARE-4239
> Allow fine-grained control over rgahp SSH BatchMode (SOFTWARE-4239)

- src/condor_contrib/bosco/bosco_cluster
One other place to worry about is: https://github.com/htcondor/htcondor/blob/master/src/condor_contrib/bosco/bosco_cluster#L326. Though it's not clear to me what the right thing to do is since we don't necessarily know what version of Python they're running on the remote host
> Fix Python invocation in bosco_cluster per TimT

- build/cmake/CondorConfigure.cmake
This PR modifies the build configuration to enable overwriting the `DLOPEN_GSI_LIBS` and `DLOPEN_SECURITY_LIBS` flags from the `cmake` command-line (e.g. `-DDLOPEN_GSI_LIBS:BOOL=FALSE`).
> Allow overwrite of DLOPEN flags from command line

- src/condor_contrib/bosco/bosco_findplatform
We'll need to set up the 1.3 -> specific version symlink as well
> Use the latest Bosco tarball for Ubuntu (SOFTWARE-4337)

- externals/bundles/boost/1.68.0/CMakeLists.txt
I presume `boost` used to be used for other things, but right now its only used for python bindings. This patch modifies the latest external boost configuration to skip _everything_ if the builder disabled the python bindings.
This is deliberately the laziest possible implementation, mainly to have a minimal diff, so I'm happy to make it 'better' if asked (indentation, etc).
> Skip boost configuration completely if not building python bindings

- src/condor_collector.V6/CMakeLists.txt
- src/condor_collector.V6/ad_transforms.cpp
- src/condor_collector.V6/ad_transforms.h
- src/condor_collector.V6/collector.cpp
- src/condor_collector.V6/collector.h
This provides a way to use HTCondor's ad transform language to change ads as they are forwarded from child to parent collector.
> Provide a transform mechanism for collector ads. HTCONDOR-93

- src/condor_includes/condor_auth_x509.h
- src/condor_includes/globus_utils.h
- src/condor_io/condor_auth_ssl.cpp
- src/condor_io/condor_auth_x509.cpp
- src/python-bindings/secman.cpp
This records the observed X509 certificate from the server and puts it in the client's session.  With this, we can return the information to the invoking user for condor ping.
We are interested in the public cert so OSG can better debug authentication failures (and understand how widely a CA is used, for example) and allow sites to easily remotely monitor the certificate's expiration time.
@brianhlin 
Fixes: HTCONDOR-43
> Record server's X509 certificate for the client. HTCONDOR-43

- src/condor_utils/MapFile.cpp
This allows the sysadmin to include all the files in a given directory into a mapfile.
Requested by OSG as this allows one to cleanly base / default authentication mappings.
> Add new INCLUDE directive to mapfiles. HTCONDOR-46

- src/condor_scripts/condor_watch_q
I noticed the following error when running `condor_watch_q` with python 3.8 and `htcondor=8.9.10` and figured I would submit a patch as it is a simple fix.
The issue is that `last_nodes_total_check_time` is first defined using the `time` but then reassigned as a `datetime.datetime`. This PR makes sure that `time.time` is used consistently. It looks like this variable isn't used outside these few lines, so I couldn't see anything else that this might break.
```python
Processing new events...Traceback (most recent call last):
File "***/bin/condor_watch_q", line 1402, in <module>
cli()
File "***/bin/condor_watch_q", line 387, in cli
abbreviate_path_components=args.abbreviate,
File "***/bin/condor_watch_q", line 491, in watch_q
and time.time() - last_nodes_total_check_time > 60
TypeError: …
```
> fix last_nodes_total_check_time

- src/condor_credd/condor_credmon_oauth/credmon/utils/api_endpoints.py
I found that without this, attempting to use gdrive credentials caused a credmon python crash (in CredMonOAuthLog) when it was trying to look up the user.
I also found that even with this, refresh tokens cannot be retrieved with gdrive.  [The google API document](https://developers.google.com/identity/protocols/oauth2/web-server#creatingclient) and the [python requests-oauthlib docs](https://requests-oauthlib.readthedocs.io/en/latest/oauth2_workflow.html#web-application-flow) indicate that `access_type=offline` needs to be added to the authorization_url.  However, I tried it and got an error saying access_type was unrecognized.  I assume that's because the el7 python2-requests-oauthlib package is too old.  I do not find a corresponding rpm available with python3 on el7, so the only …
> Prevent credmon web service from crashing when looking up gdrive user

- src/condor_credd/condor_credmon_oauth/examples/config/condor/40-oauth-credmon.conf
In my testing I found that different settings were needed for the local scitokens issuer than the default configuration had in a comment.  This PR adds more helpful comments.
I also found that encryption was also always needed, so this PR uncomments that setting.  The original scitokens-credmon [Dockerfile](https://github.com/htcondor/scitokens-credmon/blob/master/Dockerfile#L58) uncommented it with a sed command.
> Improve oauth credmon default configuration

- src/condor_contrib/bosco/bosco_cluster
`platform.dist()` and `platform.linux_distribution()` were removed in Python 3.8 (equivalents are available via [distro](https://pypi.org/project/distro/)) so we need another method to detect the OS distro
> Drop Python-based remote OS/distro detection (HTCONDOR-242)

- src/condor_daemon_core.V6/daemon_command.cpp
- src/condor_includes/CryptKey.h
- src/condor_includes/buffers.h
- src/condor_includes/condor_crypt.h
- src/condor_includes/condor_crypt_aesgcm.h
- src/condor_includes/condor_secman.h
- src/condor_includes/reli_sock.h
- src/condor_includes/sock.h
- src/condor_includes/stream.h
- src/condor_io/CMakeLists.txt
- src/condor_io/CryptKey.cpp
- src/condor_io/authentication.cpp
- src/condor_io/buffers.cpp
- src/condor_io/condor_auth_munge.cpp
- src/condor_io/condor_auth_passwd.cpp
- src/condor_io/condor_auth_ssl.cpp
- src/condor_io/condor_crypt_aesgcm.cpp
- src/condor_io/condor_secman.cpp
- src/condor_io/reli_sock.cpp
- src/condor_io/shared_port_client.cpp
- src/condor_io/sock.cpp
- src/condor_io/stream.cpp
This is the first draft of AES-GCM support in CEDAR.  AES-GCM, being an AEAD approach, integrates both encryption and authentication into a single operation and utilizes modern algorithms compared to the existing options (e.g., BLOWFISH + MD5).  By leveraging OpenSSL for these operations, we get access to hardware-based acceleration.
A few notes:
- Because the AEAD encryption operations generate a message digest for each encryption call, we can't do an encryption call for each `get_bytes` (also, calls to `get_bytes` would no longer be associative).  For AES-GCM, we have to switch to encrypting at the message level instead.
- I realized the above fact after a first draft of the code, resulting in a bit of a messy commit history.  I would suggest squashing the PR.
- Most of the difficulty …
> First revision of AES-GCM support in CEDAR

- src/condor_contrib/bosco/bosco_findplatform
(HTCONDOR-242)
Parse /etc/os-release parsing instead
Note that the new `findversion()` constructs the Bosco distro/version return strings instead of using the defined variables (https://github.com/htcondor/htcondor/blob/master/src/condor_contrib/bosco/bosco_findplatform#L9-L20). I'll submit another PR getting rid of those along with some other PEP 8 fixes.
> Replace bosco_findplatform use of deprecated platform.distro()

- src/condor_tools/nsenter.cpp
These two commits address two issues:
* Keypresses of "enter" were previously translated to newlines, since the TTY opened by `condor_nsenter` did not unset `ICRNL`. This breaks some applications, notably `nano` (trying to press "enter" to save a file fails). 
* When shuffling a lot of characters through the TTY (e.g. running `cat` on a large file or looking at logs), both `sshd` and `condor_nsenter` would use up to one CPU core each for the `read` / `write` syscalls shuffling the data through character by character. This is addressed by using an on-stack buffer. 
Pinging @GregThain as the inventor of this useful tool :+1: . 
It would be nice to also see this in the 8.8 series (if there is still a release planned), if I should do a PR against both `master` and the 8.8 branch just let me …
> Improvements for `condor_nsenter` (performance, CR/NL issue)

- src/condor_credd/condor_credmon_oauth/condor_vault_storer
Change to using dash instead of dot as the separator between the standard bearer file name and the service name, to match what the [WLCG bearer token discovery standard](https://github.com/WLCG-AuthZ-WG/bearer-token-discovery/blob/master/specification.md) says to do when tokens for multiple purposes are needed.
> Update to better match WLCG bearer token discovery standard

- build/packaging/srpm/condor.spec
- src/condor_scripts/CMakeLists.txt
- src/condor_scripts/condor_check_password
The `condor_check_password` tool will examine the passwords / keys
given (or just iterate through the known ones HTCondor uses) and
checks for short passwords or potential truncation issues.
If `--truncate` is specified, it will attempt to truncate the password
so it will be compatible with versions prior to 8.9.12.
> Add condor_check_password for password inspection. HTCONDOR-369

- src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/LocalCredmon.py
- src/condor_credd/condor_credmon_oauth/examples/config/condor/40-oauth-credmon.conf
- src/condor_utils/param_info.in
JSON in the token file is not a supported feature of the WLCG
token discovery proposal.  Further, every tool so far written
simply extracts the access_key from the json, without looking
at the expires attribute.
> Remove the JSON from the local issued token

- docs/admin-manual/setting-up-special-environments.rst
This improves the vault documentation.  The changes are in a section that does not show by default at htcondor.readthedocs.io but I made an htcondor-vault.readthedocs.io where [these changes](https://htcondor-vault.readthedocs.io/en/latest/admin-manual/setting-up-special-environments.html#using-vault-as-the-oauth-client) are already tested.
> Fix vault documentation links

- docs/version-history/upgrading-from-88-to-90-series.rst
This PR trivially fixes a broken cross-reference from
<https://htcondor.readthedocs.io/en/v9_0/version-history/upgrading-from-88-to-90-series.html#step-1>
to
<https://htcondor.readthedocs.io/en/v9_0/getting-htcondor/>
> Fix broken link to 'getting-htcondor' page

- docs/full_conf.py
I got an error building htcondor-vault.readthedocs.io and this is the fix.  I presume you will also need this for htcondor.readhthedocs.io.   The error was
```
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
```
The fix came from this [Sphinx issue](https://github.com/sphinx-doc/sphinx/issues/7747).
> Fix readthedocs build

- docs/users-manual/submitting-a-job.rst
- src/condor_utils/param_info.in
`attribue` occurs in 2 places, change it to `attribute`.
> Fix typo: 'attribue' -> 'attribute'.

- src/condor_utils/condor_scitokens.cpp
This PR patches `condor_scitokens.cpp` to enable dynamic linking of `libSciTokens` at build time, rather than using `dlopen` at run time, as is supported in a bunch of other places.
> Support using scitokens-cpp without dlopen

- externals/bundles/krb5/1.14.5/CMakeLists.txt
This PR modifies the `krb5` external configuration to attempt to find a pre-installed copy of `krb5`, rather than automatically downloading a different installation. This works with `krb5` from `conda-forge`, at least.
> Try and find krb5 on windows before downloading a copy

- src/condor_contrib/bosco/bosco_cluster
1.  RHEL-variants (CentOS, SL, Alma, Rocky) all appear to be pretty
good about putting at least 'rhel fedora' in ID_LIKE so capturing
ID_LIKE in addition to ID should give us a good chance of
detecting new RHEL-variants without having to update bosco_cluster
2.  Ubuntu has 'ID_LIKE="debian"' so we still need to capture ID to
differentiate it from Debian
3.  Debian doesn't set ID_LIKE so it's yet another reason to capture ID
> Improve distro detection

- src/condor_scripts/adstash/config.py
- src/condor_scripts/adstash/history.py
Adstash limit (10000):
We wanted to use adstash to dump more than 10000 condor history entries into an elasticsearch DB.
This was not possible due to the hard limit of: match=min(10000, args.schedd_history_max_ads).
Therefore, I changed it to be freely defined by the adstash config via {name}_{SCHEDD,STARTD}_HISTORY_MAX_ADS.
Note that eventually also the "HISTORY_HELPER_MAX_HISTORY" in the scheduler's config has to be adapted accordingly!
+ some logging added
---------------
Small bug fix:
If no password file is specified, a small bug fix is necessary.
The `conf.get("es_password_file")` in `if conf.get("es_password_file") is not None:` never evaluates to `None`, since an empty string is returned by `"es_password_file": p.get(f"{name}_ES_PASSWORD_FILE")` (L76), if no password file is given …
> Delete adstash limitation and minor fix when no passwd file is given

- docs/admin-manual/configuration-macros.rst
I noticed a typo and one thing lead to another...
> Fix various typos in the config macros

- docs/users-manual/file-transfer.rst
@Todd-L-Miller 
The extra force push is just a nit-pick over using the word "generate" twice in a sentence. This is good-to-go from my side.
> Add documentation for Google Cloud Storage file transfers

- src/condor_starter.V6.1/jic_shadow.cpp
- src/condor_starter.V6.1/starter.cpp
- src/condor_starter.V6.1/starter.h
When declining to put the job on hold when the execute directory is
missing, verify that the execute directory is expected to exist at that
point in time. Also, let the job go on hold if it's local universe, as
it has nowhere else to go if this is a recurring problem.
> Improve handling of execute directory disappearing. #680

- src/condor_tests/CMakeLists.txt
The unit_test_async_fread-1 test fails because patchelf fails to
set the RPATH because of a bug in patchelf 0.12. It will take at
least a week to get patchelf 0.13 into EPEL and then our Docker
build images and we don't want to spoil the greeness on our build
dashboard in the interim.
> HTCONDOR-699: Temporarily turn off test until we can fix patchelf

- src/condor_scripts/condor_watch_q
- src/condor_utils/file_modified_trigger.cpp
- src/condor_utils/file_modified_trigger.h
This should resolve the condor_watch_q problem, because condor_watch_q never actually blocks on a JobEventLog.
> (HTCONDOR-658)  Don't initialize inotify until we need it.

- src/condor_tests/cmd_wait_shows-all.run
- src/condor_tests/cmd_wait_shows-base.run
- src/condor_tests/cmd_wait_shows-notimeout.run
- src/condor_tests/cmd_wait_shows-partial.run
- src/condor_tests/job_core_priority_van.run
- src/condor_tests/job_core_queue_sched.run
- src/condor_tests/job_dagman_maxpostscripts.run
- src/condor_tests/job_dagman_maxprescripts.run
- src/condor_tests/job_dagman_prepost.run
- src/condor_tests/lib_auth_protocol-gsi.run
Replace use of `mkdir $$` for unique directory creation with actual temporary directory creation.  This was causing sporadic failures in the Batlab when PIDs were reused.
> Use File::Temp to create temporary directories. HTCONDOR-763

- src/condor_utils/classadHistory.cpp
> Don't serialize job classad twice when writing to the history file

- src/condor_gridmanager/proxymanager.cpp
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_utils/submit_utils.cpp
Now that we do job proxy handling without GSI, remove the check for
having GSI. Exclude windows for now, since there's some
privilege-switching code that would need some work.
> HTCONDOR-697 job proxy handling without GSI

- src/condor_utils/submit_utils.cpp
I talked to TJ about this code; he sets the desired default value for the other enumerated values before the switch.
> (HTCONDOR-778)  It makes gcc sad when values of an enum are excluded.

- docs/classad-attributes/job-classad-attributes.rst
We decided to claim, at least temporarily, that allowed_job_duration works in all universes; this removes the documented universe restrictions from the ClassAd attribute entry.
----
> (HTCONDOR-794)  Update documentation.

- docs/platform-specific/macintosh-osx.rst
- src/condor_startd.V6/CMakeLists.txt
- src/condor_sysapi/idle_time.cpp
We were using functions that allowed basic handling of 64-bit integers
on 32-bit architectures.
> HTCONDOR-834 Remove use of Carbon framework on macOS

- docs/version-history/stable-release-series-90.rst
- src/condor_io/condor_auth_kerberos.cpp
Fix crash on macOS and small memory leak in kerberos auth.
> HTCONDOR-200 krb5 crash

- src/condor_gridmanager/basejob.cpp
- src/condor_utils/classad_merge.cpp
- src/condor_utils/classad_merge.h
Add const to MergeClassAds() argument.
> HTCONDOR-834 Const-ify MergeClassAds()

- build/cmake/CondorConfigure.cmake
This PR removes an old hack which forces `SYS_ARCH` to `X86_64` on all macOS versions, which will definitely break builds on arm macs.
This hasn't been required since cmake-3.0.0,
see https://gitlab.kitware.com/cmake/cmake/-/commit/9d2a0900ed48eb4ae2df0e7672b9ede5af28e193
> HTCONDOR-839: Remove old SYS_ARCH hack on OSX

- docs/version-history/stable-release-series-90.rst
- src/condor_gridmanager/condorjob.cpp
Put Condor-C jobs on hold after failure, instead of resubmitting immediately.
https://opensciencegrid.atlassian.net/browse/HTCONDOR-871
> HTCONDOR-871 Condor-C don't resubmit after failure

- docs/version-history/stable-release-series-90.rst
- src/condor_scripts/adstash/utils.py
Fixes an issue where comparing a list of startds from the collector with a list of startds in the config lead to an empty list, even if some startds actually existed in both places.
> HTCONDOR-888 adstash startd fix

- src/condor_scripts/common-cloud-attributes-google.py
I am testing the use of the Common Cloud Attributes feature and found that we aren't properly quoting custom metadata values on Google Cloud.
This specific example
```
use feature:CommonCloudAttributesGoogle("-c created-by")
```
produces an actual ClassAd like this
```
CloudCreatedBy = projects / 615838180790 / regions / us - central1 / instanceGroupManagers / htc - type1 - mig
```
@Todd-L-Miller 
> Ensure that Google Cloud Custom metadata values are properly quoted

- docs/version-history/stable-release-series-90.rst
- src/condor_schedd.V6/qmgmt.cpp
User log can be written to wrong directory when retrieving output of spooled jobs.
https://opensciencegrid.atlassian.net/browse/HTCONDOR-886
> HTCONDOR-886 spooled user log written in wrong directory

- src/blahp/src/CMakeLists.txt
Turn libbfunctions and libblfunctions into actual static libraries in
the cmake files. Otherwise, cmake doesn't ensure that their source files
are built before the binaries that depend on them.
> HTCONDOR-878 Fix blahp build dependencies

- src/condor_utils/xform_utils.cpp
This PR addresses an 'unused variable' compiler error on macOS by only defining the relevant variable on platforms where it will be used.
> HTCondor-899: Declare variable conditionally to prevent unused variable compiler errors

- build/packaging/srpm/condor.spec
Right now make the paths used during building the same. A future effort
will eliminate the conditional and only have a single invocation of
cmake.
https://opensciencegrid.atlassian.net/browse/HTCONDOR-834
> HTCONDOR-834: Make OSG paths match UW paths for building

- build/packaging/srpm/condor.spec
https://opensciencegrid.atlassian.net/browse/HTCONDOR-838
We used to always install blahp with HTCondor. OSG depends on this behavior. So, let's restore it.
> HTCONDOR-838: Always install condor-blahp

- nmi_tools/check_nmi_queue_depth.pl
- src/condor_c-gahp/schedd_client.cpp
- src/condor_contrib/campus_factory/share/glidein_jobs/glidein_condor_config
- src/condor_contrib/campus_factory/share/glidein_jobs/job.submit.template
- src/condor_credd/condor_credmon_oauth/docker/10-docker.conf
- src/condor_dagman/dagman_classad.cpp
- src/condor_dagman/dagman_submit.cpp
- src/condor_gridmanager/gridmanager.cpp
- src/condor_includes/condor_qmgr.h
- src/condor_job_router/submit_job.cpp
- src/condor_prio/prio.cpp
- src/condor_schedd.V6/qmgr_job_updater.cpp
- src/condor_schedd.V6/qmgr_job_updater.h
- src/condor_schedd.V6/qmgr_lib_support.cpp
- src/condor_shadow.V6.1/baseshadow.cpp
- src/condor_starter.V6.1/jic_local_schedd.cpp
- src/condor_tools/qedit.cpp
- src/condor_tools/ssh_to_job.cpp
- src/condor_utils/condor_q.cpp
- src/condor_utils/submit_protocol.cpp
- src/python-bindings/schedd.cpp
Remove the unused version argument. Change the name/sinful string
argument to a DCSchedd object, which most callers already had available.
Also fix a static buffer for condor_q -global.
> HTCONDOR-899  Clean up ConnectQ() arguments

- src/condor_tests/test_custom_machine_resource.py
- src/condor_tests/test_custom_machine_resource_instances.py
This test configures a startd with 16 static slots.  While ornithology
correctly waits until all daemons are "ready", via running condor_who,
condor_who doesn't know how many slots should show up in the collector,
and sometimes thinks condor is ready when some, but not all of the slots
are in the collector -- here is evidence from the failing test:
Note that the query came in between slot updates:
01/05/22 21:48:49.011 (D_ALWAYS) StartdAd     : Inserting ** "< slot5@hostname , 172.17.0.8 >"
01/05/22 21:48:49.011 (D_ALWAYS) StartdPvtAd  : Inserting ** "< slot5@hostname , 172.17.0.8 >"
01/05/22 21:48:49.011 (D_ALWAYS) StartdAd     : Inserting ** "< slot6@hostname , 172.17.0.8 >"
01/05/22 21:48:49.011 (D_ALWAYS) StartdPvtAd  : Inserting ** "< slot6@hostname , 172.17.0.8 >"
01/05/22 …
> HTCONDOR-899 Fix rare race condition in test_custom_machine_resources

- docs/version-history/development-release-series-91.rst
- src/condor_utils/file_transfer.cpp
This ports HTCONDOR-923 from master to the 9.5.1 branch.  This pull does _not_ include the test from the master branch, because that depends on HTCONDOR-815, which seemed like a lot of extra code.
The first commit on this branch is a cherry-pick of the corresponding commit from 9.6.0; the second is the same release note as used for 9.6.0, but located in the correct place. 
> HTCONDOR-923 Parent directory fix for 9.5.1

- src/condor_procd/proc_family_client.cpp
The current pointer-arithmetic-cast-and-derefernce code doesn't appear
to cause any unaligned memory accesses, but using memcpy() ensures it
won't become a problem. It also eliminates warnings from clang.
> HTCONDOR-899 Fix memory alignment warnings in ProcFamilyClient

- src/condor_tests/cmd_q_protocols.run
This test submits a job, then immediately removes it.  In rare cases
the remove while the slot is being claimed.  In this case, the
unclaiming doesn't work, and the slot is stuck in claimed/idle for 10
minutes.  The test then submits a subsequent job which can't match
and the test times out.
To fix this problem, we'll just add a second slot in the test
condor.
> HTCONDOR-899 Make cmd_q_protocols test more robust

- docs/admin-manual/configuration-macros.rst
- docs/version-history/development-release-series-91.rst
- src/ccb/ccb_listener.cpp
- src/ccb/ccb_listener.h
- src/condor_daemon_core.V6/daemon_core.cpp
Allow glide-ins to start up faster when CCB brokers are accepting connections but not responding to them.
> HTCONDOR-925

- docs/version-history/stable-release-series-90.rst
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_htcondor_submit_constructor.py
- src/python-bindings/schedd.cpp
If the value is `_Py_NoneStruct`, when we (succesfully) convert it to an `ExprTreeHolder *`, that pointer is `NULL`.  In that case, since all we want is the string to put in the submit file, return `"undefined"` instead.
> (HTCONDOR-950)  Don't segfault in htcondor.Submit constructor.

- src/condor_dagman/parse.cpp
This ticket is a small optimization to [HTCONDOR-619](https://opensciencegrid.atlassian.net/browse/HTCONDOR-619), in which we changed DAGMan to submit jobs directly to the condor_schedd instead of forking a condor_submit process. The optimization comes in the parser code, where we read the value of the `DAMGAN_USE_DIRECT_SUBMIT` configuration knob once and store it in a global variable, instead of looking it up every time we need it.
> HTCONDOR-945: DAGMan parser shouldn't lookup DAGMAN_USE_CONDOR_SUBMIT knob on every iteration

- docs/version-history/development-release-series-91.rst
- src/condor_procapi/procapi.cpp
If you mount `/proc` with the mount option `hidepid=2`, and aren't running as root, then PID 1 will not appear in `/proc`.  This causes the procd to freak out, because we use the absence of PID 1 to help verify that we got a complete read of `/proc`.  This pattch changes procapi to check for PID 1 only if `/proc` were mounted without `hidepid=2`.  There's a small complication that because `hidepid=0` is the default, it's not explicitly listed in `/proc/self/mountinfo`.
> HTCONDOR-944: Don't require hidepid <= 1 mount option for /proc

- docs/man-pages/condor_qedit.rst
- docs/version-history/development-release-series-91.rst
- src/condor_includes/condor_qmgr.h
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_tools/qedit.cpp
- src/python-bindings/schedd.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-963
condor_qedit and python bindings shouldn't request forwarding of edits to shadow by default.
> HTCONDOR-963 qedit forwarding

- src/condor_procd/proc_family_monitor.cpp
We see a rare failure in the tests where the starter forks
to run a job, and in the child process, before it execs
the job, it registers itself as a subfamily to the procd.
The procd returns an error, rarely, claiming the pid of
the forked starter (which the starter has logged) either
doesn't exist, or isn't in the process tree of its parent.
This diff tells us which of those particular cases is
actually happening, so we can debug it further
> HTCONDOR-899 Additional procd debug line

- src/condor_utils/directory.cpp
Make Directory::Rewind() quieter about the directory not existing when
not running as root (to match its behavior when running as root).
> HTCONDOR-969 Directory quiet dprintf

- docs/extensions/jira.py
This used to double check between GitTrac and Jira ticket numbers.
I was tempted to remove the check altogether. However, it would
guard against and unfortunate key bounce. The change is going into
stable, so adding a digit to the number is a minimal change.
> HTCONDOR-1028: Allow Jira tickets over 1000

- build/packaging/new-debian/rules
- build/packaging/new-debian/rules.focal
https://opensciencegrid.atlassian.net/browse/HTCONDOR-749
> HTCONDOR-749: Get BUILD-ID into version string on Debian and Ubuntu

- docs/version-history/development-release-series-91.rst
- src/gpu/cuda_device_enumeration.h
https://opensciencegrid.atlassian.net/browse/HTCONDOR-967
In the [cuda_device_enumeration.h file (line 96)](https://github.com/htcondor/htcondor/blob/4de3b217c5583b28092176b300dc55110fb74215/src/gpu/cuda_device_enumeration.h#L96) we declare `typedef void * cudef;`  this does not force 4 byte alignment, which is needed on power-pc for these APIs.   It is suggested that we change this to an `int *` or in some other way force alignment of these pointers.
> Fix GPU discovery on powerpc HTCONDOR-967

- docs/version-history/development-release-series-91.rst
- src/condor_utils/file_transfer.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1035
Fix bug where jobs may go on hold without a HoldReason and/or HoldReasonCode.
> HTCONDOR-1035 fix missing HoldReason/HoldReasonCode

- docs/admin-manual/security.rst
The text for STARTER_ALLOW_RUNAS_OWNER and the text in the security section of the manual disagree, and the former is right.  Update the latter to be less confusingly wrong.
> HTCONDOR-1028 Small documentation fix

- docs/apis/python-bindings/api/htcondor.rst
- docs/classad-attributes/job-classad-attributes.rst
- src/condor_dagman/dagman_submit.cpp
- src/condor_includes/condor_attributes.h
- src/condor_includes/proc.h
- src/condor_q.V6/queue.cpp
- src/condor_submit.V6/submit.cpp
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_job_submit_method_recording.py
- src/condor_tools/htcondor_cli/dagman.py
- src/condor_tools/htcondor_cli/job.py
- src/condor_tools/htcondor_cli/job_set.py
- src/condor_utils/proc.cpp
- src/condor_utils/submit_utils.cpp
- src/condor_utils/submit_utils.h
- src/python-bindings/schedd.cpp
This is code to implement the JobSubmitMethod Job ad attribute. The new code: overrides the submit hash init(), sets the value at various parts in the code, allows for output display similar to Job status during condor_q --help, added an ornithology test, and documents the features.
Extra checks:
-[ ] Verify documentation looks right (job-classad-attributes.rst & schedd.cpp)
-[ ] Verify my test call is correct in the cmake file
Messed up branch naming. Is a new feature should be V9_8 not V9_0
############################################################################################
- …
> HTCONDOR-996 job submit method recording branch

- src/condor_credd/condor_credmon_oauth/condor_vault_storer
This makes 3 more improvements in the HTCondor/vault integration:
1. Don't require encryption for connections to all daemons, only to schedd and credd
2. Add a SEC_CREDENTIAL_STORECRED_OPTS variable to condor_vault_storer to enable sending additional options to every condor_store_cred command.
3. Recognize the new format of vault tokens, beginning with `hvs.` in addition to the old format beginning with `s.`.
> HTCONDOR-1091: More vault integration improvements

- src/condor_io/condor_secman.cpp
The FAMILY and MATCH methods are used for non-negotiated sessions and
don't appear in the configured authentication method lists. The local
daemon explicitly allows them and they can be trusted.
> HTCONDOR-638 Trust FAMILY and MATCH auth methods

- src/condor_io/condor_secman.cpp
When authentication is disabled (i.e. only peer IP address is used for
authorization), there's no authentication method to examine. We already
reject if authentication is required but wasn't performed.
> HTCONDOR-638 Fix crash when authentication is disabled

- src/condor_q.V6/queue_internal.h
- src/condor_utils/HashTable.h
- src/condor_utils/format_time.cpp
- src/condor_utils/history_queue.h
- src/python-bindings/classad.cpp
- src/python-bindings/classad_wrapper.h
There are a handful of C++ features that have been removed in C++17 and 20.  Sadly, HTCondor uses these.  Let's remove those now before it is a problem.  In particular
The template class std::iterator<> has been removed.  The intent was to provide a class that user iterators could inherit from that provides defaults for the five typedefs that iterator classes need.  Now we need to explicitly typedef these in our iterators.
The class std::unary_function has been removed.  This functioned somewhat like std::iterator, in that it was designed to be a base class for functors, and the 1st template argument was the argument type, and the second was the result type.  Gone in C++17
The final change is a parser change -- an anonymously declared "typedef struct { ...} name;" is illegal if the struct …
> HTCONDOR-1096 - V9_9-HTCONDOR-1096-deprecation-removal

- src/condor_io/condor_auth_passwd.cpp
Some comments imply the casts are needed for very old openssl's, but
this works with all openssl that we support now.
> HTCONDOR-1096  Remove casts that broke compilation with openssl v3

- src/condor_starter.V6.1/os_proc.cpp
This fixes a problem we occasionaly see in the test suite
where the cmd_q_protocols test fails because it removes a job
immediately after it starts.  On Windows, this requires the
job to have run long enough to install the handlers, thus
creating a race.
> HTCONDOR-1093 - V9_10-HTCONDOR-1093-cmd_q_protocols

- docs/version-history/stable-release-series-90.rst
- src/condor_io/condor_auth_ssl.cpp
Make SciTokens mapping failures more prominent in the daemon log
> HTCONDOR-1072 scitoken auth msg

- src/condor_scripts/annex/stampede2.sh
This change needs no documentation, because it's an implementation clean-up (no behavioral changes). Since this code is (deliberately) undocumented, I think that means this change needs no release note.
> (HTCONDOR-975)  Simplify Stampede 2 script to reflect changes by TACC.

- docs/version-history/development-release-series-91.rst
- src/condor_collector.V6/collector.cpp
Fix bug when forwarding private ads between collectors.
> HTCONDOR-1157 forward pvt ads

- docs/admin-manual/configuration-macros.rst
- docs/version-history/development-release-series-91.rst
- src/condor_schedd.V6/schedd.cpp
- src/condor_utils/param_info.in
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1185
set default for SCHEDD_ASSUME_NEGOTIATOR_GONE to 2,000,000,000, effectively disabling it by default
> HTCONDOR-1185 - up default for SCHEDD_ASSUME_NEGOTIATOR_GONE

- src/condor_scripts/annex/expanse.sh
According to the Expanse User Guide, this additional sbatch argument is needed to get access to Lustre.
> HTCONDOR-1117: Request Lustre access on Expanse

- docs/getting-htcondor/admin-quick-start.rst
When I moved `sudo` to after the pipe, I needed to move it to before the environment variable, not after.
> (HTCONDOR-1094)  Fix typo in "getting htcondor" instructions.

- docs/admin-manual/configuration-macros.rst
- docs/version-history/development-release-series-91.rst
- src/condor_schedd.V6/schedd.cpp
- src/condor_utils/param_info.in
when false, schedd never tries to send RESCHEDULE command to negotiator
This is useful for the CE, which doesn't have a negotiator, and this
just ends up filling the logs with detritus.
> V9_11-HTCONDOR-1192-schedd-doesnt-reschedule

- src/condor_scripts/annex/expanse.sh
1 Expanse SU gives you 1 core and 2 GB so you're leaving cores on the table if you request 3 GB.
> HTCONDOR-860: Round RequestMemory up to 2 GB/core on Expanse instead of 3 GB/core

- src/condor_utils/checksum.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1233
fix coverity-found rare memory leak in the checksum code.
> HTCONDOR-1233 fix memory leak in checksum

- build/docker/services/README.md
Also mention the term "access point."  I'm not going to replace the old term
yet because I want to maintain consistency with the manual at
https://htcondor.readthedocs.io/en/latest/admin-manual/introduction-admin-manual.html#the-different-roles-a-machine-can-play
which still uses "submit."
> HTCONDOR-1214: Fix up submit container doc: we do need 9618 open

- docs/version-history/development-release-series-91.rst
- src/condor_sysapi/free_fs_blocks.cpp
- src/condor_sysapi/sysapi.h
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_reserve_disk.py
For some reason, RESERVED_DISK was still being stored in an `int`, which rolls over and makes the available disk larger rather than smaller if it's too large.
This PR does not fix the problem that we're still using a signed integer for a size.
> HTCONDOR-1228  Fix RESERVED_DISK.

- src/condor_tests/ctest_driver
The config file genereated by ctest now closely matches the standard
configuration. Most importantly, Strong user-based authentication is now
required.
> HTCONDOR-1228 update ctest config

- src/condor_starter.V6.1/singularity.cpp
PATH
This breaks the case where the job isn't setting any PATH, and
expects the PATH to be set from the image.
This is a short term fix, but we need to get this out until
we can come up with a better fix to the problem that running
docker: images in singularity requires access to /usr/sbin/mksquashfs
> HTCONDOR-1242 singularity-path

- src/condor_io/condor_secman.cpp
The daemon family security session is only available in the primary
session cache. If we're using a tagged session cache, then don't try to
use the family session.
> HTCONDOR-1241 family-session-assert

- src/condor_status.V6/status.cpp
Strictly speaking, we shouldn't need this, but the Windows
perl tests occasionaly lose the last block of output
when run from a backtick if we don't
> HTCONDOR-1251 flush-condor_status

- src/condor_tools/htcondor_cli/annex.py
- src/condor_tools/htcondor_cli/annex_create.py
* Remove the indirect hop through the SSO.
* Add command-line options to specify the log-in name and log-in host; the former should default to nothing (so that the user's `ssh_config` works) and the latter to whatever the system's documentation says. 
* Allow both log-in name and log-in host to be specified per-system by each user in config.
> HTCONDOR-1239  Adapt HPC Annex to function without XSEDE SSO host

- build/cmake/CondorConfigure.cmake
- src/condor_includes/config.h.cmake
- src/condor_utils/threads_implementation.h
We should really fix this by having condor_util depend on
Threads::Threads in cmake, but here is a more tactical fix
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1259
> HTCONDOR-1259 cmake324

- docs/admin-manual/configuration-macros.rst
- docs/version-history/development-release-series-91.rst
- src/condor_daemon_client/daemon.cpp
- src/condor_utils/param_info.in
New config knob USE_COLLECTOR_HOST_CNAME can be set to false to restore
the old behavior of resolving the given hostname and setting that as the
alias in the collector sinful we construct.
> HTCONDOR-692 Add knob for collector hostname for SSL

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/setting-up-vm-docker-universes.rst
- src/condor_utils/docker-api.cpp
It is desirable to be able to configure Docker's `--shm-size` depending on a job's requested memory or even allow users to specify the value for it in their submission file.
Thus this adds a knob that is parsed as integral value with the machine's and job's classAd available.
If present, the value passed to `--shm-size`.
> Add `DOCKER_SHM_SIZE` knob.

- src/condor_tools/htcondor_cli/annex_create.py
When TransferInput is UNDEFINED, `jobad.get("TransferInput", "")` actually returns a classad.Value, not an empty string - this causes an AttributeError when we try to split it later on.
> HTCONDOR-1112: Handle UNDEFINED and ERROR in TransferInput in job ads

- src/condor_includes/condor_crypt.h
- src/condor_io/condor_crypt.cpp
The blowfish algorithm isn't loaded by default in OpenSSL 3. We need to
load the legacy provider.
> HTCONDOR-1168 fix blowfish on openssl3

- docs/users-manual/self-checkpointing-applications.rst
This PR fixes a trivial typo in the docs for self-checkpointing applications.
> HTCONDOR-1337: Fix trivial typo in docs for self-checkpointing applications

- docs/version-history/lts-versions-10-0.rst
- src/condor_utils/write_user_log.cpp
- src/condor_utils/write_user_log.h
-Changed WriteUserLog::initialize() to still write to other logs
even if one log file fails to open. Also, modified code to make
sure mask only applies to DAGMan logs
> HTCONDOR-1305: DAGMan stuck waiting on pending nodes

- docs/version-history/feature-versions-10-x.rst
- src/condor_tools/history.cpp
-Made it so if user passes clusterIds or cluster.procIds condor history
will stop searching the history files once all possible job ads have
been found.
-Removed warning about fprintf being passed a unused variable
> HTCONDOR-1364: Condor History stops after finding cluster(.proc) ads

- src/condor_utils/condor_threads.cpp
- src/condor_utils/threads_implementation.h
We used to always new up a ThreadImplementation,
then check to see if we are going to create "condor threads" and if we aren't (the default), destroy the ThreadImplementation, leaking a thread-local thread id along the way.
This created tons of noise in address sanitizer output, and was just redundant work.  Let's now check first to see if we need to create threads before boldly going down that road.
> HTCONDOR-1337 Fix memory leak in condor threads

- src/classad/classad/fnCall.h
- src/classad/fnCall.cpp
- src/classad/shared.cpp
- src/python-bindings/classad_python_user.cpp
Or, "What is a void *, and why can't I live without it?"
I stumbled on all these void * casts while looking for a list of classad functions...
The ClassAdFunctionMapping struct contains a std::string member, so I'm not sure I buy the explanation about having to cast function pointers to void * to make the extern C interface happy.
Notably, the cclassad.h interface does not expose this struct anyway, and cclassad.cpp (still) builds without complaint after this change.
> HTCONDOR-1337 use ClassAdFunc directly and avoid void * casts

- docs/version-history/lts-versions-10-0.rst
- src/condor_procd/proc_family.cpp
Errors of the form
Internal cgroup error when retrieving iowait statistics
no longer appear in the ProcLog when iowait statistics are not available in the blkio cgroup
> V10_0-HTCONDOR-1385-despam-proclog

- src/condor_unit_tests/OTEST_Env.cpp
- src/condor_utils/generic_stats.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1337
Fix a couple of small compiler warnings.  One introduced when we simplified the env object, and left behind some unused data members in a unit test.  The second is a simple string pointer warning.
> HTCONDOR-1337 fix warnings

- docs/version-history/lts-versions-10-0.rst
- src/condor_startd.V6/VolumeManager.cpp
- src/condor_starter.V6.1/starter.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1419
This fixes the most egregious bugs with ephemeral scratch mounting.  I suspect there are still filesystem leaks, but this will let us do more testing in CHTC.
WIth this PR, the starter now mounts the fileystems on `$(EXECUTE)/dir_xxx` instead of just `$(EXECUTE)`, and uses the lazy flag to umount them, which works around all kinds of problems.
> HTCONDOR-1419-ephemeral-filesystem

- docs/version-history/lts-versions-10-0.rst
- src/condor_filetransfer_plugins/multifile_curl_plugin.cpp
-Changed mutlifile curl plugins logic for transfer progress
timeout to use upload and download diffs from the last time
check.
> HTCONDOR-1403: Multifile curl plugin logic is wrong

- src/condor_scripts/annex/anvil.sh
- src/condor_scripts/annex/bridges2.sh
- src/condor_scripts/annex/expanse.sh
- src/condor_scripts/annex/stampede2.sh
... for the binaries (to not include the now-different `current`).  We (still :() haven't documented HPC Annex, so this doesn't need any documentation.
> (HTCONDOR-1429)  Update the HPC Annex's well-known URL

- src/condor_tests/lib_shared_port-check-ports_van.run
lib_shared_port-check-ports test counts the number of open TCP ports the shared port has.  It tries to detect if ipv6 should be in play, but did this by running condor_config_val IPV6_ENABLED.  This now returns "auto" by default which isn't useful for the test to decide if it is on or off
Instead, run condor_config_val IPV6_ADDRESS, to see if condor thinks we have a useful ipv6 address.
> HTCONDOR-1427-shared_port_test-ipv6

- docs/version-history/lts-versions-10-0.rst
- src/condor_daemon_client/daemon.cpp
Always set alias in constructed Sinful for collector.
> HTCONDOR0-1443 collector sinful alias

- src/condor_scripts/annex/anvil.sh
- src/condor_scripts/annex/bridges2.sh
- src/condor_scripts/annex/expanse.sh
- src/condor_scripts/annex/stampede2.sh
The 'current' link no longer points at 9.x and shouldn't have been used in the first place.
> (HTCONDOR-1429)  Update the HPC Annex's well-known URL for the binaries.

- CMakeLists.txt
- build/cmake/CondorConfigure.cmake
- build/cmake/CondorPackageConfig.cmake
- src/blahp/doc/CMakeLists.txt
- src/condor_tests/CMakeLists.txt
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1468
In particular, quote variable expression in if statements
Given:
set (OS_NAME "LINUX")
if (${OS_NAME} STREQUAL "LINUX") ...
This returns true on cmake 3.24 and earlier, and false on cmake 3.25, unless ${OS_NAME} is quoted.  This PR quotes those
> V10_0-HTCONDOR-1468-cmake-3-25

- docs/version-history/feature-versions-10-x.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
HTCondor should uses cgroups if we can write to them, not just if we are root. This will open the possibility to using cgroups in glideins, after we get support from having the base batch system give the pilot a writeable cgroup Also, it allows testing of cgroups with the regression test suite and a non-rootly HTCondor.
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1465
> HTCONDOR-1465-non-rootly-cgroups

- docs/version-history/feature-versions-10-x.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
[HTCONDOR-1496](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1496)
Make the leaf v1 cgroup writeable by the job
> HTCONDOR-1496-chown-cgroup

- src/condor_tests/CondorCmdStatusWorker2.pm
They stand up 2 personal condors, one of which has a schedd but no negotiator (on purpose).  Rarely, submitting to that schedd fails because the schedd is blocked, trying to send a reschedule command from a prior submit to the negotiator.  Fix this in the test by setting SCHEDD_SEND_RESCHEDULE=false for that schedd.
> HTCONDOR-1491-stablize-cmd-status-test

- docs/version-history/feature-versions-10-x.rst
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_checkpoint_destination.py
- src/condor_utils/file_transfer.cpp
This change makes `output_destination` _not_ send the standard output and error files to the output destination; they instead go back to the AP as normal.  This should make `output_destination` useful as a way to simplify writing submit files.  This PR changes the semantics unconditionally on the theory that nobody is currently using this feature and that the work-around is pretty trivial.  There are, of course, other options.
> (HTCONDOR-1365)  Make output_destination ignore the output and error files

- build/nmi-build/build-batlab-images.sh
- build/nmi-build/setup.sh
- build/packaging/rpm/condor.spec
- nmi_tools/condor_nmi_submit
- nmi_tools/glue/SubmitInfo.pm
- nmi_tools/glue/build/make-tarball-from-rpms
- nmi_tools/nmi-build-platforms
[HTCONDOR-1285](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1285)
Add Support for EL9 on x86_64 and aarch64.
Unfortunately, I had to bump up the memory request to 17G to compile on ARM EL9. That will reduce our slot count from 16 to 14 on our Docker build machine.
> HTCONDOR-1285: EL9 Support

- docs/version-history/lts-versions-10-0.rst
- src/condor_includes/proc.h
Due to a bug in `isValid()`, which is only used by the `condor_now` code, any job ID with a proc ID of 1 was considered "invalid" and therefore didn't trigger the condor_now code even if it should have.
> HTCONDOR-1519  Allow condor_now to claim resources from job ID <clusterID.1>

- src/condor_collector.V6/collector_main.cpp
- src/condor_io/condor_auth_ssl.cpp
- src/condor_io/condor_secman.cpp
- src/condor_utils/param_info.in
This puts in a few improvements to TOFU mode:
- Set OpenSSL flag to make generated key usable in a TLS connection.
- Auto-generate in a HTCondor-specific location, avoiding touching system files.
- Treat the cert/key config parameter as a list; iterate down the list until an existing file pair is found.
- Enable bootstrapping by default.
> Fixups for TOFU mode.  HTCONDOR-1455

- build/packaging/debian/htcondor.postinst
- src/condor_examples/condor.service
This PR has two, partly related, patches.
1. Remove the obsolete `StandardOutput=syslog` setting from the example `condor.service`, which gets installed on Ubuntu as the service file. This setting produces the following warning from `systemctl status condor`:
/lib/systemd/system/condor.service:20: Standard output type syslog is obsolete, automatically updating to journal. Please update your unit file, and consider removing the setting altogether.
2. Add a call to `systemctl daemon-reload` in the Debian postinst script. Without this, after an upgrade of the htcondor package, `systemctl status condor` (and any other `systemctl {command} condor`) keeps giving this warning:
Warning: The unit file, source configuration file or drop-ins of condor.service changed on disk. Run 'systemctl …
> HTCONDOR-1541: Fixes to stop systemd complaining

- docs/version-history/lts-versions-10-0.rst
- src/python-bindings/schedd.cpp
Existing uses of the python bindings are relyin on the presence of ServerTime in the job ads returned by a schedd query. To avoid breaking this code, keep requesting it from the schedd.
> HTCONDOR-1531 Python bindings now always request ServerTime in job ads

- src/condor_vm-gahp/libvirt_simple_script.awk
EL9 apparently requires microarch v2 or better, meanwhile "the default QEMU CPU models are designed such that they can run on all hosts" [\[1\]](https://manpages.ubuntu.com/manpages/focal/en/man7/qemu-cpu-models.7.html) - ie, on microarch v1, so apparently by default there is a restricted instruction set allowed for qemu-kvm jobs, even if the hardware supports more.
The result is, EL9 VMU jobs end up in a kernel panic, even on hosts which should be able to run EL9.
I was able to get EL9 jobs running by tweaking `LIBVIRT_XML_SCRIPT` to point to this modified script.
There is a question of whether to turn on host cpu passthrough all the time, or just when the job specifically requests it with some special attribute (that this script would recognize).  The more I thought about it, the more I …
> HTCONDOR-1559: Run VMU jobs with host cpu passthrough

- docs/admin-manual/configuration-macros.rst
- docs/admin-manual/monitoring.rst
- docs/version-history/feature-versions-10-x.rst
- src/gangliad/gangliad.cpp
- src/gangliad/statsd.cpp
- src/gangliad/statsd.h
-Added 'Lifetime' attribute to metric definition to set
metrics DMAX to
-Added config knob GANGLIAD_MIN_METRIC_LIFETIME to be the
minimum value the calculated DMAX can be set to.
> HTCONDOR-1547: Gangliad metric lifetime work

- docs/users-manual/file-transfer.rst
The links for Google Cloud Storage in documentation are out-of-date and require updating. I would like to see this change reflected in both the LTS and Feature Releases of HTCondor 10 documentation.
> Update Google Cloud Storage links and wording

- docs/version-history/feature-versions-10-x.rst
- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_tools/history.cpp
If the job history file doesn't exist (usually only on a fresh installation), don't treat it as an error. Still treat an undefined HISTORY parameter as an error.
> HTCONDOR-1578 missing-history-file

- nmi_tools/glue/build/build_uw_deb.sh
- nmi_tools/glue/build/build_uw_rpm.sh
I used the be commenting and uncommenting lines in these files for every release. Let's automate this.
> HTCONDOR-1489: Automatically act upon prerelease

- build/packaging/rpm/condor.spec
Alma Linux 9 turns on this option which sets the build date from the most recent changelog entry. This presents a problem for daily and RC build which do not have a changelog entry.
> HTCONDOR-1490: Don't set the build date from the changelog

- src/condor_utils/condor_regex.cpp
If a capture occurs in an optional part of the pattern that ends up not matching, the indices of the capture are set to PCRE2_UNSET, which is -1. Using that with std::string::substr() will cause a crash. Return an empty string in this case.
> HTCONDOR-1595 Check for unset captures in Regex

- docs/version-history/feature-versions-10-x.rst
- src/condor_collector.V6/view_server.cpp
if an admin removes the statistics files at just the wrong time
> V10_4-HTCONDOR-1599-view-server-assert

- src/condor_sysapi/arch.cpp
Hi, I noticed that AlmaLinux was missing from the OpsSysAndVer of our test node, ie:
`[root@b9jantest02 ~]# condor_status  $(hostname) -af CondorVersion OpSysAndVer
$CondorVersion: 10.2.3 2023-02-21 BuildID: 629848 PackageID: 10.2.3-1 $ LINUX0
[root@b9jantest02 ~]# cat /etc/redhat-release
AlmaLinux release 9.1 (Lime Lynx)`
Not sure this is everything to fix, but hoped it was at least one better than complaining on the mailing list.
> Add almalinux to sysapi_find_linux_name

- src/condor_dagman/dag.cpp
- src/condor_dagman/dagman_main.cpp
- src/condor_dagman/dagman_metrics.cpp
- src/condor_dagman/dagman_metrics.h
It is bad practice, and can lead to name conflicts when newer symbols are added to the std namespace
> HTCONDOR-1577 Removing using namespace std from dagman

- build/docker/services/README.md
Previously, the documentation for getting started with a minicondor container specified to use the el7 tag, which resulted in an outdated version of HTCondor that caused compatibility issues on some machines. Using the `latest` tag ensures an up-to-date version of of HTCondor is installed in the minicondor container.
> Update minicondor container tag from el7 to latest in docs

- src/classad/classad/common.h
- src/condor_daemon_core.V6/condor_softkill.WINDOWS.cpp
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_includes/condor_sys_nt.h
- src/condor_io/condor_auth_sspi.cpp
- src/condor_kbdd/kbdd.cpp
- src/condor_master.V6/service.WINDOWS.cpp
- src/condor_negotiator.V6/accountant_log_fixer.cpp
- src/condor_negotiator.V6/matchmaker.h
- src/condor_procapi/procapi.cpp
- src/condor_procapi/procapi_killfamily.cpp
- src/condor_rmdir/condor_rmdir.cpp
- src/condor_rmdir/harylist.h
- src/condor_startd.V6/CondorSystrayNotifier.windows.cpp
- src/condor_startd.V6/winreg.windows.cpp
- src/condor_submit.V6/submit.cpp
- src/condor_utils/directory.WINDOWS.cpp
- src/condor_utils/dprintf.cpp
- src/condor_utils/dynuser.WINDOWS.cpp
- src/condor_utils/dynuser.h
- src/condor_utils/lsa_mgr.cpp
- src/condor_utils/lsa_mgr.h
- src/condor_utils/stl_string_utils.h
- src/condor_utils/system_info.WINDOWS.cpp
- src/gpu/condor_gpu_utilization.cpp
MSVC's C++20 mode is much more strict about C++ than C++17 It is much more const-correct, which is a headache to fix, but generally a good thing to have.
It is so strict, that it can't compile Win7 headers, unless you predeclare a "struct IUnknown" before include'ing windows.h.  This patch does some of that, but not enough. Do we really need to support Win7?
Because of that, we don't turn on C++20 mode in the Cmake in this patch.  Nevertheless, the drudge work is done here.
> HTCONDOR-1601 Allow use of C++20 in Windows

- CMakeLists.txt
- build/cmake/CondorConfigure.cmake
- src/classad/CMakeLists.txt
Also need to disable CMAKE_MACOSX_RPATH, as in 3.9+, cmake tries to use @rpath in macOS install_name values by default, which we don't want.
> HTCONDOR-1626 cmake-version

- docs/version-history/lts-versions-10-0.rst
- src/condor_schedd.V6/qmgmt.cpp
We don't need to worry about submitters older than HTCondor 7.5.4, and a job ad missing CondorVersion resulted in no submit event.
> HTCONDOR-1643 Always write job submit event in schedd

- build/docker/services/README.md
\`pwd\` (with back-ticks) causes errors when the working directory contains spaces. "$(pwd)" solves this issue.
> Change docker volume bind

- docs/version-history/lts-versions-10-0.rst
- src/condor_utils/condor_scitokens.cpp
Also add a nullptr to the end of audience_ptr. Otherwise, our attempt to get the address of the vector data can crash if it's otherwise empty.
> HTCONDOR-1652 Fix bad dereference when SCITOKENS_SERVER_AUDIENCE not set

- build/packaging/debian/htcondor.postinst
- docs/version-history/lts-versions-10-0.rst
This commit corrects my blunder with confusing LOCAL_DIR and condor's home directory. (HTCONDOR-1537) It retains the change to open up the permissions on /var/lib/condor if it exists. This is required on later versions of Debian and Ubuntu because user's home directories are not world readble.  It conditionally checks for the directory's existance, because if the script produces an error, the whole installation fails.
[HTCONDOR-1689](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1689)
[HTCONDOR-1689]: …
> HTCONDOR-1689: Default condor home to /var/lib/condor on Debian/Unbuntu

- docs/version-history/feature-versions-10-x.rst
- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_daemon_core.V6/daemon_core_main.cpp
- src/condor_shadow.V6.1/remoteresource.cpp
- src/condor_shadow.V6.1/remoteresource.h
- src/condor_shadow.V6.1/shadow.cpp
- src/condor_shadow.V6.1/shadow_v61_main.cpp
- src/condor_utils/param_info.in
Daemon core now kills its immediate children in DC_Exit().  The shadow now kills its immediate children on EXCEPT().  The daemon core reaper caller now leaves the wait entry in the queue until after the callback finishes, so that the starter can tell if the job proc(s) need to be killed on the way out the door.
Also, the shadow now aborts file transfers on disconnects.
> HTCONDOR-1687  Child process clean-up.

- build/packaging/debian/control.in
This came up as I was releasing. I noticed the ppc64le htcondor-test package was not allowed into the repository, because it was incorrectly tagged as noarch. It does contain some binaries for testing. Since we only support using this package BaTLab, we can fix this up after release.
> HTCONDOR-1668: htcondor-test contains binaries

- src/condor_io/condor_auth_ssl.cpp
We don't need to do the dlopen()/dlsym() dance for functions in libcrypto, just for functions in libssl.
> HTCONDOR-1626 Don't dlopen/dlsym libcrypto functions

- bindings/python/setup.cfg
- build/cmake/CondorConfigure.cmake
- src/python-bindings/CMakeLists.txt
HTCONDOR-898: Moved setup.cfg from 8.8 branch to main
HTCONDOR-1650: Added SciTokens Library
Wheel size increases about 2MB from 49 to 51 MB
HTCONDOR-1735:
Add USE_ variables rather than setting cmake variables directly
Remove unused PYTHON3_LIBRARY_FILENAME
> HTCONDOR-1735: Updates to build Python wheels

- src/condor_tests/test_dagman_save_files.py
-The DAGMan save files test periodically times out on aarch64 AlmaLinux8
which runs a bit slower. Looking at the various test outputs the DAG job
is running successfully, but the wait handle is timing out. So, we are
increasing the wait timeout number to not fail.
> HTCONDOR-1626: Increase timeout for DAGMan save files test

- src/condor_starter.V6.1/vanilla_proc.cpp
The unprivileged cgroup v2 code isn't working in batlab
where we run in a docker container without root.  We
can make new cgroups, but the root cgroup doesn't have
cgroup.subtree_controllers settable, so we can't
move processes into the cgroups we create.
For now, turn off the ability to use cgroup v2 when
we don't have root.
> HTCONDOR-1758-cgroup-v2-batlab

- src/condor_starter.V6.1/vanilla_proc.cpp
The unprivileged cgroup v2 code isn't working in batlab
where we run in a docker container without root.  We
can make new cgroups, but the root cgroup doesn't have
cgroup.subtree_controllers settable, so we can't
move processes into the cgroups we create.
For now, turn off the ability to use cgroup v2 when
we don't have root.
> HTCONDOR-1758 turn off cgroup v2 when we don't have root

- src/condor_tests/cmd_drain_scavenging.run
This test scrapes the StartLog, and verifies that the drain, evict and other events happen at the same time if however, the first log message happens near the end of a second, and the second rolls over, we get a false negative
> HTCONDOR-1769-fix-cmd-drain-scavenging-test

- docs/version-history/lts-versions-10-0.rst
- src/condor_dagman/parse.cpp
- src/condor_tests/job_dagman_vars_prepend.run
-Changed DAGMan VARS parsing to automatically replace
'+' to 'My.' for custom variables i.e. +attr -> My.attr
-Updated test to add a custom + attr that isn't appended
to check for breakage
> HTCONDOR-1771: DAGMan fail job submission with +vars

- src/classad/view.cpp
There's no need to upcast from a derived to a base, and upcasting to a base reference generated a type-punning warning.
> HTCONDOR-1768-fix-warning

- docs/version-history/lts-versions-10-0.rst
- src/condor_utils/condor_regex.cpp
Fix an obvious bug in the regex wrapper class triggered by the ce-audit plug-in.
> (HTCONDOR-1774)  Don't dereference NULL pointers.

- src/condor_tests/job_core_perhold_local.run
It shouldn't error if there is more than one hold event for a job.  That's an expected, but rare condition
> HTCONDOR-1768-job-periodic-hold-test

- src/condor_schedd.V6/schedd.cpp
- src/condor_schedd.V6/scheduler.h
When the schedd receives the real dslot ad from the startd, copy over attributes from the original match ad that were added outside of the startd. We already do this for the pslot leftovers ad.
> HTCONDOR-1310 preserve-added-slot-attrs

- docs/version-history/stable-release-series-90.rst
- src/condor_io/condor_auth_ssl.cpp
When the client of an SSL authentication uses a proxy certificate, find and use the subject of the End Entity certificate for the authenticated identity.
(This is a back-port of HTCONDOR-1866 from 10.0.X)
> HTCONDOR-1848 Use identity of proxy in SSL authentication

- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/Starter.cpp
- src/condor_startd.V6/VolumeManager.cpp
- src/condor_starter.V6.1/starter.cpp
-Changed LVM to cleanup LV then do normal execute dir
cleanup on both Starter and Startd side
-Moved check for if using startd disk enforcment out of
VolumeManager constructor to prevent creation of object
if not using it
> HTCONDOR-1821: LVM leaking sandboxes on EP

- docs/version-history/feature-versions-10-x.rst
- src/condor_startd.V6/Starter.cpp
- src/condor_startd.V6/util.h
-Duplicated the check/removal of VM & Docker universe
recovery files to occur prior to LVM cleanup to prevent
rogue docker containers and VMs. This is also an issue
because these parts continually running prevent the LVM
from being cleanedup due to the filesystems being in use
> HTCONDOR-1895: LVM with Docker container bug

- docs/version-history/lts-versions-10-0.rst
- src/condor_utils/param_info.in
If a config knob is looked up with param_longlong(), then its declared type in the param table can't be 'int'.
> HTCONDOR-1908 preen-crash

- docs/version-history/stable-release-series-90.rst
- src/condor_io/condor_auth_ssl.cpp
During SSL authentication, we don't need to limit the length of the peer's certificate chain. The existing limit we're imposing prevents proxies managed by MyProxy from working.
> HTCONDOR-1904 ssl-chain-limit

- src/condor_tests/test_parallel_uni.py
Seems to be a problem on our very slow emulated platforms when under heavy load
> HTCONDOR-1864-fix-parallel-uni-test

- docs/admin-manual/configuration-macros.rst
- src/condor_examples/condor_config.generic.debian.patch
- src/condor_examples/condor_config.generic.rpm.patch
- src/condor_utils/condor_scitokens.cpp
- src/condor_utils/param_info.in
This simplifies the default values of PROCD_ADDRESS and SEC_SCITOKENS_CACHE, which no longer need to be overridden for linux packages or need a mgaical 'auto' value.
> HTCONDOR-1941 run-param

- src/condor_utils/CMakeLists.txt
In particular, the inotify and some of the ipv6 routines are fundamentally hard to supress warnings about alignment restrictions.  Just turn off the warnings in those files.
> HTCONDOR-1925-supress-clang-alignment-warnings

- src/condor_utils/hashkey.cpp
Now, ads sent to the collector that have the same Name and different MyAddress will no longer be considered to be separate daemons. Several pieces of condor assume each daemon advertising to the collector will have a unique Name attribute (for a given ad type).
> HTCONDOR-1948 collector-no-ip-address

- docs/version-history/lts-versions-10-0.rst
- src/condor_dagman/dag.cpp
- src/condor_dagman/dag.h
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_dagman_service_nodes.py
-Resolved an issue with the counting of submitted nodes to DAGMan.
Where service nodes were supposed to be separate, but were only
implemented partially separate. This would cause DAGMan to blowup
at an assertion check if a service node finished before the entire
DAG
-Added an ornithology test
> HTCONDOR-1909: Fix service nodes blowing up DAGMan

- src/condor_schedd.V6/qmgmt.cpp
Allow schedd to fork for a QMGMT_READ_CMD if the client doesn't send an IntializeReadOnlyConnection() RPC.
> HTCONDOR-1924 Make qmgmt IntializeReadOnlyConnection() optional

- src/condor_scripts/Condor.pm
The HTCondor perl test running assumes it can tail -f the job’s event log by repeating calling <FILE_HANDLE>, even after it hits EOF.  Debian has backported a change in perl that causes the eof to “stick”, so that subsequent calls to <FILE_HANDLE> return eof, even if the file has since been written to.
> HTCONDOR-1956-support-perl-5-36

- src/condor_includes/sockCache.h
- src/condor_io/sockCache.cpp
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_utils/ad_printmask.cpp
- src/condor_utils/ad_printmask.h
- src/condor_utils/compat_classad_util.cpp
There's a new warning in the fedora compiler where operator new[] takes a size_t as the size, and if passed a (signed) int, it gets promoted to a unsigned quantity, which if it was negative, (unlikely), gets changes to a very large integer, which triggers a warning
> HTCONDOR-1925 fix Fedora warnings

- src/condor_tests/cmd_status-compact.run
By ensuring that when we run condor_transform_ads, the partionable slot doesn't have a claimed/idle dslot under it.
> HTCONDOR-1925 robustify cmd_status-compact test

- build/packaging/debian/rules.in
- nmi_tools/glue/build/build_uw_deb.sh
So we can actually see the warnings
> HTCONDOR-1925: Reduce the verbosity of Debian build

- src/condor_tests/ornithology-docs/.readthedocs.yaml
- src/condor_tests/ornithology-docs/requirements.txt
- src/condor_tests/ornithology-docs/source/conf.py
Bunch of tweaks to make the Ornithology docs buildable at RTD again.  Should probably be a squash merge.
> (HTCONDOR-1991)  Make Ornithology docs buildable at RTD again.

- src/condor_shadow.V6.1/ShadowHookMgr.cpp
Fixing the bug where shadow job hooks cannot receive the job classad from stdin.
> HTCONDOR-1988: Fixed bug to allow shadow job hooks to get classad from stdin

- src/condor_sysapi/process_capabilities.cpp
ubsan complains that we are passing these syscall parameters into the kernel unitialiazed.  I'm not sure it is reading them all, but let's set them just to be sure.
> HTCONDOR-1992 fix unitialized read in getcap syscall

- src/condor_schedd.V6/dedicated_scheduler.cpp
slots
this would break the dedicated_scheduler with partitionable slots. Change the way we detect what kind of slots are which to be stable in the face of this change
> HTCONDOR-1992 If we change the default slot_type_id for partitionable

- src/condor_daemon_core.V6/daemon_core_main.cpp
In modern C++, new throws std::bad_alloc, and never calls the new handler.  And it usually doesn't even do that -- the OOM killer will probably get the program first, so let's just remove this unused code.
Oh, and also, we never initialize the static `oom_reserve_buf`, so this code probably never runs to begin with.
> HTCONDOR-1992 remove unused set_new_handler

- docs/admin-manual/configuration-macros.rst
- src/condor_io/reli_sock.cpp
- src/condor_io/shared_port_endpoint.cpp
- src/condor_scripts/linux_kernel_tuning
- src/condor_utils/param_info.in
This is the new value as of linux 5.4, and is thought to cause few
problems, and fixes difficult-to-debug problems with the shared
port burstily making connection attempts to busy schedds and other
daemons
> HTCONDOR-1992 Raise TCP and Domain Socket list backlog default to 4096

- src/condor_schedd.V6/qmgmt.cpp
When the job router submits a job, it usually authenticates as condor and calls QmgmtSetEffectiveOwner() to impersonate the job owner. If the job owner doesn't have a user record yet in the schedd, then the schedd needs to create one here; it can't wait until NewCluster().
> HTCONDOR-2022 job-router-user-rec

- src/condor_utils/read_user_log.cpp
- src/condor_utils/read_user_log.h
- src/condor_utils/read_user_log_state.cpp
- src/condor_utils/read_user_log_state.h
- src/condor_utils/test_log_reader.cpp
- src/condor_utils/test_log_reader_state.cpp
- src/condor_utils/test_log_verify
- src/condor_utils/test_log_writer.cpp
- src/condor_utils/user_log.c++.h
- src/condor_utils/write_user_log.cpp
- src/condor_utils/write_user_log.h
- src/condor_utils/write_user_log_state.h
It is odd to only have these in a handful of files, and emacs best practice is not to put these into individual source files. Let's just remove these.
> HTCONDOR-1994 remove ancient emacs mode subsettings in some files

- docs/man-pages/condor_watch_q.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_scripts/condor_watch_q
- Made it so -clusters shows only those specified clusters when using an old and large log file
- Added similar filtering for jobs found in queue via -batches
- Fixed bug where -batches wasn't working due to written constraint -Added new -since flag to display information of all clusters since a specified ID (inclusively)
> HTCONDOR-2046: Filter out non-specified clusters for condor_watch_q

- docs/version-history/lts-versions-23-0.rst
- src/condor_dagman/dag.cpp
- src/condor_tests/test_dagman_service_nodes.py
-Similar to the issue/fix in HTCONDOR-1909, DAGMan was failing an
assertion check due to service nodes being counted when they were
not supposed to be. This was during a node failure. The fix was
to not include service nodes in the total count of failed nodes
-Updated test to check that failed service nodes worked correctly
> HTCONDOR-2051: DAGMan service nodes failing assertion check

- docs/version-history/lts-versions-23-0.rst
- src/condor_tools/transfer_data.cpp
-Using the -addr flag for condor_transfer_data would also enable
the functionality to get all data. Since the use of -all with
a Job Id or owner fails (isn't allowed), the use of -addr and
a Job Id or owner would similarly fail.
> HTCONDOR-2105: condor_transfer_data -addr defaults to getting all data

- src/classad/classad/literals.h
- src/classad/classad/sink.h
- src/classad/classad/value.h
- src/classad/jsonSink.cpp
- src/classad/literals.cpp
- src/classad/sink.cpp
- src/classad/source.cpp
- src/classad/value.cpp
- src/classad/xmlSink.cpp
- src/condor_gridmanager/arcjob.cpp
- src/condor_startd.V6/ResMgr.h
- src/condor_utils/compat_classad_util.cpp
- src/condor_utils/expr_analyze.cpp
- src/condor_utils/submit_utils.cpp
- src/python-bindings/classad.cpp
in a classad literal.  We still parse and scale literals by the suffix factor, but we discard them now after scaling.
There should be no user-visible changes to the classad language with this change.
> V23_2-HTCONDOR-2110-no-classad-number-factor

- docs/version-history/lts-versions-23-0.rst
- src/condor_dagman/dag.cpp
-DecrementProcCount() calls cleanup() for a node which empties
the _gotEvents vector for managing job proc events. Because of
this reset happening prior to a node proc Release(), the proc
info was non-existant and the internal count decrement passed
> HTCONDOR-2102: Fix bug warning about differring internal held procs count

- docs/admin-manual/introduction-to-configuration.rst
- docs/users-manual/submitting-a-job.rst
This PR fixes a trivial typo (duplicated in two places) in the documentation for the `$F` function macro when demonstrating `$Fx(...)`.
> (HTCONDOR-2097) Fix a typo in example for Fx function macro

- docs/version-history/lts-versions-23-0.rst
- src/condor_schedd.V6/qmgmt.cpp
when a submit portal submits a job with +Owner
and the Owner value is one that has never had a job in the queue before.
> HTCONDOR-2131 Fix for a possible schedd crash with +Owner

- docs/admin-manual/configuration-macros.rst
- docs/version-history/lts-versions-23-0.rst
- src/condor_starter.V6.1/vanilla_proc.cpp
CGROUP_MEMORY_LIMIT_POLICY=custom
And fix docs so they refer to correct knob names
> HTCONDOR-2133 Add cgroup v2 support for

- docs/version-history/lts-versions-23-0.rst
- src/condor_dagman/dag.h
- src/condor_dagman/dagman_main.cpp
stuck in the removed (X) state
> HTCONDOR-2147: Fix possibility of DAGs with Final nodes being

- docs/version-history/stable-release-series-90.rst
- src/condor_includes/condor_auth_ssl.h
- src/condor_io/condor_auth_ssl.cpp
- src/condor_utils/param_info.in
…hods
During SSL authentication, add option to attempt to map the client's DN to an HTCondor identity. If no mapping can be performed, treat treat it as an authentication failure, so that other auth methods can be tried.
> HTCONDOR-2145 ssl-mapping-fallback

- build/cmake/macros/CondorDaemon.cmake
This PR fixes a [failure](https://github.com/htcondor/htcondor/pull/1986#issuecomment-1830334678) when passing the new `-DBUILD_DAEMONS:BOOL=false` flag where undefined targets were being referenced.
> Combine conditionals for BUILD_DAEMONS in condor_daemon function

- src/condor_tests/ctest_driver
ps shows that when I run ctest -j 40, there's usually a dozen python processes running box|gdrive|onedrive plugin -classad.
Testing standalone shows that just getting python off the ground takes about .2 of a second, and when we do three of these for each startd, it adds up.  We have no tests that test these plugins, and I'm not sure we have any users, so I'm just going to disable them in ctest.
Ideally, I'd like the equivalent of "-=" in config language, but for now, we'll hard code the transfer plugin list to just include the curl plugin, which we do test, and is in native condor code, so it is fast to run -classad.
- Hit the merge button if the pull request is approved and it is not a security patch (security …
> HTCONDOR-2173 Speed up ctest runs

- src/condor_tests/test_concurrency_limits.py
There's on off-by-one in the code that parses the NegotiatorLog to determine how many jobs are concurrently running.  This is a hacky fix, but will (hopefully) allow this test to be more consistenly green.
> HTCONDOR-2196 Harden test_concurrency_limits

- src/condor_tests/test_singularity_sif.py
Some versions of singularity want to see an /etc/passwd file in the image, and complain if it isn't there.  Let's put this in the minimal image file we build in this test.
> HTCONDOR-2196 Robustify singularity tests

- src/condor_utils/wait_for_user_log.h
- src/python-bindings/JobEventLog.cpp
Add the name of the log file and byte offset therein when a ULOG_RD_ERROR is thrown
> HTCONDOR-2219 Enhance Python HTCondorIOError with more info

- docs/version-history/feature-versions-23-x.rst
- src/condor_includes/condor_attributes.h
- src/condor_tests/cmd_submit_regress_dry.expect
- src/condor_tests/cmd_submit_regress_dry.subs
- src/condor_utils/metric_units.cpp
- src/condor_utils/metric_units.h
- src/condor_utils/submit_utils.cpp
- src/condor_utils/submit_utils.h
new commands gpus_minimum_memory, gpus_minimum_runtime, gpus_minimum_capability and gpus_maximum_capability these commands set new job attributes with the value given in the command and modify the RequireGPUs expression as needed to make them behave as constraints on matchmaking against GPU properties.
> HTCONDOR-2201 Add submit commands for GPU property constraints

- docs/version-history/lts-versions-23-0.rst
- src/condor_utils/read_user_log.cpp
In the test suites, we (rarely) see dagman hanging, having lost track of a job it submitted.  Turns out that the user log read code is to blame. There are cases where even though the user log writer is writing the entire event in one write(2) call, on an FD opened with O_APPEND, posix only guarantees that a reader will see every byte of that write at once if the read is started after the write returns to userspace. We make no attempts to do so.
In a couple of places in the log reader code, we fseek back to the beginning  when we detect a short read, but not all cases.  This PR adds fseek’ing back to the remaining cases.
- Hit the merge button if the pull request is approved and it is not a security patch (security …
> HTCONDOR-2236 fix bug in user log reader with short reads.

- build/packaging/debian/control.in
- build/packaging/rpm/condor.spec
- docs/version-history/lts-versions-23-0.rst
- src/condor_scripts/condor_test_token
HTCondor daemons access the cache file as user condor. condor_test_token needs to do the same when run as root.
> HTCONDOR-2241 test-token-fixes

- src/condor_shadow.V6.1/parallelshadow.cpp
Instead, dprintf a useful message.  In both cases, the job returns to idle and is run again, but now there's no shadow exception message in the log, which causes the test_parallel_uni test to fail.
> HTCONDOR-2235 Don't except on parallel uni claim failure

- src/condor_tests/test_plugin_timeout.py
This test is occasionally failing on our slower platforms because it assume that it can respond within five seconds to a slow plugin.  Let's up that timeout a bit to give our slow platforms a better chance.
> HTCONDOR-2235 Robustify plugin timeout test

- docs/version-history/lts-versions-23-0.rst
- src/condor_tools/qusers.cpp
invalid expressions were being failed without a message and the wrong exit code.
> HTCONDOR-2269 fix reporting of -format and -af errors in condor_qusers

- src/condor_examples/condor_config.generic.rpm.patch
- src/condor_scripts/make-personal-from-tarball
- src/condor_utils/param_info.in
Previously-unused ETC parameter is now used to place files and directories that normally live in /etc/condor/ on a linux pacakage installation. This allows tarball installations to have their own etc directory with all of the files/directories that live there without overriding a list of config knobs.
> HTCONDOR-2290 etc

- docs/version-history/lts-versions-23-0.rst
- src/condor_starter.V6.1/user_proc.cpp
doing so causes the event log parser to become confused.
See #2226.  This PR corrects targets `V23_0-branch`, as that PR should have.
> (HTCONDOR-2305) Don't pass newlines from the job wrapper into the error message;

- docs/version-history/lts-versions-23-0.rst
- src/condor_scripts/adstash/config.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2312
Pretty simple fix to convert offending strings to raw strings.
> HTCONDOR-2312 Fix Python 3.12 warnings in condor_adstash

- docs/man-pages/condor_submit.rst
- docs/users-manual/env-of-job.rst
- src/condor_includes/condor_attributes.h
- src/condor_scripts/adstash/convert.py
- src/condor_tests/cmd_submit_regress_dry.expect
- src/condor_tests/cmd_submit_regress_dry.subs
- src/condor_utils/docker-api.cpp
- src/condor_utils/submit_utils.cpp
- src/condor_utils/submit_utils.h
Add the possibility to the docker universe to use the executable as argument for the `--entrypoint` of docker create.
This is useful when the default entrypoint is not able to run the executable, for example when it does not interpret the first argument as the command to run.
This flags selects between two different behaviours of `docker run` as described in the [documentation](https://docs.docker.com/engine/reference/run/#default-command-and-options) in a not really obvious way.
Essentially if the docker image has an entrypoint defined:
```Dockerfile
ENTRYPOINT ["/opt/entrypoint.sh"]
```
The run command will always use it, with all the arguments passed to the entrypoint.
This means that a command like:
```shell
docker run image:latest  /usr/local/command.sh arg1 arg2
```
Is really …
> First implementation of the Docker entrypoint override.

- src/condor_io/stream.cpp
get_secret(std::string&) was adding an extra NUL to the end of the received string. No current code is affected by this, but future code may be.
> HTCONDOR-2288 secret-string

- src/condor_credd/condor_credmon_oauth/condor_vault_storer
This changes condor_vault_storer to make it clear that requesting specific scopes or audience requires a handle.  Previously it just ignored the scopes and audience in that case.
> Exit condor_vault_storer with an error if scopes or audience reduced without a handle

- src/condor_utils/HashTable.h
C++23 adds a deleted constructor to std::string:
```
std::string(nullptr_t) = delete;
```
This is wellness and good, because it turns a runtime crash into a compile time error.  However, it also cause our HashTable Iterator class to fail to compile.  This is in the Iterator dereference functions:
```
std::pair<Index, Value> operator *() const {
return std::pair<Index, Value>(m_cur ? m_cur->index : NULL, m_cur ? m_cur->value : NULL);
}
```
`m_cur` is nullptr when the iterator is at `end()`.  Technically, it is UB to dereference an at-end iterator, but I guess we are trying to be nice here.  However, if either the Index or the Value is of type `std::string`, we try to assign NULL to the `std::string`, which triggers the compile error.
I'm going to make the smallest possible change I can …
> HTCONDOR-2335 port to C++ 23

- docs/version-history/feature-versions-23-x.rst
- src/condor_io/condor_auth_passwd.cpp
- src/condor_utils/secure_file.h
This is a disruptive change for our installed base, so delay the file access checks until a future version (23.8.x).
> HTCONDOR-232 Delay enforcement of token file permissions

- src/condor_tests/job_dagman_rm-nodeF.pl
- src/condor_tests/job_dagman_rm.run
After HTCONDOR-2364 (queued dependent dag job removal)
the existing race condition in this test got worse.  This test starts a dag, then removes the dag, and verifies the jobs were removed.  It verifies the removed node jobs by first condor_wait'ing for them, then checking to see if the job created a file.  This file is created by the job after the job polls to see that the dagman proper has been killed.
We remove that second test in this PR, but as the test still condor_wait's for the node job to exit, we are still testing what we say we are.
- If the pull request is approved, take …
> HTCONDOR-2389 Robustify job_dagman_rm test

- src/classad/classad.cpp
- src/classad/classad/classad.h
- src/classad/classad/classadCache.h
- src/classad/classad/classad_containers.h
- src/classad/classadCache.cpp
classads.  None of our compilers do this anymore (and C++ 11 forbids it).  This change promotes a more perfect const-ness, which is a stepping stone to allowing cons-free string_view accessors to classads.
> HTCONDOR-2389 Remove support for copy-on-write std::strings in

- src/condor_startd.V6/ResAttributes.cpp
- src/condor_startd.V6/ResAttributes.h
- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/ResMgr.h
- src/condor_startd.V6/Resource.cpp
- src/condor_startd.V6/Starter.cpp
- src/condor_startd.V6/slot_builder.cpp
- src/condor_startd.V6/slot_builder.h
- src/condor_startd.V6/startd_cron_job_params.cpp
- src/condor_startd.V6/startd_hibernator.cpp
- src/condor_startd.V6/startd_hibernator.h
- src/condor_startd.V6/startd_main.cpp
- src/condor_startd.V6/util.cpp
- src/condor_startd.V6/util.h
- src/condor_tools/preen.cpp
> HTCONDOR-2389 startd-string-lists

- nmi_tools/glue/SubmitInfo.pm
- nmi_tools/glue/build/make-tarball-from-rpms
- nmi_tools/nmi-build-platforms
> HTCONDOR-2386: Add Fedora 40 to the build

- build/cmake/CondorConfigure.cmake
- src/condor_io/condor_auth_ssl.cpp
- src/vendor/zip-views-1.0/.gitignore
- src/vendor/zip-views-1.0/CMakeLists.txt
- src/vendor/zip-views-1.0/LICENSE.md
- src/vendor/zip-views-1.0/README.md
- src/vendor/zip-views-1.0/test_zip_view.cpp
- src/vendor/zip-views-1.0/zip_view.hpp
for it.  Should help with StringList removals
> HTCONDOR-2389 add 3rd party zip_view so we don't have to wait for C++23

- src/gpu/condor_gpu_discovery.cpp
Introducing MIG device detection accidentally broke our condor_gpu_discovery's auto mode, where it would print OpenCL devices if it couldn't find any CUDA ones.  This PR (hopefully) corrects that broken logic.
> (HTCONDOR-2377)  Allow CUDA devices to be autodectected again.

- src/classad/classad/value.h
- src/classad/classad_functional_tester.cpp
- src/classad/value.cpp
- src/condor_dagman/dagman_submit.cpp
- src/condor_filetransfer_plugins/multifile_curl_plugin.cpp
- src/condor_gridmanager/proxymanager.cpp
- src/condor_had/Utils.cpp
- src/condor_starter.V6.1/starter.cpp
- src/condor_tools/config_val.cpp
- src/condor_tools/token_list.cpp
- src/condor_utils/CondorError.cpp
- src/condor_utils/compat_classad.cpp
- src/condor_utils/dprintf.cpp
- src/condor_utils/file_transfer.cpp
- src/condor_utils/manifest.cpp
- src/gangliad/statsd.cpp
This formats a bit different than unparse, which seems like a footgun. Just use unparse everywhere.  As long as we are doing this, let's remove some other stringstreams along the way.  Also, one fewer switch-on-type in classads.
> HTCONDOR-2389 remove iostream overloads for classad value

- src/condor_master.V6/master.cpp
- src/condor_master.V6/master.h
- src/condor_master.V6/masterDaemon.cpp
> HTCONDOR-2389 Remove some StringLists from condor_master

- build/packaging/rpm/condor.spec
- docs/admin-manual/cm-configuration.rst
- docs/man-pages/condor_adstash.rst
- docs/version-history/feature-versions-23-x.rst
- src/condor_examples/condor_config.local.adstash
- src/condor_scripts/adstash/ad_sources/registry.py
- src/condor_scripts/adstash/ad_sources/schedd_job_epoch_history.py
- src/condor_scripts/adstash/adstash.py
- src/condor_scripts/adstash/config.py
- src/condor_scripts/adstash/convert.py
- src/condor_utils/param_info.in
The schedd *job epoch history* fetching works almost exactly like the schedd *job history* fetching with three major differences:
1. JSON documents use the value of `EnteredCurrentStatus` instead of `CompletionDate` to uniquely identify jobs.
2. Checkpoints additionally use `EnteredCurrentStatus` along with `ClusterId` and `ProcId` to set the `since` argument. 
3. Querying is done using `Schedd.jobEpochHistory()`.
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2076
> HTCONDOR-2076 Add job epoch history fetching to condor_adstash

- docs/version-history/feature-versions-23-x.rst
- src/condor_startd.V6/startd_main.cpp
- src/condor_utils/docker-api.cpp
to allow startd to read it, to advertise DockerImageCacheSizeMB
> HTCONDOR-2458 correctly write .startd_docker_images as user condor

- docs/version-history/lts-versions-23-0.rst
- src/condor_daemon_client/dc_startd.cpp
- src/condor_schedd.V6/schedd.cpp
The schedd was improperly detecting whether a claim id had an associated security session available for use.
> HTCONDOR-2484 match-session-disable

- src/condor_utils/condor_query.cpp
…mand
QUERY_GENERIC_ADS scans a single table, versus QUERY_ANY_ADS scaning all of the tables. In recent collector changes, QUERY_ANY_ADS stopped paying attention to TargetType in the query ad, whereas QUERY_GENERIC_ADS still looks at it.
> HTCONDOR-2497 any-query

- docs/version-history/lts-versions-23-0.rst
- src/annex/annex.cpp
The segfault only reproduces on the main branch, but this is a bug fix, so...
> (HTCONDOR-2502)  Fix `condor_annex` segfault.

- docs/version-history/lts-versions-23-0.rst
- src/condor_daemon_core.V6/daemon_core_main.cpp
The session cache is highly unlikely to contain any sessions that would authenticate differently if the new token were available. And the cache has many (non-negotiated) sessions that should not be cleared. In particular, removal of the condor@(parent|child|family) sessions will ASSERT()s and other issues.
> HTCONDOR-2517 Don't clear cache after auto-requested token is approved

- src/condor_utils/proc_family_direct_cgroup_v2.cpp
Jobs running under cgroup-v2 get OOM't if they accumulate lots of cached pages, including inode/dentry caches from reading files, since memory.current includes page caches.
Subtract inactive_anon and inactive_file to not include droppable caches in the OOM considerations.
Note: this is completely untested. I wrote this patch as a user, I don't have the possibility of actually running this code on a worker.
> Draft: cgroup-v2: fix memory attribution of cached pages to job

- src/condor_startd.V6/ResMgr.cpp
Following the discussion in the htcondor-users thread (https://www-auth.cs.wisc.edu/lists/htcondor-users/2024-March/msg00049.shtml), this PR calculates the LoadAvg for multi-core slots in a more sensible way: instead of capping the owner_load of a slot to 1.0, it will be the number of cpus in the slot.
In my case, I also wanted to have Condor EPs that are able to treat multi-core jobs somehow similarly to single-core jobs, so that multi-core jobs are able to start executing as far as the load of the machine is less than the total number of CPUs, so I also modified the configuration file to the following, overriding the POLICY:DESKTOP values, though I do not include this in the PR itself, since this is a configuration issue that probably not all sites want to have.
```
NumCPUsIdle = Cpus - …
```
> Fix LoadAvg values, so that they better reflect the number of CPUs of a slot

- src/condor_daemon_client/dc_message.cpp
When the connect fails immediately for a non-blocking message, clear out the info about an in-flight message before notifying the DCMsg about the failure. The ChildAliveMsg will attempt a retry several seconds later using the same DCMessenger, which will otherwise hit an ASSERT().
> HTCONDOR-2532 Fix ASSERT when retrying DC_CHILDALIVE to parent daemon

- src/condor_schedd.V6/schedd.cpp
If a schedd's UID_DOMAIN is changed, users can end up with two user records which differ only in their domain. When there are no more jobs under the old domain's record, the schedd will mark credentials for sweeping even if the user has jobs queued under the new domain's record. As a quick fix, always remove the mark file for a user record that has jobs queued.
> HTCONDOR-2542 Fix credential cleanup when UID_DOMAIN is changed

- nmi_tools/glue/build/build_uw_deb.sh
- nmi_tools/glue/build/make-tarball-from-debs
Previously we just incremented the build ID or added .1 or .2 to the release id. This was confusing to end users and frankly a lie when incrementing the build ID.
So, we just add a system identifier to the package release string.
> HTCONDOR-2523: System ID in release string for Debian and Ubuntu

- src/condor_dagman/parse.cpp
> HTCONDOR-2523 Remove duplicate string::c_str calls in dagman

- src/condor_includes/condor_sys_bsd.h
- src/condor_includes/condor_sys_linux.h
- src/python-bindings/condor_python.h
- src/python-bindings/python_bindings_common.h
We renamed our getline to getline_trim a long time ago, so let's stop doing this foolishness.
> HTCONDOR-2523 Stop #undef'ing getline before including system headers

- src/classad/classad/classad_flat_map.h
- src/condor_shadow.V6.1/remoteresource.cpp
- src/condor_utils/command_strings.h
Casting the an enum to a value outside of the enumeration range is just asking for trouble.
> HTCONDOR-2523 Fix conversion warnings

- src/condor_utils/compat_classad.cpp
dtors for global scope objects being destructed in undefined order. To fix one instance of this, let's not keep global the_match_ad by value in compat_classad.cpp.  Instead, keep a pointer globally, and new it up on first use.
We will leak it, but better than a crash.
Note this crash isn't just an annoyance, we have seen crashes in condor_submit after exit that confuse dagman.
> HTCONDOR-2610 We see random crashes on shutdown, perhaps caused by

- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_starter.V6.1/jic_shadow.cpp
While a small leak, and only one socket, fixes this removes over 800 asan leak report files when running the test suite.
> HTCONDOR-2610 starter memory leak

- src/condor_includes/condor_uid.h
- src/condor_startd.V6/vmuniverse_mgr.cpp
We've seen the vm-gahp block forever attempting to connect to libvirtd. The startd should timeout and kill it if that happens.
> HTCONDOR-2644 Add timeout to vm-gahp test mode invocation

- bindings/python/htcondor/personal.py
- src/condor_tests/ctest_driver
- src/condor_tests/job_core_time-deferral.run
- src/condor_tests/job_dagman_splice-scaling-splice.cmd
- src/condor_tests/ornithology/condor.py
On macOS, 'true' is in /usr/bin, not /bin.
> HTCONDOR-2610 Fix path to 'true' on macOS

- nmi_tools/glue/test/remote_post.pl
tar on macos bails on unreadable files, which some tests generate. Make all files readable before tarring.
> HTCONDOR-2675 Fix test result tarring on macos

- src/condor_utils/store_cred.cpp
This avoids putting extra load on the credmon when there's no work to do.
> HTCONDOR-2653 Don't signal credmon if .use file already exists

- src/condor_startd.V6/vmuniverse_mgr.cpp
If the startd times out waiting for the vm-gahp to exit, it needs to explicitly kill it.
> HTCONDOR-2644 Kill vm-gahp if it hangs

- src/condor_dagman/dag.cpp
- src/condor_dagman/dag.h
-DAGMan will occasionally output warnings about having idle jobs
in the queue despite not submitted nodes. This is due to the
separation of service nodes.
> HTCONDOR-2675: Fix DAGMan idle proc warnings with service nodes

- src/condor_tests/lib_shared_port-check-ports_van.run
Test broke on windows if condor was using both ipv4 and ipv6 addresses.
> HTCONDOR-2672 shared-port-test

- build/packaging/debian/condor-test.install.in
- build/packaging/rpm/condor.spec
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_awaitable_deadline_socket.py
- src/condor_tests/test_awaitable_deadline_socket_client.cpp
- src/condor_tests/test_awaitable_deadline_socketd.cpp
- src/condor_utils/dc_coroutines.cpp
- src/condor_utils/dc_coroutines.h
Implement `dc::AwaitableDeadlineSocket`.  This await()able allows us to write coroutines which return to the event loop and [a]wait for either one (or more) socket(s) to become hot (readable without blocking) or for one (or more) associated timeout(s) to pass.
The first use will be in other code currently under construction, so this PR includes a test that should also serve as an example.
No user-facing documentation or release note is necessary for this strictly-internal improvement.
> (HTCONDOR-2657)  Implement dc::AwaitableDeadlineSocket.

- bindings/python/htcondor2/_schedd.py
- docs/version-history/feature-versions-24-x.rst
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_job_spec_types.py
- src/condor_tools/htcondor_cli/job.py
This fixes a bug in `htcondor annex` and probably saves some of our users some grief.
This also fixes a bug in `htcondor job submit`, so that jobs thusly-submitted acquire credentials as if they'd been `condor_submit`ted.
> (HTCONDOR-2745) Update `job_spec` in `htcondor2.Schedd` to permit `int` cluster IDs.

- src/condor_daemon_core.V6/condor_daemon_core.h
- src/condor_daemon_core.V6/daemon_core.cpp
- src/condor_schedd.V6/schedd.cpp
- src/condor_schedd.V6/scheduler.h
This adds some maps in schedd and daemoncore code that track the runtimes of user commands, fsyncs, and reapers respectively. These statistics are then published in stats queries to the schedd.
Sidenote: some of the formatting looks weird on GitHub but I've made sure everything is spaced appropriately.
> HTCONDOR-2514: Add UserRuntimes, FsyncRuntimes, ReaperRuntimes maps

- docs/version-history/feature-versions-24-x.rst
- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/util.cpp
Using a blank execute path results in the startd trying to cleanup everything under / and all NAMED_CHROOT locations.
> HTCONDOR-2760 Ignore blank execute directory values during cleanup

- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/slot_builder.cpp
- src/condor_startd.V6/startd.h
- src/condor_startd.V6/startd_main.cpp
- src/condor_startd.V6/util.cpp
- src/condor_startd.V6/util.h
Require the EXECUTE directory be owned by the condor user. Don't cleanup invalid EXECUTE directories.
EXCEPT() on an invalid EXECUTE directory if BuildSlotFailureMode::Except is enabled.
> HTCONDOR-2789 execute-cleanup

- src/condor_utils/condor_netaddr.cpp
When condor_netaddr is given a single IPv4 address as a pattern, it sets the wrong bitmask internally. This is due to the code doing a bit shift of 32 on the 32-bit value, which the compiler appears to consider undefined behavior and ignores.
> HTCONDOR-2805 condor_netaddr sets wrong mask for explicit IPv4 address

- docs/version-history/v23-version.hist
- src/condor_schedd.V6/qmgmt_receivers.cpp
The gridmanager doesn't use NoAck and depends on CommitTransaction() succeeding after a failed SetAttribute(). It handles the failure and needs the rest of the changes in the transaction to commit.
> HTCONDOR-2845 qmgmt-xact-failure

- docs/version-history/v23-version.hist
- src/classad/source.cpp
On parse error, always delete partial ExprTree.
> HTCONDOR-2847 Fix ClassAd parsing memory leak

- src/condor_io/authentication.cpp
- src/condor_utils/param_info.in
The code to test if a SciTokens identity in the map file has an errant trailing slash is faulty. The associated knob
SEC_SCITOKENS_ALLOW_EXTRA_SLASH is undocumented.
We should just pull this code out.
> HTCONDOR-2850 scitokens-slash

- docs/version-history/v23-version.hist
- src/condor_gridmanager/gridmanager.cpp
- src/condor_gridmanager/gridmanager_main.cpp
- src/condor_schedd.V6/grid_universe.cpp
This is the only way for the gridmanager to reliably set the ScheddName attribute in its grid ads sent to the collector.
> HTCONDOR-2876 gridmanager-schedd-name

- docs/version-history/v24-version.hist
- src/condor_tools/htcondor_cli/annex.py
There's no need for the missing formal context manager for what `htcondor annex shutdown` was doing, so use `htcondor.param[]` instead.
We can't really regression test this because it requires valid credentials from external providers.  (Also a lot of network access and assumptions about the providers in question being functional but idle.)
> (HTCONDOR-2808)  `htcondor annex shutdown` doesn't work with htcondor2

- src/condor_schedd.V6/grid_universe.cpp
The new gridmanager-specific -n flag must come after the daemoncore -a flag on the command line. This wasn't an issue before 24.X, since we didn't use the -a flag with the gridmanager.
> HTCONDOR-2876 fix-gridmanager-error

- docs/admin-manual/configuration-macros.rst
- docs/classad-attributes/machine-classad-attributes.rst
- docs/version-history/v24-version.hist
- src/condor_startd.V6/ResAttributes.cpp
- src/condor_startd.V6/ResAttributes.h
- src/condor_startd.V6/Resource.cpp
- src/condor_startd.V6/Resource.h
- src/condor_startd.V6/startd_main.cpp
- src/condor_utils/param_info.in
The TotalSlot* resources of a PSlot will be reduced when a DSlot is deleted
while broken.  A new set of BrokenSlot* attributes will advertise the total
resources lost to the PSlot. The default for deleting broken DSlots when
the claim is released will be changed to
CONTINUE_TO_ADVERTISE_BROKEN_DYNAMIC_SLOTS = false
> HTCONDOR-2865 PSlot resources should reflect quantities lost

- docs/version-history/v23-version.hist
- src/condor_daemon_core.V6/daemon_command.cpp
When reusing a cached TCP connection for additional CEDAR commands (e.g. daemons updating the collector), the server shouldn't reject commands when authentication is disabled but encryption or integrity is enabled. That is now a valid configuration.
> HTCONDOR-2888 Allow clients to reuse connections with no authentication

- src/condor_tests/test_spool_preserved_relative_paths.py
This reverts commit 48f8be550f8b806a19d0501a42897c62cf506514, which had "fixed" this test to work with v1 of the bindings for the other active branches.
> Fix test_spool_preserved_relative_paths

- docs/version-history/v24-version.hist
- src/condor_tools/htcondor_cli/annex_create.py
- src/condor_tools/htcondor_cli/annex_validate.py
In addition to requiring memory to be specified, it looks like Expanse now recommends specifying considerably less than the node's listed maximum RAM.  Additionally, the `gpu-shared` queue now has a max of 3 GPUs.
> (HTCONDOR-2634)  Fix (at least some of) htcondor annex's problems with Expanse.

- src/condor_utils/DelegationInterface.cpp
@oshadura noted the following condor error with OpenSSL 3.4.0 (and no issue with OpenSSL 3.3.1):
```
02/10/25 16:00:41 Delegation error: 40F87FE42F7F0000:error:05800091:x509 certificate routines:X509_REQ_verify_ex:unsupported version:crypto/x509/x_all.c:47:
02/10/25 16:00:41 Delegation error: 
02/10/25 16:00:41 ReliSock::put_x509_delegation(): delegation failed: X509Credential::Delegate() failed
02/10/25 16:00:41 DoUpload: SUBMIT at 192.168.202.33 failed to send file(s) to <129.93.239.166:9618>: |Error: sending file /tmp/x509up_u6440; SCHEDD at 129.93.239.166 - |Error: receiving file /var/lib/condor/spool/5376/0/cluster20875376.proc0.subproc0.tmp/x509up_u6440
```
The OpenSSL error appears to be due to an additional check introduced in OpenSSL v3.4.0. …
> HTCONDOR-2904 Update proxy delegation code from ARC CE, cleanup of X509_set_version

- docs/version-history/v23-version.hist
- src/condor_scripts/adstash/ad_sources/startd_history.py
- src/condor_scripts/adstash/adstash.py
- src/condor_scripts/adstash/utils.py
Copied from #3185 rebased onto correct branch.
Instead of using `Collector.locate()`, add `MyAddress` to the projection list when fetching the non-dynamic slot ads the first time, which the Startd objects can use when being created. This not only fixes the incompatibility where `locate()` used to take a Startd slot name instead of a machine name for its `name` argument, but is also much, much faster. We should consider doing this for schedd discovery as well.
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2908
> HTCONDOR-2908 Fix condor_adstash startd discovery

- src/condor_tests/test_fto_pipe_read_full.py
- Some changes made to the FTO code in v24 development series fixed an issue where the shadow and forked child fto shared a data structure which resulted in the spooled files list being passed over the pipe twice (once on input and once on output) resulting in the test message being written twice. This is no longer the case and thus the expected test message is only written once.
> HTCONDOR-2859: fix test in main

- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/schedd.cpp
When an expression rather than a plain string is used for a concurrency limit, recycled claims and partitionable slot leftovers were ignoring the concurrency limit of jobs.
In addition, when a plain string was used for the concurrency limit, recycled claims were not being used to run jobs with identical concurrency limits.  Instead, they were only being used to run jobs with no concurrency limits (or jobs having concurrency limit expressions, not plain strings), irrespective of the matched concurrency limits stored in the claim.
I based this patch on the main branch, but it would be great if we could get it in 23 or 24 LTS.  Concurrency limits could be a good solution for providing a "fast queue" for CMS analysis facilities.
I wish this patch also solved the harder problem of making use …
> Fix bugs affecting concurrency limits expressions, claim recycling, and partitionable slot leftovers.

- src/condor_credd/credd.cpp
- src/condor_tests/test_issue_credentials.py
- src/condor_tools/htcondor_cli/credential.py
- src/condor_tools/store_cred_main.cpp
- src/condor_utils/store_cred.cpp
When the user does condor_store_cred add-oauth or htcondor credential add, if the given service name doesn't match any of the credmons, then the credential data is written directly to a .use file in the user's oauth credentials directory. All credmons will ignore it, and it can be requested by a job via use_oauth_services.
> HTCONDOR-2803 user-stored-creds

- src/condor_daemon_client/dc_startd.cpp
- src/condor_daemon_client/dc_startd.h
- src/condor_includes/condor_commands.h
- src/condor_schedd.V6/schedd.cpp
- src/condor_shadow.V6.1/NTreceivers.cpp
- src/condor_shadow.V6.1/remoteresource.cpp
- src/condor_shadow.V6.1/remoteresource.h
- src/condor_shadow.V6.1/shadow.cpp
- src/condor_startd.V6/ResMgr.cpp
- src/condor_startd.V6/ResMgr.h
- src/condor_startd.V6/ResState.cpp
- src/condor_startd.V6/Resource.cpp
- src/condor_startd.V6/Resource.h
- src/condor_startd.V6/Starter.cpp
- src/condor_startd.V6/Starter.h
- src/condor_startd.V6/claim.cpp
- src/condor_startd.V6/claim.h
- src/condor_startd.V6/cod_mgr.cpp
- src/condor_startd.V6/command.cpp
- src/condor_startd.V6/startd.h
- src/condor_startd.V6/startd_bench_job_mgr.cpp
- src/condor_startd.V6/startd_cron_job_mgr.cpp
- src/condor_startd.V6/startd_main.cpp
- src/condor_tests/test_fto_failure_propagation.py
- src/condor_utils/condor_claimid_parser.h
instead of DEACTIVATE_CLAIM_FORCIBLY when it detects a startd version that understands it.
The Startd will handle this command by delaying the deactivation reply until it has reaped the starter
This fixes the Starter/Shadow/Startd race that was causing lost updates and also
allows for the detection of slots broken by starter exit code before the deactivation reply.
> HTCONDOR-2882 Add DEACTIVATE_CLAIM_JOB_DONE which shadow will use

- docs/version-history/v23-version.hist
- src/condor_filetransfer_plugins/multifile_curl_plugin.cpp
- src/condor_filetransfer_plugins/multifile_curl_plugin.h
- src/condor_tests/test_curl_plugin.py
An RCF noticed that when the local-file source for a URL transfer doesn't exist, the hold message is awful (because the curl plug-in doesn't generate valid output in that case).  This PR generates valid output in that case, causing a dramatic improvement in the hold message.
Arguably, HTCondor should check for file existence before asking a plug-in to work with it, but that's a much bigger ticket.
> (HTCONDOR-2790)  If we can't find a local file, don't not tell Condor.

- docs/version-history/v23-version.hist
- src/condor_collector.V6/collector.cpp
Don't check NEGOTIATOR-level authorization for sending private attributes in query results unless the client is requesting them.
> HTCONDOR-2964 Remove scary security message in collector log

- src/python-bindings/classad2/classad.cpp
- src/python-bindings/htcondor2/job_event_log.cpp
- src/python-bindings/htcondor2/schedd.cpp
I looked for other py_new_*() invocations and a few others where the result went through another function before being returned.  Many (the list-creation routines) were already correct; some were not, and have been fixed.
> (HTCONDOR-2977)  Don't leak pyClusterAd.

- src/condor_tests/CheckOutputFormats.pm
It was looking up an invalid attribute, which causes a perl warning, and happened to pass on machines with no physical gpus.  On machines with gpus, test would always fail
> HTCONDOR-2988 Fix cmd-status-transform test on machines with GPUs

- docs/version-history/v23-version.hist
- src/condor_shadow.V6.1/remoteresource.cpp
When the shadow learns on reconnect that the starter is gone, it shouldn't wait for the job lease to expire before exiting.
Also, don't try to decode a bogus job exit code when the starter exits before job completion.
> HTCONDOR-2997 Shadow shouldn't wait on dead starter

- src/condor_tests/test_fto_failure_propagation.py
- src/condor_tests/test_fto_pipe_read_full.py
The root cause is that occasionally, the starter and shadow get out of sync on job exit, and the starter thinks the old job is still using the slot, and will not accept new activations.
> HTCONDOR-2988 Hacky fix to test flakiness -- up timeout

- src/condor_tests/cmd_q_shows-name.run
- src/condor_tests/cmd_q_shows-pool.run
- src/condor_tests/job_local_resources.run
by replacing condor_status -af Machine with native perl code to get the hostname.  The former doesn't work when you query before the startd ad has made it to the collector.
> HTCONDOR-2988 Robustify flakey tests

- src/condor_kbdd/XInterface.unix.cpp
When investigating the Dreamwork kbdd issue, it would have been much better for the kbdd to log which X server it was trying to talk to. The customer may have been able to solve the issue without contacting us.
> HTCONDOR-2988: kbdd always reports X display

- src/condor_includes/proc.h
- src/condor_utils/proc_id.cpp
- src/condor_utils/ranger.cpp
C++ 23 deprecates std::rel_ops.  This class, given operators < and == synthesizes all the other comparison operators, assuming sane mathematical properties.
The easier way to do this as of C++ 20 is to use the spaceship operator, or better yet, the default spaceship operator.
Let's add the default spaceship to PROC_ID and JOB_ID_KEY, then we can remove the std::rel_ops from the ranger.
Less code, more features!
> HTCONDOR-2988 Fix Fedora 42 warnings about deprecated std::rel_ops

- docs/version-history/lts-versions-23-0.rst
- docs/version-history/v23-version.hist
- src/condor_startd.V6/Resource.h
- src/condor_startd.V6/command.cpp
before putting the slot into claimed state. We also do the check while changing the state, but if the check fails while changing to claimed state there is chance to hit a use-after-free bug leading to a crash of the schedd.
> HTCONDOR-3013 Check to see if a static slot is willing to run a job

- view/ce_dashboard/flask/static/htcondorview.js
We recently added an option “reload_page” to the HTCondorViewRanged class.  The idea is to all graphs on a page to be controlled by one range (day/week/month) selector, and reload all graphs on the page if the range changes.  This is used by the CE Dashboard on some pages.  However, the graph containing the range selector always loaded much slower than all the other graphs on the page.  This commit fixes that.
[Ticket HTCONDOR-3038](https://opensciencegrid.atlassian.net/browse/HTCONDOR-3038)
> HTCONDOR-3038 Fix ce-dashboard reload delay

- build/packaging/rpm/condor.spec
It turns out that the pelican rpm requires glibc-common and that is not available on openSUSE LEAP 15
> HTCONDOR-2983: Remove pelican dependency for openSUSE

- docs/version-history/v24-version.hist
- src/condor_starter.V6.1/jic_shadow.cpp
- src/condor_starter.V6.1/starter.cpp
- src/condor_tests/CMakeLists.txt
- src/condor_tests/test_clean_output_failure.py
Previously, the starter would unconditionally wait a shadow reconnect (or job lease expiration) if transferring output failed for any reason.  This did not cause problems because the starter had already called `notifyStarterError(critical=True)` during the output "clean up"; this caused the shadow to send a `DEACTIVATE_CLAIM_JOB_DONE` command to the startd, which in turn shut down the starter.
Currently, the startd does _not_ shut down the starter after getting that command; it believes it is keeping the slot claimed during clean-up.
This PR changes the starter in two ways:
1.  `JICShadow::notifyStarterError()` will now, when critical is true, also close the syscall socket and set `fast_exit` to true.  This combination will cause it to actually exit as intended.  (In particular, the …
> (HTCONDOR-3073)  Remove inappropriate wait for reconnect

- src/condor_includes/condor_debug.h
- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_schedd.V6/pccc.cpp
- src/condor_schedd.V6/prio_rec.h
- src/condor_schedd.V6/qmgmt.cpp
- src/condor_schedd.V6/qmgmt.h
- src/condor_schedd.V6/schedd.cpp
- src/condor_schedd.V6/schedd_negotiate.cpp
- src/condor_schedd.V6/schedd_negotiate.h
- src/condor_schedd.V6/schedd_stats.cpp
- src/condor_schedd.V6/scheduler.h
- src/condor_tools/advertise.cpp
- src/condor_utils/dprintf_common.cpp
match_rec, and ResourceRequestList classes in the Schedd.  The joblist for each resource request is no longer consumed while talking to the negotiator.  This enables the use of a more complex joblist that can be referred to when matches arrive. This commit also fixes a bug in the stats where the time spend calculating autoclusters was being double counted.
> HTCONDOR-3087 Modernize the c++ and data structure choices for PrioRec

- src/condor_tests/test_condor_history.py
condor_history prints dates of the form "MM/DD " as "MM/D  " (with two spaces) when the date is a single digit.  Update the regexp in the test to match, so that the test passes on single digit days of the month
> HTCONDOR-3060 Fixup test_condor_history regexp for single digit dates

- docs/version-history/v24-version.hist
- src/condor_filetransfer_plugins/multifile_curl_plugin.cpp
This patch sets the user-agent to multifile_curl_plugin/0.2 (or whatever the current version of the plug-in is), which seems to work with that URL fine.  I don’t know what effects, if any, it will have on other servers.
> (HTCONDOR-3121)  Some HTTP URLs require a `user-agent` header

- src/condor_io/condor_auth_passwd.cpp
If the user attempts to look up a token while the database doesn't exist, a version of the `idtokens_minting` table gets created without the `capability` column, leading to a crash.
> Fix missing field in idtokens_minting table

- src/condor_utils/proc_family_direct_cgroup_v2.cpp
Event if constructed with the nothow option, operator++ can still throw...
> HTCONDOR-3186 Always catch exception from stdfs recursive directory iterator

- docs/version-history/v24-version.hist
- src/condor_utils/submit_utils.cpp
This fixes a problem added when the `FROM TABLE` feature went in where in-line item data using item separator was incorrectly parsed.
This fixes such files submitted via *condor_submit* in 24.0, but doesn't help with item data values containing spaces submitted via the Python bindings until later (25.0.x at the latest).
> (HTCONDOR-3272)  Fix in-line unit separators.

- docs/version-history/v24-version.hist
- src/python-bindings/htcondor2/schedd.cpp
Fixes a bug reported by JasonP that we probably hadn't hit before because it requires ignoring an exception.
> (HTCONDOR-3314)  Report the error we checked for instead of blithely skipping into a segfault.

- src/condor_shadow.V6.1/pseudo_ops.cpp
- src/condor_tests/test_cif.py
- src/condor_tests/test_cif_catalogs.py
Move a `dprintf(D_TEST, ...` from where it was printing once per shadow to where the test thought it was printing, once per producer.
As a test-only commit, this PR doesn't need version history, documentation, or its own regression test.
> (HTCONDOR-3313)  Improve test_cif_catalogs.py's reliability.

- docs/admin-manual/configuration-macros.rst
- docs/version-history/v25-version.hist
- src/condor_schedd.V6/dedicated_scheduler.cpp
- src/condor_schedd.V6/dedicated_scheduler.h
- src/condor_schedd.V6/schedd.cpp
- src/condor_schedd.V6/scheduler.h
- src/condor_startd.V6/claim.cpp
- src/condor_startd.V6/command.cpp
- src/condor_utils/param_info.in
Now, the schedd insists that the startd always sends alives and the shadow/starter handle alives when they're running. The startd will still honor schedd-sends-alives requests from the schedd, thought it now assumes no direction from the schedd means startd-sends-alives.
Also, keep match_rec::last_alive in synch with ATTR_LAST_JOB_LEASE_RENEWAL in all code paths and use it instead of consulting the job ad.
> HTCONDOR-3312 startd-always-sends-alives
