htcondor/htcondor

src/condor_gridmanager/boinc-client.cpp, src/condor_gridmanager/boincjob.cpp, src/condor_gridmanager/boincjob.h
This pull request is to make it possible to set the following parameters:
rsc_fpops_est, rsc_fpops_bound, rsc_memory_bound, rsc_disk_bound, delay_bound, app_version_num
when submitting to BOINC through Condor.
See: https://github.com/BOINC/boinc/pull/2377
=> parameter passing to BOINC

src/condor_gridmanager/boinc-client.cpp, src/condor_gridmanager/boincjob.cpp
This change is required to support the parsing of job parameters via the BOINC GAHP.
https://github.com/BOINC/boinc/pull/2416
https://github.com/BOINC/boinc/pull/2512
=> Added support for job parameters

.appveyor.yml, .travis.yml
Tinkering with expanding the Travis build matrix.
=> First whack at adding OS X support to Travis

src/condor_io/condor_auth_ssl.cpp, src/condor_utils/param_info.in
This is something we did a few years back for GSI and is likely what sysadmins expect to be done already!
=> Provide hostname matching for SSL gt7030

src/python-bindings/schedd.cpp
Currently, Submit objects must be assigned strings, as in:
```
sub["foo"] = "1"
```
We now convert to string when this can be done cleanly. Example:
```
sub["foo"] = 1
```
Further, we special case this for assigning ClassAds and Expressions:
```
sub["MY.foo"] = classad.ExprTree("A < B")
```
=> Allow submit object to be assigned non-strings.  #7065

src/condor_daemon_core.V6/daemon_core_main.cpp
This allows users to approve token requests for their own identity. It is semantically equivalent to having the user generate their own token (which is currently allowed) followed by copy/pasting it to a remote machine.
With this work, token generation can be done completely without the user ever "seeing" the token; if the user never touches the token contents, then it reduces the likelihood they'll copy/paste it into a Jupyter notebook and commit it to GitHub!
=> Allow users to approve some token requests. #7159

build/packaging/srpm/condor.spec, src/condor_scripts/CMakeLists.txt, src/condor_scripts/onedrive_plugin.py, src/condor_utils/param_info.in
The OneDrive file transfer plugin uses transfer_input_files
to download files from an individual's OneDrive account.
=> Add the OneDrive file transfer plugin

src/condor_utils/file_transfer.cpp
The FTO should be careful about excluding newlines from hold messages, as these characters are banned by the schedd and cause the entire update to be dropped.  With this change, a newline character becomes the two character sequence `\n`.
=> Escape newlines in hold messages. #7395

src/condor_scripts/condor_aklog
when in part 2 a call to exitwitherr did not propagate the exit code to part 1 - this should fix it
=> extend exitwitherr for part2

src/condor_tools/condor_gpu_discovery.cpp
=> Update condor_gpu_discovery for Ampere GPUs

src/condor_gridmanager/remote_gahp
Accepted format: `[<USER>@]<HOSTNAME>[:<PORT>]`
Inspired by https://github.com/slateci/slate-catalog/pull/337, built off of #130
=> Allow users to specify an SSH port (default: 22)

docs/admin-manual/installation-startup-shutdown-reconfiguration.rst, docs/cloud-computing/using-annex-first-time.rst, docs/overview/support-downloads-bug-reports.rst
This is a mess, but hopefully readable! @Todd-L-Miller
=> Christina's additions to Todd's install instructions

docs/man-pages/condor_history.rst, src/classad/classad/jsonSink.h, src/classad/jsonSink.cpp, src/condor_tools/history.cpp, src/condor_utils/compat_classad.cpp, src/condor_utils/compat_classad.h
"jsonl" is "JSON Lines" - one classad in json per line
=> add -jsonl output format option to condor history (HTCONDOR-35)

docs/getting-htcondor/install-windows-as-administrator.rst
First pass, with minimal editing. 
Could leave open for Todd to look at later today, or merge so changes are "live"
=> Windows installation instructions

src/condor_io/condor_auth_ssl.cpp, src/condor_utils/condor_scitokens.cpp, src/condor_utils/condor_scitokens.h
If there isn't one explicitly configured, utilize a mechanism for locating a token as described here:
https://zenodo.org/record/3937438
=> Use bearer token discovery protocol. HTCONDOR-92

src/python-bindings/collector_plugin.cpp
…-405
This converts a variadic function call using `apply` to simply invoking the plugin with a fixed number of python arguments (which it will always have here).
This also wraps the error handling in a try/catch block, preventing it from propagating exceptions back to the collector (which will then crash the collector).
=> Avoid using `apply` function that does not exist in Python3. HTCONDOR-405

build/docker/services/base/container-install-htcondor.sh
=> Update Ubuntu repo and GPG key URLs

docs/getting-htcondor/admin-quick-start.rst, docs/getting-htcondor/from-our-repositories.rst, docs/getting-htcondor/index.rst, docs/overview/exceptional-features.rst, docs/overview/high-throughput-computing-requirements.rst, docs/overview/htcondors-power.rst, docs/overview/support-downloads-bug-reports.rst
Mostly missing or extra words, punctuation, or misspellings.
=> Fixed some typos in documentation

src/condor_contrib/bosco/bosco_cluster
https://opensciencegrid.atlassian.net/browse/SOFTWARE-4125
=> Keep copies of overridden Bosco files (SOFTWARE-4125)

build/docker/services/build-images
https://opensciencegrid.atlassian.net/browse/HTCONDOR-582
=> Add support for OSG registry (hub.opensciencegrid.org)

src/gpu/cuda_device_enumeration.cpp
=> HTCONDOR-760 fix for segfault in gpu discovery MIG detection

docs/version-history/development-release-series-91.rst
Trying out the personal fork rather than making a branch for this tiny commit.
=> Fix typo in documentation.

src/condor_scripts/get_htcondor, src/condor_tests/test_get_htcondor.py
_get_htcondor_ should treat SL7 as if it were CentOS7
=> V9_1-HTCONDOR-686-branch

docs/version-history/development-release-series-91.rst, src/condor_utils/config.cpp, src/condor_utils/param_info.in
and change AssignAccountingGroup to new syntax
=> HTCONDOR-796 allow herefiles in metaknobs

docs/man-pages/htcondor.rst, docs/version-history/development-release-series-91.rst, src/condor_tests/test_htcondor_cli.py
Couple of things I missed and/or got wrong in the original PR.
=> Fixed tests, man pages and added version history (HTCONDOR-783)

src/condor_utils/globus_utils.cpp, src/python-bindings/schedd.cpp
I found a couple problems when preparing the merge to master.
=> HTCONDOR-810 no gsi, take two

src/condor_io/shared_port_client.cpp
=> HTCONDOR-725 shared port cookie

docs/version-history/stable-release-series-90.rst, src/classad/fnCall.cpp, src/condor_unit_tests/OTEST_Old_Classads.cpp
=> HTCONDOR-823 classad substr crash

docs/version-history/development-release-series-91.rst
=> HTCONDOR-794 Docs for allowed_job_duration

src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-832 disable USE_JOBSETS knob in 9.0

src/condor_starter.V6.1/remote_proc.cpp, src/condor_tests/job_core_bigenv.c, src/condor_utils/credmon_interface.cpp, src/condor_utils/read_user_log.cpp
=> HTCONDOR-834 use std::ignore to silence compiler warnings about unused

docs/version-history/development-release-series-91.rst, src/condor_starter.V6.1/os_proc.cpp
=> HTCONDOR-837 singularity checkpoint

.github/pull_request_template.md
=> (HTCONDOR-834)  Fix a typo in the pull request template.

docs/version-history/development-release-series-91.rst, src/condor_starter.V6.1/docker_proc.cpp, src/condor_starter.V6.1/docker_proc.h, src/condor_starter.V6.1/vanilla_proc.h
=> HTCONDOR-841 docker checkpoint

src/condor_utils/named_classad_list.cpp, src/condor_vm-gahp/vmgahp_common.cpp
=> HTCONDOR-834 "Supplimental"

.github/pull_request_template.md
=> (HTCONDOR-834)  Add regression test(s) to the PR check list.

src/condor_tests/test_num_holds.py
See https://opensciencegrid.atlassian.net/browse/HTCONDOR-849
=> HTCONDOR-849 Fix race condition in test_num_holds.py regression test. 

docs/getting-htcondor/install-macos-as-root.rst
Take advantage of tar options and condor_master's auto creation of
directories to reduce the number of commands that need to be run.
=> HTCONDOR-768 Simplify macOS root install instructions

docs/version-history/development-release-series-91.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-809
=> (HTCONDOR-809)  Version history entry

src/condor_schedd.V6/schedd.cpp
=> fix possible schedd crash in previous HTCONDOR-755 patch

src/condor_tests/ornithology/handles.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-856
Do not process an entire block of job log events before evaluating
wait conditions on a job handle, because this could result in
wait conditions never firing if a jobs state changes rapidly.
Instead, evaluate wait conditions after every job state change.
Also, only sleep if reading the job event log would have blocked.
=> Fix ornithology bug re missed job state changes. HTCONDOR-856

src/classad/operators.cpp
=> HTCONDOR-834 Speed up classad loop with shift right operator

src/classad/classad/common.h, src/classad/fnCall.cpp, src/classad/fuzzer.cpp
=> HTCONDOR-834 Fix random(0) classad function to return error

src/condor_tests/test_docker.py
=> HTCONDOR-866 add standalone docker universe test

docs/version-history/development-release-series-91.rst, src/condor_starter.V6.1/docker_proc.cpp, src/condor_utils/docker-api.cpp
=> HTCONDOR-867 Allow docker universe jobs to run without file xfer

docs/users-manual/file-transfer.rst
Make a number of small changes to improve the S3 documentation.
=> HTCONDOR-868: Improve documentation for non-commercial S3 providers

build/nmi-build/x86_64_AmazonLinux2/Dockerfile, build/nmi-build/x86_64_CentOS7/Dockerfile, build/nmi-build/x86_64_CentOS8/Dockerfile, build/nmi-build/x86_64_Debian10/Dockerfile, build/nmi-build/x86_64_Fedora32/Dockerfile, build/nmi-build/x86_64_Ubuntu18/Dockerfile, build/nmi-build/x86_64_Ubuntu20/Dockerfile
Note: I just blindly added the dependencies called out in the
blahp packaging. There are some duplicates, but I don't care for now.
A wholesale cleanup is coming soon.
=> HTCONDOR-838: Add dependencies to build blahp

src/condor_includes/condor_attributes.h, src/condor_utils/param_info.in, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
=> HTCONDOR-872 submit side support for container universe

nmi_tools/glue/build/set-tarball-rpath
=> HTCONDOR-878 fix up set-tarball-rpath to work on Fedora

build/packaging/srpm/condor.spec, src/condor_contrib/bosco/CMakeLists.txt
https://opensciencegrid.atlassian.net/browse/HTCONDOR-887
=> HTCONDOR-887 Add condor_remote_cluster as alias of bosco_cluster

docs/users-manual/self-checkpointing-applications.rst
First pass at improving self-checkpointing docs by removing knowledge of SPOOL.
=> HTCONDOR-657 Simplify self-checkpointing docs

docs/admin-manual/setting-up-special-environments.rst, docs/man-pages/condor_submit.rst
…_submit man-page (HTCONDOR-788)
=> HTCONDOR-788 Add links between docs on file transfer plugins

src/condor_utils/file_transfer.cpp
=> HTCONDOR-889 Erroneous error message on plug-in failure

docs/admin-manual/configuration-macros.rst, docs/admin-manual/singularity-support.rst, docs/classad-attributes/job-classad-attributes.rst, docs/classad-attributes/machine-classad-attributes.rst, docs/man-pages/condor_remote_cluster.rst, docs/misc-concepts/print-formats.rst, docs/users-manual/choosing-an-htcondor-universe.rst, docs/users-manual/container-universe-jobs.rst, docs/users-manual/index.rst, docs/version-history/development-release-series-91.rst
=> HTCONDOR-881 document container universe

docs/version-history/stable-release-series-90.rst, src/condor_starter.V6.1/singularity.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-885
=> HTCONDOR-885 Fix wrong env var paths inside Singularity

build/packaging/srpm/condor.spec, build/packaging/srpm/rhel7-python2.patch, src/condor_credd/condor_credmon_oauth/condor_credmon_oauth
https://opensciencegrid.atlassian.net/browse/HTCONDOR-633
=> HTCONDOR-633: Package credmon-oauth for EL8

docs/version-history/stable-release-series-90.rst, src/condor_scripts/condor_top
Fixed a bug where the same timestamp value was used for both ads where comparing daemons that don't put either `DaemonStartTime` or `StatsLifetime` in the ad. Also:
- Added a check for if `DaemonStartTime` is different between two daemon ads, and 
- Added a check on the first ad returned by a daemon to make sure it has comparable statistics (otherwise exit early).
Added version history. Nothing changed that affects docs (i.e. the man page).
There are no tests for `condor_top` (not even sure how we would test it), but I tested by hand against each of a CHTC startd, schedd, collector, and negotiator. 
- If the pull request is approved, take the ticket out of …
=> HTCONDOR-880 Fix timestamp problems in condor_top

src/blahp/doc/CMakeLists.txt, src/blahp/src/BUpdaterSGE.c, src/blahp/src/CMakeLists.txt, src/blahp/src/blah_job_registry_add.c, src/blahp/src/blah_utils.c, src/blahp/src/blparser_master.c, src/blahp/src/cmdbuffer.c, src/blahp/src/job_registry_updater.c, src/blahp/src/job_status.c, src/blahp/src/main_daemon.c, src/blahp/src/resbuffer.h, src/blahp/src/server.c, src/blahp/src/test_job_registry_access.c, src/blahp/src/test_job_registry_create.c, src/blahp/src/test_job_registry_update.c, src/blahp/src/test_job_registry_update_from_network.c, src/condor_io/cedar.t.unix.cpp
=> HTCONDOR-878 blahp cleanup

externals/bundles/voms/2.0.13/CMakeLists.txt
=> HTCONDOR-890: Check if using VOMS before searching for libs

docs/overview/contributions-and-acknowledgments.rst, docs/overview/exceptional-features.rst, docs/overview/htcondors-power.rst, docs/overview/support-downloads-bug-reports.rst
=> HTCONDOR-900 Modernize HTCondor's "exception features"

docs/version-history/development-release-series-91.rst, src/blahp/src/scripts/condor_submit.sh
https://opensciencegrid.atlassian.net/browse/HTCONDOR-895
=> HTCONDOR-895 Disable email notifications for blahp->condor jobs.

src/blahp/src/CMakeLists.txt, src/blahp/src/config.c, src/blahp/src/server.c, src/condor_schedd.V6/qmgmt.h, src/python-bindings/python_bindings_common.h
=> HTCONDOR-899 Remove warnings

src/blahp/src/BLClient.c, src/blahp/src/BLParserLSF.c, src/blahp/src/BLParserPBS.c, src/blahp/src/BNotifier.c, src/blahp/src/BUpdaterCondor.c, src/blahp/src/BUpdaterLSF.c, src/blahp/src/BUpdaterPBS.c, src/blahp/src/BUpdaterSGE.c, src/blahp/src/Bfunctions.c, src/blahp/src/blah_job_registry_purge.c, src/blahp/src/blah_job_registry_scan_by_subject.c, src/blahp/src/classad_binary_op_unwind.C, src/blahp/src/classad_c_helper.C, src/blahp/src/commands.c, src/blahp/src/job_registry.c, src/blahp/src/job_registry_updater.c, src/blahp/src/server.c, src/blahp/src/test_job_registry_access.c, src/blahp/src/test_job_registry_create.c, src/blahp/src/test_job_registry_purge.c, src/blahp/src/test_job_registry_update_from_network.c
=> HTCONDOR-899 Fix more blahp compiler warnings.

src/condor_tests/cmd_q_protocols.run
[This page intentionally left blank.]
=> (HTCONDOR-899)  Add a comment explaining the commented-out test config added in HTCONDOR-861.

src/condor_includes/condor_debug.h, src/condor_schedd.V6/jobsets.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_startd.V6/command.cpp, src/condor_utils/DelegationInterface.cpp, src/condor_utils/tree.h
=> V9_6-HTCONDOR-899-fewer-warnings

docs/version-history/stable-release-series-90.rst, src/annex/annex.cpp, src/ec2_gahp/amazonCommands.cpp
A patch from condor-admin 105181.
=> HTCONDOR-910  Fix instance tags and UserData in condor_annex.

build/packaging/srpm/condor.spec
https://opensciencegrid.atlassian.net/browse/HTCONDOR-733
=> HTCONDOR-733: Mark RPM obsolete so that it gets removed upon upgrade

docs/admin-manual/configuration-macros.rst, docs/admin-manual/introduction-admin-manual.rst, docs/admin-manual/networking.rst, docs/classad-attributes/daemon-master-classad-attributes.rst, docs/man-pages/condor_stats.rst, docs/man-pages/condor_status.rst, docs/misc-concepts/classad-mechanism.rst, docs/users-manual/virtual-machine-applications.rst
=> HTCONDOR-914 remove checkpoint server documentation

.github/workflows/publish_release_to_website.yml
Adds workflow that fires when releases are released and adds the release info to htcondor-web. 
Works by using the Github API to get the release info which is dumped into a yaml file at root. This is done with the action posted here -> https://github.com/CHTC/build_release_page/tree/master.
The remaining part of the action ( Line 21+ ) clones the current website and adds the generated yaml file in the appropriate folder to be released on the website.
I have tested using a [forked repo](https://github.com/CannonLock/htcondor) and [test branch on HTCondor-web](https://github.com/htcondor/htcondor-web/commits/preview-test).
- If the pull request is approved, …
=> (HTCONDOR-859) Add workflow to auto Publish/Update/Delete Release News

docs/admin-manual/policy-configuration.rst, docs/version-history/stable-release-series-90.rst, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
https://opensciencegrid.atlassian.net/browse/HTCONDOR-904
=> HTCONDOR-904 blahp default resource requests

build/nmi-build/x86_64_Rocky8/Dockerfile, docs/version-history/introduction-version-history.rst, docs/version-history/stable-release-series-90.rst, nmi_tools/glue/SubmitInfo.pm, nmi_tools/glue/build/make-tarball-from-rpms, nmi_tools/glue/build/remote_declare.pl, nmi_tools/glue/build/remote_post.pl, nmi_tools/glue/build/remote_pre.pl, nmi_tools/glue/build/remote_task.pl, nmi_tools/nmi-build-platforms
https://opensciencegrid.atlassian.net/browse/HTCONDOR-911
My apologies for getting an extra commit regarding the manual in the merge.
=> HTCondor-911: Rocky build on the feature branch

docs/version-history/development-release-series-91.rst, src/condor_utils/user_job_policy.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-922
=> HTCONDOR-922 job duration limit fixes

src/blahp/src/BLfunctions.c, src/blahp/src/Bfunctions.c, src/blahp/src/config.c, src/blahp/src/job_registry.c, src/blahp/src/job_registry_updater.c, src/blahp/src/mapped_exec.c, src/blahp/src/server.c
=> HTCONDOR-899 fix pass at coverity-found blahp issues

src/condor_scripts/get_htcondor, src/condor_tests/test_get_htcondor.py
=> HTCONDOR-94, HTCONDOR-911: get_htcondor updates for Debian 11 and Rocky

docs/getting-htcondor/index.rst, nmi_tools/glue/build/make-tarball-from-debs
Also fix tarball generation for Debian 12 (unsupported)
=> HTCONDOR-94, HTCONDOR-911: Update supported platforms

src/condor_tests/test_allowed_job_duration.py
=> HTCONDOR-899 Allow test_allowed_job_duration a one second rounding error

src/blahp/src/BLfunctions.c, src/blahp/src/Bfunctions.c, src/blahp/src/config.c, src/blahp/src/env_helper.c, src/blahp/src/job_registry.c, src/blahp/src/job_registry.h, src/blahp/src/mapped_exec.c, src/blahp/src/server.c
=> HTCONDOR-899 Second round at fixing coverity-found issues in blahp

src/blahp/src/Bfunctions.c, src/blahp/src/job_registry.c, src/blahp/src/server.c, src/condor_schedd.V6/schedd_negotiate.cpp, src/condor_shadow.V6.1/NTreceivers.cpp, src/condor_starter.V6.1/find_child_proc.cpp, src/condor_starter.V6.1/os_proc.cpp, src/condor_starter.V6.1/singularity.cpp, src/condor_utils/data_reuse.cpp, src/condor_utils/docker-api.cpp, src/condor_utils/user_job_policy.cpp, src/python-bindings/classad.cpp, src/python-bindings/exprtree_wrapper.h
=> HTCONDOR-899 warning removal

docs/version-history/development-release-series-91.rst, src/condor_daemon_client/daemon_list.cpp
=> HTCONDOR-931 collector updating

docs/grid-computing/grid-universe.rst, docs/man-pages/condor_submit.rst, docs/version-history/development-release-series-91.rst, src/condor_gridmanager/arcjob.cpp, src/condor_includes/condor_attributes.h, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
https://opensciencegrid.atlassian.net/browse/HTCONDOR-932
=> HTCONDOR-932 arc env vars

src/blahp/src/CMakeLists.txt, src/blahp/src/job_registry.c, src/blahp/src/server.c
=> HTCONDOR-899 more warning fixes in the blahp

docs/version-history/development-release-series-91.rst, src/condor_unit_tests/CMakeLists.txt, src/condor_unit_tests/OTEST_Timeslice.cpp, src/condor_unit_tests/unit_tests.cpp, src/condor_utils/condor_timeslice.cpp
use the same high precision clock to avoid skew
=> HTCONDOR-934 The timeslice object should never call time(), always

src/condor_utils/file_transfer.cpp
This patch:
* Moves the declaration of `rc` into the loop, but only initializes it once.
* Adds an explicit boolean `all_transfers_succeeded`.  This boolean is `true` at the beginning of time and becomes `false` when the main loop reports an error.  This bool prevents subsequent errors, if any, from over-writing the first one, and is also used to avoid running the plug-in unnecessarily.
* Sets `HoldReasonSubcode` to `0` instead of `rc`, but with a comment indicating that it shouldn't be relied upon until HTCONDOR-847 settles the issue(s) about error reporting.
Not resetting `rc` on each loop iteration may be unduly cautious if we're depending on `all_transfers_succeeded`.
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 …
=> HTCONDOR-915 Alternate Fix

src/blahp/src/BLfunctions.c, src/blahp/src/Bfunctions.c, src/blahp/src/job_registry.c, src/blahp/src/server.c
=> HTCONDOR-899 blahp warnings

docs/version-history/stable-release-series-90.rst, nmi_tools/glue/build/make-tarball-links
https://opensciencegrid.atlassian.net/browse/HTCONDOR-942
=> HTCondor-942: Symlink libgetpwname.so to lib in RPM tarballs

src/condor_tests/job_startd_rank_preempt.run
=> HTCONDOR-899 Fix rare test race condition by using job_prios

nmi_tools/glue/build/make-tarball-from-debs, nmi_tools/glue/build/make-tarball-from-rpms
https://opensciencegrid.atlassian.net/browse/HTCONDOR-946
=> HTCONDOR-946: Don't put the boinc_gahp into the tarball

src/condor_procd/cgroup_tracker.linux.cpp
=> HTCONDOR-899 Use correct class name (CGroupTracker) in procd dprintf

src/condor_tests/CMakeLists.txt, src/condor_tests/test_dagman_submit_description.py
Added tests for DAGMan's new SUBMIT-DESCRIPTION command.
=> HTCONDOR-943 Add tests for DAGMan SUBMIT-DESCRIPTION statements

docs/admin-manual/configuration-macros.rst, docs/version-history/development-release-series-91.rst, src/ccb/ccb_listener.cpp, src/ccb/ccb_listener.h, src/condor_daemon_core.V6/daemon_core.cpp
Duplicates #429, except targets the 9.5.3 branch (and the release note is therefore in a different place).
=> HTCONDOR-925

src/condor_dagman/dagman_main.cpp
Initialized a newly-added DAGMan variable to keep Coverity happy
=> HTCONDOR-899 Coverity update

src/condor_tests/cmd_q_protocols.run
If two jobs happen to run in different slots, that's ok,
ignore the RemoteHost for the diff of condor_q -l output
=> HTCONDOR-899 Fix race condition in cmd_q_protocols test

src/condor_tests/test_htcondor_736.py
=> (HTCONDOR-899)  Spell 'now()' correctly as 'time()'.

docs/admin-manual/configuration-macros.rst, docs/version-history/development-release-series-91.rst, src/condor_includes/condor_attributes.h, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_shadow.V6.1/remoteresource.h, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/job_info_communicator.cpp, src/condor_starter.V6.1/job_info_communicator.h
https://opensciencegrid.atlassian.net/browse/HTCONDOR-954
=> HTCONDOR-954 detect dead starter that fails to send updates

src/blahp/src/job_registry.c, src/blahp/src/job_registry_updater.c, src/blahp/src/job_status.c, src/blahp/src/mapped_exec.c, src/blahp/src/server.c, src/condor_dagman/parse.cpp
=> HTCONDOR-899 several small coverity-found fixes in the blahp and dagman

src/condor_utils/compat_classad.cpp
At TJ's request, merge the "magic function" for matching nested ads.  The magic function will remain deliberately undocumented until further notice (the PEP deliverable which requires it), and we expect some potentially non-trivial changes to it as a result.
The following config may be useful for acceptance testing:
```
if false
x = [ a = "bar"; b = "baz"; ]
y = [ a = "bar"; b = "foo"; ]
z = [ a = "zod"; b = "foo"; ]
AssignedGPUs = { x, y, z }
STARTD_ATTRS = $(STARTD_ATTRS) x y z AssignedGPUs
STARTD_DEBUG = D_FULLDEBUG
NEGOTIATOR_DEBUG = D_FULLDEBUG
SCHEDD_DEBUG = D_FULLDEBUG
```
as might the following submit file fragment:
```
#+w                        = "zod"
#+gpu_requirements         = a == w && b == "foo"
#+AssignedGPUs             = "failure"
```
I have done no acceptance testing …
=> HTCONDOR-710  Merge "magic function" for matching against nested ads

docs/version-history/development-release-series-91.rst
=> HTCONDOR-822 Version history for new file transfer stats. 

src/condor_includes/exit.h, src/condor_schedd.V6/dedicated_scheduler.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_shadow.V6.1/baseshadow.cpp, src/condor_shadow.V6.1/baseshadow.h, src/condor_shadow.V6.1/mpiresource.cpp, src/condor_shadow.V6.1/parallelshadow.cpp, src/condor_shadow.V6.1/parallelshadow.h, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_shadow.V6.1/shadow_v61_main.cpp, src/condor_starter.V6.1/local_user_log.cpp, src/condor_starter.V6.1/os_proc.cpp, src/condor_starter.V6.1/remote_proc.cpp, src/condor_utils/classad_helpers.cpp
=> HTCONDOR-899 misc cleanup

src/classad/CMakeLists.txt
=> HTCONDOR-966 Allow a standalone cmake build of the classad library

src/condor_tests/job_dagman_pre_skip-C.dag, src/condor_tests/job_dagman_pre_skip-C_A.pl, src/condor_tests/job_dagman_pre_skip-C_A.sh
=> HTCONDOR-969 Updated job_dagman_pre_skip-C test to use cross-platform Perl script

docs/users-manual/container-universe-jobs.rst, docs/version-history/development-release-series-91.rst, src/condor_starter.V6.1/os_proc.cpp, src/condor_starter.V6.1/singularity.cpp
=> HTCONDOR-965 run singularity containers "as jobs"

src/condor_schedd.V6/dedicated_scheduler.cpp
=> HTCONDOR-969  Add missing newline to ded sched dprintf

docs/version-history/stable-release-series-90.rst, src/python-bindings/startd.cpp
=> HTCONDOR-936 fix python bindings with startd draining

src/condor_tools/htcondor_cli/job.py
When submitting a job for a specific annex, tag that job with the annex's name, require both that the job run on that annex and that the same user started the annex, and set up job-specific flocking to the annex CM.
=> HTCONDOR-979  Implement `htcondor job submit --annex-name`.

docs/admin-manual/configuration-macros.rst, docs/admin-manual/setting-up-vm-docker-universes.rst, docs/man-pages/condor_submit.rst, docs/users-manual/docker-universe-applications.rst, docs/version-history/development-release-series-91.rst, src/condor_includes/condor_attributes.h, src/condor_startd.V6/ResAttributes.cpp, src/condor_utils/docker-api.cpp, src/condor_utils/submit_utils.cpp
=> HTCONDOR-995 docker-networks

docs/version-history/stable-release-series-90.rst, src/condor_schedd.V6/schedd.cpp, src/condor_tests/CMakeLists.txt, src/condor_tests/test_parallel_uni.py
by storing the name of the dslot, not the pslot.
=> HTCONDOR-986 Allow dedicated scheduler to work with partitionable slots

src/condor_tools/htcondor_cli/dagman.py
=> HTCONDOR-929 Added check to make sure dag status is called on an actual DAGMan job

src/condor_tools/htcondor_cli/annex.py, src/condor_tools/htcondor_cli/job.py
Includes two small changes in other parts of the code for time-pressure reasons.
=> (HTCONDOR-982)  Implement `htcondor annex status`

docs/admin-manual/policy-configuration.rst, docs/classad-attributes/job-classad-attributes.rst, docs/man-pages/condor_submit.rst, docs/version-history/development-release-series-91.rst, src/condor_includes/condor_attributes.h, src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/ResAttributes.h, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h, src/condor_startd.V6/StartdHookMgr.cpp, src/condor_startd.V6/command.cpp, src/condor_startd.V6/slot_builder.cpp, src/condor_startd.V6/startd_cron_job_mgr.cpp, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h, src/gpu/condor_gpu_discovery.cpp, src/gpu/cuda_device_enumeration.h, src/gpu/simulated_device_enumeration.cpp
and allow jobs to require specific custom resources when matchmaking
=> HTCONDOR-953 publish custom resource props as nested ads

src/condor_startd.V6/Resource.cpp
=> HTCONDOR-953 fix previous PR

src/condor_starter.V6.1/starter.cpp, src/condor_utils/DelegationInterface.cpp, src/python-bindings/schedd.cpp
=> V9 8 htcondor 969 warning removal

docs/version-history/stable-release-series-90.rst, src/condor_daemon_core.V6/daemon_core_main.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-937
=> HTCONDOR-937 family session invalidation

src/condor_daemon_core.V6/daemon_core_main.cpp
=> HTCONDOR-969 Improve key invalidate string handling

src/condor_scripts/annex/stampede2.sh, src/condor_tools/htcondor_cli/annex.py, src/condor_tools/htcondor_cli/annex_create.py
This is probably one of those PRs which will probably only make sense if reviewed one commit at a time.
=> HTCONDOR-1000  Miscellaneous pre-release improvements.

docs/users-manual/file-transfer.rst, docs/version-history/stable-release-series-90.rst, src/condor_filetransfer_plugins/multifile_curl_plugin.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1011
Obsoletes #439 
=> HTCONDOR-1011 Access creds with underscores in curl plugin

src/condor_scripts/annex/stampede2.sh, src/condor_tools/htcondor_cli/annex.py, src/condor_tools/htcondor_cli/annex_create.py, src/condor_tools/htcondor_cli/job.py
The machine-table stuff could be pulled out into another branch, especially if that helps merge Mat's changes, but the actual effect on the code is small.
=> HTCONDOR-1004 Miscellaneous pre-release UI/UX improvements.

src/condor_procapi/procapi.cpp, src/condor_procapi/procapi.h, src/condor_procd/proc_family_monitor.cpp, src/condor_procd/proc_family_monitor.h
=> HTCONDOR-1001 - V9_8-HTCONDOR-1001-procd-debug

build/cmake/CondorConfigure.cmake
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1014
=> HTCONDOR-1014: dlopen voms libraries even without GSI present

nmi_tools/glue/build/build.win.bat
=> HTCONDOR-1008 fix for packages missing version in filename on windows

build/packaging/srpm/condor.spec, docs/version-history/development-release-series-91.rst, src/condor_gridmanager/remote_gahp, src/condor_scripts/condor_remote_cluster, src/rvgahp/CMakeLists.txt, src/rvgahp/common.c, src/rvgahp/common.h, src/rvgahp/rvgahp_client.c, src/rvgahp/rvgahp_proxy.c, src/rvgahp/rvgahp_server.c
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1007
=> HTCONDOR-1007 import rvgahp with minor changes

src/condor_tools/htcondor_cli/job.py
If it's not enable, bail. (See HTCONDOR-1021.)
=> (HTCONDOR-1025)  Use the new job transform.

docs/grid-computing/grid-universe.rst
Includes adding section about condor_remote_cluster and the Reverse
GAHP.
=> HTCONDOR-969 Update grid batch docs

docs/users-manual/file-transfer.rst
=> HTCONDOR-969: Fixup Pygment lexer in file transfer docs

docs/admin-manual/configuration-macros.rst, docs/man-pages/condor_token_fetch.rst, docs/version-history/development-release-series-91.rst, docs/version-history/stable-release-series-88.rst, src/condor_daemon_client/daemon.cpp, src/condor_daemon_client/daemon.h, src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_includes/condor_attributes.h, src/condor_tools/token_fetch.cpp, src/condor_utils/param_info.in
Allow the user to choose from an admin-defined list of signing keys which key to sign their `condor_token_request` with.
=> (HTCONDOR-1024)  Implement condor_token_fetch -key.

build/packaging/srpm/condor.spec
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1030
=> HTCONDOR-1030: Don't have a Globus conditional in the RPM spec

src/condor_scripts/condor_remote_cluster
- Use 9.x, 10.x, etc. for feature releases
- Adjust to ISO 8601 date format in condor_version
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1029
=> HTCONDOR-1029: Fix condor_remote_cluster script

docs/version-history/stable-release-series-90.rst, src/classad/classad/literals.h, src/classad/classad/source.h, src/classad/fuzzer.cpp, src/classad/literals.cpp, src/classad/source.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-998
=> HTCONDOR-998: Backport HTCONDOR-814

docs/version-history/development-release-series-91.rst, src/condor_schedd.V6/prio_rec.h, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-961 prio rec sorting

src/condor_schedd.V6/qmgmt.cpp
=> HTCONDOR-961: Review change: const args in prio_compar

src/condor_utils/docker-api.cpp, src/condor_utils/submit_utils.cpp
=> HTCONDOR-1043 All docker uni jobs to explicitly request "nat" network

docs/admin-manual/security.rst, docs/man-pages/condor_ping.rst, docs/version-history/development-release-series-91.rst, src/condor_contrib/campus_factory/python-lib/GlideinWMS/condorSecurity.py, src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_includes/condor_perms.h, src/condor_startd.V6/startd_main.cpp, src/condor_tools/ping.cpp, src/condor_utils/command_strings.cpp, src/condor_utils/condor_perms.cpp, src/condor_utils/param_info.in, src/python-bindings/secman.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1023
=> HTCONDOR-1023 Remove OWNER auth level

src/classad/classad/value.h, src/classad/fnCall.cpp, src/classad_analysis/analysis.cpp, src/python-bindings/schedd.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-972
=> HTCONDOR-972 Fix minor boolean -> integer conversion in ClassAds

src/condor_tests/job_router_xform.run
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1050
=> HTCONDOR-1050 - V9_8-HTCONDOR-1050-fix-router-test

src/condor_tools/htcondor_cli/annex.py
I screwed up the commit history in #524, this PR replaces that one (and targets the correct branch).
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1021
=> HTCONDOR-1021 HTCondor CLI checks if annex enabled

src/condor_scripts/annex/bridges2.multi-pilot, src/condor_scripts/annex/bridges2.pilot, src/condor_scripts/annex/bridges2.sh, src/condor_tools/htcondor_cli/annex_create.py
A Bridges-2 backend for HPC Annex.  This does not include the GPU queues because the semantics for accessing those are different enough that we can save them for later.
=> HTCONDOR-983: Bridges-2 backend

src/condor_scripts/annex/expanse.sh, src/condor_scripts/annex/stampede2.sh, src/condor_tools/htcondor_cli/annex.py, src/condor_tools/htcondor_cli/annex_create.py, src/condor_tools/htcondor_cli/job.py
Lots of mostly minor changes from Miron's feedback.
=> HTCONDOR-1033 Miron demo feedback.

src/condor_tests/job_dagman_maxpostscripts-checkin.template, src/condor_tests/job_dagman_prepost-posthello.template, src/condor_tests/job_dagman_prepost-prehello.template
=> HTCONDOR-1052 - V9_8-HTCONDOR-1052-dagman-test

src/condor_scripts/annex/annex-local-universe.py, src/condor_scripts/annex/bridges2.sh, src/condor_tools/htcondor_cli/annex.py, src/condor_tools/htcondor_cli/annex_create.py, src/condor_utils/param_info.in
Fetching a new collector token for each new annex request makes it dead simple to do key management, plus it removes the need for the admins to issue collector tokens to new users.
=> HTCONDOR-1020  Fetch collector token on every annex request.

src/condor_collector.V6/view_server.cpp, src/condor_negotiator.V6/Accountant.cpp, src/condor_schedd.V6/dedicated_scheduler.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_utils/log.h
=> HTCONDOR-1026 - V9_8-HTCONDOR-1026-no-use-std

src/condor_tests/test_job_submit_method_recording.py
=> HTCONDOR-1048 Improve Job Submit Method Recording Ornithology Test

docs/version-history/stable-release-series-90.rst, src/condor_includes/condor_config.h, src/condor_tools/config_val.cpp, src/condor_utils/config.cpp
=> HTCONDOR-1032 add support for multiline values to condor_config_val

docs/admin-manual/singularity-support.rst, docs/version-history/development-release-series-91.rst, src/condor_starter.V6.1/singularity.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1059
=> HTCONDOR-1059 - V9_8-HTCONDOR-1059-singularity-docker

src/condor_includes/condor_constants.h, src/condor_includes/condor_universe.h, src/condor_utils/condor_universe.cpp
=> HTCONDOR-1026 Remove BOOLEAN typedef

docs/version-history/development-release-series-91.rst, src/classad/operators.cpp, src/condor_unit_tests/OTEST_Old_Classads.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1065
=> HTCONDOR-1065 - V9_8-HTCONDOR-1065-classad-array

docs/classads/classad-mechanism.rst, docs/users-manual/submitting-a-job.rst
=> HTCONDOR-1026 - V9_8-HTCONDOR-1026-doc-typos

build/nmi-build/x86_64_AmazonLinux2/Dockerfile, build/nmi-build/x86_64_CentOS7/Dockerfile, build/nmi-build/x86_64_Debian10/Dockerfile, build/nmi-build/x86_64_Debian11/Dockerfile, build/nmi-build/x86_64_Debian12/Dockerfile, build/nmi-build/x86_64_Fedora32/Dockerfile, build/nmi-build/x86_64_Rocky8/Dockerfile, build/nmi-build/x86_64_Ubuntu18/Dockerfile, build/nmi-build/x86_64_Ubuntu20/Dockerfile
Note that we can't remove pcre (1) for quite some time
=> HTCONDOR-1066 - V9_8-HTCONDOR-1066-pcre2-images

docs/version-history/development-release-series-91.rst
=> (HTCONDOR-1070)  Release note.

build/nmi-build/x86_64_Debian10/Dockerfile, build/nmi-build/x86_64_Debian11/Dockerfile, build/nmi-build/x86_64_Debian12/Dockerfile, build/nmi-build/x86_64_Ubuntu18/Dockerfile, build/nmi-build/x86_64_Ubuntu20/Dockerfile
=> HTCONDOR-1076 - V9_9-HTCONDOR-1076-pcre2-headers

src/condor_scripts/CondorPersonal.pm
=> HTCONDOR-1081 - V9_8-HTCONDOR-1081-condor-offest

docs/admin-manual/security.rst
=> HTCONDOR-1026: Fix formatting in documentation

src/blahp/CMakeLists.txt, src/blahp/config/CMakeLists.txt, src/openstack_gahp/rapidjson.src/example/CMakeLists.txt
=> HTCONDOR-1026 - V9_8-HTCONDOR-1026-cmake-minimum

src/condor_daemon_client/daemon.cpp, src/condor_daemon_client/daemon.h, src/condor_daemon_client/dc_message.cpp, src/condor_daemon_client/dc_message.h, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_includes/condor_secman.h, src/condor_io/condor_secman.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1054
=> HTCONDOR-1054 Make DCSignalMsg non-blocking again

src/classad/CMakeLists.txt, src/classad/fnCall.cpp
I was able to pass the tests by first installing only the libraries for classad, and then running in the project's build directory:
`LD_PRELOAD=/path/to/classad/libs/libclassad.so` ctest3 -j 40 -R classad`
However, I was able to pass the tests even with some part of the code changed, so I am not completely sure if my changes are valid.
=> Update PCRE library to PCRE2 for classad

src/condor_collector.V6/collector.cpp, src/condor_collector.V6/collector.h, src/condor_collector.V6/collector_engine.cpp, src/condor_collector.V6/collector_engine.h, src/condor_collector.V6/view_server.cpp, src/condor_collector.V6/view_server.h, src/condor_utils/hashkey.h
Keep "private" attributes in a second ad inside the collector. No visible change in the public interfaces of the collector.
=> HTCONDOR-1083 - V9_9-HTCONDOR-1083-collector-private-ad

src/condor_utils/submit_utils.cpp
=> HTCONDOR-996 job submit method recording branch

docs/admin-manual/configuration-macros.rst, docs/version-history/stable-release-series-88.rst, docs/version-history/stable-release-series-90.rst, src/condor_includes/condor_cron_job.h, src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/schedd_td.cpp, src/condor_tests/test_htcondor_971.py, src/condor_utils/cron_job.cpp
1. 7d63472bf1bc52fb841c2943f650313be225b9b1 implements the minimum improvement.
2. 5bafb1d37a38feefc4d7b18cca4642aec8db6216 tests the minimal improvement.
3. 68474f0ea5cd4febfe9a08aa6346368d76456c92 and e1f9648530308eb3bf3242c515505c7f0304a0a6 implement something that would very nice to have, but could be vetoed by the reviewer as too large/risky/new for stable.
=> HTCONDOR-971  Log schedd/startd cron errors

src/condor_tests/cmd_q_protocols.run
=> HTCONDOR-1026 - V9_9-HTCONDOR-1026-cmd_q_D_NETWORK

bindings/python/classad/__init__.py, bindings/python/htcondor/__init__.py
Replaced one-line `memoryview()` hack with an explicit "no-op" context manager.
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1008
=> HTCONDOR-1008 Fix Python init scripts for Python 2.7

src/condor_collector.V6/collector_engine.cpp, src/condor_schedd.V6/qmgmt.cpp, src/rvgahp/rvgahp_server.c
=> HTCONDOR-1096 Fix unused variable warnings

docs/man-pages/condor_set_shutdown.rst, docs/version-history/stable-release-series-90.rst, src/condor_master.V6/master.cpp, src/condor_master.V6/master.h, src/condor_master.V6/masterDaemon.cpp, src/condor_tools/tool.cpp
=> HTCONDOR-1102 improve manual, usage and logging 

src/condor_master.V6/master.cpp
=> HTCONDOR-1096 - V9_9-HTCONDOR-1096-master

docs/admin-manual/security.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-651
=> HTCONDOR-651 Add doc note about DN+FQAN serialization in the map file

src/condor_scripts/annex/anvil.multi-pilot, src/condor_scripts/annex/anvil.pilot, src/condor_scripts/annex/anvil.sh, src/condor_tools/htcondor_cli/annex_create.py
=> HTCONDOR-1031  Anvil back-end script

src/blahp/config/blah.config.template, src/condor_collector.V6/collector_engine.cpp, src/condor_collector.V6/collector_engine.h, src/condor_tests/unit_test_sinful.run, src/condor_utils/KeyCache.cpp
=> HTCONDOR-1096 - V9_10-HTCONDOR-1096-misc-cleanup

src/condor_collector.V6/CMakeLists.txt
=> HTCONDOR-1096 - V9_10-HTCONDOR-1096-ceaudit-needs-condorutils

docs/admin-manual/configuration-macros.rst, docs/admin-manual/policy-configuration.rst
=> HTCONDOR-912 First cut at documentation

src/condor_includes/condor_attributes.h, src/condor_q.V6/queue.cpp, src/condor_schedd.V6/qmgmt_receivers.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/schedd_main.cpp, src/condor_utils/classad_oldnew.cpp, src/condor_utils/classad_oldnew.h, src/condor_utils/condor_q.cpp, src/condor_utils/condor_q.h, src/python-bindings/schedd.cpp
Only send ServerTime to condor_q
=> HTCONDOR-1125 Reduce use of ServerTime attribute

src/condor_q.V6/queue.cpp
=> HTCONDOR-1128 - V9_10-HTCONDOR-1128-flush_condor_q

docs/man-pages/condor_advertise.rst
Invalidation ads need a Name or Machine and SlotID attribute.
=> HTCONDOR-1130 Fix condor_advertise example

src/condor_rm.V6/rm.cpp, src/condor_tools/config_val.cpp, src/condor_tools/history.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1116
=> HTCONDOR-1116 - Remove duplicate code in condor_config_val

externals/bundles/voms/2.1.0/CMakeLists.txt, externals/bundles/voms/2.1.0/voms-openssl3.patch
=> HTCONDOR-1131 - V9_10-HTCONDOR-1131-voms-openssl3

src/condor_tests/job_filexfer_merged-stdout_van.run
Cherry-pick fixing of this test to 9.0, where the test was introduced.
=> HTCONDOR-1101 Modify merged stdout/err test on Windows

docs/admin-manual/configuration-macros.rst, docs/version-history/development-release-series-91.rst, src/condor_daemon_client/daemon.cpp, src/condor_daemon_client/daemon.h, src/condor_tools/drain.cpp, src/condor_tools/fetch_log.cpp, src/condor_tools/token_request_auto_approve.cpp, src/condor_tools/user_prio.cpp, src/condor_utils/param_info.in, src/defrag/defrag.cpp, src/python-bindings/dc_tool.cpp
Use RemoteAdminCapability everywhere
=> HTCONDOR-1122 Use remote admin capability

docs/classad-attributes/job-classad-attributes.rst, docs/classad-attributes/machine-classad-attributes.rst, docs/classad-attributes/scheduler-classad-attributes.rst
Also move some mis-placed index entries.
=> HTCONDOR-1130 Fix up ServerTime and MyCurrentTime attr docs

src/condor_schedd.V6/schedd.cpp, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_shadow.V6.1/shadow.cpp, src/condor_starter.V6.1/NTsenders.cpp, src/condor_starter.V6.1/jic_shadow.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-960
=> HTCONDOR-960 shadow failure handling

docs/version-history/development-release-series-91.rst, src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/singularity.h
=> HTCONDOR-1137 - V9_10-HTCONDOR-1137-apptainer-env

docs/version-history/development-release-series-91.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-960
=> HTCONDOR-960 docs for shadow bug fixes

build/packaging/srpm/condor.spec, docs/version-history/stable-release-series-90.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1127
=>  HTCONDOR-1127: RPM packaging to ensure proper python-condor version

docs/version-history/development-release-series-91.rst, src/condor_io/condor_auth_ssl.cpp
=> HTCONDOR-1148 - V9_10-HTCONDOR-1148-openssl-v3

src/annex/annex.cpp, src/arc_gahp/arcCommands.cpp, src/condor_utils/AWSv4-utils.cpp, src/condor_utils/AWSv4-utils.h, src/condor_utils/CMakeLists.txt, src/condor_utils/shortfile.cpp, src/condor_utils/shortfile.h, src/ec2_gahp/amazonCommands.cpp, src/gce_gahp/gceCommands.cpp
We had a bunch of copy-and-pasted implementations, one of which had a bug fixed in the others.
=> (HTCONDOR-1145)  Unify [read|write]ShortFile() implementations.

build/packaging/srpm/condor.spec, docs/version-history/development-release-series-91.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1074
=> HTCONDOR-1074: Require matching version of condor with blahp

src/condor_tools/htcondor_cli/annex_create.py
as per announcement at https://www.rcac.purdue.edu/news/4444
=> HTCONDOR-860: Update anvil queue definition for HPC annex to rename standard to wholenode

src/condor_tests/testoverride.not
=> HTCONDOR-1121 minor fix up

src/condor_utils/xform_utils.cpp
=> HTCONDOR-1121 xform_utils null checks, and allocate Basic defaults

build/docker/services/build-images
https://opensciencegrid.atlassian.net/browse/HTCONDOR-969
=> HTCONDOR-1096: Fix up date format for generating Docker images

docs/admin-manual/configuration-macros.rst, docs/version-history/development-release-series-91.rst, src/condor_io/condor_auth_x509.cpp, src/condor_utils/globus_utils.cpp, src/condor_utils/param_info.in
=> HTCONDOR-1161 Disable VOMS by default

docs/admin-manual/security.rst, docs/version-history/development-release-series-91.rst, src/condor_utils/condor_perms.cpp
ADVERTISE_* auth levels imply READ auth
=> HTCONDOR-1164 - ADVERTISE_* auth levels imply READ auth

src/condor_tests/CMakeLists.txt, src/condor_tests/cmd_status_shows-help.run
=> HTCONDOR-1176 - V9_10_0-HTCONDOR-1176-qemu-test-fixes

build/packaging/srpm/condor.spec, docs/version-history/stable-release-series-90.rst
[HTCONDOR-1177>](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1177)
=> HTCONDOR-1177: Relax condor-externals dependencies

build/packaging/srpm/condor.spec, docs/version-history/development-release-series-91.rst
[HTCONDOR-1177](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1177)
=> HTCONDOR-1177: Remove unneeded condor-externals package

build/packaging/srpm/condor.spec, docs/version-history/development-release-series-91.rst
=> HTCONDOR-1177: Still need externals package to help yum with upgrades

docs/apis/user-job-log-reader-api.rst
=> HTCONDOR-1130 Fix wrong class name in c++ log reader api docs

docs/admin-manual/directories.rst
=> (HTCONDOR-1147)  Update `SPOOL` section.

docs/version-history/stable-release-series-90.rst, src/condor_io/shared_port_endpoint.cpp, src/condor_io/shared_port_endpoint.h
=> V9 0 htcondor 1178 branch

externals/bundles/scitokens-cpp/0.5.0/CMakeLists.txt, externals/bundles/scitokens-cpp/0.5.0/sqlite3-leak.patch
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1188
=> HTCONDOR-1188 Patch fd leak in SciTokens library

docs/version-history/stable-release-series-90.rst, src/condor_scripts/condor_check_config
Just like #669 but targeting the correct branch...
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1186
=> HTCONDOR-1186 Fix undefined variable in condor_check_config

externals/bundles/scitokens-cpp/0.7.0/CMakeLists.txt, externals/bundles/scitokens-cpp/0.7.0/sqlite3-leak.patch
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1188
=> HTCONDOR-1188 - Fix fd leak in scitokens library

docs/version-history/stable-release-series-90.rst, src/gpu/condor_gpu_discovery.cpp
=> HTCONDOR-1191 gpu discovery crash formatting diag message in OpenCL code path

src/condor_status.V6/status.cpp, src/condor_utils/condor_query.cpp, src/condor_utils/condor_query.h, src/condor_who/who.cpp, src/python-bindings/collector.cpp
=> HTCONDOR-1189 add -snapshot debugging argument to condor_who

docs/version-history/development-release-series-91.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1125
=> HTCONDOR-1125 Version history for ServerTime change

docs/version-history/development-release-series-91.rst, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_tests/cmd_q_protocols.run, src/condor_tests/test_activation_metrics.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1190
Note: we may want this to go into V9_10_1-branch once it exists if it is too late for going into V9_10_0-branch....
=> HTCONDOR-1190 Fix for inflated values of ActivationSetupDuration for checkpointing jobs

docs/version-history/development-release-series-91.rst, src/classad/CMakeLists.txt
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1196
=> HTCONDOR-1196  Restore CLASSAD_USER_LIBS functionality of dlopen'ing custom classad function extensions

src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_negotiator.V6/matchmaker.h
=> HTCONDOR-1163 Remove last vestiges of quill

docs/version-history/stable-release-series-90.rst, src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_includes/condor_debug.h, src/condor_utils/dprintf.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1200
=> HTCONDOR-1200 fix shutdown crashes

build/cmake/CondorConfigure.cmake
as it tends to crash on qemu (at least).
=> V9_11-HTCONDOR-1200-ppc-cant-backtrace

NOTICE.txt
=> HTCONDOR-1163: Drop makemsi external from NOTICE file

docs/version-history/stable-release-series-90.rst, src/condor_gridmanager/infnbatchjob.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1199
=> HTCONDOR-1199 report blahp provisioned resources

docs/admin-manual/user-priorities-negotiation.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1209
Negotiator rank sorting isn't explained well in the manual.  Add an example with a table to try to explain it better.
=> HTCONDOR-1209 Update manual to explain negotiator rank sorting better

docs/version-history/development-release-series-91.rst, src/condor_dagman/dagman_main.cpp, src/condor_dagman/parse.cpp, src/condor_dagman/parse.h, src/condor_tests/job_dagman_vars_prepend.run
-Fixed broken default behavior to work correctly rather than always appending
-Updated test to better check for correct output so default isn't overlooked
=> HTCONDOR-1080: DAGMan ability to PREPEND/APPEND VARS to job submit files

docs/version-history/stable-release-series-90.rst, src/condor_starter.V6.1/jic_shadow.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1213
=> HTCONDOR-1213 starter cleanup hang

docs/admin-manual/policy-configuration.rst, docs/man-pages/condor_gpu_discovery.rst, docs/version-history/development-release-series-91.rst, src/gpu/condor_gpu_discovery.cpp
Where "docs" include the man page and admin config guide.
=> HTCONDOR-717 add -not-nested argument to condor_gpu_discovery and update docs

src/python-bindings/schedd.cpp
I spent too much time figuring out how this works to not update the docs to make it easier for the next person.
Also fix a bunch of typos and spelling errors.
=> HTCONDOR-1163 Clarify python bindings docs around spooling submits

src/condor_utils/job_ad_instance_recording.cpp
=> HTCONDOR-1136 add windows append mode code to job ad epoch recording

docs/admin-manual/singularity-support.rst, docs/classad-attributes/job-classad-attributes.rst, docs/man-pages/condor_submit.rst, docs/version-history/development-release-series-91.rst, src/condor_includes/condor_attributes.h, src/condor_starter.V6.1/os_proc.cpp, src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/singularity.h, src/condor_tests/test_container_uni.py, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1171
=> HTCONDOR-1171  Add per-job container target dir

src/condor_utils/globus_utils.cpp
Since we are possibly moving/removing the wiki I have created a permanent location for this on the HTCSS website.
https://htcondor.org/news/plan-to-replace-gst-in-htcss/
=> HTCONDOR-1212: Update url of the GST Transition document

build/packaging/srpm/condor.spec, docs/version-history/stable-release-series-90.rst
=> HTCONDOR-1217: python3 mod wsgi dependency

src/condor_contrib/plumage/src/plumage_history_load_main.cpp, src/condor_schedd.V6/dedicated_scheduler.cpp, src/condor_schedd.V6/dedicated_scheduler.h, src/condor_unit_tests/OTEST_StringList.cpp, src/condor_utils/string_list.cpp, src/gpu/condor_gpu_utilization.cpp
=> HTCONDOR-1163 convert qsort(3) to std::sort

docs/admin-manual/configuration-macros.rst
=> HTCONDOR-1130 Fix SEC_*_CRYPTO_METHODS docs

src/condor_startd.V6/VolumeManager.cpp, src/condor_startd.V6/VolumeManager.h
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1219
=> HTCONDOR-1219 fix-lvs-crash

docs/version-history/stable-release-series-90.rst, src/condor_gridmanager/infnbatchjob.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1199
=> HTCONDOR-1199 blahp resources for 9.0.15

src/blahp/src/scripts/slurm_status.py
(Copied from github.com/htcondor/BLAH)
=> HTCONDOR-1207 report slurm cpus allocated

docs/version-history/development-release-series-91.rst, src/condor_utils/file_transfer.cpp
Submit files like the following
```
transfer_input_files        = output/dirA
transfer_checkpoint_files   = output/dirA/checkpoint
preserve_relative_paths     = true
```
would go on hold, and submit files like the following would silently fail to transfer files in `output` that weren't in the checkpoint:
```
transfer_input_files        = output
transfer_checkpoint_files   = output/checkpoint
preserve_relative_paths     = true
```
In the first case, the file de-duplication code in `DoUpload()` was incorrectly not ignoring directories.  In the second case, the file de-duplication code in `HandleCommands()` was incorrectly not ignoring directories.
- If the …
=> HTCONDOR-1218  More checkpointing + preserve relative path failures.

docs/version-history/stable-release-series-90.rst, src/condor_ft-gahp/io_loop.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1222
=> HTCONDOR-1222 fix ft-gahp proxy refresh

docs/version-history/stable-release-series-90.rst, src/condor_gridmanager/infnbatchjob.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1223
=> HTCONDOR-1223 gridmanager proxy cleanup

docs/version-history/stable-release-series-90.rst, src/condor_gridmanager/infnbatchjob.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1224
=> HTCONDOR-1224 batch removed jobid

docs/version-history/stable-release-series-90.rst, src/condor_gridmanager/infnbatchjob.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1226
=> HTCONDOR-1226 don't resubmit grid batch jobs

src/condor_job_router/JobRouter.cpp
=> HTCONDOR-1228 warning-removal

docs/version-history/development-release-series-91.rst, src/condor_utils/file_transfer.cpp
We're going to try this in 9.11.0 and see how it goes.
=> HTCONDOR-1218  Cherry-pick back to 9.11.0

src/condor_collector.V6/collector.cpp
=> HTCONDOR-1233 fix-use-after-free

docs/version-history/stable-release-series-90.rst, src/condor_utils/dynuser.WINDOWS.cpp
=> HTCONDOR-1232 increase complexity of windows slot user passwords

README.md, build/docker/services/mini/00-minicondor-ubuntu, build/packaging/new-debian/changelog, build/packaging/new-debian/control, build/packaging/new-debian/control.focal, build/packaging/new-debian/control.stretch, build/packaging/new-debian/control.xenial, build/packaging/new-debian/upstream/metadata, build/packaging/srpm/condor.spec, docs/apis/python-bindings/install.rst, docs/apis/python-bindings/tutorials/ClassAds-Introduction.ipynb, docs/getting-htcondor/admin-quick-start.rst, docs/grid-computing/grid-universe.rst, docs/overview/support-downloads-bug-reports.rst, docs/users-manual/quick-start-guide.rst, src/condor_examples/00-minicondor
Changes over the links to point to the new domain name. 
=> HTCONDOR-1205 Update the research.cs.wisc.edu links to point to the new domain

src/condor_scripts/adstash/elastic.py
Cherry-picked https://github.com/htcondor/htcondor/pull/722 to LTS branch. Resolves #722. Minor fix for error that only happens when other things go wrong, probably doesn't need docs.
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1237
=> HTCONDOR-1237 Fix missing sys import for line 136

src/condor_daemon_core.V6/daemon_core.cpp, src/condor_dagman/parse.cpp, src/condor_starter.V6.1/singularity.cpp
=> HTCONDOR-1233 fix memory leaks

src/ccb/ccb_server.cpp, src/condor_collector.V6/collector.cpp, src/condor_credd/credd.cpp, src/condor_daemon_client/dc_message.cpp, src/condor_daemon_client/dc_schedd.cpp, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_command.cpp, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_gridmanager/gridmanager.cpp, src/condor_io/condor_secman.cpp, src/condor_io/shared_port_client.cpp, src/condor_master.V6/master.cpp, src/condor_schedd.V6/dedicated_scheduler.cpp, src/condor_schedd.V6/qmgmt_receivers.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/tdman.cpp, src/condor_schedd.V6/transfer_queue.cpp, src/condor_shadow.V6.1/shadow.cpp, src/condor_startd.V6/claim.cpp, src/condor_startd.V6/startd_main.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_transferd/td_init.cpp
=> HTCONDOR-1228 misc-cleanup

docs/version-history/stable-release-series-90.rst, src/condor_tools/drain.cpp
=> HTCONDOR-1236 add -debug option to condor_drain

docs/version-history/development-release-series-91.rst
Version history for blahp reporting cpus allocated by slurp
=> HTCONDOR-1207 Docs for slurm cpu allocation reporting in blahp

src/condor_utils/test_sinful.cpp
=> HTCONDOR-1228 fix memory leak in test suite

src/condor_q.V6/queue.cpp
=> HTCONDOR-1233 condor_q leak

src/annex/CheckConnectivity.h, src/annex/CheckForStack.h, src/annex/CondorStatusReply.h, src/annex/CreateKeyPair.h, src/annex/CreateStack.h, src/annex/GetFunction.h, src/annex/GetInstances.h, src/annex/SetupReply.h, src/annex/StatusReply.h, src/annex/UploadFile.h, src/annex/WaitForStack.h
At GregT's request, remove superfluous private data members that we making  clang unhappy.
=> (HTCONDOR-1243)  Remove superfluous private data members.

src/condor_unit_tests/OTEST_StringList.cpp
=> HTCONDOR-1233 StringList test should not #include string_list.cpp

docs/version-history/development-release-series-91.rst, src/condor_starter.V6.1/os_proc.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1245
=> HTCONDOR-1245 ssh-to-container-job

docs/version-history/development-release-series-91.rst, src/condor_starter.V6.1/docker_proc.cpp, src/condor_starter.V6.1/os_proc.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1244
Note this doesn't require a version history note.
=> HTCONDOR-1244 enable-ssh-knob-disables-containers

src/condor_scripts/CheckOutputFormats.pm
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1246
=> HTCONDOR-1246 Robustify cmd_status_tests

src/condor_dagman/dag.cpp
=> HTCONDOR-1228 dagman leak at exit

src/condor_daemon_core.V6/self_draining_queue.cpp, src/condor_daemon_core.V6/self_draining_queue.h, src/condor_q.V6/queue.cpp
=> HTCONDOR-1233 schedd-leak

src/condor_submit.V6/factory_test.cpp, src/condor_sysapi/ncpus.cpp, src/condor_unit_tests/OTEST_Old_Classads.cpp, src/condor_unit_tests/async_freader_tests.cpp, src/gangliad/gangliad.cpp
=> HTCONDOR-1233 leak-cleanups

src/classad/classad_functional_tester.cpp, src/classad/collectionBase.cpp, src/classad/cxi.cpp, src/classad/indexfile.cpp, src/classad/literals.cpp, src/classad/sink.cpp, src/classad/util.cpp, src/classad/xmlLexer.cpp
=> HTCONDOR-1233 fix warnings size_t vs int in classad

src/condor_q.V6/queue.cpp
=> HTCONDOR-1233 fix-condor_q-leak

docs/classad-attributes/machine-classad-attributes.rst, docs/version-history/development-release-series-91.rst, src/condor_includes/condor_attributes.h, src/condor_startd.V6/ResAttributes.cpp, src/condor_sysapi/processor_flags.cpp, src/condor_sysapi/reconfig.cpp, src/condor_sysapi/sysapi.h, src/condor_sysapi/sysapi_externs.h
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1252
=> HTCONDOR-1252 microarch

src/condor_dagman/dag.cpp, src/condor_dagman/parse.cpp
=> HTCONDOR-1233 fix-dagman-leaks

CMakeLists.txt, build/cmake/CondorConfigure.cmake, externals/bundles/boost/1.68.0/CMakeLists.txt, src/condor_includes/condor_sys_linux.h, src/condor_kbdd/XInterface.unix.h, src/condor_startd.V6/startd_bench_job_mgr.cpp, src/condor_startd.V6/startd_bench_job_mgr.h, src/condor_tools/tool.cpp, src/condor_utils/checksum.cpp
=> HTCONDOR-1233 fix warnings

docs/version-history/stable-release-series-90.rst, src/condor_schedd.V6/schedd.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1261
=> HTCONDOR-1261 sched-uni-fd-leak

src/condor_schedd.V6/schedd.cpp, src/condor_utils/ntsysinfo.WINDOWS.cpp, src/condor_utils/ntsysinfo.WINDOWS.h
=> HTCONDOR-1233 fixes for windows ntsysinfo warnings

src/condor_tools/htcondor_cli/annex.py, src/condor_tools/htcondor_cli/annex_create.py
[HTCONDOR-1239](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1239)
=> HTCONDOR-1239: Cherry-pick back to 9.11.1

src/condor_starter.V6.1/io_proxy_handler.cpp, src/condor_status.V6/status.cpp
=> V9_12-HTCONDOR-1233-fix-leaks

.gitignore, src/condor_had/Utils.cpp, src/condor_includes/condor_crypt.h, src/condor_io/condor_crypt.cpp, src/condor_io/condor_crypt_3des.cpp, src/condor_io/condor_crypt_blowfish.cpp, src/condor_io/condor_secman.cpp, src/condor_tests/test_aes_file_transfer.py, src/condor_utils/DelegationInterface.cpp, src/condor_utils/condor_md.cpp
=> HTCONDOR-1168: remove deprecated openssl functions branch

docs/version-history/stable-release-series-90.rst, src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/OAuthCredmon.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1270
=> HTCONDOR-1270 Include scope and audience claims when refreshing OAuth tokens

src/condor_tests/CMakeLists.txt, src/condor_tests/test_condor_token_fetch_key.py
Regression test for `condor_token_fetch -key`.  As an internal-only change, this doesn't require documentation or a release note.
=> HTCONDOR-1027 test for condor_token_fetch -key

src/condor_status.V6/status.cpp, src/condor_tools/history.cpp, src/condor_who/who.cpp
=> HTCONDOR-1233 fix-tool-leaks

docs/admin-manual/configuration-macros.rst, docs/version-history/development-release-series-91.rst, src/condor_had/DownloadReplicaTransferer.cpp, src/condor_had/UploadReplicaTransferer.cpp, src/condor_utils/param_info.in
=> HTCONDOR-1234 change HAD_FIPS_MODE default to 1

docs/version-history/development-release-series-91.rst, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-1233 fix schedd spooling memory leak

docs/version-history/development-release-series-91.rst, src/condor_utils/submit_utils.cpp
-Added JOB and RETRY to list of words to ignore warning about if
unused during job submission time
=> HTCONDOR-1273: DAGMan writes warning for JOB macro

docs/admin-manual/configuration-macros.rst, docs/admin-manual/security.rst, docs/conf.py, docs/man-pages/index.rst, docs/version-history/development-release-series-91.rst, src/condor_collector.V6/collector_main.cpp, src/condor_io/condor_auth_ssl.cpp, src/condor_utils/param_info.in
Minor fixes to Trust On First Use code
=> HTCONDOR-501 TOFU fixups

docs/classad-attributes/job-classad-attributes.rst, docs/version-history/development-release-series-91.rst, src/condor_shadow.V6.1/baseshadow.cpp, src/condor_shadow.V6.1/baseshadow.h, src/condor_utils/condor_holdcodes.h, src/condor_utils/file_transfer.cpp
[Improve File Transfer Hold Info](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1134)
=> HTCONDOR-1134 improve filetransfer errors

docs/version-history/stable-release-series-90.rst, src/condor_gridmanager/proxymanager.cpp, src/condor_io/condor_auth_fs.cpp, src/condor_io/condor_auth_munge.cpp, src/condor_utils/my_username.cpp, src/condor_utils/my_username.h
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1229
=> HTCONDOR-1229 large-uids

docs/admin-manual/configuration-macros.rst, docs/admin-manual/setting-up-vm-docker-universes.rst, docs/version-history/development-release-series-91.rst, src/condor_utils/docker-api.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1282
=> HTCONDOR-1282 docker-shm-size-branch

src/condor_utils/param_info.in
Remove config knob for collector python plugin
=> HTCONDOR-1235 remove python collector plugin config knob

src/condor_sysapi/ncpus.cpp
This isn't a real problem, but quiets a ton of noise
=> HTCONDOR-1233 ubsan fix for ncpus

src/condor_starter.V6.1/CMakeLists.txt
=> HTCONDOR-1233 Allow exit_37 statically linker helper to compile with

src/condor_tests/test_xfer_hold_codes.py
getting resuts
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1281
=> HTCONDOR-1281-async-test-for-xfer-holds

src/condor_scripts/condor_remote_cluster
The URLs for future pre-release tarballs on the website will not include a
datestamp.
=> HTCONDOR-1280 Remove dates from tarball URLs for condor_remote_cluster

build/packaging/srpm/condor.spec
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1279
=> HTCONDOR-1279 Vault credmon depends on python3-cryptography

docs/admin-manual/configuration-macros.rst
=> HTCONDOR-1286 document-negotiator-num-threads

src/condor_dagman/dag.cpp, src/condor_dagman/dag.h, src/condor_dagman/dagman_commands.cpp, src/condor_dagman/dagman_main.cpp
-Added changes to set user defined done nodes via JOB line
in .dag file after the DAG adjusts to avoid ASSERT faliure
becuase the job is marked STATUS_DONE
=> HTCONDOR-1267: DAGMan JOB line with DONE assertion failure (Master)

docs/version-history/stable-release-series-90.rst, src/condor_dagman/dag.cpp, src/condor_dagman/dag.h, src/condor_dagman/dagman_commands.cpp, src/condor_dagman/dagman_main.cpp
=> V9 0 17 htcondor 1267 dag man job line with done assertion failure branch

build/docker/hpc-annex-pilot/Dockerfile, build/docker/hpc-annex-pilot/build.sh, build/docker/hpc-annex-pilot/install-pilot.sh, build/docker/hpc-annex-pilot/push.sh, src/condor_scripts/annex/path-facility.pilot, src/condor_scripts/annex/path-facility.sh, src/condor_tools/htcondor_cli/annex_create.py
Container universe support and random bugfixes for HPC Annex on the PATH Facility.
Since the PATh Facility runs all jobs in Singularity, this PR includes the definition of an image that has the necessary software to run the annex pilot.
Known bug:
- container universe jobs need to have the sif file used in `container_image` listed in  `transfer_input_files` to avoid a shadow exception due to not being able to find the image file
=> HTCONDOR-1265: HPC-Annex+PATh Facility container universe and bugfixes

docs/admin-manual/configuration-macros.rst, docs/admin-manual/directories.rst, docs/admin-manual/policy-configuration.rst
=> HTCONDOR-912 fix-doc-typos

docs/classad-attributes/machine-classad-attributes.rst, docs/version-history/development-release-series-91.rst, src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/singularity.h, src/condor_starter.V6.1/starter_v61_main.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1274
=> HTCONDOR-1274 don't advertise has_singularity when we don't have it

build/docker/hpc-annex-pilot/Dockerfile, build/docker/hpc-annex-pilot/build.sh, build/docker/hpc-annex-pilot/install-pilot.sh, build/docker/hpc-annex-pilot/push.sh, src/condor_scripts/annex/path-facility.multi-pilot, src/condor_scripts/annex/path-facility.pilot, src/condor_scripts/annex/path-facility.sh, src/condor_tools/htcondor_cli/annex_create.py
=> HTCONDOR-1265: Cherry-pick to 9.11.1

docs/admin-manual/configuration-macros.rst, src/condor_startd.V6/VolumeManager.cpp, src/condor_utils/param_info.in
thinpool
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1300
=> HTCONDOR-1300 public-ephemeral-scratch

docs/admin-manual/configuration-macros.rst, src/condor_startd.V6/VolumeManager.cpp, src/condor_utils/param_info.in
[https://opensciencegrid.atlassian.net/browse/HTCONDOR-1300](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1300)
=> HTCONDOR-1300: Backport to 9.12.0

CMakeLists.txt
=> HTCONDOR-1301 C++17

src/condor_utils/ClassAdLogReader.h, src/condor_utils/classad_log.h
=> HTCONDOR-1308 std-iterator removal

src/openstack_gahp/CMakeLists.txt
=> HTCONDOR-1309 stop-building-openstack

docs/man-pages/condor_transform_ads.rst, src/condor_tools/transform_ads.cpp, src/condor_utils/xform_utils.cpp, src/condor_utils/xform_utils.h
=> HTCONDOR-1312 apply JOB_TRANSFORM_* rules in condor_transform_ads

src/condor_sysapi/ncpus.cpp, src/condor_sysapi/reconfig.cpp, src/condor_sysapi/sysapi_externs.h
=> HTCONDOR-1307 remove dead code in sysapi

src/condor_schedd.V6/schedd.cpp, src/condor_unit_tests/OTEST_Env.cpp, src/condor_utils/compat_classad.cpp, src/condor_utils/cron_job_params.cpp, src/condor_utils/env.cpp, src/condor_utils/env.h, src/condor_utils/submit_utils.cpp
=> HTCONDOR-1311 Allow delim prefix when parsing v1 format environment

docs/version-history/lts-versions-10-0.rst
=> HTCONDOR-1277: Documentation

docs/version-history/stable-release-series-90.rst
[HTCONDOR-1297](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1297)
=> HTCONDOR-1297: Transplant version history to LTS version

src/condor_dagman/dagman_submit.cpp
=> HTCONDOR-1277 cherry pick

docs/man-pages/condor_submit.rst
and demote "log_xml = true" to "ADVANCED"
=> V10_HTCONDOR-1331-cleanup-submit-docs

src/condor_gridmanager/boinc-client.cpp, src/condor_gridmanager/boincresource.cpp, src/condor_gridmanager/condorjob.cpp, src/condor_gridmanager/ec2-gahp-client.cpp, src/condor_gridmanager/gahp-client.cpp, src/condor_gridmanager/generic-gahp-client.cpp, src/condor_gridmanager/infnbatchjob.cpp
2nd try for this PR, but we've now have one big commit with all of jfreys suggested fixes in.
=> HTCONDOR-1306 clang-tidy the gridmanager with jfrey's fixes all in one

docs/version-history/lts-versions-10-0.rst, src/arc_gahp/arcCommands.cpp
Accept new ARC CE response format
=> HTCONDOR-1327 arc server response

src/condor_io/condor_auth_kerberos.cpp, src/condor_io/condor_auth_munge.cpp, src/condor_io/condor_auth_ssl.cpp
Using decltype simplifies the function pointer typing.
=> HTCONDOR-1337 use decltype with dlopen()

src/condor_tests/CMakeLists.txt
tests)
When building (and testing) out of source, need to copy CheckOutputFormats.pm to the build tree
=> V10-HTCONDOR-1331-checkoutformats-out-of-source

src/condor_schedd.V6/schedd.cpp, src/condor_unit_tests/OTEST_Env.cpp, src/condor_utils/compat_classad.cpp, src/condor_utils/cron_job_params.cpp, src/condor_utils/env.cpp, src/condor_utils/env.h, src/condor_utils/submit_utils.cpp
=> cherry-pick of HTCONDOR-1235 and HTCONDOR-1311 Env changes from main

nmi_tools/glue/build/remote_pre.pl
=> HTCONDOR-1331 fix nmi build glue to put ISO date into version

docs/admin-manual/configuration-macros.rst, docs/admin-manual/introduction-to-configuration.rst, src/condor_examples/condor_config.annotated, src/condor_sysapi/reconfig.cpp, src/condor_utils/condor_config.cpp, src/condor_utils/param_info.in
=> HTCONDOR-1307 cherry-pick of fbf808f2212a45c2 and c0c6fa5429ca90d

src/condor_utils/param_info.in
=> HTCONDOR-1234 change default for SLOTS_CONNECTED_TO_* knobs to be 0 

docs/version-history/lts-versions-10-0.rst, src/condor_daemon_core.V6/daemon_command.cpp, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_includes/KeyCache.h, src/condor_includes/condor_secman.h, src/condor_includes/sock.h, src/condor_io/condor_secman.cpp, src/condor_io/safe_sock.cpp, src/condor_io/sock.cpp, src/condor_negotiator.V6/matchmaker.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_startd.V6/claim.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_utils/KeyCache.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1342
=> HTCONDOR-1342 improve security session cache

docs/version-history/lts-versions-10-0.rst, src/condor_negotiator.V6/matchmaker.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1349
=> HTCONDOR-1349 negotiator admin attrs

src/arc_gahp/io_loop_pthread.cpp, src/condor_startd.V6/VolumeManager.cpp, src/condor_submit.V6/submit.cpp
=> HTCONDOR-1331 fix two small warnings

docs/man-pages/condor_transform_ads.rst, src/condor_tools/transform_ads.cpp, src/condor_utils/xform_utils.cpp, src/condor_utils/xform_utils.h
=> HTCONDOR-1312 cherry-pick 3a561310a6d7115b to 10.0

src/condor_utils/ClassAdLogReader.h, src/condor_utils/classad_log.h
=> HTCONDOR-1308 cherry-pick e05cd867f507

docs/version-history/stable-release-series-90.rst, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/job_info_communicator.h, src/condor_starter.V6.1/os_proc.cpp, src/condor_starter.V6.1/starter.cpp, src/condor_starter.V6.1/starter.h
<[Fix job manifest feature](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1350)>
=> HTCONDOR-1350 fix job manifest

src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/singularity.h
appropriately
This removes ugly warnings at apptainer startup time
=> HTCONDOR-1137 If singularity is really apptainer, set env vars

docs/admin-manual/directories.rst, docs/admin-manual/introduction-to-configuration.rst, docs/admin-manual/user-priorities-negotiation.rst, docs/man-pages/classad_eval.rst, docs/man-pages/condor_gpu_discovery.rst, docs/man-pages/condor_now.rst, docs/man-pages/condor_submit.rst, docs/users-manual/automatic-job-management.rst, docs/users-manual/docker-universe-applications.rst, docs/users-manual/file-transfer.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1352
=> HTCONDOR-1352 spell check manual

src/condor_starter.V6.1/starter.cpp
=> HTCONDOR-1355 fix merge conflict

src/condor_tests/CMakeLists.txt, src/condor_tests/test_condor_history_reads_epochs.py, src/condor_tools/history.cpp
=> htcondor 1284 job epoch ads reading branch

docs/version-history/lts-versions-10-0.rst, src/condor_utils/directory.cpp
=> HTCONDOR-1354 nofollow-symlink-scratch-dir

docs/version-history/lts-versions-10-0.rst, src/condor_utils/hibernator.linux.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1357
=> HTCONDOR-1357 hibernate disk

src/classad/classad.cpp, src/classad/classad/classad.h
=> HTCONDOR-1337 classad-ctor

docs/man-pages/condor_q.rst, docs/version-history/feature-versions-10-x.rst, src/condor_q.V6/queue.cpp
=> HTCONDOR-1064 condor q runtime changes branch

docs/man-pages/condor_submit.rst
Remove doc that hasn't been true for a decade.
=> HTCONDOR-1337-doc-cleanup

build/docker/services/base/container-install-htcondor.sh, build/docker/services/build-images
This PR changes the scripts for building the htcondor/{base,cm,execute,mini,submit} images to understand the new 9.0/9.x versioning schema, and add 'lts' and 'feature' tags.
I check the Git tags to figure out which version is the latest in each release series (and which series is the latest) and error out if there's a version mismatch between the RPM/DEB repos and the Git tags.
In order to make the code simpler, I dropped pre-9.0 code (8.9 is out of support and we never had 8.8 images).
Other included changes:
- a `--no-cache` argument to skip using the build cache during the docker build
- a `--one-tag` argument to only create the most specific tags for builds (e.g. "9.11.0-el7" but not "9.x-el7")
- daily builds are enabled for Ubuntu
- daily builds put the HTCondor build date, not the …
=> HTCONDOR-829: Docker tags for 9.x

src/condor_scripts/condor_submit_as_dag
… through condor_submit_as_dag.  Also, correct the usage message.
=> (HTCONDOR-1373)  Don't propogate late materialization commands

docs/version-history/lts-versions-10-0.rst, src/condor_schedd.V6/qmgmt.cpp, src/condor_tests/CMakeLists.txt, src/condor_tests/job_xform_factory.run
=> HTCONDOR-1369 apply submit transforms to late mat factories and jobs

docs/version-history/lts-versions-10-0.rst, src/condor_tools/CMakeLists.txt, src/condor_tools/tool.cpp
The Tool should targets' remote admin capability.
=> HTCONDOR-1371 the-tool-admin-capability

docs/version-history/lts-versions-10-0.rst, src/condor_utils/AWSv4-utils.cpp
Replace stupid nonsense with `ends_with()`.
=> (HTCONDOR-1378)  can't pre-sign URLs with short hostnames

build/docker/services/base/container-install-htcondor.sh, build/docker/services/build-images, build/docker/services/execute/container-install-execute.sh, build/docker/services/mini/container-install-minicondor.sh
- Switch from CentOS 8 to Alma Linux 8
- LTS version do not have an update repository
=> HTCONDOR-1376: Update building HTCSS Docker images

docs/version-history/lts-versions-10-0.rst, src/condor_tools/preen.cpp
-Changed PREEN_COREFILE_MAX_SIZE from int to long long to allow
specification of file size maximums greater than 2GB
-Modified condor_preen to check large core files for if they
belong to certain daemons (Schedd, Negotiator, Collector) it
checks all core files from newest to oldest for the total space
to be under a max sum.
-Added hidden knobs for these max sums:
-PREEN_SCHEDD_COREFILES_MAX_SUM
-PREEN_NEGOTIATOR_COREFILES_MAX_SUM
-PREEN_COLLECTOR_COREFILES_MAX_SUM
-Fixed spelling error for core file stale age knob. …
=> HTCONDOR-1377: condor_preen deleting important core files

src/condor_io/condor_secman.cpp, src/condor_negotiator.V6/GroupEntry.h, src/condor_utils/file_transfer.h
=> V10_1-HTCONDOR-1337-more-warning-fixes

docs/version-history/lts-versions-10-0.rst, src/condor_io/condor_secman.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1372
=> HTCONDOR-1372 session reuse crash

src/condor_gridmanager/basejob.cpp, src/condor_io/ca_utils.cpp, src/condor_starter.V6.1/jic_local.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_sysapi/processor_flags.cpp, src/condor_utils/condor_config.cpp, src/condor_utils/condor_event.cpp, src/condor_utils/submit_utils.cpp, src/condor_utils/write_user_log.cpp, src/condor_utils/xform_utils.h
=> HTCONDOR-1337 warning-fixes-arm64

src/condor_daemon_core.V6/daemon_core.cpp, src/condor_tools/tool.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1371
=> HTCONDOR-1371 Advertise all command ints for RemoteAdminCapability

src/condor_tests/cmd_drain_scavenging.run
=> HTCONDOR-1384 Fix race condition in cmd_drain_scavenging test

src/condor_job_router/NewClassAdJobLogConsumer.cpp, src/condor_tools/transform_ads.cpp, src/condor_utils/compat_classad_util.cpp, src/condor_utils/compat_classad_util.h, src/condor_utils/config.cpp
=> HTCONDOR-1337 Remove dead arg from ParseClassAdRvalExpr

src/condor_collector.V6/collector.cpp
That is, stop protecting collector ads.
=> HTCONDOR-1337 protect-collector-ads

src/condor_collector.V6/collector.cpp, src/condor_negotiator.V6/matchmaker.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1371
=> HTCONDOR-1371 Limit sending of private attributes to the negotiator

src/python-bindings/schedd.cpp
=> V10_0-HTCONDOR-1331-python-bindings-null-term

docs/getting-htcondor/from-our-repositories.rst
Replace "we only have x86-64 repos" now that we have arm and ppc.
=> V10_0-HTCONDOR-1331-document-non-x86-repos

src/classad/classad/classad.h, src/condor_collector.V6/view_server.cpp, src/condor_gridmanager/basejob.cpp, src/condor_includes/condor_accountant.h, src/condor_includes/condor_qmgr.h, src/condor_negotiator.V6/Accountant.cpp, src/condor_negotiator.V6/GroupEntry.h, src/condor_negotiator.V6/matchmaker.cpp, src/condor_negotiator.V6/matchmaker.h, src/condor_q.V6/jobmatch.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/qmgmt_common.cpp, src/condor_schedd.V6/qmgmt_receivers.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/schedd_negotiate.cpp, src/condor_shadow.V6.1/baseshadow.cpp, src/condor_shadow.V6.1/baseshadow.h, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_shadow.V6.1/shadow.cpp, src/condor_tools/give_interactive.cpp, src/condor_tools/user_prio.cpp, src/condor_unit_tests/OTEST_Old_Classads.cpp, src/condor_unit_tests/unit_test_utils.cpp, src/condor_unit_tests/unit_test_utils.h, src/condor_utils/condor_event.cpp, src/condor_utils/condor_event.h, src/condor_utils/history_utils.h, src/condor_utils/totals.cpp
Too timid now to rename LookupFloat to LookupDouble, but at least get the type right.  We no longer coerce doubles down to float as they go in or out of classads.
=> V10_1-HTCONDOR-1337-no-more-floats

docs/version-history/lts-versions-10-0.rst, src/condor_starter.V6.1/singularity.cpp
=> V10 0 htcondor 1386 apptainer env

src/condor_utils/dagman_utils.cpp, src/condor_utils/dagman_utils.h, src/condor_utils/env.cpp, src/condor_utils/env.h, src/condor_utils/submit_utils.cpp
=> V10_1-HTCONDOR-1337-env-with-templates

src/condor_includes/condor_attributes.h, src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/ResAttributes.h, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResState.cpp, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h, src/condor_startd.V6/claim.cpp, src/condor_startd.V6/cod_mgr.cpp, src/condor_startd.V6/command.cpp, src/condor_startd.V6/slot_builder.cpp, src/condor_startd.V6/slot_builder.h, src/condor_startd.V6/startd_cron_job_mgr.cpp
=> HTCONDOR-1388 add SLOT_TYPE_<N>_BACKFILL slots Phase 1

docs/version-history/upgrading-from-9-0-to-10-0-versions.rst
=> HTCONDOR-953 upgrading from 9.0 to 10.0 note

src/condor_startd.V6/startd_cron_job_mgr.cpp
=> HTCONDOR-1337 quieter logging of conditional Startd cron

src/condor_utils/condor_event.cpp
<[HTCONDOR-1263 Event Log parse off-by-one bug](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1263)>
=> HTCONDOR-1263 event log parse bug

docs/version-history/lts-versions-10-0.rst, src/condor_startd.V6/ResAttributes.cpp
=> HTCONDOR-1397 Take Offline GPUs out of AvailableGPUs list

src/condor_includes/condor_attributes.h, src/condor_utils/classad_helpers.cpp, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
=> V10_1-HTCONDOR-1396-remove-job-root-dir

docs/classad-attributes/job-classad-attributes.rst, docs/version-history/feature-versions-10-x.rst, src/condor_gridmanager/condorjob.cpp, src/condor_tools/give_interactive.cpp, src/condor_utils/classad_helpers.cpp, src/condor_utils/submit_utils.cpp
=> V10_1-HTCONDOR-1393-CompletionDate-undefined

src/condor_utils/submit_utils.cpp
=> V10_1-HTCONDOR-1337-dead-vars-removal

docs/version-history/lts-versions-10-0.rst, src/condor_io/condor_auth_passwd.cpp, src/condor_io/condor_secman.cpp, src/condor_utils/param_info.in
=> HTCONDOR-1381 default TRUST_DOMAIN to UID_DOMAIN

src/condor_io/condor_secman.cpp
=> HTCONDOR-1337 Fix init value of SecMan::m_cached_return_value

docs/conf.py, docs/extensions/index.py
=> HTCONDOR-1398: Fix man command manual pages bug

docs/classad-attributes/scheduler-classad-attributes.rst, src/condor_includes/condor_attributes.h, src/condor_schedd.V6/schedd.cpp
-Added new schedd attr EffectiveFlockList
-Made so schedd sets attr to all flock collectors less than
flock level and advertise to local pool collector
=> HTCONDOR-1389: Advertise schedd flock list to collector

docs/version-history/lts-versions-10-0.rst, nmi_tools/glue/build/set-tarball-rpath
=> HTCONDOR-1405: Set RPATH in tarball executables

docs/version-history/lts-versions-10-0.rst, src/condor_starter.V6.1/os_proc.cpp
=> V10 0 htcondor 1406 ssh to singularity target dir

docs/version-history/feature-versions-10-x.rst, src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/starter.cpp, src/condor_starter.V6.1/starter_v61_main.cpp, src/condor_utils/submit_utils.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1412
=> HTCONDOR-1412-docker-images-with-singularity

docs/version-history/lts-versions-10-0.rst
=> HTCONDOR-1312 version history

docs/man-pages/condor_userprio.rst, docs/version-history/feature-versions-10-x.rst, src/condor_includes/condor_accountant.h, src/condor_includes/condor_commands.h, src/condor_negotiator.V6/Accountant.cpp, src/condor_negotiator.V6/matchmaker.cpp, src/condor_negotiator.V6/matchmaker.h, src/condor_schedd.V6/qmgmt.cpp, src/condor_tools/user_prio.cpp
This is a try-to-guarantee minimum number of slots that a given user should get
=> V10_1-HTCONDOR-557-negotiator-floor

docs/version-history/feature-versions-10-x.rst, src/condor_starter.V6.1/singularity.cpp
<[Mount OpenCL drivers from host into Singularity job containers for slots allocated GPUs](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1410)>
=> HTCONDOR-1410 opencl support in singularity in container

docs/admin-manual/configuration-macros.rst
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1240
=> HTCONDOR-1240-reserved-disk-docs

docs/version-history/feature-versions-10-x.rst, src/condor_utils/docker-api.cpp
=> HTCONDOR-1421-docker-hates-big-uids

src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/ResAttributes.h, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h, src/condor_startd.V6/startd_cron_job_mgr.cpp
=> HTCONDOR-1388 Assign backfill resource conflicts to slots

src/condor_negotiator.V6/matchmaker.cpp, src/condor_negotiator.V6/matchmaker.h
=> HTCONDOR-1423-fix-negotiator-floor

src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/ResAttributes.h
=> HTCONDOR-1388 remove code that should not have been in previous commit

src/condor_tools/user_prio.cpp, src/gpu/simulated_device_enumeration.cpp
=> HTCONDOR-1337 fix minor warnings

docs/version-history/lts-versions-10-0.rst, src/condor_filetransfer_plugins/multifile_curl_plugin.cpp, src/condor_tests/test_curl_plugin.py, src/condor_utils/file_transfer.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1426
=> HTCONDOR-1426-fix-curl-segfault

src/condor_starter.V6.1/singularity.cpp
Config knob to control if Singularity should use PID namespaces or not.  Note: documentation not included here, since another incoming ticket will enhance this functionality.  See JIRA ticket:
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1408
=> HTCONDOR-1408 singularity pidnamespace knob

src/classad_analysis/analysis.cpp, src/classad_analysis/interval.cpp, src/classad_analysis/interval.h
=> HTCONDOR-1337 vectorize classad_analysis

docs/users-manual/dagman-workflows.rst
Link to ticket: [HTCONDOR-1439](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1439)
=> HTCONDOR-1439: Fix DAGMan broken links

docs/version-history/feature-versions-10-x.rst, src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/LocalCredmon.py, src/condor_credd/condor_credmon_oauth/examples/config/condor/40-oauth-credmon.conf
Cherry-picked from #947 (already merged) to 10.1.3
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1402
=> HTCONDOR-1402 Add group authorizations to local issuer credmon

src/condor_tests/test_xfer_hold_codes.py
For now just comment out the offending test until we can come up with a better way to test this.  I tried mkdir'ing a chmod 000 directory, but the test failed when trying to clean up.
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1325
=> HTCONDOR-1325-branch

src/condor_collector.V6/ce-audit-plugin.cpp, src/condor_collector.V6/collector_stats.h, src/condor_tools/preen.cpp, src/condor_tools/testwritelog.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1337
=> HTCONDOR-1337-dead-code-elimination

docs/admin-manual/singularity-support.rst, docs/version-history/feature-versions-10-x.rst, src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/starter.cpp, src/condor_utils/param_info.in
=> HTCONDOR-1436 Add support for SINGULARITY_VERBOSITY knob, defaults to -s

build/cmake/CondorPackageConfig.cmake, nmi_tools/glue/SubmitInfo.pm, nmi_tools/glue/build/build.win.bat, nmi_tools/glue/build/remote_post.pl, nmi_tools/glue/build/remote_pre.pl, nmi_tools/glue/test/remote_declare.pl, nmi_tools/glue/test/remote_post.pl, nmi_tools/nmi-build-platforms
=> HTCONDOR-1441 nmi_tools changes for Morgridge VM Windows build machine

docs/version-history/lts-versions-10-0.rst, src/condor_filetransfer_plugins/multifile_curl_plugin.cpp
=> HTCONDOR-1447 multifile curl plugin scitoken parsing branch

src/condor_utils/log_rotate.cpp
instead of allocating memory to find all the files in a directory sort them, and project out the lowest sorted one
=> HTCONDOR-1337-log-rotate

docs/admin-manual/configuration-macros.rst, docs/version-history/lts-versions-10-0.rst, src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/VaultCredmon.py, src/condor_credd/condor_credmon_oauth/examples/config/condor/40-vault-credmon.conf
Copy of #953 with commits cherry-picked to LTS branch and version history added. Obsoletes #953.
The commits from @DrDaveD are already code-reviewed and approved by @jasoncpatton. Assuming no build breakage (which this shouldn't, since it doesn't touch core functionality), this just needs a review and merge for the version history.
Links to tickets:
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1017
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1179
=> HTCONDOR-1179 HTCONDOR-1017 Vault improvements

src/condor_shadow.V6.1/pseudo_ops.cpp
=> HTCONDOR-1337-shadow-memory-leak

docs/version-history/feature-versions-10-x.rst
=> HTCONDOR-1389: version history

build/nmi-build/x86_64_Ubuntu18/Dockerfile
=> HTCONDOR-1451-ubuntu-18-gcc-8

docs/version-history/lts-versions-10-0.rst, src/condor_gridmanager/arcjob.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1448
=> HTCONDOR-1448 arc exit info time

build/cmake/CondorConfigure.cmake
Because it generates way too much noise now.
=> HTCONDOR-1337-conversion-warning-placeholder

src/condor_dagman/dag.cpp, src/condor_dagman/dagman_submit.cpp, src/condor_gridmanager/basejob.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_shadow.V6.1/shadow.cpp, src/condor_tests/lib_eventlog_base.cpp, src/condor_tests/x_write_joblog.cpp, src/condor_tests/x_write_joblog_events.cpp, src/condor_userlog/condor_check_userlogs.cpp, src/condor_utils/condor_event.cpp, src/condor_utils/condor_event.h, src/condor_utils/test_libcondorapi.cpp, src/condor_utils/test_log_writer.cpp, src/condor_utils/userlog_to_classads.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1337
=> HTCONDOR-1337 userlog

src/condor_schedd.V6/dedicated_scheduler.cpp, src/condor_schedd.V6/dedicated_scheduler.h, src/condor_userlog/userlog.cpp, src/condor_utils/historyFileFinder.cpp
=> HTCONDOR-1337-std-sort

src/condor_schedd.V6/prio_rec.h, src/condor_schedd.V6/qmgmt.cpp
because sorting by cluster/proc will also sort by qdate
=> HTCONDOR-1337-no-sort-by-qdate

docs/version-history/lts-versions-10-0.rst, externals/bundles/openssl/packaged/CMakeLists.txt, src/condor_scripts/macosx_rewrite_libs
=> HTCONDOR-1458 macos dist libressl

build/cmake/CondorConfigure.cmake, build/packaging/rpm/condor.spec, nmi_tools/glue/build/install_cmake, nmi_tools/glue/build/remote_pre.pl, src/condor_tests/job_kvm_basic.run, src/condor_tests/job_ligo_x86-64-chkpttst.pl
=> HTCONDOR-1337  use https

docs/version-history/lts-versions-10-0.rst, src/condor_utils/make_printmask.cpp
=> HTCONDOR-1464 Fix for print-format segfault on FIELDSUFFIX

src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/singularity.h
=> HTCONDOR-1454 Apptainer-bind

docs/version-history/lts-versions-10-0.rst, src/condor_starter.V6.1/cgroup_limits.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1466
=> HTCONDOR-1466-no-memsw-on-debian

docs/version-history/lts-versions-10-0.rst, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-1472-condor-rm-f

docs/version-history/lts-versions-10-0.rst, msconfig/WiX/xml/win.xsl.in, msconfig/do_wix.bat
=> HTCONDOR-1474 use localized Users group in Windows installer

src/condor_utils/param_info.in
https://opensciencegrid.atlassian.net/browse/HTCONDOR-1476
=> HTCONDOR-1476-document-negotiator-num-threads

docs/version-history/feature-versions-10-x.rst, src/condor_shadow.V6.1/NTreceivers.cpp, src/condor_starter.V6.1/NTsenders.cpp, src/condor_starter.V6.1/NTsenders.h, src/condor_starter.V6.1/jic_shadow.cpp
=> HTCONDOR-1360 syscall-error-handling

src/condor_tests/test_dagman_futile_nodes.py
[HTCONDOR-1467](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1467)
=> HTCONDOR-1467: Imporve DAGMan futile nodes test

build/cmake/CondorConfigure.cmake
[HTCONDOR-1479](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1479)
=> HTCONDOR-1479-python-312-cmake

docs/man-pages/condor_submit.rst, docs/version-history/feature-versions-10-x.rst, src/condor_includes/condor_attributes.h, src/condor_utils/docker-api.cpp, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
[HTCONDOR-1482](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1482)
=> HTCONDOR-1482-docker-pull

src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/scheduler.h
=> HTCONDOR-1337-no-n-squared

build/cmake/CondorConfigure.cmake
We need this all the time, but somehow don't print it out
=> HTCONDOR-1337-print-cmake-version

build/packaging/rpm/condor.spec, docs/version-history/lts-versions-10-0.rst, nmi_tools/glue/build/make-tarball-from-rpms
=> HTCONDOR-1332: Add condor-stash-plugin to HTCondor build

docs/version-history/feature-versions-10-x.rst, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_schedd.V6/schedd_main.cpp, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_utils/CMakeLists.txt, src/condor_utils/proc_family_direct.h, src/condor_utils/proc_family_direct_cgroup_v2.cpp, src/condor_utils/proc_family_direct_cgroup_v2.h, src/condor_utils/proc_family_interface.cpp, src/condor_utils/proc_family_interface.h, src/condor_utils/proc_family_proxy.cpp, src/condor_utils/proc_family_proxy.h
[HTCONDOR-1457](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1457)
=> HTCONDOR-1457-cgroup-v2

docs/admin-manual/setting-up-special-environments.rst, docs/users-manual/file-transfer.rst, nmi_tools/glue/build/make-tarball-from-rpms, nmi_tools/glue/build/set-tarball-rpath
=> HTCONDOR-1332: Docs and fixup tarballs

src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h
=> HTCONDOR-1491-remove-qsort

build/nmi-build/setup.sh, build/packaging/debian/control.in, build/packaging/debian/rules.in, nmi_tools/nmi-build-platforms
For various reasons, we need to build for both Python 2 and Python 3 on Ubuntu 18 (bionic beaver).
This also fixes python3 dependencies that caused test failures on the feature branch.
=> HTCONDOR-1333: Update Debian build files

docs/version-history/lts-versions-10-0.rst
=> HTCONDOR-1492 version history changes branch

src/condor_tests/test_xfer_stats_overflow_regression.py
Change test to fake transferring large files rather than creating files of large size to test job ad attribute overflowing. also, just some clean up/better logic.
=> HTCONDOR-1495: Improve xfer stats overflow test

src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-1389: Fix segfaulting due to NULL pointer for collector address

src/condor_utils/killfamily.cpp
=> HTCONDOR-1491-vectorize

docs/version-history/feature-versions-10-x.rst, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_utils/killfamily.cpp
=> HTCONDOR-1500-rm-cgroup

src/condor_tools/history.cpp
[HTCONDOR-1497](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1497)
=> HTCONDOR-1497: Refactor condor_history for different ads

docs/version-history/feature-versions-10-x.rst, src/condor_utils/condor_scitokens.cpp
=> HTCONDOR-1498 accept EGI CheckIn tokens

src/classad/CMakeLists.txt, src/classad/classad.cpp, src/classad/classad/classad.h, src/classad/classad/exprTree.h, src/classad/classad/value.h, src/classad/exprTree.cpp, src/classad/fnCall.cpp, src/classad/value.cpp, src/condor_utils/classad_oldnew.cpp
and modifying EvaluateExpr and EvaluateAttr to convert results to self-contained by default. This changes the classad ABI, so the SOVERSION is updated to 16
=> HTCONDOR-1484 fix for eval crash by adding to_delete ptrs to EvalState

src/condor_io/condor_auth_ssl.cpp
Add missing line for formatting the environment name for generic claims.
=> HTCONDOR-1498 egi-tokens-bugfix

src/classad/CMakeLists.txt
to help with building fuzzer without building all of HTCondor
=> HTCONDOR-1491-standalone-classad-cmake

src/condor_tools/history.cpp
=> HTCONDOR-1506: fix condor history matching job id logic

src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_tools/history.cpp, src/condor_utils/historyFileFinder.cpp, src/condor_utils/historyFileFinder.h
=> HTCONDOR-1504: Modernize history file finder

docs/version-history/lts-versions-10-0.rst, src/condor_tests/CMakeLists.txt, src/condor_tests/test_ft_plugin_stuff.py, src/condor_utils/file_transfer.cpp, src/condor_utils/submit_utils.cpp
=> (HTCONDOR-1501)  Properly report missing file-transfer plug-ins.

src/condor_starter.V6.1/vanilla_proc.cpp
=> HTCONDOR-1491-missing-include

docs/version-history/feature-versions-10-x.rst, src/condor_tests/test_condor_history_reads_epochs.py
=> HTCONDOR-1506: version history & regression test

build/nmi-build/setup.sh, build/packaging/debian/htcondor.postinst, docs/getting-htcondor/from-our-repositories.rst, docs/getting-htcondor/index.rst, docs/version-history/lts-versions-10-0.rst
=> HTCondor-1304: Ubuntu 22.04 support

src/classad/attrrefs.cpp, src/classad/classad.cpp, src/classad/fnCall.cpp, src/classad/value.cpp, src/classad_analysis/analysis.cpp, src/condor_collector.V6/collector.cpp, src/condor_collector.V6/offline_plugin.cpp, src/condor_negotiator.V6/matchmaker.cpp, src/condor_q.V6/jobmatch.cpp, src/condor_schedd.V6/dedicated_scheduler.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_shadow.V6.1/baseshadow.cpp, src/condor_startd.V6/Resource.cpp, src/condor_starter.V6.1/os_proc.cpp, src/condor_starter.V6.1/starter.cpp, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_status.V6/status.cpp, src/condor_tools/give_interactive.cpp, src/condor_unit_tests/OTEST_Old_Classads.cpp, src/condor_utils/ad_printmask.cpp, src/condor_utils/compat_classad_util.cpp, src/condor_utils/compat_classad_util.h, src/condor_utils/config.cpp, src/condor_utils/expr_analyze.cpp, src/condor_utils/file_transfer.cpp, src/condor_utils/test_compat_classad.cpp, src/condor_utils/totals.cpp, src/condor_utils/write_user_log.cpp
=> HTCONDOR-1484 Add value type mask to EvalExprTree and fixup callers

docs/version-history/feature-versions-10-x.rst, src/condor_utils/file_transfer_stats.cpp
Well, _hopefully_ less-confusing.
=> (HTCONDOR-1473)  Less-confusing more-informative error when plug-in stalls.

src/classad/attrrefs.cpp, src/classad/classad/exprTree.h, src/classad/fuzzer.cpp
=> HTCONDOR-1509-classad-recursion

src/condor_startd.V6/ResAttributes.h, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h, src/condor_startd.V6/StartdHookMgr.cpp, src/condor_startd.V6/claim.h, src/condor_startd.V6/command.cpp
=> HTCONDOR-1510 change most floats to doubles in startd

src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h, src/condor_startd.V6/startd_main.cpp
=> HTCONDOR-1510 cleanup some obscure dprintfs

src/classad/operators.cpp
=> HTCONDOR-1484-no-idiv-fpe

nmi_tools/glue/test/remote_pre.pl, src/condor_tests/test_allowed_execute_duration.py, src/condor_tests/test_checkpoint_destination.py, src/condor_tests/test_curl_plugin.py, src/condor_tests/test_ft_plugin_stuff.py, src/condor_tests/test_htcondor_955.py, src/condor_tests/test_multifile_curl_plugin_timeout.py, src/condor_tests/test_plugin_timeout.py, src/condor_tests/test_xfer_hold_codes.py, src/condor_tests/test_xfer_stats_overflow_regression.py
=> HTCONDOR-1491 disable transfer plugins by default in the nmi test glue

src/classad/fnCall.cpp
=> HTCONDOR-1509-join-recursion

src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h
=> HTCONDOR-1510 minimize use of resources[i] in ResMgr class

src/condor_starter.V6.1/vanilla_proc.cpp
[HTCONDOR-1511](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1511)
Cgroup v2 code will check if config'd cgroup is writeable, and use it if it thinks it is, instead of only when root.
=> HTCONDOR-1511-writeable-cgroups

src/condor_startd.V6/ResMgr.cpp
=> HTCONDOR-1510 cleanup exit path of findRipForNewCOD in startd

docs/admin-manual/configuration-macros.rst, docs/admin-manual/setting-up-special-environments.rst, docs/version-history/feature-versions-10-x.rst, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_utils/param_info.in
[HTCONDOR-1512](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1512)
=> HTCONDOR-1512-remove-ignore-leaf-oom

src/condor_unit_tests/OTEST_UserPolicy.cpp, src/condor_utils/condor_crontab.cpp, src/condor_utils/condor_crontab.h
=> HTCONDOR-1491-crontab-vector

docs/admin-manual/user-priorities-negotiation.rst, docs/man-pages/condor_userprio.rst
=> HTCONDOR-1513-better-ceiling-docs

src/condor_schedd.V6/dedicated_scheduler.cpp, src/condor_schedd.V6/dedicated_scheduler.h
=> HTCONDOR-1491-vectorize-ded-sched

docs/version-history/lts-versions-10-0.rst
=> HTCONDOR-1475 Docs for blahp files missing on Debian/Ubuntu

docs/admin-manual/security.rst
=> HTCONDOR-1463 plugin docs

docs/admin-manual/user-priorities-negotiation.rst, docs/man-pages/condor_userprio.rst
=> HTCONDOR-1517-better-floor-docs

src/condor_utils/classadHistory.cpp
=> HTCONDOR-1491-fix-warning

src/condor_startd.V6/backfill_mgr.cpp, src/condor_startd.V6/backfill_mgr.h, src/condor_startd.V6/boinc_mgr.cpp, src/condor_startd.V6/boinc_mgr.h
=> HTCONDOR-1491 vectorize-backfill

nmi_tools/condor_nmi_submit, nmi_tools/glue/build/build_uw_rpm.sh
=> HTCONDOR-1489: Adjust BaTLab memory requests per platform

src/condor_tests/test_multifile_curl_plugin_timeout.py
=> HTCONDOR-1523: add test timing leeway

src/condor_schedd.V6/qmgmt.cpp, src/condor_utils/compat_classad_util.cpp, src/condor_utils/compat_classad_util.h
=> HTCONDOR-1338 Change Schedd to do Env conversion before $$ expansion

src/condor_schedd.V6/dedicated_scheduler.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/scheduler.h
=> HTCONDOR-1491-vectorize-schedd

src/condor_tests/job_ad_epoch_recording.run, src/condor_tools/history.cpp, src/condor_utils/compat_classad.cpp, src/condor_utils/compat_classad.h, src/condor_utils/job_ad_instance_recording.cpp
=> HTCONDOR-1521: History banner Ad Type base logic plumbing

docs/version-history/lts-versions-10-0.rst, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/VolumeManager.cpp
[HTCONDOR-1524](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1524)
[HTCONDOR-1524]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-1524-thinpool-crash

src/condor_collector.V6/view_server.cpp, src/condor_collector.V6/view_server.h, src/condor_tools/give_interactive.cpp, src/condor_utils/condor_config.cpp
=> HTCONDOR-1491 vectorize misc classes

src/condor_gridmanager/baseresource.cpp, src/condor_gridmanager/condorjob.cpp, src/condor_gridmanager/condorresource.cpp, src/condor_gridmanager/condorresource.h, src/condor_gridmanager/gahp-client.cpp, src/condor_gridmanager/gahp-client.h, src/condor_gridmanager/generic-gahp-client.cpp, src/condor_gridmanager/infnbatchresource.cpp, src/condor_startd.V6/ResAttributes.cpp, src/condor_unit_tests/CMakeLists.txt, src/condor_unit_tests/FTEST_string_vector.cpp, src/condor_unit_tests/OTEST_StringList.cpp, src/condor_unit_tests/unit_test_utils.cpp, src/condor_unit_tests/unit_tests.cpp, src/condor_utils/condor_query.cpp, src/condor_utils/stl_string_utils.cpp, src/condor_utils/stl_string_utils.h, src/condor_utils/string_list.cpp, src/condor_utils/string_list.h, src/condor_utils/xform_utils.cpp
=> HTCONDOR-1491 stringlist-alternative

docs/getting-htcondor/from-our-repositories.rst
=> HTCONDOR-1424: Update repository links with proper version

src/condor_tools/history.cpp, src/condor_utils/history_queue.cpp, src/condor_utils/history_queue.h, src/condor_utils/param_info.in
-Added plumbing for condor_history to remote query from
different record sources
-Implemented remote querying of epoch files
-Fixed bug where doing a remote condor history query with
a constraint would cause the tool to crash
=> HTCONDOR-1499: condor_history remote query epochs

docs/version-history/feature-versions-10-x.rst, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-1529-missing-memory.peak

src/condor_procapi/procapi.h
=> HTCONDOR-1491-remove-dead-win-code

docs/version-history/feature-versions-10-x.rst, src/condor_io/condor_auth_ssl.cpp
=> HTCONDOR-1516 scitokens-plugin-envvars

docs/version-history/feature-versions-10-x.rst, src/condor_scripts/linux_kernel_tuning
[HTCONDOR-1528](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1528)
[HTCONDOR-1528]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-1528-cgroup-tuning-script

src/condor_io/condor_auth_ssl.cpp
Fix broken build from windows-only change
=> HTCONDOR-1455 tofu-fixes

src/condor_gridmanager/condorjob.cpp, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/startd_main.cpp, src/rvgahp/rvgahp_server.c
My builds now complete without warnings.  Yay!
=> HTCONDOR-1491  Fix warnings.

build/packaging/debian/htcondor.postinst
It is possible that the condor_master will create it later with proper permissions.
=> HTCONDOR-1537: Only chmod local dir when it already exists

src/condor_examples/condor_config.generic.debian.patch
This PR updates the Debian patch that is applied to the example `condor_config`, which is installed by the HTCondor deb as the actual `/etc/condor/condor_config`.
Debian and Ubuntu systems do not have the `/etc/ssl/certs/localhost.crt` file, but many have `/etc/ssl/certs/ssl-cert-snakeoil.pem`. This certificate and key are generated automatically when the `ssl-cert` package is installed. They're essentially a self-signed certificate for the hostname.
The `ssl-cert` package is a dependency of `postfix` (and of several other server packages). Postfix is the default MTA on Ubuntu, so `ssl-cert` and the snakeoil certificates will be installed on most systems.
An even neater solution would be to also add `ssl-cert` to `htcondor.deb`'s dependencies.
- Hit the merge button if the pull request is …
=> Correct Debian/Ubuntu SSL certs location

src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp
=> HTCONDOR-1491-vector-reaper

src/condor_includes/proc.h, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-1519 add key range tests to PROC_ID struct, default to -1,-1

docs/apis/python-bindings/api/htchirp.rst
=> HTCONDOR-1394: remove missing phase method from htchirp docs

docs/version-history/feature-versions-10-x.rst, src/condor_starter.V6.1/condor_ssh_to_job_sshd_setup, src/condor_starter.V6.1/starter.cpp, src/condor_tools/getpwnam.cpp
[HTCONDOR-1543](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1543)
[HTCONDOR-1543]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-1543 ssh to job

docs/version-history/feature-versions-10-x.rst, src/condor_starter.V6.1/condor_ssh_to_job_sshd_setup, src/condor_starter.V6.1/starter.cpp, src/condor_tools/getpwnam.cpp
=> HTCONDOR-1534: Cherry-pick to 10.2.1 version

docs/version-history/lts-versions-10-0.rst, src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_shadow.V6.1/shadow_v61_main.cpp
=> HTCONDOR-1549 smaller-pipe-buffers

docs/version-history/feature-versions-10-x.rst, src/python-bindings/schedd.cpp
=> HTCONDOR-1531: Cherry-pick to 10.2.1 version

docs/version-history/feature-versions-10-x.rst, src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_shadow.V6.1/shadow_v61_main.cpp
=> HTCONDOR-1549: Cherry-pick to 10.2.1

build/packaging/debian/control.in, docs/version-history/lts-versions-10-0.rst
=> HTCONDOR-1548: Fix Ubuntu 18.04 installation (python 3.6)

docs/version-history/lts-versions-10-0.rst, src/condor_tools/htcondor_cli/annex_create.py
See https://crt.cs.wisc.edu/rt/Ticket/Display.html?id=108092.
=> HTCONDOR-1534  Fix Python warning

src/condor_utils/docker-api.cpp
[HTCONDOR-1494](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1494)
[HTCONDOR-1494]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-1494-fix-advertise-docker-cache

src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_command.h, src/condor_daemon_core.V6/daemon_core.cpp
=> HTCONDOR-1491-vector-com

src/condor_scripts/annex/anvil.sh, src/condor_scripts/annex/bridges2.sh, src/condor_scripts/annex/expanse.sh, src/condor_scripts/annex/path-facility.sh, src/condor_scripts/annex/stampede2.sh
=> (HTCONDOR-1552)  Update the HTCondor version of the pilot to 10.0.1.

src/condor_scripts/annex/hpc.sh, src/condor_scripts/annex/path-facility.sh, src/condor_scripts/annex/stampede2.fragment, src/condor_tools/htcondor_cli/annex_validate.py
=> (HTCONDOR-1554)  Update feature-series annex to 10.2.0

docs/version-history/lts-versions-10-0.rst, src/condor_starter.V6.1/condor_ssh_to_job_sshd_setup, src/condor_starter.V6.1/starter.cpp, src/condor_tools/getpwnam.cpp
=> HTCONDOR-1543: Cherry-pick to 10.0 branch

src/condor_tools/htcondor_cli/job.py
=> (HTCONDOR-1321)  Fix a typo.

src/condor_daemon_core.V6/daemon_core.cpp, src/condor_daemon_core.V6/self_monitor.cpp, src/condor_gridmanager/arcjob.cpp, src/condor_includes/condor_secman.h, src/condor_io/condor_auth_kerberos.cpp, src/condor_io/condor_ipverify.cpp, src/condor_io/condor_secman.cpp, src/condor_io/shared_port_client.cpp, src/condor_io/shared_port_client.h, src/condor_io/shared_port_endpoint.cpp, src/condor_io/shared_port_server.cpp, src/condor_schedd.V6/qmgmt_receivers.cpp, src/condor_schedd.V6/qmgmt_send_stubs.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_utils/condor_getcwd.cpp, src/condor_utils/condor_getcwd.h, src/condor_utils/dagman_utils.cpp, src/condor_utils/docker-api.cpp, src/condor_utils/email_cpp.cpp, src/condor_utils/internet.cpp, src/condor_utils/limit_directory_access.cpp, src/condor_utils/proc_family_proxy.cpp, src/condor_utils/proc_family_proxy.h, src/condor_utils/read_multiple_logs.cpp, src/condor_utils/stat_wrapper.cpp, src/condor_utils/stat_wrapper.h, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
=> HTCONDOR-1491 strings

docs/version-history/feature-versions-10-x.rst, src/condor_scripts/linux_kernel_tuning
Raise the value of /proc/sys/fs/pipe-user-pages-soft to 128k if it was below that.
[HTCONDOR-1556](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1556)
[HTCONDOR-1556]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-1556-pipe-kernel-tuning

docs/version-history/lts-versions-10-0.rst, src/condor_vm-gahp/libvirt_simple_script.awk
=> HTCONDOR-1559: Cherry-pick

docs/version-history/lts-versions-10-0.rst, src/condor_scripts/condor_remote_cluster
=> HTCONDOR-1562: Fetch AlmaLinux tarballs for EL8 and EL9

src/condor_negotiator.V6/matchmaker.cpp, src/condor_negotiator.V6/matchmaker.h
The feature(s) in this PR are deliberately undocumented and known to be incomplete, but two of three people who are going to care about the feature(s) would rather not run an unofficial release to start testing them and figuring out what else is needed.
See the JIRA ticket for further design and usage notes.
=> HTCONDOR-918  Add MachineMatchCount and OfflineMatches attributes to offline ads.

docs/admin-manual/security.rst
=> HTCONDOR-1362 token-docs

build/nmi-build/build-batlab-images.sh, build/nmi-build/setup.sh, build/packaging/debian/prepare-build-files.sh, nmi_tools/glue/build/build_uw_deb.sh, nmi_tools/glue/build/make-tarball-from-debs, nmi_tools/glue/build/make-tarball-from-rpms, nmi_tools/glue/build/make-tarball-links, nmi_tools/nmi-build-platforms
[HTCONDOR-997](https://opensciencegrid.atlassian.net/browse/HTCONDOR-997)
- build nmi-build containers in parallel
- fetch packages when building nmi-build containers (Debian/Ubuntu cannot cope with repo changes)
- consolidate unpacking debs and RPMs into a function rather than duplicating code
- Adjust tarball symlinks to account for condor-stash-rpm making an RPM style libexec in a deb package
[HTCONDOR-997]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
=> HTCONDOR-997: Move externals into build containers

src/condor_tools/htcondor_cli/annex.py, src/condor_tools/htcondor_cli/cli.py
systems and their (known) queues.  Also, if the user doesn't specify a queue@system on the command line, invoke the `list` the command.
=> (HTCONDOR-1363)  Add the `systems` verb to `annex`, which lists the known systems

src/condor_utils/MapFile.cpp
=> HTCONDOR-1572-log-pcre2-offset

build/nmi-build/setup.sh
Although the variable expands with quotes,
file globbing does not.
[HTCONDOR-997](https://opensciencegrid.atlassian.net/browse/HTCONDOR-997)
[HTCONDOR-997]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-997: Remove 32 bit externals from tarballs

src/condor_tests/CMakeLists.txt, src/condor_tests/job_core_remote-initialdir_van.cmd, src/condor_tests/test_xfer_hold_codes.py
=> HTCONDOR-1566 ornithology macos

src/condor_tests/test_xfer_stats_overflow_regression.py
The old version of bash on macOS doesn't understand &>>. Despite this causing the test jobs to fail, the test itself still passed. So add some validation checks in the test.
=> HTCONDOR-1566 Fix test_xfer_stats_overflow_regression

src/condor_unit_tests/FTEST_stl_string_utils.cpp, src/condor_utils/stl_string_utils.cpp, src/condor_utils/stl_string_utils.h
So range-based for loops work with it, e.g.
for (auto &s: StringTokenIterator("JobUniverse MemoryUsage Foo")) {
operation(s);
}
=> HTCONDOR-1577-string-token-iterator

src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp
=> HTCONDOR-1491-pipehandle-vector

docs/version-history/lts-versions-10-0.rst, src/condor_schedd.V6/qmgmt.cpp
=> HTCONDOR-1581-late-mat-crash

src/condor_tests/CMakeLists.txt, src/condor_tests/test_condor_history.py
=> HTCONDOR-1565: make condor_history regression test

docs/version-history/lts-versions-10-0.rst, src/condor_tests/CMakeLists.txt, src/condor_tests/test_pcre.py, src/condor_utils/MapFile.cpp
=> HTCONDOR-1573  Properly handle escaped escape characters.

docs/version-history/upgrading-from-9-0-to-10-0-versions.rst
=> HTCONDOR-1409: Add more gotcha info online

docs/version-history/feature-versions-10-x.rst, src/condor_shadow.V6.1/remoteresource.cpp
=> HTCONDOR-1585-shadow-segfault

src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp
=> HTCONDOR-1577-vector-sock-table

docs/version-history/lts-versions-10-0.rst, src/condor_shadow.V6.1/remoteresource.cpp
=> HTCONDOR-1585 Fix condor_shadow crash seen on osgconnect

src/condor_tools/history.cpp
-added function to sort job match filter info, and then
condense into the minimum number of objects (2 2.1 2.2 -> 2)
-Restructured the post job print match check code
=> HTCONDOR-1526: condor_history jid matching

docs/version-history/.#lts-versions-10-0.rst, docs/version-history/lts-versions-10-0.rst, src/condor_daemon_core.V6/condor_lock_file.cpp, src/condor_daemon_core.V6/condor_lock_implementation.cpp
=> HTCONDOR-1590 schedd ha locking

docs/version-history/feature-versions-10-x.rst, src/blahp/src/CMakeLists.txt, src/blahp/src/blah_utils.c, src/blahp/src/commands.c, src/blahp/src/commands.h, src/blahp/src/scripts/condor_ping.sh, src/blahp/src/scripts/kubernetes_ping.sh, src/blahp/src/scripts/lsf_ping.sh, src/blahp/src/scripts/nqs_ping.sh, src/blahp/src/scripts/pbs_ping.sh, src/blahp/src/scripts/sge_ping.sh, src/blahp/src/scripts/slurm_ping.sh, src/blahp/src/server.c, src/condor_gridmanager/baseresource.cpp, src/condor_gridmanager/baseresource.h, src/condor_gridmanager/gahp-client.cpp, src/condor_gridmanager/gahp-client.h, src/condor_gridmanager/infnbatchjob.cpp, src/condor_gridmanager/infnbatchresource.cpp, src/condor_includes/condor_attributes.h
=> HTCONDOR-1582 batch-failure-monitoring

CMakeLists.txt, src/condor_utils/CMakeLists.txt
not global across all libraries/executables
=> HTCONDOR-1577-cmake-stdfs

docs/classad-attributes/job-classad-attributes.rst, docs/version-history/feature-versions-10-x.rst, src/condor_includes/condor_attributes.h, src/condor_utils/file_transfer.cpp
and add documentation for TransferInputStats and TransferOutputStats
[HTCONDOR-1588](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1588)
[HTCONDOR-1588]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-1588-container-duration

src/condor_credd/credd.cpp, src/condor_negotiator.V6/GroupEntry.cpp, src/condor_negotiator.V6/GroupEntry.h, src/condor_negotiator.V6/matchmaker.cpp, src/condor_negotiator.V6/matchmaker.h, src/condor_q.V6/jobmatch.cpp
=> HTCONDOR-1577-remove-ClassAdListDoesNotDeleteAds

docs/version-history/lts-versions-10-0.rst, src/condor_examples/condor.service
[HTCONDOR-1594](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1594)
[HTCONDOR-1594]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1594?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-1594: Don't start HTCondor until remote filesystems are mounted

docs/version-history/lts-versions-10-0.rst
=> HTCONDOR-1594: Updates per code review

src/condor_job_router/submit_job.cpp, src/condor_schedd.V6/qmgmt.cpp
=> HTCONDOR-111 branch

src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_negotiator.V6/matchmaker.cpp
=> HTCONDOR-1577-fix-warnings

CMakeLists.txt, src/classad/CMakeLists.txt, src/classad/classad.cpp, src/classad/classad/classad.h, src/classad/classad/common.h
=> HTCONDOR-1571 Add classad transparent comparators

docs/version-history/lts-versions-10-0.rst, src/condor_shadow.V6.1/NTreceivers.cpp, src/condor_tests/test_xfer_hold_codes.py
=> HTCONDOR-1600 missing-job-creds-hold

docs/version-history/lts-versions-10-0.rst, src/condor_schedd.V6/qmgmt_factory.cpp
=> HTCONDOR-1603 fix for TotalSubmitProcs wrong for late mat after reload

docs/version-history/lts-versions-10-0.rst, src/condor_gridmanager/gahp-client.cpp
=> HTCONDOR-1604 grid condor inherit

docs/version-history/lts-versions-10-0.rst
TimT pointed this problem out.
=> Clarify that the "different" bug was also fixed.

docs/cloud-computing/annex-users-guide.rst, docs/cloud-computing/using-annex-first-time.rst, docs/users-manual/quick-start-guide.rst, docs/users-manual/submitting-a-job.rst
Fix a formatting typo in the manual sphinx file that hides important information.
=> HTCONDOR-1331-fix-docs

.readthedocs.yml, docs/requirements.txt
[HTCONDOR-1597](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1597)
[HTCONDOR-1597]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-1597: Update requirements to build the manual

docs/version-history/lts-versions-10-0.rst, src/condor_gridmanager/arcjob.cpp
=> HTCONDOR-1583 arc submit failure

src/condor_tests/test_tom_directory_creation.py, src/condor_utils/param_info.in
=> HTCONDOR-1325: Turn ALLOW_TRANSFER_REMAP_TO_MKDIR back on

src/condor_unit_tests/FTEST_stl_string_utils.cpp, src/condor_utils/stl_string_utils.h
=> V10_4-HTCONDOR-1577-case-string-view

src/condor_master.V6/masterDaemon.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_shadow.V6.1/pseudo_ops.cpp, src/condor_utils/compat_classad.cpp
=> HTCONDOR-1577 Fix two small warnings

docs/classad-attributes/machine-classad-attributes.rst, docs/version-history/feature-versions-10-x.rst, src/condor_starter.V6.1/starter_v61_main.cpp
=> HTCONDOR-1614-advertise-sshd

docs/classad-attributes/machine-classad-attributes.rst, docs/version-history/feature-versions-10-x.rst, src/condor_starter.V6.1/starter_v61_main.cpp
=> HTCONDOR-1614 Advertise HasSshd if /usr/sbin/sshd exists on system

docs/version-history/lts-versions-10-0.rst, src/condor_schedd.V6/schedd.cpp, src/condor_unit_tests/OTEST_UserPolicy.cpp, src/condor_utils/condor_crontab.cpp
=> HTCONDOR-1624 crondor loop

.github/workflows/publish_release_to_website.yml
=> HTCONDOR-1570: Update Ubuntu Version in Automatic Deployment Actions

docs/version-history/lts-versions-10-0.rst, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-1629: fixed non-removable cron with invalid time specifications

docs/version-history/lts-versions-10-0.rst, src/annex/annex-setup.cpp, src/annex/setup/Makefile, src/annex/setup/generate-template, src/annex/setup/odi-lease.js, src/annex/setup/sfr-lease.js, src/annex/setup/upgrade-runtime.py
Users will be unable to set up `condor_annex` in a region after March 31 without this patch.
=> HTCONDOR-1627  Update condor_annex runtime.

docs/version-history/lts-versions-10-0.rst, src/condor_schedd.V6/schedd.cpp, src/condor_unit_tests/OTEST_UserPolicy.cpp, src/condor_utils/condor_crontab.cpp
=> HTCONDOR-1624: Merge to main

src/condor_schedd.V6/qmgmt.cpp
in preparation for adding a User record.  No version history, this is a defensive change with no user visible effect. 
=> HTCONDOR-1432 Make job queue record type checks more robust

docs/version-history/feature-versions-10-x.rst, src/condor_utils/job_ad_instance_recording.cpp
=> HTCONDOR-1631: Job epoch writing set priv_condor

src/classad/classad/common.h, src/condor_utils/load_dll.WINDOWS.cpp, src/condor_utils/load_dll.WINDOWS.h
=> HTCONDOR-1577-quiet-warnings

build/packaging/rpm/condor.spec
=> HTCONDOR-1635: Prohibit building on EL9

build/packaging/rpm/condor.spec, docs/version-history/feature-versions-10-x.rst
=> HTCONDOR-1571: Eliminate SELinux warning in EL9

docs/admin-manual/configuration-macros.rst, docs/classad-attributes/job-classad-attributes.rst, docs/version-history/feature-versions-10-x.rst, src/condor_dagman/dagman_main.cpp, src/condor_dagman/dagman_main.h, src/condor_dagman/dagman_submit.cpp
=> HTCONDOR-1634: DAGMan knob to insert node retry into job ad

docs/version-history/lts-versions-10-0.rst, src/condor_gridmanager/remote_gahp
=> HTCONDOR-1632 old-bosco

build/packaging/debian/control.in, nmi_tools/nmi-build-platforms
=> HTCONDOR-1570: Update build images

build/packaging/debian/control.in, build/packaging/rpm/condor.spec, nmi_tools/nmi-build-platforms
=> HTCONDOR-1569: Update to gcc12 on EL8

build/nmi-build/build-batlab-images.sh, docs/getting-htcondor/from-our-repositories.rst, docs/getting-htcondor/index.rst, docs/version-history/lts-versions-10-0.rst, nmi_tools/nmi-build-platforms
This PR only addressed removing Ubuntu 18.04 from the build. Cleanup (such as removing special cmake directives) will be performed on the main branch.
=> HTCONDOR-1637: Drop Ubuntu 18.04 (Bionic Beaver) Support

src/condor_utils/condor_ver_info.cpp, src/condor_utils/network_adapter.cpp, src/condor_utils/param_info.cpp, src/condor_utils/param_info.h, src/gpu/cuda_device_enumeration.h
=> HTCONDOR-1626-fix-odr

docs/version-history/lts-versions-10-0.rst, src/condor_job_router/submit_job.cpp, src/condor_shadow.V6.1/baseshadow.cpp
Also have the shadow exception code write these events.
=> HTCONDOR-1642 Have job router write Job Ad Information events

src/condor_includes/file_lock.h, src/condor_io/condor_secman.cpp, src/condor_shadow.V6.1/NTreceivers.cpp, src/condor_startd.V6/ResMgr.h, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_tests/x_job_mem_checker.c, src/condor_utils/CMakeLists.txt, src/condor_utils/ClassAdLogReader.cpp, src/condor_utils/ClassAdLogReader.h, src/condor_utils/classad_log.h, src/condor_utils/file_lock.cpp, src/condor_utils/format_time.cpp, src/condor_utils/log_rotate.cpp, src/condor_utils/metric_units.cpp, src/condor_utils/proc_id.cpp, src/condor_utils/setenv.cpp, src/condor_utils/stat_info.cpp, src/condor_utils/submit_utils.cpp
=> HTCONDOR-1626 warning-fixes

src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/starter.cpp, src/condor_unit_tests/OTEST_ArgList.cpp, src/condor_unit_tests/OTEST_Env.cpp, src/condor_utils/check_events.cpp, src/condor_utils/check_events.h, src/condor_utils/condor_arglist.cpp, src/condor_utils/condor_arglist.h, src/condor_utils/dagman_utils.cpp, src/condor_utils/docker-api.cpp, src/condor_utils/env.cpp, src/condor_utils/env.h, src/condor_utils/java_config.cpp, src/condor_utils/submit_utils.cpp
=> HTCONDOR-1626 string-cleanup

src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResState.cpp, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h
=> HTCONDOR-1502 fix for recursion bug when d-slots are deleted

docs/version-history/feature-versions-10-x.rst, src/condor_utils/docker-api.cpp
=> HTCONDOR-1645-docker-image-cache-stderr

src/condor_job_router/submit_job.cpp, src/condor_tests/appendmsg.cpp, src/condor_tests/sleep.cpp, src/condor_tests/tiny_winapi.h, src/condor_utils/filename_tools.cpp, src/condor_utils/my_async_fread.cpp, src/condor_utils/network_adapter.unix.cpp, src/condor_utils/network_adapter.unix.h, src/condor_utils/subsystem_info.cpp, src/condor_utils/subsystem_info.h, src/condor_utils/write_user_log.cpp, src/condor_utils/write_user_log.h
=> HTCONDOR-1626 const-cast

docs/version-history/lts-versions-10-0.rst, src/condor_gridmanager/arcjob.cpp
The tag is case-sensitive and the first 't' should be lower-case.
=> HTCONDOR-1648 Fix mispelled <RuntimeEnvironment> in ARC CE ADL

src/condor_startd.V6/ResState.cpp
=> HTCONDOR-1502 quiet state change time warning

docs/version-history/feature-versions-10-x.rst, src/condor_utils/docker-api.cpp
=> HTCONDOR-1645: Backport to 10.4.0

docs/conf.py, docs/index.rst, docs/man-pages/condor_watch_q.rst
=> HTCONDOR-1654: docs-wayfinding

docs/version-history/feature-versions-10-x.rst, src/condor_examples/condor-annex-ec2.service, src/condor_examples/condor.service
=> HTCONDOR-1655 sssd in systemd init script

docs/users-manual/quick-start-guide.rst
And add in required Request* commands
=> HTCONDOR-1659-update-quickstart

src/arc_gahp/arcgahp_common.cpp, src/arc_gahp/io_loop_pthread.cpp, src/arc_gahp/io_loop_pthread.h, src/ccb/ccb_listener.cpp, src/condor_c-gahp/schedd_client.cpp, src/condor_gridmanager/gridmanager.cpp, src/condor_gridmanager/proxymanager.cpp, src/condor_gridmanager/proxymanager.h, src/condor_vm-gahp/vmgahp.cpp, src/condor_vm-gahp/vmgahp.h, src/condor_vm-gahp/xen_type.linux.cpp, src/condor_vm-gahp/xen_type.linux.h, src/ec2_gahp/amazongahp_common.cpp, src/ec2_gahp/io_loop_pthread.cpp, src/ec2_gahp/io_loop_pthread.h, src/gce_gahp/gcegahp_common.cpp, src/gce_gahp/io_loop_pthread.cpp, src/gce_gahp/io_loop_pthread.h, src/openstack_gahp/io_loop_pthread.cpp, src/openstack_gahp/io_loop_pthread.h, src/openstack_gahp/openstackgahp_common.cpp
=> HTCONDOR-1626-remove-simplelist

src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp
=> HTCONDOR-1577-vectorize-pipe

docs/users-manual/automatic-job-management.rst, docs/users-manual/container-universe-jobs.rst, docs/users-manual/dagman-workflows.rst, docs/users-manual/docker-universe-applications.rst, docs/users-manual/file-transfer.rst, docs/users-manual/java-applications.rst, docs/users-manual/parallel-applications.rst, docs/users-manual/self-checkpointing-applications.rst, docs/users-manual/special-environment-considerations.rst, docs/users-manual/submitting-a-job.rst, docs/users-manual/welcome-to-htcondor.rst
=> HTCONDOR-1665-Add-Request-to-manual

src/condor_utils/condor_query.h, src/condor_utils/generic_query.cpp, src/condor_utils/generic_query.h
=> HTCONDOR-1626-simplelist

docs/version-history/feature-versions-10-x.rst, src/condor_gridmanager/arcjob.cpp, src/condor_gridmanager/gahp-client.cpp, src/condor_gridmanager/gahp-client.h
Commands that affect multiple jobs are highest priority and submission of new jobs is lowest priority. Other commands are medium priority. This mirrors the command priorities for Condor-C jobs.
=> HTCONDOR-1666 prioritize-arc-commands

docs/version-history/lts-versions-10-0.rst, src/condor_startd.V6/startd_cron_job_mgr.cpp, src/condor_startd.V6/startd_cron_job_params.cpp, src/gpu/condor_gpu_utilization.cpp
=> (HTCONDOR-1660)  Resize sample vector to the number of returned samples.

docs/version-history/feature-versions-10-x.rst, src/condor_starter.V6.1/vanilla_proc.cpp
=> HTCONDOR-1672-cpu_command_cpuacct

docs/conf.py
=> HTCONDOR-1667-sphinx-warnings

src/blahp/src/server.c, src/classad_analysis/analysis.cpp, src/classad_analysis/boolExpr.cpp, src/classad_analysis/boolValue.cpp, src/classad_analysis/condition.cpp, src/classad_analysis/explain.cpp, src/classad_analysis/interval.cpp, src/classad_analysis/multiProfile.cpp, src/classad_analysis/resourceGroup.cpp, src/condor_collector.V6/view_server.h, src/condor_gridmanager/azurejob.cpp, src/condor_gridmanager/ec2job.cpp, src/condor_gridmanager/gcejob.cpp, src/condor_had/HAD.cpp, src/condor_had/HAD_Version.cpp, src/condor_had/Utils.cpp, src/condor_io/cedar.t.unix.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_startd.V6/startd_cron_job_params.cpp, src/condor_status.V6/prettyPrint.cpp, src/condor_unit_tests/FTEST_flatten_and_inline.cpp, src/condor_unit_tests/OTEST_UserPolicy.cpp, src/condor_utils/cron_job_list.cpp, src/condor_utils/generic_stats.h, src/condor_utils/mk_cache_links.cpp, src/condor_utils/read_multiple_logs.cpp
=> HTCONDOR-1626-fix-warnings

docs/admin-manual/configuration-macros.rst, docs/admin-manual/security.rst
=> HTCONDOR-855 Expand IDTOKENS documentation, adding SEC_TOKEN_ISSUER_KEY

docs/users-manual/submitting-a-job.rst
=> HTCONDOR-1656-doc-require-gpus

docs/version-history/lts-versions-10-0.rst, src/condor_scripts/condor_remote_cluster
=> HTCONDOR-1670 bosco arch

src/condor_gridmanager/arcjob.cpp
=> HTCONDOR-1626 Fix incorrect usage of std::remove_if()

src/arc_gahp/arcCommands.cpp, src/condor_collector.V6/ce-audit-plugin.cpp, src/condor_negotiator.V6/matchmaker.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_tools/config_val.cpp, src/condor_unit_tests/OTEST_Regex.cpp, src/condor_utils/MapFile.cpp, src/condor_utils/MapFile.h, src/condor_utils/classad_log.cpp, src/condor_utils/classad_log.h, src/condor_utils/classad_usermap.cpp, src/condor_utils/compat_classad.cpp, src/condor_utils/compat_classad_util.h, src/condor_utils/condor_crontab.cpp, src/condor_utils/condor_regex.cpp, src/condor_utils/condor_regex.h, src/condor_utils/libcondorapi_stubs.cpp, src/condor_utils/test_mapfile.cpp, src/condor_utils/test_user_mapping.cpp, src/ec2_gahp/amazonCommands.cpp, src/gangliad/statsd.cpp
=> HTCONDOR-1626 convert-strings

docs/admin-manual/configuration-macros.rst, docs/admin-manual/hooks.rst, docs/admin-manual/installation-startup-shutdown-reconfiguration.rst, docs/admin-manual/introduction-admin-manual.rst, docs/admin-manual/introduction-to-configuration.rst, docs/admin-manual/logging.rst, docs/admin-manual/networking.rst, docs/admin-manual/security.rst, docs/admin-manual/setting-up-special-environments.rst, docs/admin-manual/user-priorities-negotiation.rst
=> HTCONDOR-1694-remove-vestigal-docs

docs/version-history/lts-versions-10-0.rst, src/condor_c-gahp/schedd_client.cpp, src/condor_job_router/submit_job.cpp
=> HTCONDOR-1695 Make c-gahp and job router set cluster attributes

docs/admin-manual/logging.rst, docs/admin-manual/monitoring.rst, docs/admin-manual/networking.rst, docs/admin-manual/policy-configuration.rst, docs/admin-manual/power-management.rst, docs/admin-manual/security.rst, docs/admin-manual/setting-up-special-environments.rst, docs/admin-manual/setting-up-vm-docker-universes.rst, docs/admin-manual/user-priorities-negotiation.rst, docs/version-history/feature-versions-10-x.rst
=> HTCONDOR-1697 Add :macro: tags to config knobs in manual

src/condor_daemon_core.V6/daemon_core.cpp, src/condor_includes/reli_sock.h, src/condor_includes/safe_sock.h, src/condor_includes/sock.h, src/condor_includes/stream.h, src/condor_io/reli_sock.cpp, src/condor_io/safe_sock.cpp, src/condor_io/shared_port_endpoint.cpp, src/condor_io/shared_port_endpoint.h, src/condor_io/sock.cpp
=> HTCONDOR-1626 sock serialize

externals/bundles/boost/1.49.0/CMakeLists.txt, externals/bundles/boost/1.66.0/CMakeLists.txt, externals/bundles/boost/1.68.0/CMakeLists.txt
=> HTCONDOR-1626: Make the required boost version match the external

docs/users-manual/index.rst, docs/users-manual/when-job-wont-run.rst
=> HTCONDOR-1700-doc-when-job-idle

docs/admin-manual/user-priorities-negotiation.rst
=> HTCONDOR-1699-document-multiple-negotiators

docs/users-manual/submitting-a-job.rst
=> HTCONDOR-1656 Update docs so GPU examples work with current HTCondor

docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-10-x.rst, src/arc_gahp/arcCommands.cpp, src/arc_gahp/io_loop_pthread.cpp, src/arc_gahp/io_loop_pthread.h, src/arc_gahp/thread_control.h, src/condor_gridmanager/arcjob.cpp, src/condor_utils/param_info.in
=> HTCONDOR-1690 arc-gahp-threads

docs/users-manual/dagman-workflows.rst, docs/users-manual/file-transfer.rst, docs/users-manual/managing-a-job.rst, docs/users-manual/parallel-applications.rst, docs/users-manual/quick-start-guide.rst, docs/users-manual/running-a-job-steps.rst, docs/users-manual/services-for-jobs.rst, docs/users-manual/special-environment-considerations.rst, docs/users-manual/submitting-a-job.rst, docs/users-manual/submitting-a-remote-job.rst, docs/users-manual/virtual-machine-applications.rst, docs/users-manual/when-job-wont-run.rst
=> HTCONDOR-1701-switch-users-man-to-ap

SECURITY.md
=> HTCONDOR-1626-add-security-github-pointer

src/condor_tools/preen.cpp, src/condor_utils/file_transfer.cpp, src/condor_utils/file_transfer.h, src/condor_utils/uids.cpp
If the admin specifies test URLs for a given schema, test the file transfer plugin using that URL prior to declaring it available.
=> HTCONDOR-1608 Allow testing of file transfer plugins

src/condor_tools/preen.cpp, src/condor_utils/file_transfer.cpp, src/condor_utils/file_transfer.h, src/condor_utils/uids.cpp
=> V10_5-HTCONDOR-1608-filetranfer-plugin-testing

docs/admin-manual/setting-up-special-environments.rst
=> HTCONDOR-1701 fix typo

docs/admin-manual/setting-up-special-environments.rst, src/condor_io/condor_secman.cpp
=> HTCONDOR-1693: Remove TOFU openssl 3 deprecation warnings

docs/users-manual/quick-start-guide.rst
=> HTCONDOR-1707-doc-num-retries

docs/version-history/upgrading-from-9-0-to-10-0-versions.rst
=> HTCONDOR-1656: Link require_gpus from the gotchas

build/cmake/CondorConfigure.cmake
This reverts commit 17c2edebf09bc301b7978ea50aaf389910498b70.
=> HTCONDOR-1626: Revert "Get RPM builds to work on CentOS8 by removing -g3"

docs/version-history/feature-versions-10-x.rst
=> HTCONDOR-1715: fix 10.4 version history for desktop policy

docs/version-history/lts-versions-10-0.rst, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_shadow.V6.1/remoteresource.h, src/condor_shadow.V6.1/shadow.cpp, src/condor_shadow.V6.1/shadow_v61_main.cpp, src/condor_utils/param_info.in
=> HTCONDOR-1716 Backport -1687 to stable

src/condor_daemon_core.V6/daemon_core.cpp, src/condor_daemon_core.V6/self_monitor.cpp, src/condor_daemon_core.V6/timer_manager.cpp, src/condor_includes/condor_config.h, src/condor_includes/condor_sockaddr.h, src/condor_includes/sockCache.h, src/condor_schedd.V6/qmgmt_factory.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h, src/condor_utils/condor_config.cpp, src/condor_utils/condor_sockaddr.cpp, src/condor_utils/generic_stats.cpp, src/condor_utils/generic_stats.h
=> HTCONDOR-1626 string work

src/condor_sysapi/arch.cpp
=> HTCONDOR-1718 macos-ventura

docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-10-x.rst, src/condor_dagman/dagman_main.cpp, src/condor_dagman/dagman_main.h, src/condor_dagman/dagman_submit.cpp, src/condor_utils/param_info.in
=> HTCONDOR-1717: DAGMan record requested machine attrs

src/condor_tests/shadow_mem_usage-basic.run
Also error out if not specified
=> HTCONDOR-1637: Shadow memory test updates

src/condor_sysapi/arch.cpp
=> HTCONDOR-1720-alma-linux

docs/admin-manual/logging.rst, docs/admin-manual/setting-up-special-environments.rst, docs/extensions/macro.py
-Fixed a broken :ref:
-Removed a :index: that was next to :macro:
-Added python logic to automatically make index directives for :macro: calls
=> HTCONDOR-1719: Auto index at macro directives in documentation

docs/man-pages/condor_transform_ads.rst, docs/version-history/feature-versions-10-x.rst, src/condor_job_router/JobRouter.cpp, src/condor_tools/transform_ads.cpp, src/condor_utils/xform_utils.cpp, src/condor_utils/xform_utils.h
=> HTCONDOR-1710 can pass a config file to condor_transform_ads -rules

nmi_tools/glue/build/build_uw_deb.sh, nmi_tools/glue/build/make-tarball-from-debs, nmi_tools/glue/build/make-tarball-links
This seems all that's necessary to build the .debs and tarballs on this platform.
=> (HTCONDOR-1721)  Recognize "chimaera" as Devuan 4.

src/condor_tools/CMakeLists.txt, src/condor_tools/tail.cpp
=> HTCONDOR-1726-condor-tail

docs/admin-manual/introduction-to-configuration.rst
=> HTCONDOR-1727 Clarify docs for Macros that Require a Restart

src/condor_starter.V6.1/starter.cpp
=> HTCONDOR-1737: Write ads to execute dir post LVM thinpool creation

src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-1626 Fix very unlikely fd leak if stdin is somehow closed

src/classad/classad/common.h
=> HTCONDOR-1626 fix gcc-13 warning about casts in constexpr functions

src/ec2_gahp/amazonCommands.h
=> HTCONDOR-1626 Fix gcc warning about hidden overriden function in

docs/version-history/feature-versions-10-x.rst, src/condor_includes/condor_attributes.h, src/condor_shadow.V6.1/mpiresource.cpp, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_shadow.V6.1/remoteresource.h, src/condor_shadow.V6.1/shadow.cpp, src/condor_startd.V6/ResAttributes.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_utils/compat_classad_util.cpp, src/condor_utils/compat_classad_util.h, src/condor_utils/condor_event.cpp, src/condor_utils/condor_event.h
=> HTCONDOR-1722 Add sandbox path and resource quantities to ExecuteEvent

src/condor_tools/preen.cpp
=> HTCONDOR-1738: Update preen to know about epoch files

src/condor_dagman/dagman_main.cpp, src/condor_dagman/parse.cpp, src/condor_ft-gahp/io_loop.cpp, src/condor_includes/basename.h, src/condor_io/shared_port_endpoint.cpp, src/condor_unit_tests/FTEST_dirname.cpp, src/condor_utils/basename.cpp, src/condor_utils/classadHistory.cpp, src/condor_utils/classad_log.cpp, src/condor_utils/condor_config.cpp, src/condor_utils/dprintf.cpp, src/condor_utils/file_transfer.cpp, src/condor_utils/fs_util.cpp, src/condor_utils/historyFileFinder.cpp, src/condor_utils/limit_directory_access.cpp, src/condor_utils/log_rotate.cpp, src/condor_utils/tmp_dir.cpp
Change condor_dirname to return a std::string and not a mallocated char *
This fixes some memory leaks where we were assigning the mallocated char * to a std::string, and many performance embarrassments where we were usually immediately copying the char * to a string.
=> HTCONDOR-1734-condor_dirname

docs/version-history/lts-versions-10-0.rst, src/condor_gridmanager/gahp-client.cpp, src/condor_gridmanager/gahp-client.h, src/condor_gridmanager/infnbatchjob.cpp
=> HTCONDOR-1747 remote-gahp-condor-inherit

docs/version-history/feature-versions-10-x.rst, src/condor_gridmanager/gahp-client.cpp, src/condor_gridmanager/gahp-client.h, src/condor_gridmanager/infnbatchjob.cpp
=> HTCONDOR-1747: remote-gahp-condor-inherit cherry-pick to 10.4.2

src/condor_starter.V6.1/starter.cpp
-If we are using LVM and we fail to successfully set up LVM
partition through creation of our handle then ASSERT fail
-During execute dir cleanup just reset LVM handle pointer
to let LVM handle destructor to clean up rather than doing /bin/rm
=> HTCONDOR-1753: Improve starter LVM logic

src/condor_utils/dagman_utils.cpp
=> HTCONDOR-1626: remove mystringtokener from dagman utils branch

docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-10-x.rst, src/condor_tests/test_dagman_proper_env.py, src/condor_utils/dagman_utils.cpp
-Expanded hard coded list to include HOME, USER, LANG, and LC_ALL -Updated documentation
-Updated test to know of these changes
=> HTCONDOR-1725: Expand list of env vars passed to DAGMan jobs getenv

src/condor_includes/condor_config.h, src/condor_includes/condor_qmgr.h, src/condor_includes/proc.h, src/condor_includes/stream.h, src/condor_io/stream.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_utils/MyString.h, src/condor_utils/classad_command_util.cpp, src/condor_utils/condor_config.cpp, src/condor_utils/condor_crontab.cpp, src/condor_utils/proc_id.cpp
=> HTCONDOR-1626 fewer mystrings

docs/version-history/lts-versions-10-0.rst, src/condor_schedd.V6/qmgmt.cpp
=> HTCONDOR-1755 owner-in-proc-ad

docs/version-history/feature-versions-10-x.rst, src/condor_schedd.V6/qmgmt.cpp
=> HTCONDOR-1755 owner-in-proc-ad (for 10.4.2)

docs/version-history/lts-versions-10-0.rst, src/condor_daemon_client/daemon.cpp
=> HTCONDOR-1713 private-network-ssl-auth

src/condor_credd/condor_credmon_oauth/condor_vault_storer, src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/VaultCredmon.py
Addresses [HTCONDOR-1527](https://opensciencegrid.atlassian.net/browse/HTCONDOR-1527).  Also includes several other small miscellaneous improvements in the same two vault-integration files that users have run into.  Each of those improvements is in a separate commit. 
[HTCONDOR-1527]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-1527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-1527 Improve vault token weakening

docs/version-history/lts-versions-10-0.rst
Adds version history for external contribution https://github.com/htcondor/htcondor/pull/1307
=> HTCONDOR-1527 Version history

src/condor_ft-gahp/io_loop.cpp, src/condor_includes/condor_auth_ssl.h, src/condor_io/authentication.cpp, src/condor_io/condor_auth_munge.cpp, src/condor_io/condor_auth_ssl.cpp, src/condor_io/condor_secman.cpp, src/condor_shadow.V6.1/NTreceivers.cpp, src/condor_starter.V6.1/NTsenders.cpp
=> HTCONDOR-1751 security logging

src/condor_daemon_core.V6/HookClient.cpp, src/condor_daemon_core.V6/HookClient.h, src/condor_daemon_core.V6/HookClientMgr.cpp, src/condor_daemon_core.V6/HookClientMgr.h, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_io/condor_auth_ssl.cpp, src/condor_job_router/JobRouterHookMgr.cpp, src/condor_schedd.V6/schedd_negotiate.cpp, src/condor_startd.V6/StartdHookMgr.cpp, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_utils/condor_crontab.cpp, src/condor_utils/filesystem_remap.cpp, src/condor_utils/read_multiple_logs.cpp
=> HTCONDOR-1626 daemoncore-strings

src/condor_tests/CheckOutputFormats.pm, src/condor_utils/print_format_tables.cpp
=> HTCONDOR-1761-cmd_status-transform-test

src/CODING_GUIDELINES, src/condor_gridmanager/arcjob.h, src/condor_includes/authentication.h, src/condor_includes/condor_auth_kerberos.h, src/condor_includes/internet.h, src/condor_io/condor_auth_passwd.cpp, src/condor_io/condor_ipverify.h, src/condor_io/shared_port_client.h, src/condor_negotiator.V6/matchmaker.cpp, src/condor_schedd.V6/grid_universe.cpp, src/condor_startd.V6/startd.h, src/condor_tools/ssl_fingerprint.cpp, src/condor_unit_tests/OTEST_Env.cpp, src/condor_unit_tests/unit_test_utils.cpp, src/condor_unit_tests/unit_test_utils.h, src/condor_utils/classad_collection.h, src/condor_utils/condor_regex.h, src/condor_utils/condor_sockfunc.cpp, src/condor_utils/condor_user_policy.cpp, src/condor_utils/submit_protocol.cpp
=> HTCONDOR-1626 remove now superflous includes

docs/admin-manual/introduction-to-configuration.rst, docs/version-history/lts-versions-10-0.rst, src/condor_utils/condor_config.cpp
=> HTCONDOR-1733 Add CONFIG_ROOT to config as detected value

src/condor_utils/condor_config.cpp
=> HTCONDOR-1626 dirname

nmi_tools/glue/SubmitInfo.pm, nmi_tools/nmi-build-platforms
=> HTCONDOR-1765 Add macOS 13 as a batlab build platform

src/condor_tests/test_allowed_job_duration.py
=> HTCONDOR-1766-allowed-execute-duration-test

src/condor_tests/test_custom_machine_resource.py, src/condor_tests/test_custom_machine_resource_instances.py
=> HTCONDOR-1767-fix-test-cmr
