htcondor/htcondor

docs/version-history/feature-versions-23-x.rst, src/classad/lexer.cpp, src/classad/value.cpp
=> HTCONDOR-2455 remove classad unit suffix

src/condor_startd.V6/CMakeLists.txt, src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/ResAttributes.h, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h, src/condor_startd.V6/Starter.cpp, src/condor_startd.V6/Starter.h, src/condor_startd.V6/VolumeManager.cpp, src/condor_startd.V6/VolumeManager.h, src/condor_startd.V6/command.cpp, src/condor_startd.V6/util.cpp, src/condor_startd.V6/util.h, src/condor_starter.V6.1/starter.cpp, src/condor_starter.V6.1/starter.h
=> HTCONDOR-2471 STARTD pass LV name in environment to Starter

src/condor_daemon_client/daemon.cpp, src/condor_daemon_client/daemon.h, src/condor_includes/named_classad_list.h, src/condor_negotiator.V6/Accountant.cpp, src/condor_negotiator.V6/GroupEntry.cpp, src/condor_negotiator.V6/matchmaker.cpp, src/condor_negotiator.V6/matchmaker.h, src/condor_startd.V6/startd_cron_job.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/jic_shadow.h, src/condor_starter.V6.1/os_proc.cpp, src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/starter.cpp, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_utils/compat_classad.cpp, src/condor_utils/compat_classad_util.cpp, src/condor_utils/compat_classad_util.h, src/condor_utils/named_classad_list.cpp
=> HTCONDOR-2475 yet-more-code-cleanup

src/condor_starter.V6.1/starter.cpp
=> HTCONDOR-2475 fix warning

docs/version-history/feature-versions-23-x.rst
=> HTCONDOR-2475 Fix doc typo

docs/version-history/feature-versions-23-x.rst, src/condor_starter.V6.1/singularity.cpp
=> HTCONDOR-2274  apptainer home dir

src/condor_utils/param_info.in
and ad arguments to the template for cache size, location and federation
=> HTCONDOR-2437 Fix STARTD_ENVIRONMENT in PelicanCache config template

docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-23-x.rst, src/condor_examples/condor_config.annotated, src/condor_examples/condor_config.submit.generic, src/condor_schedd.V6/schedd.cpp, src/condor_tests/x_condor_config_template, src/condor_utils/param_info.in
=> HTCONDOR-2300 Lower default value of MAX_SHADOW_EXCEPTIONS from 5 to 2

build/docker/services/mini/container-install-minicondor.sh
Do not yum install flask into the htcondor/mini image because the version provided by the OS is too old. pip will install it later (because it is a dependency), and it will get a decent version.
 
=> Install Flask from pip instead of the OS into htcondor/mini image (HTCONDOR-2427)

src/condor_job_router/submit_job.cpp
=> HTCONDOR-2475 fix unused function warning

docs/version-history/introduction-version-history.rst
=> HTCONDOR-2475: Document our four repositories for each version

docs/version-history/feature-versions-23-x.rst, src/condor_starter.V6.1/vanilla_proc.cpp
=> HTCONDOR-2491 user checkpoints cgroup v2

docs/version-history/feature-versions-23-x.rst, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2490 cgroup populate num procs

src/condor_dagman/dag.cpp
=> HTCONDOR-2475 Shorter, faster, and clearer way to copy vector of job*'s

src/ccb/ccb_client.cpp, src/ccb/ccb_client.h, src/ccb/ccb_listener.cpp, src/condor_q.V6/queue.cpp, src/condor_status.V6/status.cpp, src/condor_submit.V6/factory_test.cpp, src/condor_submit.V6/submit.cpp, src/condor_submit.V6/submit_factory.cpp, src/condor_submit.V6/submit_internal.h, src/condor_utils/adcluster.cpp, src/condor_utils/adcluster.h, src/condor_utils/compat_classad.h, src/gangliad/gangliad.cpp
=> HTCONDOR-2475 most-list-conversions

docs/admin-manual/configuration-macros.rst
=> HTCONDOR-2475 Document units for RESERVED_MEMORY

src/condor_scripts/annex/delta.fragment
It does what it says on the tin.
=> (HTCONDOR-2376)  Update the Delta tarball to the 23.7.2 release.

src/gangliad/gangliad.cpp, src/gangliad/statsd.cpp, src/gangliad/statsd.h
=> HTCONDOR-2475 Remove StringLists from gangliad

src/condor_submit.V6/submit_internal.h, src/condor_utils/config.cpp, src/condor_utils/passwd_cache.unix.cpp
=> HTCONDOR-2475 Remove StringList from passwd cache

src/condor_startd.V6/Starter.cpp, src/condor_startd.V6/startd.h, src/condor_startd.V6/startd_main.cpp
=> HTCONDOR-2471 add LVM LV name uniqueness knob

docs/automated-workflows/dagman-advance-functionality.rst, docs/version-history/feature-versions-23-x.rst, src/condor_dagman/dagman_submit.cpp, src/condor_dagman/script.cpp
=> HTCONDOR-2492: Prohibit multi-proc jobs for DAGMan provisioner node

docs/admin-manual/security.rst, docs/version-history/feature-versions-23-x.rst, src/condor_includes/condor_sockfunc.h, src/condor_io/sock.cpp, src/condor_utils/condor_sockaddr.cpp, src/condor_utils/condor_sockfunc.cpp
=> HTCONDOR-2466 local-ips-alias

src/condor_schedd.V6/qmgmt.cpp, src/condor_startd.V6/startd_cron_job.cpp
=> HTCONDOR-2475 data-struct-cleanup

docs/automated-workflows/dagman-advance-functionality.rst, docs/automated-workflows/dagman-completion.rst, docs/automated-workflows/dagman-information-files.rst, docs/automated-workflows/dagman-interaction.rst, docs/automated-workflows/dagman-introduction.rst, docs/automated-workflows/dagman-reference.rst, docs/automated-workflows/dagman-using-other-dags.rst, docs/automated-workflows/index.rst, docs/full_conf.py, docs/version-history/feature-versions-23-x.rst, src/condor_dagman/dagman_submit.cpp, src/condor_dagman/parse.cpp, src/condor_tests/job_dagman_all_nodes.dag
=> HTCONDOR-2499: add node cmd to dag desc lang branch

docs/version-history/lts-versions-23-0.rst, src/condor_io/condor_auth_ssl.cpp
=> HTCONDOR-2503 zero length scitokens

src/condor_utils/config.cpp
=> HTCONDOR-2475 Remove last StringLists from config.cpp

docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-23-x.rst, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2493 unprivileged cgroup v2

docs/automated-workflows/dagman-advance-functionality.rst, docs/automated-workflows/dagman-completion.rst, docs/automated-workflows/dagman-information-files.rst, docs/automated-workflows/dagman-interaction.rst, docs/automated-workflows/dagman-introduction.rst, docs/automated-workflows/dagman-reference.rst, docs/automated-workflows/dagman-using-other-dags.rst, docs/automated-workflows/index.rst, docs/full_conf.py, docs/version-history/feature-versions-23-x.rst, src/condor_dagman/dagman_submit.cpp, src/condor_dagman/parse.cpp, src/condor_tests/job_dagman_all_nodes.dag
=> HTCONDOR-2510 Revert dagman NODE cmd, as per RCF wish

bindings/python/htcondor2/__init__.py
=> (HTCONDOR-2495)  Set CONDOR_CONFIG to /dev/null if appropriate.

bindings/python/htcondor2/_job_event_log.py, src/condor_tests/test_python_bindings_jobeventlog.py
=> (HTCONDOR-2496)  Actually finish implementing JobEventLog pickling.

build/nmi-build/build-batlab-images.sh, docs/getting-htcondor/from-our-repositories.rst, nmi_tools/nmi-build-platforms
=> HTCONDOR-2468: Drop ppc64el builds on Ubuntu 20.04

src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_tests/test_drain_policies.py, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2513 Fix permission problem when opening cgroup.kill

src/condor_tests/CMakeLists.txt
=> HTCONDOR-2515: Re-enable test on ARM, since we have a ARM machine

docs/version-history/feature-versions-23-x.rst, src/condor_startd.V6/Resource.cpp
=> HTCONDOR-2512 allow SLOT_TYPE_N_ prefix for MODIFY_REQUEST_EXPR knobs

src/ccb/ccb_client.cpp, src/ccb/ccb_server.cpp, src/ccb/ccb_server.h, src/condor_daemon_client/daemon.cpp, src/condor_io/condor_ipverify.cpp, src/condor_io/condor_ipverify.h, src/condor_tools/condor_test_match.cpp
=> HTCONDOR-2475 cleanup of hash

src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp
Also refuse to make user records for unmapped identities.
=> HTCONDOR-2473 condor-name-recognition

src/condor_daemon_client/dc_transfer_queue.cpp, src/condor_daemon_client/dc_transfer_queue.h
=> HTCONDOR-2489 Exponentially backup file xfer queue report updates

src/condor_utils/condor_threads.cpp, src/condor_utils/threads_implementation.h
=> HTCONDOR-2475 Remove hashtable from condor_threads

src/condor_io/condor_auth_kerberos.cpp
=> HTCONDOR-2523 krb-logging

src/condor_procapi/procapi.cpp, src/condor_procapi/procapi.h, src/condor_procd/proc_family_monitor.cpp, src/condor_procd/proc_family_monitor.h, src/condor_procd/tracker_helper_list.h
=> HTCONDOR-2523 procd-hashtables

src/condor_includes/condor_accountant.h, src/condor_negotiator.V6/Accountant.cpp, src/condor_negotiator.V6/hgq_group_tester.cpp, src/condor_negotiator.V6/matchmaker.cpp, src/condor_negotiator.V6/matchmaker.h
=> HTCONDOR-2523 Replace ClassAdListDoesNotDelete ads with vector

docs/version-history/feature-versions-23-x.rst
=> HTCONDOR-2523 Fix sphinx warnings

docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-23-x.rst, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2521 cgroup no count cache

src/ccb/ccb_server.cpp
=> HTCONDOR-2526 Fix crash in ccb server when unregistering

src/condor_tools/htcondor_cli/job.py
=> HTCONDOR-2528 add htcondor cli template

src/condor_utils/passwd_cache.unix.cpp
=> HTCONDOR-2475 fix-passwd-cache

src/condor_status.V6/prettyPrint.h, src/condor_status.V6/setflags.cpp, src/condor_status.V6/status.cpp
=> HTCONDOR-2522 improve reporting of conflicting args to condor_status

src/ccb/ccb_server.cpp
=> HTCONDOR-2526 ccb-sweep-reconnect

src/condor_tools/htcondor_cli/credential.py, src/condor_utils/store_cred.cpp, src/python-bindings/htcondor2/credd.cpp
At least for now, only for OAuth2.
This PR also fixes a bug introduced by HTCONDOR-2498.
=> (HTCONDOR-2507)  Add user-authenticated-as to `htcondor credential list`

src/ccb/ccb_server.cpp
=> HTCONDOR-2526 Fix iterator invalidation in CCBServer::PollSockets()

src/condor_daemon_core.V6/daemon_core.cpp, src/condor_utils/proc_family_direct_cgroup_v2.cpp, src/condor_utils/proc_family_direct_cgroup_v2.h, src/condor_utils/proc_family_interface.h
=> HTCONDOR-2527 Create cgroup in parent before fork.

src/condor_tools/htcondor_cli/credential.py
This was actually a branch from HTCONDOR-2507, but that has since merged to main.
=> (HTCONDOR-2506)  Add a list of jobs using the credential in question to `htcondor credential list`

src/condor_collector.V6/collector_engine.h, src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/scheduler.h, src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/ResAttributes.h, src/condor_utils/file_transfer.cpp, src/condor_utils/file_transfer.h, src/condor_utils/log_transaction.cpp, src/condor_utils/log_transaction.h
=> HTCONDOR-2523 fewer hashtables

src/classad/classad.cpp, src/classad/classad/classad.h
=> HTCONDOR-2523 fix unsigned comparison warning

src/condor_schedd.V6/schedd.cpp
get_condor_username() doesn't include a domain on unix.
=> 2473 Fix detection of whether qmgmt client is condor user

src/condor_scripts/CMakeLists.txt
annex/spark.fragment with executable bits set
=> HTCONDOR-2523 Fix packaging warning by not installing

src/condor_tools/preen.cpp
=> HTCONDOR-2533 fix preen assert

src/classad/source.cpp, src/condor_unit_tests/OTEST_Old_Classads.cpp
=> HTCONDOR-2530 elvis precedence branch merge conflict fixup

build/cmake/CondorConfigure.cmake, externals/bundles/pcre2/10.44/CMakeLists.txt
=> HTCONDOR-2536 Bump pcre2 to 10.44

src/condor_utils/file_transfer.cpp, src/condor_utils/file_transfer.h
=> HTCONDOR-2523 file-xfer-hashtables

src/condor_collector.V6/collector.h
=> HTCONDOR-2523 Remove out-of-date comment

bindings/python/htcondor2/_ad_type.py, docs/version-history/feature-versions-23-x.rst, src/python-bindings/daemon_and_ad_types.cpp
=> HTCONDOR-2474 add Slot And StartDaemon to python bindings AdTypes enum

bindings/python/htcondor2/_collector.py
=> (HTCONDOR-2534)  Fix brain-fart found by TimC.

docs/man-pages/htcondor.rst, docs/version-history/feature-versions-23-x.rst, src/condor_tools/htcondor_cli/credential.py
=> (HTCONDOR-2505)  Implement `htcondor credential listall`.

src/blahp/CMakeLists.txt, src/condor_gridmanager/CMakeLists.txt, src/condor_io/condor_crypt_aesgcm.cpp, src/condor_procd/CMakeLists.txt, src/condor_schedd.V6/CMakeLists.txt, src/condor_unit_tests/CMakeLists.txt, src/condor_utils/strupr.cpp, src/gpu/CMakeLists.txt
=> HTCONDOR-2540  cmake unity build

src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-2542 Fix wrong variable name

src/classad/operators.cpp, src/condor_schedd.V6/qmgmt.cpp
=> HTCONDOR-2523 replace hashtable with set

docs/version-history/feature-versions-23-x.rst, src/condor_utils/docker-api.cpp
=> HTCONDOR-2547 leaking docker images

docs/version-history/feature-versions-23-x.rst, src/condor_submit.V6/submit.cpp, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
=> HTCONDOR-2485: improve condor submit error with dag file

src/classad/classad/jsonSource.h, src/classad/classad/source.h, src/condor_utils/read_multiple_logs.h
=> HTCONDOR-2523 Remove unused #include <iosfwd>'s

docs/version-history/feature-versions-23-x.rst, src/condor_startd.V6/VolumeManager.cpp, src/condor_startd.V6/VolumeManager.h, src/condor_starter.V6.1/CMakeLists.txt, src/condor_starter.V6.1/execute_dir_monitor.cpp, src/condor_starter.V6.1/execute_dir_monitor.h, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/starter.cpp, src/condor_starter.V6.1/starter.h
=> HTCONDOR-2456: report lv usage branch

build/packaging/rpm/condor.spec, src/classad/CMakeLists.txt, src/classad/classad/classad.h, src/classad/classad/flat_set.h, src/condor_schedd.V6/autocluster.cpp, src/condor_utils/compat_classad.cpp
=> HTCONDOR-2554 flat_set

docs/version-history/feature-versions-23-x.rst, src/condor_status.V6/status.cpp
=> HTCONDOR-2556 Restore condor_status -compact mode rollup for -gpus

src/classad/source.cpp, src/condor_collector.V6/ce-audit-plugin.cpp, src/condor_collector.V6/collector.cpp, src/condor_collector.V6/collector_stats.cpp, src/condor_collector.V6/view_server.cpp, src/condor_daemon_client/daemon.cpp, src/condor_daemon_client/dc_startd.cpp, src/condor_dagman/condor_submit_dag.cpp, src/condor_dagman/dag.cpp, src/condor_dagman/dagman_main.cpp, src/condor_gridmanager/ec2job.cpp, src/condor_gridmanager/infnbatchjob.cpp, src/condor_io/authentication.cpp, src/condor_io/condor_ipverify.cpp, src/condor_io/sock.cpp, src/condor_job_router/JobRouterHookMgr.cpp, src/condor_master.V6/master.cpp, src/condor_negotiator.V6/matchmaker.cpp, src/condor_q.V6/jobmatch.cpp, src/condor_q.V6/queue.cpp, src/condor_schedd.V6/autocluster.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/os_proc.cpp, src/condor_status.V6/prettyPrint.cpp, src/condor_userlog/condor_check_userlogs.cpp, src/condor_utils/consumption_policy.cpp, src/condor_utils/data_reuse.cpp, src/condor_utils/test_user_mapping.cpp, src/condor_vm-gahp/xen_type.linux.cpp
into methods that take a std::string.  This avoids a useless copy.
When we still had many MyString's in the code, when we needed to call a function that took a std::string, but had a MyString in hand, we'd frequently call .c_str() on the MyString to implicitly construct the callee's needed std::string.  When we replaced the MyString's with std::strings, we didn't always remove this now redundant copy.
clang-tidy does a good job of finding this, but I'm not sure that each change is guaranteed to be safe.  I've checked each of these, but we need to make sure the callee is taking a _const_ std::string &, AND that the caller isn't injecting a null byte in the middle of the std::string, so that the cstring is shorter than the std::string
<Insert PR description here, and leave checklist below …
=> HTCONDOR-2523 Remove redundent std::string::c_str() calls when calling

docs/version-history/feature-versions-23-x.rst, src/condor_startd.V6/util.cpp
=> HTCONDOR-2559: fix leaky lv issue branch

docs/version-history/feature-versions-23-x.rst
=> HTCONDOR-2521 Fixup jira link in version history

docs/extensions/tool.py
=> HTCONDOR-2562: Improve :tool: role to anchor to htcondor cli noun verbs listing

src/condor_includes/match_prefix.h, src/condor_job_router/NewClassAdJobLogConsumer.h, src/condor_schedd.V6/dedicated_scheduler.h, src/condor_startd.V6/VolumeManager.h, src/condor_unit_tests/function_test_driver.h, src/condor_unit_tests/unit_test_utils.h, src/condor_utils/access.h, src/condor_utils/classad_helpers.h, src/condor_utils/cred_dir.h, src/condor_utils/systemd_manager.h, src/gpu/cuda_header_doc.h, src/gpu/hip_header_doc.h, src/gpu/nvml_stub.h, src/gpu/opencl_header_doc.h
=> HTCONDOR-2537 Add missing macro guards to many header files

docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-23-x.rst, src/condor_utils/param_info.in
=> HTCONDOR-2565 Change CGROUP_IGNORE_CACHE_MEMORY to True by default

docs/version-history/feature-versions-23-x.rst, src/condor_tests/ornithology/plugin.py, src/condor_tests/ornithology/scripts/fail_plugin.py, src/condor_tests/test_xfer_hold_codes.py, src/condor_utils/file_transfer.cpp
Fix one obviously-wrong/missed case where we called `invokeMultiUplladPlugin()` so it now shifts the exit code left by eight to generate the hold reason subcode.  Do NOT fix, but dprintf() a note about another case which might be unfixable.
Add a file-transfer plug-in and corresponding Ornithology fixture to the test suite; the plug-in always fails with exit code 17.
Fix some non-idiomatic spacing in `text_xfer_hold_codes.py`.  Added a test to verify that output failures generate the correct hold reason subcode.  Added an assertion about the hold subcode for non-plug-in output transfers.  Added the same test, but for input plug-in failures.
Changed some D_FULLDEBUG constants in the file transfer object to make it clearer which one was being printed, and what they actually meant.
- Hit the …
=> (HTCONDOR-2555)  Output transfers have incorrect `HoldReasonSubCode`

docs/version-history/feature-versions-23-x.rst
=> HTCONDOR-2561 classad-crash

docs/version-history/lts-versions-23-0.rst, src/condor_io/condor_auth_ssl.cpp
=> V23 0 13 htcondor 2503 zero length scitokens

docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-23-x.rst, src/condor_dagman/dagman_classad.cpp, src/condor_dagman/dagman_classad.h, src/condor_dagman/dagman_main.cpp, src/condor_dagman/dagman_main.h, src/condor_dagman/dagman_submit.cpp, src/condor_tests/CMakeLists.txt, src/condor_tests/test_dagman_inherit_attrs.py
=> HTCONDOR-1845 dag jobs inherit attrs

src/classad/classad.cpp, src/condor_utils/classad_oldnew.cpp
=> HTCONDOR-2523 remove ancient if 0's

docs/version-history/feature-versions-23-x.rst, src/condor_utils/proc_family_direct_cgroup_v1.cpp, src/condor_utils/proc_family_direct_cgroup_v1.h
=> HTCONDOR-2572 no memory usage cgroup v1

src/classad/classad/lexer.h, src/classad/lexer.cpp
This one weird trick speeds up condor_history by almost 10%.
=> HTCONDOR-2523 Inline calls to classad::Lexer::wind

docs/version-history/lts-versions-23-0.rst, src/condor_utils/docker-api.cpp
=> HTCONDOR-2574 docker memory changes

docs/version-history/feature-versions-23-x.rst, src/condor_starter.V6.1/singularity.cpp
=> HTCONDOR-2571 Make shell prompt inside apptainer the slot name

build/cmake/CondorConfigure.cmake, src/CMakeLists.txt, src/condor_birdwatcher/CMakeLists.txt
=> HTCONDOR-2523 cleanup chatty and useless cmake debug messages

src/condor_io/condor_auth_passwd.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2576
NOTE: No documentation needed, and the only code change here is a comment block, so no new testing, no need to wait for build results, etc.
=> HTCONDOR-2576 document akep2

docs/version-history/lts-versions-23-0.rst, src/condor_shadow.V6.1/baseshadow.cpp
Simplify the reason rewriting code to tolerate semicolons in the root error message.
=> HTCONDOR-2560 Fix truncation of transfer-related hold reasons

src/condor_dagman/dagman_submit.cpp, src/condor_includes/condor_qmgr.h, src/condor_schedd.V6/qmgmt_common.cpp, src/condor_submit.V6/submit.cpp, src/condor_submit.V6/submit_internal.h, src/condor_utils/submit_protocol.cpp, src/condor_utils/submit_protocol.h, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h, src/python-bindings/htcondor2/submit.cpp, src/python-bindings/schedd.cpp
and new TABLE(<opts>) keyword
Refactor condor_submit and v1 python bindings to more similar for for job submission
add prototype funciton to dagman_submit with similar flow and support for late-mat
=> HTCONDOR-2548 Milestone 1 - add ITERATE as replacement for QUEUE

src/condor_dagman/dagman_submit.cpp, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
=> HTCONDOR-2523 fix warnings

build/cmake/CondorConfigure.cmake, nmi_tools/glue/build/remote_task.pl, src/condor_schedd.V6/CMakeLists.txt, src/condor_utils/CMakeLists.txt
=> HTCONDOR-2581 Enable compiler warnings-are-errors on Fedorae

bindings/python/htcondor2/_schedd.py, bindings/python/htcondor2/_submit.py, docs/version-history/feature-versions-23-x.rst, src/python-bindings/htcondor2/schedd.cpp, src/python-bindings/htcondor2/submit.cpp, src/python-bindings/htcondor2_impl.cpp
Mostly discovered by CRAB.
* Implement `Schedd.RefreshGSIProxy()`.
* Fix bug in `Schedd.edit()` caused by some `ExprTree`s having string representations which we can't parse.
* Rewrite `Submit.from_dag()`'s docstring not to be a blatant lie.
* Don't iterate over an empty `Submit` object.
=> (HTCONDOR-2577)  Fixes for htcondor2/classad2.

src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_daemon_core.V6/self_draining_queue.h, src/condor_daemon_core.V6/timer_manager.cpp, src/condor_includes/condor_sockfunc.h, src/condor_startd.V6/Resource.cpp, src/condor_starter.V6.1/StarterHookMgr.cpp, src/condor_starter.V6.1/docker_proc.cpp, src/condor_starter.V6.1/java_proc.cpp, src/condor_starter.V6.1/jic_local.cpp, src/condor_starter.V6.1/jic_local_schedd.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/job_info_communicator.cpp, src/condor_starter.V6.1/os_proc.cpp, src/condor_starter.V6.1/remote_proc.cpp, src/condor_starter.V6.1/script_proc.cpp, src/condor_starter.V6.1/sshd_proc.cpp, src/condor_starter.V6.1/starter_v61_main.cpp, src/condor_starter.V6.1/stream_handler.cpp, src/condor_starter.V6.1/tool_daemon_proc.cpp, src/condor_starter.V6.1/user_proc.cpp, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_starter.V6.1/vm_proc.cpp, src/condor_utils/ClassAdLogParser.cpp, src/condor_utils/classad_log.cpp, src/condor_utils/condor_sockaddr.cpp, src/condor_utils/condor_sockfunc.cpp, src/condor_utils/job_ad_instance_recording.cpp, src/condor_utils/log_rotate.cpp, src/condor_utils/write_user_log.cpp
This is enough to allow me to build with a 16-way unity build configuration.
=> HTCONDOR-2523  more unity build cleanups

docs/version-history/lts-versions-23-0.rst, src/condor_tests/job_late_materialize.run, src/condor_utils/spooled_job_files.cpp
=> HTCONDOR-2113 Fix .digest and .items left behind in spool

README.md
=> HTCONDOR-2523 bump link in README.md from htc 22 to htc 24.

src/classad/lexer.cpp
=> HTCONDOR-2523 don't strcasecmp to identify string constants in

src/classad/lexer.cpp
=> HTCONDOR-2523 fix typo in previous commit

docs/version-history/feature-versions-23-x.rst, src/condor_utils/proc_family_direct_cgroup_v1.cpp, src/condor_utils/proc_family_direct_cgroup_v1.h, src/condor_utils/proc_family_direct_cgroup_v2.cpp, src/condor_utils/proc_family_direct_cgroup_v2.h
=> HTCONDOR-2590 pid namespaces and cgroup

docs/version-history/feature-versions-23-x.rst, src/condor_utils/docker-api.cpp, src/condor_utils/nvidia_utils.cpp, src/condor_utils/nvidia_utils.h
when the AssignedGPUs has the "stable" name as well as the CUDA name
=> HTCONDOR-2591 docker universe jobs with GPUs should pass --device

docs/version-history/lts-versions-23-0.rst
=> HTCONDOR-2519: Add EL9 cgroup v2 known issue

src/classad/classad/jsonSource.h, src/classad/classad/lexer.h, src/classad/classad/source.h, src/classad/lexer.cpp
=> HTCONDOR-2523 Remove dead code in the classad lexer

src/condor_utils/MapFile.cpp, src/condor_utils/dagman_utils.cpp
=> HTCONDOR-2523 remove redundant calls to c_str()

docs/version-history/feature-versions-23-x.rst, src/condor_daemon_client/dc_collector.cpp, src/condor_daemon_client/dc_collector.h
In `DCCollector::sendTCPUpdate()`, if an update fails, the socket is destroyed and the connection immediately rebuilt; this PR forces the address of the collector to be resolved again when this happens.
Also resolve the collector's address again if the update failed for some reason that did not result in the destruction of the socket (e.g., the socket wasn't created because the connection failed).  This will result in an additional look-ups, but I don't think there's anything we can do about that.
=> (HTCONDOR-2579)  Re-`locate()` the collector on a lost connection.

docs/users-manual/submitting-a-job.rst
=> HTCONDOR-2593 Remove example of multiple queue statements in docs

docs/users-manual/env-of-job.rst, docs/version-history/feature-versions-23-x.rst, src/condor_utils/param_info.in, src/condor_utils/submit_utils.cpp
=> HTCONDOR-2595 container uni xfer defaults

src/condor_dagman/dag.h
We needed this with our old, internal-iterator based containers Now that we have external iteration, we don't need this to be mutable, so remove the evidence.
=> HTCONDOR-2523 remove "mutable" from dagman

src/condor_tests/test_dagman_script_macros.py
=> HTCONDOR-2523: Increase test_dagman_script_macros timeout

docs/version-history/feature-versions-23-x.rst, src/condor_tests/CMakeLists.txt, src/condor_tests/test_plugins_dont_see_directories.py, src/condor_utils/file_transfer.cpp
=> (HTCONDOR-2594)  Don't try to transfer directories to URLs.

src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-2598 schedd-user-recs

build/packaging/debian/condor-upgrade-checks.install, build/packaging/debian/condor.install, build/packaging/debian/control.in, build/packaging/rpm/condor.spec
=> HTCONDOR-2523: Fold condor_upgrade_checks into main package

src/condor_tools/transform_ads.cpp
when processing -rules "config://..."
=> HTCONDOR-2596 fix for segfault in condor_transform_ads

docs/version-history/feature-versions-23-x.rst, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/jic_shadow.h, src/condor_tests/CMakeLists.txt, src/condor_tests/test_unspecified_checkpoint.py
The starter just doesn't set the exclusion lists.
=> (HTCONDOR-2566)  Exclude starter-generated files from checkpoint transfer.

src/condor_schedd.V6/dedicated_scheduler.cpp, src/condor_schedd.V6/dedicated_scheduler.h
=> HTCONDOR-2523 dedicated-schedd-tables

build/packaging/debian/control.in, docs/version-history/lts-versions-23-0.rst
=> HTCONDOR-2600: Ubuntu24 now depends on libssl3

docs/version-history/lts-versions-23-0.rst, src/condor_daemon_core.V6/daemon_core.cpp
=> HTCONDOR-2599 fix Create_Process on windows to return errors

docs/version-history/feature-versions-23-x.rst, src/condor_tools/user_prio.cpp
=> HTCONDOR-2603 show floor in userprio

docs/version-history/feature-versions-23-x.rst, src/condor_scripts/condor_watch_q.in
=> HTCONDOR-2602: defer DAGMan log tracking for watch q if DNE at execution time

build/packaging/debian/condor-upgrade-checks.install, build/packaging/debian/condor.install.in, build/packaging/debian/control.in, build/packaging/rpm/condor.spec
=> HTCONDOR-2523: Restore condor-upgrade-checks package

docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-23-x.rst, src/condor_utils/param_info.in
=> HTCONDOR-2606: turn on epoch history by default

docs/version-history/feature-versions-23-x.rst, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2521: Update version history for CGROUP_IGNORE_CACHE

src/condor_scripts/condor_diagnostics
A last-minute bugfix and some code cleanup in the condor_diagnostics script.
=> HTCONDOR-2604: Finalize condor_diagnostics

src/condor_utils/param_info.in
but left the param knob in.  Remove it now
=> HTCONDOR-2523 We remove the BIOTECH code ten years ago,

src/condor_utils/classad_log.cpp, src/condor_utils/compat_classad.h, src/condor_utils/file_transfer.cpp
=> HTCONDOR-2523 Remove use of fixed length classad lookup strings from

docs/admin-manual/configuration-macros.rst, docs/admin-manual/ep-policy-configuration.rst, docs/version-history/feature-versions-23-x.rst, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_utils/param_info.in
=> HTCONDOR-2525: Use PID namespaces by default

src/condor_collector.V6/collector_engine.cpp, src/condor_dagman/dag.cpp, src/condor_dagman/dagman_classad.cpp, src/condor_dagman/dagman_classad.h, src/condor_gridmanager/basejob.cpp, src/condor_gridmanager/baseresource.cpp, src/condor_gridmanager/condorjob.cpp, src/condor_gridmanager/gridmanager_main.cpp, src/condor_gridmanager/infnbatchjob.cpp, src/condor_includes/condor_email.h, src/condor_job_router/submit_job.cpp, src/condor_procapi/procapi.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_status.V6/totals.cpp, src/condor_unit_tests/OTEST_Old_Classads.cpp, src/condor_utils/condor_event.cpp, src/condor_utils/email_cpp.cpp, src/condor_utils/proc_family_direct_cgroup_v1.cpp, src/python-bindings/classad2/classad.cpp, src/python-bindings/htcondor2/schedd.cpp, src/python-bindings/htcondor2/submit.cpp
=> HTCONDOR-2610 coverity fixes

src/condor_dagman/dagman_submit.cpp, src/condor_submit.V6/submit.cpp, src/condor_utils/submit_protocol.cpp, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h, src/python-bindings/schedd.cpp
and honoring table_opts for whitespace and separator char. 
Also fix some issues with ordering of setting livevars into the SubmitHash for late mat submits.
=> HTCONDOR-2548 submit SubmitForeachArss::split_item using string_view

docs/version-history/lts-versions-23-0.rst, src/condor_utils/proc_family_direct_cgroup_v1.cpp, src/condor_utils/proc_family_direct_cgroup_v1.h
=> HTCONDOR-2572: Revert Create cgroup in parent before fork (in 23.0 LTS)

build/packaging/debian/control.in, build/packaging/rpm/condor.spec, src/condor_examples/00-execution-point, src/condor_examples/CMakeLists.txt
=> HTCONDOR-2267: Add EP packages

docs/man-pages/htcondor.rst, docs/version-history/feature-versions-23-x.rst, src/condor_tests/test_htcondor_cli_sys_status.py, src/condor_tools/htcondor_cli/__init__.py, src/condor_tools/htcondor_cli/server.py
=> HTCONDOR-2580: Rename htcondor system noun to server

src/classad/classad/flat_set.h, src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_io/condor_auth_passwd.cpp, src/condor_job_router/JobRouter.cpp, src/condor_master.V6/masterDaemon.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_startd.V6/ResAttributes.cpp, src/condor_status.V6/status.cpp, src/condor_submit.V6/submit_help.cpp, src/condor_utils/compat_classad_util.cpp, src/condor_utils/generic_stats.cpp, src/condor_utils/print_format_tables.cpp, src/condor_utils/proc_family_direct_cgroup_v2.cpp, src/condor_utils/store_cred.cpp, src/condor_utils/submit_utils.cpp
=> HTCONDOR-2610 const auto ref

bindings/python/htcondor2/_submit.py, docs/version-history/lts-versions-24-0.rst, src/python-bindings/htcondor2/submit.cpp
=> Fix some bindings v2 bugs

src/condor_collector.V6/collector.cpp, src/condor_dagman/dagman_main.cpp, src/condor_ft-gahp/io_loop.cpp, src/condor_io/condor_ipverify.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_startd.V6/vmuniverse_mgr.cpp, src/condor_starter.V6.1/starter.cpp, src/condor_utils/condor_event.cpp, src/condor_utils/dagman_utils.cpp, src/condor_utils/dprintf.cpp, src/condor_utils/file_transfer.cpp, src/gangliad/gangliad.cpp, src/python-bindings/htcondor2/credd.cpp
=> HTCONDOR-2610 misc coverity fixes

src/condor_collector.V6/offline_plugin.cpp, src/condor_collector.V6/view_server.cpp, src/condor_collector.V6/view_server.h, src/condor_daemon_client/dc_transfer_queue.cpp, src/condor_dagman/dag.cpp, src/condor_dagman/debug.cpp, src/condor_gridmanager/condorjob.cpp, src/condor_job_router/submit_job.cpp, src/condor_negotiator.V6/matchmaker.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_shadow.V6.1/baseshadow.cpp, src/condor_shadow.V6.1/baseshadow.h, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_shadow.V6.1/shadow.cpp, src/condor_startd.V6/ResState.cpp, src/condor_startd.V6/claim.cpp, src/condor_startd.V6/claim.h, src/condor_status.V6/prettyPrint.cpp, src/condor_tools/give_interactive.cpp, src/condor_tools/user_prio.cpp, src/condor_utils/classad_helpers.cpp, src/condor_utils/credmon_interface.cpp, src/condor_utils/directory.cpp, src/condor_utils/file_transfer.cpp, src/condor_utils/format_time.cpp, src/condor_utils/format_time.h, src/condor_who/who.cpp
=> HTCONDOR-2610 Fix Y2038 bugs by providing 64 bit clean path for time_t's

bindings/python/htcondor/_utils/ansi.py, src/condor_scripts/condor_watch_q.in
=> HTCONDOR-2580: Fix condor_watch_q import & spell capable correctly

bindings/python/htcondor2/_schedd.py, docs/version-history/lts-versions-24-0.rst
TJ pointed out that I'd missed a check in this function.
=> Filter newlines from itemdata values, as well.

docs/version-history/feature-versions-23-x.rst, src/condor_starter.V6.1/singularity.cpp
=> HTCONDOR-2620 apptainer tmpdir branch

src/condor_dagman/dagman_submit.cpp, src/condor_submit.V6/submit.cpp, src/condor_submit.V6/submit_internal.h, src/condor_submit.V6/submit_simulate.cpp, src/condor_tests/test_lm_more.py, src/condor_utils/submit_protocol.cpp, src/condor_utils/submit_protocol.h, src/python-bindings/htcondor2/schedd.cpp, src/python-bindings/htcondor2/submit.cpp, src/python-bindings/schedd.cpp
=> HTCONDOR-2619 Refactor v2 python bindings to use SubmitStepFromQArgs

docs/man-pages/condor_submit.rst
=> HTCONODR-2624 Remove confusing working about vm universe request_memory

src/condor_tests/test_activation_metrics.py, src/condor_tests/test_checkpoint_ct.py
=> HTCONDOR-2617 flaky-tests

src/condor_utils/condor_netaddr.cpp
=> HTCONDOR-2610 Fix overflow in ipv6 code

src/condor_utils/condor_ver_info.cpp, src/condor_utils/config.cpp
=> HTCONDOR-2610 condor_ver_info should treat empty string the same as null

src/condor_schedd.V6/qmgmt.cpp
Don't look in the transaction log, as this check is only for previously- submitted jobs.
=> HTCONDOR-2628 Optimize dirty attribute check in SetAttribute()

docs/version-history/lts-versions-24-0.rst, src/condor_scripts/condor_watch_q.in
=> HTCONDOR-2625: Fix condor_watch_q None batch name bug

src/condor_tools/htcondor_cli/server.py
=> HTCONDOR-2610 Fix python warning re: \d not \\d in regexp

src/condor_collector.V6/collector_engine.cpp, src/condor_gridmanager/baseresource.cpp, src/condor_gridmanager/condorjob.cpp, src/condor_gridmanager/condorjob.h, src/condor_gridmanager/infnbatchjob.cpp, src/condor_schedd.V6/transfer_queue.cpp
=> HTCONDOR-2610 fix 32 bit time_t problems

src/condor_starter.V6.1/starter_v61_main.cpp
=> HTCONDOR-2558: Add check for cryptsetup for LVM encryption as safegaurd

src/condor_utils/file_transfer_stats.cpp
=> HTCONDOR-2610 Fix memory leak in file xfer stats

src/condor_gridmanager/baseresource.cpp, src/condor_gridmanager/condorjob.cpp, src/condor_job_router/JobRouter.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/transfer_queue.cpp, src/condor_shadow.V6.1/shadow.cpp, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Starter.cpp
=> HTCONDOR-2610 time t

docs/version-history/lts-versions-24-0.rst, src/blahp/src/scripts/sge_submit.sh
=> HTCONDOR-2630 file-leak

src/condor_daemon_core.V6/HookClientMgr.cpp, src/condor_master.V6/master.cpp, src/condor_schedd.V6/dedicated_scheduler.cpp, src/python-bindings/classad2/classad.cpp
=> HTCONDOR-2610coverity memory leaks

docs/version-history/feature-versions-23-x.rst, src/condor_utils/proc_family_direct_cgroup_v2.cpp, src/condor_utils/proc_family_direct_cgroup_v2.h
=> HTCONDOR-2639 reused cgroup cpu usage fix

docs/version-history/lts-versions-24-0.rst, src/condor_includes/condor_qmgr.h, src/condor_schedd.V6/qmgmt.cpp, src/condor_submit.V6/submit.cpp
=> HTCONDOR-2638 submit failure msg

src/condor_startd.V6/Starter.cpp, src/condor_starter.V6.1/starter.cpp
=> HTCONDOR-2610 uninitialized pointers

src/classad/classad/value.h, src/condor_includes/condor_crypt_aesgcm.h, src/condor_io/condor_crypt_aesgcm.cpp, src/condor_utils/env.h, src/condor_utils/proc_family_direct_cgroup_v1.cpp
=> HTCONDOR-2609 except is not assert

docs/version-history/feature-versions-23-x.rst, src/condor_startd.V6/VolumeManager.h, src/condor_starter.V6.1/starter.cpp
=> HTCONDOR-2635: Fix LVM job sandbox permissions

src/condor_utils/proc_family_direct_cgroup_v1.cpp, src/condor_utils/proc_family_direct_cgroup_v1.h, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2640 allow cgroup v1 cpu tracking to work in the face of a

docs/classad-attributes/job-classad-attributes.rst
=> HTCONDOR-2624 Clarify docs around Durations that are per-launch

src/condor_io/sock.cpp
=> HTCONDOR-2610 always initialize crypto key

docs/version-history/lts-versions-24-0.rst, src/condor_startd.V6/VolumeManager.cpp, src/condor_utils/param_info.in
=> HTCONDOR-2641: Default thick provisioning for LVM

build/packaging/debian/control.in, build/packaging/rpm/condor.spec
=> HTCONDOR-2642: Break condor-upgrade-checks circular dependency

docs/getting-htcondor/from-our-repositories.rst
=> Add Ubuntu 24 and LTS releases.

src/condor_tools/history.cpp, src/condor_utils/submit_utils.cpp
And other places, as found by address sanitizer
=> HTCONDOR-2610 Fix memory leak in condor_history

src/condor_negotiator.V6/matchmaker.cpp, src/condor_tools/qusers.cpp
=> HTCONDOR-2610 memory leaks

src/condor_utils/proc_family_direct_cgroup_v1.cpp, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2647 no peak cgroup memory

src/condor_dagman/node.cpp, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h, src/condor_starter.V6.1/user_proc.h, src/gangliad/statsd.cpp
=> HTCONDR-2610 nitialize members

src/condor_scripts/condor_upgrade_check
=> HTCONDOR-2610: Update next major version for condor_upgrade_check

docs/version-history/feature-versions-23-x.rst, src/condor_utils/proc_family_direct_cgroup_v1.cpp, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2647 no cgroup peak

src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2651 After cgroup kills the processes in a job, poll until they

src/condor_utils/file_transfer.cpp
=> HTCONDOR-2610 log stderr for plugin -classad output

src/condor_collector.V6/view_server.cpp, src/condor_collector.V6/view_server.h, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/condor_timer_manager.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_daemon_core.V6/timer_manager.cpp, src/condor_gridmanager/condorjob.cpp, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h
=> HTCONDOR-2610 more 32 bit time t

docs/man-pages/condor_gpu_discovery.rst, docs/version-history/lts-versions-24-0.rst, src/gpu/condor_gpu_discovery.cpp
Also allow both -cuda and -hip options to be used at the same time to
mean that just Cuda and HIP detection (but not OpenCL) is desired.
=> HTCONDOR-2509 Document the new -hip option to condor_gpu_discovery.

src/condor_collector.V6/view_server.cpp, src/condor_collector.V6/view_server.h, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/Resource.cpp
=> HTCONDOR-2160 fixup time_t's

src/condor_dagman/dag.cpp, src/condor_dagman/dag.h, src/condor_dagman/dagman_classad.cpp, src/condor_dagman/dagman_main.cpp, src/condor_dagman/dagman_main.h, src/condor_dagman/dagman_metrics.cpp, src/condor_dagman/dagman_metrics.h, src/condor_dagman/dagman_submit.cpp, src/condor_dagman/parse.cpp
=> HTCONDOR-2652: improve dag man config value handling

src/condor_collector.V6/view_server.cpp, src/condor_io/condor_secman.cpp, src/condor_io/sock.cpp, src/condor_tools/wait.cpp, src/condor_utils/read_user_log.cpp
=> HTCONDOR-2610 quell loop once warning

src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_utils/proc_family_direct.h, src/condor_utils/proc_family_direct_cgroup_v1.cpp, src/condor_utils/proc_family_direct_cgroup_v1.h, src/condor_utils/proc_family_direct_cgroup_v2.cpp, src/condor_utils/proc_family_direct_cgroup_v2.h, src/condor_utils/proc_family_interface.h, src/condor_utils/proc_family_proxy.cpp, src/condor_utils/proc_family_proxy.h
=> HTCONDOR-2655 backport cgroup escape fixes to 23.0

src/classad/classad.cpp, src/classad/classad/classad.h, src/classad/test_classad_parse.cpp
=> HTCONDOR-2610 remove old classad ifdefs

src/condor_dagman/dag.cpp, src/condor_dagman/jobstate_log.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_startd.V6/Resource.h, src/ec2_gahp/amazonCommands.cpp
=> HTCONDOR-2610 coverity cleanups

docs/admin-manual/configuration-macros.rst, docs/admin-manual/introduction-to-configuration.rst
=> Improve GPU_DISCOVERY_EXTRA docs.

docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-24-x.rst, src/condor_starter.V6.1/docker_proc.cpp, src/condor_starter.V6.1/docker_proc.h, src/condor_utils/docker-api.cpp, src/condor_utils/docker-api.h
=> HTCONDOR-2661 docker check arch

src/condor_shadow.V6.1/baseshadow.cpp
Memory corruption can occur if it does.
=> HTCONDOR-2610 BaseShadow::reconnectFailed() shouldn't return

src/condor_collector.V6/ce-audit-plugin.cpp, src/condor_collector.V6/collector_engine.cpp, src/condor_utils/param_info.in
=> HTCONDOR-2610 return values

src/condor_startd.V6/Resource.cpp, src/condor_utils/expr_analyze.cpp
=> HTCONDOR-2610 add needed const'ness

docs/version-history/lts-versions-24-0.rst, src/gpu/condor_gpu_discovery.cpp
[<(https://opensciencegrid.atlassian.net/browse/HTCONDOR-2669)>](https://opensciencegrid.atlassian.net/browse/HTCONDOR-2669)
=> HTCONDOR-2669 fix -divide option to condor_gpu_discovery

docs/version-history/lts-versions-24-0.rst, src/condor_tests/test_htcondor_cli_sys_status.py, src/condor_tools/htcondor_cli/server.py
=> HTCONDOR-2667: fix htcondor server status bug

src/condor_scripts/condor_upgrade_check
=> HTCONDOR-2665: v23 to v24 upgrade checks

src/condor_tests/test_dagman_check_q_and_exit.py
=> HTCONDOR-2675: Improve flaky DAGMan test (test_dagman_check_q_and_exit)

docs/classad-attributes/job-classad-attributes.rst, docs/version-history/feature-versions-24-x.rst, src/condor_includes/condor_attributes.h, src/condor_schedd.V6/schedd.cpp, src/condor_tests/cmd_q_protocols.run
=> HTCONDOR-2676 add FirstJobMatchDate job attribute

src/condor_utils/ipv6_interface.cpp
=> HTCONDOR-2664 fix interface loop

src/condor_utils/docker-api.cpp
thrown
No more "failed to inspect container" errors
=> HTCONDOR-2679 Put docker jobs on hold appropriate when multi-line errors

src/gangliad/statsd.cpp
=> HTCONDOR-2675 always check return from ftell

docs/admin-manual/configuration-macros.rst, docs/version-history/lts-versions-23-0.rst
=> HTCONDOR-2675 cleanup doc warnings

src/condor_negotiator.V6/matchmaker.cpp
=> HTCONDOR-2675 fixup classad list shuffle bug

src/condor_release/examples/recipes/hostname.sub
=> HTCONDOR-2646 Add example recipe for htcondor job template

bindings/python/htcondor2/_submit.py, docs/version-history/lts-versions-24-0.rst, src/condor_tests/CMakeLists.txt, src/condor_tests/test_submit_itemdata_qargs.py
This PR does three closely-related things:
* Implements `htcondor2.Submit.itemdata(qargs=qargs)`.
* Converts an index out of bounds exception to an explicit ValueError if you pass a multi-line `qargs` with a trailing newline not immediately preceded by a close parenthesis.
* Change the documentation on `htcondor2.Submit.setQArgs()` to match the function name.  I may change this back later, but ofr now I'm not liking the inconsistency, even if `setQArgs()` allows for queue statements (as being less confusing then rejecting them for new users).
=> (HTCONDOR-2618)  Implement missing `qargs` parameter for `htcondor2.Submit.itemdata()`.

src/condor_includes/condor_accountant.h, src/condor_includes/condor_auth_kerberos.h, src/condor_schedd.V6/grid_universe.cpp, src/condor_schedd.V6/grid_universe.h
=> HTCONDOR-2672 de-hashtable the grid universe

src/condor_startd.V6/ResAttributes.cpp
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2684
Note: No version history or documentation needed, as that was handled in HTCONDOR-2678
While it is unlikely to matter matter for GPU management, it is possible that some sites may assume that the order in which non-fungible resources are defined in the config file is the order in which that are assigned to slots (since was true HTCSS 23.0). To restore the validity of this assumption, the data structure in the startd needs to change from a std:multiset  to std::vector (which can preserve the order elements are added).
- Assign …
=> HTCONDOR-2684 Preserve non-fungible resource ordering in the startd.

docs/version-history/lts-versions-24-0.rst, src/condor_io/condor_secman.cpp
=> HTCONDOR-2685 family session rejection

docs/admin-manual/configuration-macros.rst, docs/version-history/lts-versions-24-0.rst, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_starter.V6.1/vanilla_proc.h, src/condor_utils/param_info.in
=> HTCONDOR-2686 Add STARTER_ALWAYS_HOLD_ON_OOM knob

bindings/python/CMakeLists.txt, bindings/python/htcondor2/_utils/ansi.py, src/condor_tests/test_job_submit_method_recording.py, src/condor_tools/htcondor_cli/annex.py, src/condor_tools/htcondor_cli/annex_create.py, src/condor_tools/htcondor_cli/dagman.py, src/condor_tools/htcondor_cli/eventlog.py, src/condor_tools/htcondor_cli/job.py, src/condor_tools/htcondor_cli/job_set.py
=> (HTCONDOR-2623)  Switch `htcondor` CLI (and utilities) to use version 2 bindings

src/condor_schedd.V6/schedd_main.cpp
=> HTCONDOR-2672 remove dead code

src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_tools/tool.cpp, src/condor_utils/condor_event.cpp
=> HTCONDOR-2675 Fix some minor bugs found by Coverity

docs/version-history/lts-versions-23-0.rst, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_utils/proc_family_interface.h
=> HTCONDOR-2697: Backport cgroup v2 interactive fix

src/condor_utils/file_transfer.cpp
=> HTCONDOR-2672 Fix 64 bit time_t in dataflow

src/condor_includes/condor_cron_job_params.h, src/condor_utils/cron_job_params.cpp
=> HTCONDOR-2672 fix conversion warning

docs/version-history/lts-versions-23-0.rst
=> HTCONDOR-2665: Version history for classad unit specifier check

docs/version-history/feature-versions-24-x.rst, src/condor_starter.V6.1/os_proc.cpp, src/condor_tools/nsenter.cpp
=> HTCONDOR-2695  ssh to job supplemental groups

src/defrag/defrag.cpp
=> HTCONDOR-2672 Make defrag daemon 64 bit time_t clean

docs/admin-manual/configuration-macros.rst, docs/automated-workflows/dagman-information-files.rst, docs/version-history/feature-versions-24-x.rst, src/condor_dagman/dag.cpp, src/condor_dagman/dag.h, src/condor_dagman/dagman_classad.cpp, src/condor_dagman/dagman_classad.h, src/condor_dagman/dagman_main.cpp, src/condor_dagman/dagman_main.h, src/condor_dagman/dagman_metrics.cpp, src/condor_dagman/dagman_metrics.h
=> HTCONDOR-2682: dagman metrics v2 branch

src/condor_utils/user_job_policy.cpp
=> HTCONDOR-2672 make allowed_execution_duration 64 bit time_t clean

src/condor_c-gahp/schedd_client.cpp, src/condor_gridmanager/arcjob.cpp, src/condor_gridmanager/azurejob.cpp, src/condor_gridmanager/basejob.cpp, src/condor_gridmanager/baseresource.cpp, src/condor_gridmanager/condorjob.cpp, src/condor_gridmanager/ec2job.cpp, src/condor_gridmanager/gcejob.cpp, src/condor_gridmanager/gridmanager.cpp, src/condor_gridmanager/infnbatchjob.cpp, src/condor_includes/stream.h, src/condor_io/stream.cpp, src/condor_schedd.V6/qmgmt_send_stubs.cpp
=> HTCONDOR-2672 grid-time

build/packaging/debian/condor.install.in, build/packaging/rpm/condor.spec, docs/conf.py, docs/man-pages/index.rst, src/condor_tools/CMakeLists.txt
=> HTCONDOR-2700 Remove condor_stats

docs/_static/css/htcondor-manual.css, docs/_static/js/tool-mindmap.js, docs/_templates/layout.html, docs/full_conf.py, docs/man-pages/index.rst
=> HTCONDOR-2699: Defer loading of mindmap tool reference clickability

src/condor_gridmanager/condorjob.cpp, src/condor_tools/nsenter.cpp, src/condor_userlog/userlog.cpp, src/condor_utils/dprintf.cpp, src/condor_utils/format_time.cpp, src/condor_utils/format_time.h
=> HTCONDOR-2672 minor time t

src/condor_examples/00-security, src/condor_utils/param_info.in
=> HTCONDOR-2701 security default

docs/admin-manual/configuration-macros.rst, docs/admin-manual/introduction-to-configuration.rst, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/command.cpp, src/condor_startd.V6/startd.h, src/condor_startd.V6/startd_main.cpp, src/condor_sysapi/last_x_event.cpp, src/condor_sysapi/sysapi.h
and non-condor LoadAvg.
- SLOTS_CONNECTED_TO_* knobs now use SlotId to determine connectedness, so if a p-slot is connected, all d-slots will be also.
- Non-condor LoadAvg is now distributed to pslots and static slots by SlotId in 3 passes
- slots in Owner state
- slots in Unclaimed state (p-slots are normally unclaimed)
- slots in all other states where d-slots get the minimum of the p-slot load and their TotalSlotCpus value. This change prevents the load from moving around the d-slots as they come and go.
- Assign …
=> HTCONDOR-2689 New EP strategy for KeyboardIdle, ConsoleIdle

src/classad/classad/lexer.h, src/classad/classad/literals.h
casts.
These aren't real problems, but as they are in headers, they generate thousands of noisy warnings.
=> HTCONDOR-2672 Fix warnings of narrowing conversions with explicit

src/condor_startd.V6/ResMgr.cpp
=> HTCONDOR-2689 fixup unused variable warning

src/condor_tests/CMakeLists.txt
=> HTCONDOR-2704 fixup windows cmake warnings about building tests

src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h, src/condor_userlog/userlog.cpp, src/condor_utils/format_time.cpp, src/condor_utils/format_time.h
=> HTCONDOR-2672 coverity found time t

docs/version-history/lts-versions-24-0.rst
=> HTCONDOR-2644 Docs for timeout in querying libvirtd

docs/version-history/lts-versions-24-0.rst
=> HTCONDOR-2701 Docs for new security config working with older binaries

docs/version-history/lts-versions-24-0.rst
=> HTCONDOR-2679 docs branch

docs/version-history/lts-versions-24-0.rst
=> HTCONDOR-2647 docs

src/condor_startd.V6/startd_main.cpp
=> HTCONDOR-2675 do not reset lv_name_uniqueness on reconfig

docs/STYLE.md, docs/admin-manual/ep-policy-configuration.rst, docs/conf.py, docs/full_conf.py, docs/requirements.txt
=> HTCONDOR-2705: integrate sphinx tabs directive

src/condor_shadow.V6.1/shadow_v61_main.cpp, src/condor_starter.V6.1/starter_v61_main.cpp, src/condor_utils/submit_utils.cpp
and only works with removed MPI universe
=> HTCONDOR-2706 Don't advertise Has MPI, it confuses users

docs/classad-attributes/machine-classad-attributes.rst
=> HTCONDOR-2707 clear up docs around CpuModelNumber

docs/man-pages/index.rst
=> HTCONDOR-2672 condor_q and condor_qedit went to the same place in the

src/condor_startd.V6/ResState.cpp, src/condor_startd.V6/ResState.h, src/condor_utils/my_popen.cpp, src/condor_utils/my_popen.h, src/condor_who/who.cpp
=> HTCONDOR-2672 Fixup more 32 bit time math

build/docker/services/build-images
Docker now enforces that you specify the platform if is does not match the CPU architecture.
=> HTCONDOR-2612: Be able to build arm64 images on dumbo

src/condor_tests/shadow_mem_usage-basic.run
=> HTCONDOR-2711 Add Fedora 41 to shadow mem test

src/condor_userlog/userlog.cpp
=> HTCONDOR-2672  time t userlog

docs/auto-redirect.html
=> HTCONDOR-2672: Extract url root from page url to form auto redirect urls

src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-2675 Remove spurious D_BACKTRACE

docs/version-history/feature-versions-24-x.rst, src/condor_daemon_client/daemon_list.cpp, src/condor_daemon_client/daemon_list.h, src/condor_daemon_client/dc_collector.cpp, src/condor_daemon_client/dc_collector.h, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-2709 invalidate-on-shutdown

docs/getting-htcondor/from-our-repositories.rst, docs/getting-htcondor/index.rst, docs/version-history/introduction-version-history.rst
=> HTCONDOR-2611: Update Docs for 24.0

docs/man-pages/condor_submit.rst, docs/version-history/feature-versions-24-x.rst, src/condor_includes/condor_attributes.h, src/condor_includes/condor_uid.h, src/condor_shadow.V6.1/baseshadow.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_utils/condor_holdcodes.h, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h, src/condor_utils/uids.cpp
=> HTCONDOR-2702 primary gid swapping

docs/getting-htcondor/index.rst, docs/version-history/introduction-version-history.rst
=> HTCONDOR-2611: Update support macOS 13 and later

docs/man-pages/condor_submit.rst
=> HTCONDOR-2672 Fixup glaring errors in condor_submit man page

docs/getting-htcondor/from-our-repositories.rst, docs/getting-htcondor/index.rst, docs/version-history/introduction-version-history.rst
=> Update Docs for 24.x

src/condor_dagman/dagman_main.cpp
=> HTCONDOR-2714: DAGMan set batch name when ran manually

src/condor_utils/my_popen.cpp
=> HTCONDOR-2710: Report correct units in debug log

docs/man-pages/condor_continue.rst, docs/man-pages/man-page.template
=> HTCONDOR-2719: Update condor_continue man page

docs/man-pages/condor_continue.rst, docs/man-pages/man-page.template
=> HTCONDOR-2719: small changes to condor continue man page

src/condor_gridmanager/baseresource.cpp, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_tools/user_prio.cpp, src/condor_utils/dprintf.cpp
=> HTCONDOR-2672 Fix 64 bit time_t in the gridmanager, shadow and user_prio

src/ccb/ccb_client.cpp, src/ccb/ccb_listener.cpp, src/ccb/ccb_listener.h, src/condor_c-gahp/schedd_client.cpp
=> HTCONDOR-2672 64 bit time_t in ccb

docs/man-pages/condor_continue.rst, docs/man-pages/condor_suspend.rst, docs/man-pages/man-page.template
=> HTCONDOR-2722: update condor suspend man page

src/condor_tools/htcondor.c
=> HTCONDOR-2675 htcondor will crash if it cannot import htcondor_cli.cli

src/condor_tools/htcondor_cli/__init__.py
=> HTCONDOR-2675 annex noun can't load on windows, so don't try

src/condor_shadow.V6.1/remoteresource.cpp, src/condor_shadow.V6.1/remoteresource.h, src/condor_utils/my_popen.cpp
=> HTCONDOR-2723 Fixup 32 bit time in the shadow and my_popen

src/blahp/src/job_registry.c, src/condor_utils/condor_event.cpp
=> HTCONDOR-2723 fixup more 32 bit time calculations

src/condor_examples/00-minicondor
=> HTCONDOR-2670: Fix minicondor configuration

src/condor_utils/passwd_cache.unix.cpp, src/condor_utils/passwd_cache.unix.h
=> HTCONDOR-2723 Remove uncalled functions

docs/version-history/lts-versions-24-0.rst
=> HTCONDOR-2653 Docs for credmon signalling fix

build/cmake/CondorConfigure.cmake, externals/bundles/scitokens-cpp/1.1.2/CMakeLists.txt
=> HTCONDOR-2735 bump scitokens external to 1.1.2

build/packaging/debian/condor.install.in, build/packaging/rpm/condor.spec, docs/admin-manual/configuration-macros.rst, docs/version-history/feature-versions-24-x.rst, src/condor_starter.V6.1/CMakeLists.txt, src/condor_starter.V6.1/condor_container_launcher.sh, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/os_proc.cpp, src/condor_starter.V6.1/os_proc.h, src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/singularity.h, src/condor_utils/file_transfer.cpp, src/condor_utils/file_transfer.h, src/condor_utils/param_info.in
=> HTCONDOR-1446 singularity launcher wrapper

src/condor_includes/condor_accountant.h, src/condor_negotiator.V6/Accountant.cpp, src/condor_negotiator.V6/matchmaker.cpp, src/condor_negotiator.V6/matchmaker.h
=> HTCONDOR-2723 Fixup 32 bit time_t's in negotiator

docs/version-history/lts-versions-23-0.rst, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-2730 schedd-dollardollar-crash

src/condor_tools/history.cpp
=> HTCONDOR-2744 condor_history should create classad by value, not by

src/condor_had/ReplicatorStateMachine.cpp, src/condor_job_router/JobRouter.cpp
=> HTCONDOR-2723 fix 64 bit time_t warnings in the job router and had

src/classad/classad/classad_flat_map.h, src/condor_utils/classadHistory.cpp, src/condor_utils/compat_classad.cpp, src/condor_utils/compat_classad.h
optimally
Hard to measure schedd improvement, but improves condor_history by about 20%
=> HTCONDOR-2729 Speed up sched and condor_history by sorting history files

src/condor_scripts/condor_remote_cluster
If the passphrase file doesn't exist, assume the ssh key isn't encrypted.
=> HTCONDOR-1790 Allow passphrase-less ssh keys in condor_remote_cluster

bindings/python/htcondor2/_collector.py, docs/version-history/lts-versions-24-0.rst
=> HTCONDOR-2738 python-locate-collector

docs/admin-manual/configuration-macros.rst, docs/admin-manual/security.rst
IDTOKENS names don't go through the map file.
Remove the term 'unified'.
=> HTCONDOR-2724 Update authentication map file docs

docs/man-pages/condor_release.rst
=> HTCONDOR-2748: Update condor_release man page

docs/man-pages/condor_release.rst
=> HTCONDOR-2748: Document missing -reason flag

src/condor_master.V6/masterDaemon.cpp, src/condor_startd.V6/Starter.cpp, src/condor_starter.V6.1/jic_shadow.cpp
=> HTCONDOR-2723 64 bit clean time_t's

docs/version-history/lts-versions-24-0.rst, src/condor_scripts/annex/hpc.sh, src/condor_scripts/annex/path-facility.pilot, src/condor_scripts/annex/spark.sh
Reverts an untested change to the `htcondor annex`'s pilot configuration.
=> (HTCONDOR-2745)  Partial fix for the 24.0 branch.

src/condor_tools/htcondor_cli/annex_create.py, src/condor_utils/dc_coroutines.h
We try not to modify APIs in the stable series, so 23.0 requires a different fix.
=> (HTCONDOR-2745)  Fix `htcondor annex` for 23.0

src/condor_shadow.V6.1/baseshadow.cpp, src/condor_shadow.V6.1/baseshadow.h, src/condor_utils/condor_event.cpp, src/condor_utils/condor_event.h
Also label the vacate reason string and ensure all of the vacate reason information is read by the log reader.
=> HTCONDOR-2749 evict-event-code

docs/man-pages/condor_vacate_job.rst
=> HTCONDOR-2750: Update condor_vacate_job man page

docs/admin-manual/configuration-macros.rst, docs/admin-manual/introduction-to-configuration.rst, src/condor_kbdd/kbdd.cpp, src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/ResAttributes.h, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/command.cpp, src/condor_startd.V6/startd.h, src/condor_startd.V6/startd_main.cpp, src/condor_sysapi/idle_time.cpp, src/condor_sysapi/last_x_event.cpp, src/condor_sysapi/sysapi.h, src/condor_utils/param_info.in
=> HTCONDOR-2689: Fix initial values for KeyboardIdle and LoadAvg in new d-slots

src/condor_procd/local_server.UNIX.cpp, src/condor_procd/local_server.WINDOWS.cpp, src/condor_procd/local_server.h, src/condor_procd/named_pipe_reader.unix.cpp, src/condor_procd/named_pipe_reader.unix.h, src/condor_procd/proc_family_server.cpp, src/condor_startd.V6/ResAttributes.cpp, src/condor_tools/wait.cpp, src/condor_utils/file_modified_trigger.cpp, src/condor_utils/file_modified_trigger.h, src/condor_utils/wait_for_user_log.cpp, src/condor_utils/wait_for_user_log.h, src/condor_who/who.cpp
=> HTCONDOR-2723 more 64 bit clean time_t

src/condor_schedd.V6/schedd.cpp, src/condor_starter.V6.1/starter.cpp
=> HTCONDOR-2723 64 bit clean time in schedd

src/condor_tests/test_job_token_transfer.py
=> HTCONDOR-2757 Credd in test now binds to port 9621, not the default.

src/condor_daemon_core.V6/condor_timer_manager.h, src/condor_daemon_core.V6/timer_manager.cpp, src/condor_startd.V6/Resource.cpp, src/condor_utils/dc_coroutines.cpp, src/condor_utils/dc_coroutines.h
=> HTCONDOR-2723 fix 64 bit time_t in startd

src/condor_daemon_core.V6/condor_timer_manager.h, src/condor_daemon_core.V6/timer_manager.cpp
=> HTCONDOR-2744 Remove unused Register_Timer "release" callbacks

src/condor_daemon_client/daemon.cpp, src/condor_daemon_client/daemon.h, src/condor_daemon_client/dc_transfer_queue.cpp, src/condor_daemon_client/dc_transfer_queue.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_includes/buffers.h, src/condor_includes/reli_sock.h, src/condor_includes/sock.h, src/condor_includes/stream.h, src/condor_io/buffers.cpp, src/condor_io/condor_rw.cpp, src/condor_io/condor_rw.h, src/condor_io/reli_sock.cpp, src/condor_io/sock.cpp, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-2723 Make many epoch time quantities time_t's, not ints

src/condor_tests/ornithology-docs/source/conf.py
=> HTCONDOR-2727: Add style theme back to ornithology docs

docs/man-pages/condor_rm.rst, src/condor_rm.V6/rm.cpp
=> HTCONDOR-2759 update condor rm man page

src/condor_examples/00-minicondor
Need to back-port this fix into 23.x
=> HTCONDOR-2747: Fix minicondor CONDOR_HOST configuration

src/condor_startd.V6/ResAttributes.cpp
=> HTCONDOR-2723 64 bit clean time_t

docs/version-history/lts-versions-24-0.rst, src/condor_scripts/adstash/interfaces/elasticsearch.py, src/condor_scripts/adstash/interfaces/opensearch.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2614
=> HTCONDOR-2614 condor_adstash OpenSearch 2.x compatibility

src/condor_includes/condor_secman.h, src/condor_io/authentication.cpp, src/condor_io/condor_secman.cpp, src/condor_utils/file_transfer.cpp, src/python-bindings/schedd.cpp
=> HTCONDOR-2723 more 64 bit clear time_t

src/condor_c-gahp/schedd_client.cpp, src/condor_daemon_client/dc_transfer_queue.cpp, src/condor_includes/condor_qmgr.h, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/qmgmt_send_stubs.cpp, src/condor_schedd.V6/transfer_queue.cpp, src/condor_schedd.V6/transfer_queue.h, src/condor_utils/file_transfer.cpp, src/python-bindings/schedd.cpp
=> HTCONDOR-2723 make time 64 bit clean

src/condor_daemon_core.V6/condor_timer_manager.h, src/condor_daemon_core.V6/timer_manager.cpp
=> HTCONDOR-2691 refactor timer interface to only accept std::function args

src/condor_dagman/dag.cpp, src/condor_dagman/dag.h, src/condor_dagman/dagman_main.cpp, src/condor_dagman/dagman_main.h, src/condor_dagman/dagman_submit.cpp, src/condor_utils/dagman_utils.cpp, src/condor_utils/dagman_utils.h
=> HTCONDOR-2761: dagman utils message printing

build/packaging/rpm/condor.spec, docs/conf.py
=> HTCONDOR-2744 add condor_qusers to the list of man pages to generate

docs/version-history/lts-versions-24-0.rst
=> HTCONDOR-2647 Clarify docs

src/condor_startd.V6/Starter.cpp, src/condor_startd.V6/Starter.h, src/condor_startd.V6/claim.cpp
=> HTCONDOR-2723 fixup 64 bit times in the startd

docs/version-history/feature-versions-23-x.rst, src/condor_utils/dagman_utils.cpp, src/condor_utils/dagman_utils.h, src/python-bindings/htcondor2/submit.cpp, src/python-bindings/schedd.cpp
=> HTCONDOR-2736: python bindings from dag check setup options failure

docs/faq/DAGMan/bagman-exit-at-percent-done.rst
=> HTCONDOR-2744: Update DAGMan % done example to not query schedd

docs/version-history/lts-versions-23-0.rst, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/util.cpp
=> HTCONDOR-2760 Ignore blank execute directory values during cleanup

docs/grid-computing/job-router.rst
=> HTCONDOR-2747 Fix JobRouter route documentation for REQUIREMENTS command

src/condor_daemon_client/dc_transfer_queue.cpp, src/condor_daemon_client/dc_transfer_queue.h, src/condor_schedd.V6/transfer_queue.h
=> HTCONDOR-2723 make time 64 bit clean in dc_transfer_queue

src/condor_startd.V6/claim.cpp
Just in case init is slow with the reaping
=> HTCONDOR-2756 When checking for unkillable processes, loop and retry

docs/STYLE.md, docs/conf.py, docs/extensions/hidden.py, docs/full_conf.py, docs/man-pages/condor_dagman.rst
=> HTCONDOR-2773: create custom hidden sphinx directive

docs/apis/python-bindings/api/htcondor.rst, src/python-bindings/schedd.cpp
Correct mistake in spool() docstring and add example.
=> (HTCONDOR-2772)  Improve Schedd.spool() documentation for version 1.

docs/man-pages/condor_version.rst, src/condor_tools/version.cpp
=> HTCONDOR-2776: Update condor_version man page

src/condor_schedd.V6/schedd_stats.cpp, src/condor_utils/generic_stats.cpp
=> HTCONDOR-2723 Explicitly cast 64 bit time diffs to int

docs/faq/users/index.rst, docs/faq/users/transfer-files-on-rm.rst
=> HTCONDOR-2783 Document our hacky file transfer on rm options

docs/version-history/feature-versions-24-x.rst, src/condor_tests/test_dagman_produce_creds.py, src/condor_tests/test_htcondor_credential.py, src/condor_tests/test_issue_credentials.py, src/condor_tests/test_job_token_transfer.py, src/condor_utils/param_info.in
=> HTCONDOR-2763 credd uses shared port

docs/man-pages/condor_watch_q.rst, src/condor_scripts/condor_watch_q.in
=> HTCONDOR-2784: update condor watch q man page

docs/admin-manual/configuration-macros.rst, docs/admin-manual/ep-policy-configuration.rst, docs/classad-attributes/job-classad-attributes.rst, docs/classad-attributes/machine-classad-attributes.rst, docs/man-pages/condor_submit.rst, docs/overview/exceptional-features.rst, docs/users-manual/env-of-job.rst, docs/users-manual/file-transfer.rst, docs/users-manual/submitting-a-remote-job.rst, docs/users-manual/welcome-to-htcondor.rst
=> HTCONDOR-2787 Replace "worker node" with "execution point"

docs/admin-manual/file-and-cred-transfer.rst, docs/man-pages/condor_submit.rst, docs/users-manual/file-transfer.rst
=> HTCONDOR-2787 Clarify that output_destination does not include

src/condor_had/AbstractReplicatorStateMachine.cpp
=> HTCONDOR-2785 Convert had to CreateProcessNew

docs/version-history/feature-versions-24-x.rst, src/condor_tools/htcondor_cli/job.py, src/condor_tools/htcondor_cli/utils.py
etc., to match rest of HTCondor
=> HTCONDOR-2788 htcondor cli should report in binary kb/mb/gb, not KiB,

docs/version-history/feature-versions-23-x.rst, docs/version-history/v23-version.hist, src/condor_startd.V6/VolumeManager.cpp
=> HTCONDOR-2792: Disable LVM metadata archiving

src/condor_startd.V6/LoadQueue.cpp, src/condor_startd.V6/LoadQueue.h, src/condor_startd.V6/ResState.cpp, src/condor_startd.V6/ResState.h, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h
=> HTCONDOR-2723 fixup 64 bit time_t and inline LoadQueue into the Resource

src/condor_collector.V6/collector.cpp, src/condor_collector.V6/collector_engine.cpp, src/condor_collector.V6/collector_engine.h, src/condor_utils/HashTable.cpp, src/condor_utils/HashTable.h
=> HTCONDOR-2797 Make collector generic table names case insensitive

src/condor_includes/condor_attributes.h, src/condor_schedd.V6/qmgmt_factory.cpp, src/condor_shadow.V6.1/baseshadow.cpp, src/condor_tests/CMakeLists.txt, src/condor_tests/test_wait_duration.py
=> HTCONDOR-2795 initial job duration

src/condor_includes/condor_attributes.h, src/condor_schedd.V6/qmgmt_factory.cpp, src/condor_shadow.V6.1/baseshadow.cpp, src/condor_tests/CMakeLists.txt, src/condor_tests/test_wait_duration.py
=> HTCONDOR-2785 inital job duration

docs/version-history/lts-versions-23-0.rst, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_starter.V6.1/vanilla_proc.h
=> HTCONDOR-2800 cgroup latch memory

docs/version-history/feature-versions-24-x.rst
=> HTCONDOR-2789 Docs for EXECUTE validation/cleanup improvements

docs/admin-manual/configuration-macros.rst, docs/version-history/lts-versions-23-0.rst, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_starter.V6.1/vanilla_proc.h, src/condor_utils/param_info.in
=> HTCONDOR-2802 more frequent cgroup polling

docs/version-history/feature-versions-24-x.rst, src/condor_daemon_core.V6/daemon_core.cpp
=> HTCONDOR-2799 startup without ipv6

docs/version-history/lts-versions-23-0.rst, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2804 cgroup read memory stat

build/packaging/debian/condor-test.install.in, build/packaging/rpm/condor.spec, src/condor_tests/CMakeLists.txt, src/condor_tests/memory_exerciser_dinner.cpp
=> (HTCONDOR-2798)  A memory-usage exerciser, as specified.

docs/version-history/feature-versions-24-x.rst, src/blahp/config/blah.config.template, src/blahp/src/scripts/blah_common_submit_functions.sh
=> HTCONDOR-2793 blahp-merge-paths

docs/version-history/lts-versions-23-0.rst, src/condor_utils/proc_family_direct_cgroup_v1.cpp
=> HTCONDOR-2806 cgroup v1 oom

docs/version-history/lts-versions-23-0.rst, src/condor_utils/proc_family_direct_cgroup_v1.cpp
=> HTCONDOR-2807 cgroup v1 memory usage no longer includes cached disk pages

src/condor_tests/CMakeLists.txt, src/condor_tests/ornithology/scripts/debug_plugin.py, src/condor_tests/test_debug_plugin.py, src/condor_tests/test_fto_failure_propagation.py
=> HTCONDOR-2801: add transfer plugin result propagation test

docs/version-history/feature-versions-24-x.rst
This was missing from https://opensciencegrid.atlassian.net/browse/HTCONDOR-2408
=> HTCONDOR-2408 Version history

docs/version-history/feature-versions-24-x.rst
=> HTCONDOR-2729: condor_history performance 24.3 version history

src/condor_schedd.V6/qmgmt.cpp
=> HTCONDOR-2814 Remove trailing space after newline in dprintf message

docs/version-history/lts-versions-24-0.rst, src/condor_utils/cron_job.cpp
=> HTCONDOR-2817 schedd cron stderr leak

docs/admin-manual/file-and-cred-transfer.rst, docs/requirements.txt
=> HTCONDOR-2787 sphinxcontrib-mermaid v1.0.0 breaks git diagram

src/condor_q.V6/jobmatch.cpp, src/condor_q.V6/queue.cpp, src/condor_q.V6/queue_internal.h, src/condor_startd.V6/Resource.cpp, src/condor_utils/expr_analyze.cpp, src/condor_utils/expr_analyze.h
* to distinguish between counts of slots and counts of machines.
* to separate the counts of slots in the current state from simulated drained p-slots.
* to print a table of numbered expression clauses when doing match analysis.
* fixed a bug where -analyze did not always do match analysis when it should.
=> HTCONDOR-2720 changed condor_q -analyze output

docs/automated-workflows/index.rst, docs/conf.py, docs/extensions/dag-cmd.py, docs/man-pages/condor_dagman.rst, docs/man-pages/condor_submit_dag.rst, docs/man-pages/index.rst, src/condor_dagman/dagman_main.cpp, src/condor_utils/dagman_utils.h
=> HTCONDOR-2816: update dagman man pages

build/packaging/rpm/condor.spec, docs/classad-attributes/machine-classad-attributes.rst, docs/version-history/feature-versions-24-x.rst, nmi_tools/glue/build/set-tarball-rpath, src/condor_starter.V6.1/CMakeLists.txt, src/condor_starter.V6.1/get_user_ns.c, src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/singularity.h, src/condor_starter.V6.1/starter_v61_main.cpp
=> HTCONDOR-2818 startd advertise singularity setuid

docs/version-history/lts-versions-23-0.rst, docs/version-history/v23-version.hist
=> HTCONDOR-2821: Update 23.0.20 version history to use flatten history

src/condor_dagman/dag.cpp, src/condor_dagman/dag_priority_q.h, src/condor_dagman/dagman_commands.cpp, src/condor_dagman/dagman_main.cpp, src/condor_dagman/dagman_submit.cpp, src/condor_dagman/jobstate_log.cpp, src/condor_dagman/node.cpp, src/condor_dagman/node.h, src/condor_dagman/parse.cpp
=> HTCONDOR-2811 cleanup dagman nodes class

docs/version-history/v23-version.hist
=> HTCONDOR-2821: Fix v23 version history file

docs/version-history/feature-versions-24-x.rst, docs/version-history/lts-versions-24-0.rst, docs/version-history/v24-version.hist
=> HTCONDOR-2821: flatten history

docs/version-history/lts-versions-24-0.rst, src/condor_daemon_client/dc_collector.h, src/condor_negotiator.V6/matchmaker.cpp
=> HTCONDOR-2819 offline ad negotiator crash

docs/version-history/upgrading-from-23-0-to-24-0-versions.rst
=> HTCONDOR-2823 Added upgrade gotcha for PASSWORD identity change

src/condor_daemon_core.V6/condor_lock_file.cpp, src/condor_includes/condor_sys_types.h, src/condor_io/reli_sock.cpp, src/condor_master.V6/masterDaemon.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_shadow.V6.1/ShadowHookMgr.cpp, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/util.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/singularity.cpp, src/condor_submit.V6/submit.cpp, src/condor_submit.V6/submit_factory.cpp, src/condor_tools/history.cpp, src/condor_tools/preen.cpp, src/condor_utils/ClassAdLogProber.cpp, src/condor_utils/MapFile.cpp, src/condor_utils/classadHistory.cpp, src/condor_utils/condor_config.cpp, src/condor_utils/credmon_interface.cpp, src/condor_utils/file_transfer.cpp, src/condor_utils/hook_utils.cpp, src/condor_utils/job_ad_instance_recording.cpp, src/condor_utils/spooled_job_files.cpp, src/condor_utils/submit_utils.cpp, src/condor_utils/which.cpp
=> HTCONDOR-2782 reduce-stat-info-usage

build/packaging/debian/copyright.in, docs/conf.py
=> HTCONDOR-2787 New Year, new copyright!

docs/man-pages/condor_history.rst, src/condor_tools/history.cpp
=> HTCONDOR-2827 update condor history man page

docs/version-history/v23-version.hist, src/classad/lexer.cpp
=> HTCONDOR-2829 container port forwarding

docs/conf.py, docs/extensions/man-page-dummies.py, docs/full_conf.py
=> HTCONDOR-2787: Minimize man page build warnings

src/condor_utils/expr_analyze.cpp
=> HTCONDOR-2720 fix match analysis to handle ! and ?: better

docs/version-history/v23-version.hist, src/condor_scripts/condor_upgrade_check
=> HTCONDOR-2823 Add upgrade check for PASSWORD identity change

src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-2676 Set FirstJobMatchDate if needed when a match is re-used

docs/version-history/v23-version.hist, src/condor_daemon_client/dc_collector.cpp
=> HTCONDOR-2831 dc collector check nullptr

src/condor_startd.V6/Starter.cpp
=> HTCONDOR-2787 log receipt of final update in STARTD at D_STATUS

docs/version-history/feature-versions-24-x.rst
=> HTCONDOR-2787 fixup sphinx warning

src/condor_includes/condor_sys_nt.h
=> HTCONDOR-2782 fixup windows warning about multiply defined stat macros

docs/version-history/feature-versions-23-x.rst, docs/version-history/upgrading-from-23-0-to-24-0-versions.rst
=> HTCONDOR-2787 Fix sphinx warnings about undefined deprecated knobs

src/condor_startd.V6/util.cpp
Some existing deployments use 1777 permissions and we shouldn't break them. Just print a warning instead.
=> HTCONDOR-2789 Don't require EXECUTE permissions of 0755

docs/users-manual/env-of-job.rst
=> HTCONDOR-2848 document dollar dollar $$ in container_image

docs/version-history/v24-version.hist, src/condor_gridmanager/gridmanager_main.cpp, src/condor_schedd.V6/grid_universe.cpp, src/condor_utils/param_info.in
=> HTCONDOR-2846 gridmanager-log-name

docs/version-history/v23-version.hist, docs/version-history/v24-version.hist
=> HTCONDOR-2780: Cleanup 24.4.0 version history to use custom sphinx roles

docs/grid-computing/grid-universe.rst, docs/man-pages/condor_submit.rst, docs/version-history/v24-version.hist, src/condor_gridmanager/arcjob.cpp, src/condor_includes/condor_attributes.h, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
=> HTCONDOR-2774 arc-data-staging

build/nmi-build/build-batlab-images.sh, build/nmi-build/setup.sh, build/packaging/rpm/condor.spec, nmi_tools/glue/SubmitInfo.pm, nmi_tools/glue/build/make-tarball-from-rpms, nmi_tools/nmi-build-platforms, src/condor_tests/shadow_mem_usage-basic.run
=> HTCONDOR-2849: Build on AlmaLinux 10-kitten

build/nmi-build/build-batlab-images.sh, nmi_tools/glue/SubmitInfo.pm, nmi_tools/glue/build/make-tarball-from-rpms, nmi_tools/nmi-build-platforms
=> HTCONDOR-2858: Add Fedora 41 to build matrix

src/gpu/BasicProps.h, src/gpu/condor_gpu_discovery.cpp, src/gpu/cuda_device_enumeration.cpp, src/gpu/cuda_device_enumeration.h
=> HTCONDOR-2865 Advertise the nvidia driver version

src/condor_daemon_client/dc_message.cpp, src/condor_daemon_client/dc_message.h, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_schedd.V6/CMakeLists.txt
=> HTCONDOR-2862 Fix warnings with multiple inheritance

docs/admin-manual/configuration-macros.rst, docs/version-history/v24-version.hist, src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/ResAttributes.h, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/ResMgr.h, src/condor_startd.V6/ResState.cpp, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h, src/condor_startd.V6/Starter.cpp, src/condor_startd.V6/claim.cpp, src/condor_startd.V6/command.cpp, src/condor_startd.V6/startd.h, src/condor_startd.V6/startd_main.cpp, src/condor_status.V6/prettyPrint.cpp, src/condor_status.V6/status.cpp, src/condor_utils/param_info.in
A new knob CONTINUE_TO_ADVERTISE_BROKEN_DYNAMIC_SLOTS controls
whether broken dslots will be deleted or not when the become unclaimed
Adds a new broken_things data structure to the STARTD that holds information
about slots and other resources that are broken, this structure will
hold the job and claim information that were in effect at the time the
resource became broken so that the STARTD daemon ad can populate a
new BrokenContextAds attribute.  A new knob BROKEN_SLOT_CONTEXT_ATTRS
controls which attributes from the job and claim are published there.
- If the pull request is approved, …
=> HTCONDOR-2844 Add knob to disable deleting of unclaimed broken dslots

docs/version-history/v23-version.hist, src/condor_starter.V6.1/jic_shadow.cpp
=> HTCONDOR-2866 Allow chirp to work inside docker containers started as

bindings/python/htcondor2/_schedd.py, bindings/python/htcondor2/_submit.py, docs/version-history/v24-version.hist, src/condor_tests/CMakeLists.txt, src/condor_tests/test_queue_from_table.py, src/condor_utils/stl_string_utils.cpp, src/condor_utils/stl_string_utils.h, src/python-bindings/htcondor2/submit.cpp
=> (HTCONDOR-2830)  Fix QUEUE FROM TABLE in htcondor2.

src/condor_shadow.V6.1/pseudo_ops.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/starter_guidance.cpp, src/condor_tests/test_guidance_commands.py
=> (HTCONDOR-2867)  Circuit breakers for guidance.

src/condor_utils/proc_family_direct_cgroup_v1.cpp, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2871 Always check return values

docs/version-history/v24-version.hist, src/condor_dagman/dag.cpp, src/condor_dagman/dag.h, src/condor_dagman/dagman_main.cpp
=> HTCONDOR-2872: Fix negative failed jobs in DAGMan job state table

docs/version-history/v23-version.hist, src/condor_utils/except.cpp
=> HTCONDOR-2873 except recursion

src/condor_startd.V6/util.cpp
=> HTCONDOR-2875 Fix STARTD retry exec dir delete on windows

src/condor_startd.V6/Starter.cpp, src/condor_startd.V6/Starter.h, src/condor_startd.V6/claim.cpp
=> HTCONDOR-2860 Log pending update bytes when reaping the starter

src/condor_had/StateMachine.cpp, src/condor_had/StateMachine.h, src/condor_tools/nsenter.cpp
=> HTCONDOR-2850 minor-cleanup

bindings/python/htcondor2/_schedd.py, bindings/python/htcondor2/_submit.py, docs/version-history/v24-version.hist, src/condor_tests/CMakeLists.txt, src/condor_tests/test_queue_from_table.py, src/condor_utils/stl_string_utils.cpp, src/condor_utils/stl_string_utils.h, src/python-bindings/htcondor2/submit.cpp
=> (HTCONDOR-2830)  Do complicated merge to main.

build/cmake/macros/CondorPLTest.cmake, src/condor_tests/ctest_driver.py
=> HTCONDOR-2864 make ctest_driver more portable

src/condor_gridmanager/baseresource.cpp
=> HTCONDOR-2876 Use correct schedd name in grid ad invalidation request

src/condor_starter.V6.1/jic_shadow.cpp
=> HTCONDOR-2857 allow use krb5 in personal condors without crashing

src/condor_schedd.V6/qmgmt.h, src/condor_schedd.V6/qmgmt_receivers.cpp
This is necessary if we want to allow parallel transactions.
=> HTCONDOR-2850 Add CondorError to QmgmtPeer

docs/version-history/v23-version.hist, src/condor_schedd.V6/qmgmt.cpp, src/condor_tests/CMakeLists.txt, src/condor_tests/test_spool_preserved_relative_paths.py
=> (HTCONDOR-2877) Don't remove relative paths from spooled jobs if the submitter asked to preserve them.

docs/admin-manual/configuration-macros.rst, src/condor_starter.V6.1/starter.cpp
=> HTCONDOR-2850 default lv cleanup makes broken slots false

docs/version-history/v24-version.hist
=> HTCONDOR-2850: Remove version history

build/packaging/debian/control.in, build/packaging/rpm/condor.spec
condor_upgrade_checks no longer requires these programs
=> HTCONDOR-2883: Drop requiremnt for pcre2 tools

docs/classad-attributes/machine-classad-attributes.rst, docs/version-history/v24-version.hist
=> HTCONDOR-2856 document new nvidia driver attribute

src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/util.cpp, src/condor_startd.V6/util.h
=> HTCONDOR-2894 Startd should not assert when PREEMPT is undefined

docs/admin-manual/ap-policy-configuration.rst, docs/admin-manual/networking.rst, docs/users-manual/env-of-job.rst, docs/users-manual/file-transfer.rst
=> HTCONODR-2897 Update manual to use new "access point" terms

docs/version-history/v23-version.hist, src/condor_schedd.V6/grid_universe.cpp, src/condor_schedd.V6/grid_universe.h
=> HTCONDOR-2895 gridmanager selection

docs/version-history/v23-version.hist, src/condor_starter.V6.1/docker_proc.cpp
=> HTCONDOR-2890 docker volume crash

docs/version-history/v24-version.hist, src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/startd.h, src/condor_startd.V6/startd_main.cpp
=> HTCONDOR-2901 Distribute LoadAvg from p-slot to d-slot

build/packaging/debian/condor-test.install.in, build/packaging/rpm/condor.spec, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_tests/CMakeLists.txt, src/condor_tests/test_std_pipe_handler.cpp, src/condor_tests/test_std_pipe_handler.py, src/condor_utils/dc_coroutines.cpp
=> (HTCONDOR-2896)  Add std::function registration for reapers and pipes.

docs/man-pages/condor_token_create.rst
"For keys other than the POOL key, you can write the key file directly with whatever sufficiently-random contents you want. The file must be owned by root and readable only by root."
=> Upon per Jamie Frey email to HTCondor users list Feb 13 2053 UTC.

docs/version-history/v23-version.hist, src/condor_utils/DelegationInterface.cpp
=> HTCONDOR-2904 proxy delegation failure with openssl 3.4.0

docs/version-history/v23-version.hist, src/condor_utils/classadHistory.cpp
=> HTCONDOR-2902 no except per job history tmp

bindings/python/htcondor2/_collector.py, src/condor_scripts/adstash/ad_sources/ad_file.py, src/condor_scripts/adstash/ad_sources/schedd_history.py, src/condor_scripts/adstash/ad_sources/schedd_job_epoch_history.py, src/condor_scripts/adstash/ad_sources/schedd_transfer_epoch_history.py, src/condor_scripts/adstash/ad_sources/startd_history.py, src/condor_scripts/adstash/config.py, src/condor_scripts/adstash/convert.py, src/condor_scripts/adstash/utils.py, src/condor_scripts/annex/annex-local-universe.py, src/condor_scripts/condor_adstash, src/condor_scripts/condor_check_config, src/condor_scripts/condor_check_password, src/condor_scripts/condor_diagnostics, src/condor_scripts/condor_test_token, src/condor_scripts/condor_top, src/condor_scripts/condor_upgrade_check, src/condor_scripts/condor_watch_q.in, src/condor_scripts/run_test.pl, src/condor_scripts/slurm_job_status, src/condor_scripts/slurm_submit, src/condor_tests/test_awaitable_deadline_socket.py, src/condor_tests/test_dc_std_function_timer.py, src/python-bindings/htcondor2/collector.cpp
Hand smoke-tested:
The source makes no reference to `slurm_job_status` or `slurm_submit`, so unless somebody adopts them, I will ignore them.
=> (HTCONDOR-2668)  Switch "everything else" to use the version 2 bindings.

docs/man-pages/htcondor.rst, docs/version-history/v24-version.hist, src/condor_tools/htcondor_cli/annex.py
=> (HTCONDOR-2809)  Implement `htcondor annex login`

src/condor_tests/conftest.py
by removing an unused parameter
=> HTCONDOR-2905 Fix pytest 7 deprecation warning

docs/version-history/v23-version.hist, src/condor_gridmanager/arcresource.cpp
=> HTCONDOR-2907 arc gridmanager crash

src/condor_starter.V6.1/starter.cpp, src/condor_utils/dc_coroutines.cpp, src/condor_utils/dc_coroutines.h
=> (HTCONDOR-2813)  Remove unnecessary Service inheritance in coroutines.

docs/version-history/v23-version.hist, src/condor_tests/test_ft_plugin_stuff.py, src/condor_utils/file_transfer.cpp, src/condor_utils/file_transfer.h
=> HTCONDOR-2910 trailing semi output remaps

docs/version-history/v23-version.hist, src/condor_schedd.V6/qmgmt.h, src/condor_schedd.V6/qmgmt_receivers.cpp
=> HTCONDOR-2917 submit failure contagion

docs/version-history/v23-version.hist
=> HTCONDOR-2904 Fixup typo in version history

build/cmake/CondorConfigure.cmake
By removing dprint'ing of variables we never set
=> HTCONDOR-2897 Clean up cmake configure output

externals/bundles/pcre2/10.44/CMakeLists.txt, externals/bundles/scitokens-cpp/1.1.2/CMakeLists.txt
=> HTCONDOR-2922 Fix warning about deprecated cmake function

src/condor_utils/condor_event.h, src/condor_utils/read_user_log.cpp, src/condor_utils/write_eventlog.cpp, src/condor_utils/write_user_log.cpp
=> HTCONDOR-2925 dedup

docs/version-history/v23-version.hist, src/condor_tests/CMakeLists.txt, src/condor_tests/test_fto_pipe_read_full.py, src/condor_utils/file_transfer.cpp, src/condor_utils/file_transfer.h
=> HTCONDOR-2859: fto pipe hanging causing shadow exception

src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2893 Supress spurious warning message in dprintf log

docs/version-history/v23-version.hist
=> HTCONDOR-2929: Update v23-version.hist

src/condor_shadow.V6.1/pseudo_ops.cpp, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_starter.V6.1/starter_guidance.cpp, src/condor_utils/file_transfer.cpp, src/condor_utils/guidance.h
There's a race between the starter asking for advice and the forked-child FTO getting reaped by the shadow (which needs to happen for the shadow to learn the outcome of file tansfer).  Fixing the race on the shadow side would be a giant pain, so -- since we'll need the command later anyway -- ask the starter to ask again in a few seconds.
=> (HTCONDOR-2914)  CEDAR transfers failures don't always get starter log

src/condor_unit_tests/CMakeLists.txt, src/condor_unit_tests/OTEST_DagFileParser.cpp, src/condor_unit_tests/unit_tests.cpp, src/condor_utils/CMakeLists.txt, src/condor_utils/dag_commands.cpp, src/condor_utils/dag_commands.h, src/condor_utils/dag_parser.cpp, src/condor_utils/dag_parser.h, src/condor_utils/dagman_utils.cpp, src/condor_utils/dagman_utils.h
=> HTCONDOR-2869 separated dag file parser

docs/version-history/v24-version.hist, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_starter.V6.1/vanilla_proc.cpp
=> HTCONDOR-2944 delegated cgroup oom

docs/version-history/v24-version.hist
=> HTCONDOR-2937 documentation for concurrency limits fix

docs/version-history/v24-version.hist, src/condor_includes/condor_attributes.h, src/condor_startd.V6/VolumeManager.cpp, src/condor_startd.V6/startd_main.cpp, src/condor_starter.V6.1/starter_v61_main.cpp, src/condor_starter.V6.1/vm_proc.cpp
=> HTCONDOR-2945: LVM hide mount incompatible with VM universe jobs

src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/util.cpp, src/condor_starter.V6.1/docker_proc.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/os_proc.cpp, src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/singularity.h, src/condor_starter.V6.1/starter.cpp, src/condor_starter.V6.1/starter.h
=> HTCONDOR-2941 separate job scratch dir from htcondor system dir

docs/admin-manual/configuration-macros.rst, docs/version-history/v24-version.hist, src/condor_io/condor_auth_claim.cpp, src/condor_utils/param_info.in
=> HTCONDOR-2915 switch SEC_CLAIMTOBE_INCLUDE_DOMAIN to be fully qualified

src/python-bindings/CMakeLists.txt
=> HTCONDOR-2922 fixup typo in cmakelists.txt with missing close brace

src/condor_startd.V6/claim.cpp, src/condor_utils/param_info.in
=> HTCONDOR-2946 Flip default for STARTD_LEFTOVER_PROCS_BREAK_SLOTS to

build/cmake/CondorConfigure.cmake
=> HTCONDOR-2947 Don't try to detect python2 by default

docs/admin-manual/configuration-macros.rst, docs/version-history/v24-version.hist
=> HTCONDOR-2726 Add docs for STARTD_RECOMPUTE_DISK and spelling fixes

externals/bundles/scitokens-cpp/1.1.2/CMakeLists.txt
=> HTCONDOR-2922 Remove cmake deprecation warning in scitoken external

build/cmake/CondorConfigure.cmake, externals/bundles/scitokens-cpp/1.1.3/CMakeLists.txt
=> HTCONDOR-2951 Bump scitokens external to 1.1.3

build/nmi-build/build-batlab-images.sh, build/packaging/debian/control.in, build/packaging/rpm/condor.spec, nmi_tools/nmi-build-platforms
=> HTCONDOR-2886: Update to Pelican 7.14.1

build/packaging/debian/control.in, build/packaging/rpm/condor.spec, nmi_tools/nmi-build-platforms
=> HTCONDOR-2884: Update to Pelican 7.14.1

build/nmi-build/build-batlab-images.sh, build/packaging/debian/control.in, build/packaging/rpm/condor.spec, nmi_tools/nmi-build-platforms
=> HTCONDOR-2885: Update to Pelican 7.14.1

src/condor_scripts/CondorPersonal.pm
=> HTCONDOR-2932 Faster test startup by not running ps so frequently

src/condor_scripts/condor_credmon_oauth_dummy, src/condor_tests/test_dagman_service_nodes_lifetime.py, src/condor_tests/test_guidance_commands.py, src/condor_tools/htcondor_cli/access_point.py, src/condor_tools/htcondor_cli/central_manager.py, src/condor_tools/htcondor_cli/convert_ad.py, src/condor_tools/htcondor_cli/server.py
=> HTCONDOR-2955 Remove v1 bindings uses from the htcondor_cli

docs/version-history/v23-version.hist
=> HTCONDOR-2884: Pelican version version history plus spell check

src/condor_tests/job_core_macros-dollardollar_van.cmd, src/condor_tests/job_core_macros-dollardollar_van.run, src/condor_tests/test_ft_plugin_stuff.py
=> HTCONDOR-2675 test fixes

docs/admin-manual/configuration-macros.rst, docs/admin-manual/ep-policy-configuration.rst, docs/version-history/v24-version.hist, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_utils/param_info.in
=> HTCONDOR-2960: DISABLE_SWAP_FOR_JOB is true by default

docs/version-history/v23-version.hist, src/condor_starter.V6.1/jic_shadow.cpp
It appears that the problem was not the assumption that the CWD is the job sandbox -- although that assumption has been rendered unnecessary -- but the assumption that either the starter was in PRIV_USER or that PRIV_CONDOR had permission to read the sandbox directory.  The former is apparently generally not true and was always wrong to have been missing; the latter was saving us, but we changed the default mode on the sandbox directory to `0700` a few years ago.
=> (HTCONDOR-2916)  Manifest submit option unable to write in/out manifest to sandbox directory on CHTC pool.

docs/version-history/v23-version.hist, src/condor_collector.V6/ce-audit-plugin.cpp
PCRE2's regex compile appears to always fail if the error-reporting parameters aren't provided.
=> HTCONDOR-2963 Fix regex compile call in ce-audit plugin

src/condor_utils/param_info.in
=> HTCONDOR-2932: Remove duplicates in the param table

docs/admin-manual/file-and-cred-transfer.rst, src/condor_credd/condor_credmon_oauth/examples/config/condor/40-oauth-credmon.conf
=> HTCONDOR-2950 multi-credmon-docs

docs/version-history/v24-version.hist, src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/LocalCredmon.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2965
=> HTCONDOR-2965 Fix unset profile variable if local credmon token version is not configured

docs/apis/python-bindings/api/version2/migration-guide.rst
=> (HTCONDOR-2932)  Fix a very important typo in the migration guide.

docs/version-history/v24-version.hist, src/condor_includes/pool_allocator.h, src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/Resource.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_utils/ad_printmask.h, src/condor_utils/condor_config.cpp, src/condor_utils/env.cpp, src/condor_utils/ntsysinfo.WINDOWS.cpp, src/condor_who/who.cpp
=> HTCONDOR-2927 add condor_who -print-format -banner-format and -ospool

src/condor_daemon_core.V6/daemon_core.cpp
Because a daemon core callback can check the FullyQualifiedUserName
so cached the value around the callback.
Ditto in the reaper callback
=> HTCONDOR-2932 Fix use-after-free in daemon core

docs/version-history/v23-version.hist, src/condor_utils/docker-api.cpp
=> HTCONDOR-2961: Calculate docker universe job memory usage for cgroups v2

docs/STYLE.md, docs/version-history/v23-version.hist
=> HTCONDOR-2897 fix bad indent warning in version history

CMakeLists.txt
=> HTCONDOR-2932 Supress cmake install "up-to-date" message printing

build/cmake/CondorConfigure.cmake
[HTCONDOR-2970](https://opensciencegrid.atlassian.net/browse/HTCONDOR-2970)
[HTCONDOR-2970]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-2970?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-2970 Improve cmake detection of Python on Windows

docs/classad-attributes/job-classad-attributes.rst, docs/version-history/v24-version.hist, src/condor_includes/condor_attributes.h, src/condor_starter.V6.1/jic_shadow.cpp
=> HTCONDOR-2972 advertise home directory

src/condor_tools/ping.cpp
=> HTCONDOR-2958 fix memory leak in condor_ping

src/condor_includes/condor_attributes.h, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/qmgmt.h, src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/scheduler.h, src/condor_utils/param_info.in, src/condor_utils/set_user_priv_from_ad.cpp, src/condor_utils/spooled_job_files.cpp
=> HTCONDOR-2931 user-over-owner-2

src/condor_startd.V6/ResMgr.cpp, src/condor_startd.V6/Resource.cpp
=> HTCONDOR-2968 fix umr in startd

src/condor_shadow.V6.1/NTreceivers.cpp
=> HTCONDOR-2958 Fix memory leak in shadow get creds

src/condor_shadow.V6.1/remoteresource.cpp
=> HTCONDOR-2392 Fix memory leak in shadow with epoch ads

src/condor_daemon_client/dc_startd.cpp
=> HTCONDOR-2882 fix version check for DEACTIVATE_CLAIM_JOB_DONE

src/condor_scripts/condor_watch_q.in
=> HTCONDOR-2958: Fix condor_watch_q progess bar ordering issues

src/condor_starter.V6.1/CMakeLists.txt
Somehow the old rules don't work with newer cmakes
=> HTCONDOR-2932 Update cmake rules for address sanitizer

docs/admin-manual/ep-policy-configuration.rst
=> HTCONDOR-2897 Better docker image docs and spell checking

src/condor_tools/config_val.cpp, src/condor_tools/tool.cpp
=> HTCONDOR-2932 Remove support for now-defunct purify tool

src/condor_master.V6/master.cpp
=> HTCONDOR-2988 Fix typo in dprintf message found by ligo

docs/version-history/v23-version.hist, src/condor_scripts/condor_watch_q
=> HTCONDOR-2992: Fix job id sorting for display of range in condor_watch_q

bindings/python/htcondor2/_credd.py, docs/version-history/v24-version.hist
Fix a typo in the v2 bindings.
=> (HTCONDOR-2993)  Can't raise `TypError` [sic]

docs/version-history/v24-version.hist
=> HTCONDOR-2870 Add version history entry

src/condor_tests/extended_submit_cmds.run, src/condor_tests/test_checkpoint_destination_two.py, src/condor_tests/x_cat.pl
=> HTCONDOR-2949 tests should use _CONDOR_JOB_AD instead of hardcoded path

src/condor_tests/job_basic_preempt.run
It is sleeping for 120 seconds when 40 will do, and has a couple of uncalled functions
=> HTCONDOR-2988 cleanup and speedup job-basic-preempt-test

src/condor_startd.V6/Reqexp.cpp, src/condor_startd.V6/Reqexp.h, src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/ResAttributes.h, src/condor_startd.V6/StartdHookMgr.cpp, src/condor_startd.V6/startd.h, src/condor_startd.V6/startd_main.cpp
Static slots will now use WithinResourceLimits like the other slot types
=> HTCONDOR-2967 use WithinResourceLimits for NO_JOB_NETWORKING matching

src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-2998 Fix bug from HTCONDOR-2882 that caused

src/python-bindings/CMakeLists.txt
=> HTCONDOR-2886: Fix Python wheel build

src/condor_daemon_client/dc_schedd.h, src/python-bindings/classad2/classad.cpp, src/python-bindings/htcondor2/schedd.cpp, src/python-bindings/htcondor2/submit.cpp
=> (HTCONDOR-2981)  Fix some memory leaks in the v2 implemenation.

src/condor_tests/test_fto_failure_propagation.py
=> HTCONDOR-2988: Don't reuse any slots in test_fto_failure_propogation

docs/version-history/v23-version.hist, src/condor_shadow.V6.1/remoteresource.cpp
=> HTCONDOR-2997 Shadow shouldn't wait on dead starter

build/nmi-build/setup.sh, build/packaging/rpm/condor.spec, nmi_tools/nmi-build-platforms
=> HTCONDOR-2886: Require Appaiter 1.4.0

src/condor_utils/submit_utils.cpp
=> HTCONDOR-2843 Make submit quoting for transfer in/out/remaps consistent

src/condor_tests/broken_startd.run
By querying the startd directly, instead of the condor. Sometimes the update hasn't made it to the collector at the time of the query.
=> HTCONDOR-2988 Robustify broken_startd test

docs/man-pages/condor_watch_q.rst, docs/man-pages/index.rst
=> HTCONDOR-2988 add watch_q to mindmap

src/condor_scripts/condor_watch_q.in
=> HTCONDOR-2988: Fix all condor_watch_q imports to use v2 api

src/condor_tests/test_dagman_inline_shell_submit.py
=> HTCONDOR-2988 up timeout in test

src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-2988 Double check that we don't accidentally add entry to

src/condor_tests/test_allowed_execute_duration.py
=> HTCONDOR-2988 test-allowed-execute-duration needs 8 cpus to be robust

build/nmi-build/build-batlab-images.sh, nmi_tools/nmi-build-platforms
=> HTCONDOR-2883: Update to scitokens-cpp 1.1.3

build/packaging/debian/control.in, build/packaging/rpm/condor.spec, docs/version-history/v23-version.hist, nmi_tools/nmi-build-platforms
=> HTCONDOR-2884: Update to scitokens-cpp 1.1.3, pelican 7.15.0

build/packaging/debian/control.in, build/packaging/rpm/condor.spec, docs/version-history/v23-version.hist, nmi_tools/nmi-build-platforms
=> HTCONDOR-2885: Update to scitokens-cpp 1.1.3, pelican 7.15.0

CITATION.cff, CMakeLists.txt, build/packaging/debian/control.in, build/packaging/rpm/condor.spec, docs/conf.py, docs/version-history/feature-versions-24-x.rst, docs/version-history/v23-version.hist, docs/version-history/v24-version.hist, nmi_tools/nmi-build-platforms
=> HTCONDOR-2886: Update to scitokens-cpp 1.1.3, Pelican 7.15.0

src/condor_shadow.V6.1/pseudo_ops.cpp, src/condor_tests/test_guidance_commands.py
This test fails intermittently because of a race condition where the starter can ask for guidance before the shadow has reaped the forked FTO child.  The reaper (calls a function which, etc) writes the end-of-input-transfer event that's missing, but if the starter asks for guidance before the reaper fires, then in the test case the shadow will immediately reply `CarryOn`, causing the starter to exit so quickly that reaping the forked FTO child either doesn't happen or is ignored.
To (hopefully) work around this, the test now asks the starter to call it back in five seconds the first time after retrying file transfer.
This change does _not_ attempt to address the potential absence of end-of-input-transfer events during normal operation; we could use the same work-around we do for the test, …
=> (HTCONDOR-3001)  Robustify test_guidance_commands.

docs/users-manual/env-of-job.rst
=> HTCONDOR-2988 Document docker auth with apptainer

src/condor_tests/CMakeLists.txt, src/condor_tests/test_cgroup_oom.py, src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-3007 add regression test for cgroup oom handling

src/condor_tests/shadow_mem_usage-basic.run
=> HTCONDOR-2988 Update shadow memory test for Fedora 42

docs/version-history/v23-version.hist, src/condor_utils/dagman_utils.cpp, src/condor_utils/dagman_utils.h
=> HTCONDOR-3011: DAGMan respect max idle configuration value

docs/admin-manual/configuration-macros.rst, docs/users-manual/env-of-job.rst, docs/version-history/v24-version.hist, src/condor_starter.V6.1/starter.cpp, src/condor_tools/getpwnam.cpp
=> HTCONDOR-3010 home env var

src/condor_utils/docker-api.cpp
=> HTCONDOR-3015 Fix docker image cache gc'ing

src/condor_shadow.V6.1/baseshadow.cpp, src/condor_starter.V6.1/starter.cpp
=> HTCONDOR-2932 vacate-logging

src/condor_job_router/JobRouter.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/qmgmt_receivers.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_starter.V6.1/jic_local.cpp, src/condor_starter.V6.1/jic_shadow.cpp, src/condor_starter.V6.1/job_info_communicator.cpp, src/condor_tools/give_interactive.cpp, src/condor_utils/checkpoint_cleanup_utils.cpp, src/condor_utils/cron_job.cpp, src/condor_utils/uids.cpp, src/condor_utils/write_user_log.cpp
=> HTCONDOR-2986 os-identity

docs/man-pages/condor_who.rst
=> HTCONDOR-2927 update condor_who man page for new formatting args

docs/version-history/v24-version.hist, src/condor_starter.V6.1/jic_shadow.cpp
=> HTCONDOR-3020 always chmod cmd

src/condor_io/condor_auth_passwd.cpp, src/condor_io/condor_auth_ssl.cpp, src/vendor/jwt-cpp/README, src/vendor/jwt-cpp/include/jwt-cpp/base.h, src/vendor/jwt-cpp/include/jwt-cpp/jwt.h, src/vendor/jwt-cpp/include/jwt-cpp/traits/boost-json/defaults.h, src/vendor/jwt-cpp/include/jwt-cpp/traits/boost-json/traits.h, src/vendor/jwt-cpp/include/jwt-cpp/traits/danielaparker-jsoncons/defaults.h, src/vendor/jwt-cpp/include/jwt-cpp/traits/danielaparker-jsoncons/traits.h, src/vendor/jwt-cpp/include/jwt-cpp/traits/defaults.h.mustache, src/vendor/jwt-cpp/include/jwt-cpp/traits/kazuho-picojson/traits.h, src/vendor/jwt-cpp/include/jwt-cpp/traits/nlohmann-json/defaults.h, src/vendor/jwt-cpp/include/jwt-cpp/traits/nlohmann-json/traits.h, src/vendor/jwt-cpp/include/jwt-cpp/traits/open-source-parsers-jsoncpp/defaults.h, src/vendor/jwt-cpp/include/jwt-cpp/traits/open-source-parsers-jsoncpp/traits.h
This fixes several warnings with gcc-15 aboute deprecated wstring operations, but also introduces breaking interface changes, requiring changes to condor_auth_ssl and _passwd that use jwt's.
=> HTCONDOR-2988 Bump jwt-cpp from 0.6.0 to 0.7.1

docs/admin-manual/configuration-macros.rst, docs/version-history/v24-version.hist, src/condor_dagman/dag.cpp, src/condor_dagman/dagman_main.cpp, src/condor_dagman/dagman_main.h, src/condor_dagman/node.cpp, src/condor_dagman/node.h, src/condor_tests/CMakeLists.txt, src/condor_tests/test_dagman_job_list_failure_tolerance.py, src/condor_tests/test_dagman_script_macros.py
=> HTCONDOR-3019 dagman job list failure tolerance

src/condor_tests/starter_breaks_resource.run
By querying the startd directly, instead of assuming that an update made it to the collector.
=> HTCONDOR-2988 Robustify starter_breaks_resource test

docs/version-history/v23-version.hist, docs/version-history/v24-version.hist
=> HTCONDOR-2886: Cleanup version history for v24.7.x release

docs/version-history/v24-version.hist, src/condor_utils/file_transfer.cpp
=> HTCONDOR-3027 dataflow subsecond stat

src/condor_tests/test_fto_pipe_read_full.py
=> HTCONDOR-2988 robustify test fto pipe read full

src/condor_tests/test_dagman_job_list_failure_tolerance.py
=> HTCONDOR-2988: Up timeout for test_dagman_job_failure_tolerance

src/condor_starter.V6.1/StarterHookMgr.h, src/condor_tests/test_cgroup_oom.py
=> HTCONDOR-3029 Add more cgroup tests

docs/version-history/v23-version.hist, src/condor_starter.V6.1/jic_shadow.cpp
=> HTCONDOR-3016 starter xfer crash

docs/version-history/v24-version.hist, src/condor_utils/file_transfer.cpp
=> HTCONDOR-3027 Add dataflow sub-second timestamps on macOS

docs/version-history/v24-version.hist, src/condor_utils/dprintf_setup.cpp, src/python-bindings/htcondor2/loose_functions.cpp
=> (HTCONDOR-3004)  Fix htcondor2.enable_log() failure handling.

src/condor_utils/proc_family_direct_cgroup_v2.cpp
=> HTCONDOR-3008 when counting procs in a cgroup, need to go recursively

src/condor_sysapi/phys_mem.cpp
=> HTCONDOR-2988 Allow for long cgroup names when detected memory limits

view/ce_dashboard/flask/blueprints/landing.py, view/ce_dashboard/flask/blueprints/overview.py, view/ce_dashboard/flask/utils.py
When the CE Dashboard displays the name of the institution, use the new InstitutionID database with standardized institution names instead of the haphazard topology facility names.  These Instituion Names are cached first to disk, so that when using a multi-process server (like gunicorn), only one process needs to fetch and process the database.  Other server processes will read the pickled database from local disk, and then use it to create an in-memory dictionary.
[See ticket HTCONDOR-3030](https://opensciencegrid.atlassian.net/browse/HTCONDOR-3030)
- Assign JIRA Ticket back to the …
=> HTCONDOR-3030 Use InsitutionID names in CE Dashboard

build/cmake/CondorPackageConfig.cmake, docs/version-history/v24-version.hist, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-3036 local univ execute perms

docs/full_conf.py
=> HTCONDOR-2988: Enable 'Edit on Github' for documentation pages

src/condor_vm-gahp/libvirt_simple_script.awk
In support of [SOFTWARE-6039](https://opensciencegrid.atlassian.net/browse/SOFTWARE-6039), update libvirt_simple_script.awk to support launching libvirt VMs on ARM hosts. This PR makes several file path references to files included by libvirt on ARM el9:
- /usr/share/edk2/aarch64/QEMU_EFI-silent-pflash.qcow2
- /usr/share/edk2/aarch64/vars-template-pflash.qcow2
```bash
$ yum whatprovides '/usr/share/edk2/aarch64/*'
Last metadata expiration check: 0:00:33 ago on Tue 08 Apr 2025 03:08:12 PM CDT.
edk2-aarch64-20240524-9.el9.noarch : UEFI firmware for aarch64 virtual machines
Repo        : AppStream_aarch64_local
Matched from:
Filename    : /usr/share/edk2/aarch64/QEMU_EFI-pflash.qcow2
Filename    : /usr/share/edk2/aarch64/QEMU_EFI-pflash.raw
Filename    : …
```
=> SOFTWARE-6039: Update libvirt_simple_script.awk to detect arch, configure UEFI boot on ARM

build/packaging/debian/condor-upgrade-checks.install, build/packaging/debian/condor.install.in, build/packaging/debian/control.in, build/packaging/rpm/condor.spec, docs/version-history/v24-version.hist
=> HTCONDOR-2995: Fold condor_upgrade_check into the main condor package

docs/man-pages/condor_status.rst, docs/version-history/v24-version.hist, src/condor_status.V6/status.cpp
=> HTCONDOR-3044: condor_status -totals (sigh)

docs/version-history/v24-version.hist, src/condor_startd.V6/ResState.cpp
[HTCONDOR-3045](https://opensciencegrid.atlassian.net/browse/HTCONDOR-3045)
[HTCONDOR-3045]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-3045?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-3045 fix claim reuse

docs/version-history/v24-version.hist, src/condor_shadow.V6.1/remoteresource.cpp, src/condor_starter.V6.1/jic_shadow.cpp
=> HTCONDOR-3047 slot name in execute event

docs/man-pages/condor_adstash.rst, docs/version-history/v24-version.hist, src/condor_scripts/adstash/ad_sources/schedd_history.py, src/condor_scripts/adstash/ad_sources/schedd_job_epoch_history.py, src/condor_scripts/adstash/ad_sources/schedd_transfer_epoch_history.py, src/condor_scripts/adstash/ad_sources/startd_history.py, src/condor_scripts/adstash/adstash.py, src/condor_scripts/adstash/config.py, src/condor_scripts/adstash/convert.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-2680
=> HTCONDOR-2680 Adstash custom projections

docs/version-history/v23-version.hist, src/condor_schedd.V6/dedicated_scheduler.cpp
=> HTCONDOR-3049 ded sched crashes

docs/version-history/v23-version.hist, src/condor_schedd.V6/dedicated_scheduler.cpp
=> HTCONDOR-3049 ded sched merge

docs/apis/python-bindings/api/version2/migration-guide.rst
=> (HTCONDOR-2999)  Show how to use an IDTOKEN to do remote submission.

src/condor_scripts/get_htcondor
=> HTCONDOR-3043: Augment get htcondor

docs/admin-manual/configuration-macros.rst, docs/version-history/v24-version.hist, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_master.V6/masterDaemon.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_startd.V6/Starter.cpp, src/condor_starter.V6.1/vanilla_proc.cpp, src/condor_utils/proc_family_direct_cgroup_v2.cpp, src/condor_utils/proc_family_direct_cgroup_v2.h
=> HTCONDOR-3032 cgroup all the daemons

docs/users-manual/env-of-job.rst
=> HTCONDOR-3054 Add missing _CONDOR_CREDS env var docs

src/condor_daemon_core.V6/daemon_core.cpp
=> (HTCONDOR-3062)  No need for this typo.

docs/version-history/v23-version.hist, src/condor_utils/dprintf.cpp
=> HTCONDOR-3066 no retry failed fclose

src/condor_tests/test_dagman_proper_env.py, src/condor_utils/dagman_utils.cpp
This allow us to use asan on dagman without polluting its log files
=> HTCONDOR-3060 pass address and leak sanitizer options into dagman

src/condor_utils/MapFile.cpp
=> HTCONDOR-3060 Revirtualize CanononicalMapEntry

src/condor_includes/condor_attributes.h, src/condor_shadow.V6.1/pseudo_ops.cpp, src/condor_starter.V6.1/starter.h, src/condor_starter.V6.1/starter_guidance.cpp, src/condor_starter.V6.1/starter_v61_main.cpp
With this PR:
* The starter advertises `HasCommonFilesTransfer`, if appropriate.
* When the starter asks for job-setup guidance, it sends the above attribute and value along.
* The starter no longer asks for guidance about the job environment after being told to retry a request for job setup guidance.  This would happen if the shadow commanded uncommon input file transfer to happen first, and that transfer finished before the common input became available.  (The retry-request guidance is implemented by returning to the event loop after setting a timer for the retry; the old implementation asked for job-environment guidance before returning to the event loop.)
- Hit the merge button if the pull request is approved and it is not a security patch (security changes require 2 additional …
=> (HTCONDOR-3051)  Advertise `HasCommonFilesTransfer = 1`

docs/version-history/v23-version.hist, src/condor_utils/selector.cpp
=> HTCONDOR-3079 huge ulimit dash n

docs/version-history/v23-version.hist, docs/version-history/v24-version.hist
=> HTCONDOR-2985: Cleanup version history for v24.8 (and friends) release

src/condor_startd.V6/ResAttributes.cpp, src/condor_startd.V6/Resource.cpp, src/condor_startd.V6/Resource.h, src/condor_startd.V6/claim.cpp
=> HTCONDOR-3072 more logging of GPUs on backfill slots

view/ce_dashboard/flask/blueprints/overview.py, view/ce_dashboard/flask/static/htcondorview.js, view/ce_dashboard/flask/templates/overview.html.j2
Address some shortcomings of the CE Overview page.
Details in the ticket:
[HTCONDOR-3076](https://opensciencegrid.atlassian.net/browse/HTCONDOR-3076
)
[HTCONDOR-3076]: https://opensciencegrid.atlassian.net/browse/HTCONDOR-3076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HTCONDOR-3076 CE dashboard overview page improvements

docs/admin-manual/configuration-macros.rst, src/condor_utils/email.cpp
Also, fix up one old website address (Many more should be checked)
=> HTCONDOR-3060: Fix up defrag doc link

docs/version-history/v24-version.hist, src/condor_credd/condor_credmon_oauth/credmon/CredentialMonitors/VaultCredmon.py
https://opensciencegrid.atlassian.net/browse/HTCONDOR-3086
Hand tested on CHTC's test AP against an external Vault server.
=> HTCONDOR-3086 Fix Vault credmon failing to generate access tokens if AUTH_SSL_CLIENT_CAFILE/CADIR undefined

src/condor_scripts/get_htcondor
=> HTCONDOR-3043: get_htcondor doesn't configure a non-running firewall

externals/bundles/boost/1.66.0/CMakeLists.txt, externals/bundles/voms/2.1.0/CMakeLists.txt
This is all hackery, but it should all go away when we switch to the v2 python bindings, so I'm not going to spend more time tiding it up.
=> HTCONDOR-3090 Alma 10 cmake boost build rules

src/condor_tests/unit_test_sinful.run
It isn't set outside of NMI/batlab
=> HTCONDOR-3090 Don't use NMI_PLATFORM to detect test platform

src/condor_tests/test_chirp_to_dagman_log.py, src/condor_tests/test_dagman_proper_env.py, src/condor_tests/test_protected_url_xfers.py
=> HTCONDOR-3090 When tests poll, sleep between polling cycles

docs/version-history/v24-version.hist, src/condor_daemon_core.V6/daemon_core.cpp, src/condor_utils/proc_family_direct_cgroup_v1.cpp, src/condor_utils/proc_family_direct_cgroup_v1.h, src/condor_utils/proc_family_direct_cgroup_v2.cpp, src/condor_utils/proc_family_direct_cgroup_v2.h, src/condor_utils/proc_family_interface.h
=> HTCONDOR-3094 cgroup v1 oom

src/classad/classad_unit_tester.cpp
=> HTCONDOR-3095 add classad move assignment operator test

src/condor_tools/preen.cpp
=> HTCONDOR-3108 Also fix copy of earlier memory leaking code in preen

src/condor_credd/credd.cpp
=> HTCONDOR-3116 Fix memory leak in credd

build/lsan.supp, src/condor_utils/test_log_reader.cpp
=> HTCONDOR-3105 suppress memory leak in java and python code

src/condor_tests/test_condor_history.py, src/condor_tools/history.cpp
=> HTCONDOR-3061: Fix history default job print format table

src/condor_status.V6/prettyPrint.cpp, src/condor_status.V6/prettyPrint.h, src/condor_status.V6/status.cpp
=> HTCONDOR-3105 fix condor_status to use built-in print format headings

src/python-bindings/condor_python.h
The previous value had an extra zero at the end, upshifting the value by 4 bits.
=> HTCONDOR-3129 Fix incorrect value for Py_LIMITED_API

build/packaging/rpm/condor.spec
=> HTCONDOR-3056: Apptainer is not available for AmazonLinux 2023

build/cmake/CondorConfigure.cmake, externals/bundles/scitokens-cpp/1.1.4-beta/CMakeLists.txt
=> HTCONDOR-3131 bump scitokens source external to 1.1.4-beta

docs/version-history/v24-version.hist, src/condor_tests/test_cif.py, src/condor_utils/guidance.cpp
Allows this part of the code to work on OS Pool.
=> (HTCONDOR-3128)  Shorten startd sinful strings to fit in filenames by hashing them.

src/condor_utils/submit_utils.cpp
=> HTCONDOR-3105 Fix memory leak in schedd with protected urls

docs/codes-other-values/hold-reason-codes.rst, docs/users-manual/troubleshooting.rst, src/condor_q.V6/jobmatch.cpp
=> HTCONDOR-3114 Next steps at adding troubleshoot held jobs docs

docs/classad-attributes/job-classad-attributes.rst, docs/classads/print-formats.rst, docs/extensions/hidden.py, docs/full_conf.py
=> HTCONDOR-3105: Update print format table documentation

src/condor_includes/condor_email.h, src/condor_includes/proc.h, src/condor_shadow.V6.1/baseshadow.cpp, src/condor_shadow.V6.1/baseshadow.h, src/condor_utils/email_cpp.cpp, src/condor_utils/submit_utils.cpp
=> HTCONDOR-3133 Add Start to email notify lists

docs/version-history/v23-version.hist, src/condor_tools/htcondor_cli/dagman.py, src/condor_tools/htcondor_cli/eventlog.py
=> HTCONDOR-3112 fix timedelta seconds issue in all htc cli verbs

build/nmi-build/build-batlab-images.sh, build/nmi-build/setup.sh, build/packaging/rpm/condor.spec, nmi_tools/glue/SubmitInfo.pm, nmi_tools/nmi-build-platforms
=> HTCONDOR-3090: Support x86_64_v2 on AlmaLinux 10

build/nmi-build/build-batlab-images.sh, build/nmi-build/setup.sh, build/packaging/rpm/condor.spec, nmi_tools/glue/SubmitInfo.pm, nmi_tools/nmi-build-platforms
=> HTCONDOR-3090: Updates for x86_64_v2 on AlmaLinux 10

docs/classads/print-formats.rst
=> HTCONDOR-3105: Use correct word in print format tables docs

bindings/python/htcondor2/__init__.py, docs/apis/python-bindings/api/version2/htcondor2/module.rst, docs/version-history/v24-version.hist, src/condor_includes/condor_debug.h, src/condor_utils/dprintf_config.cpp, src/python-bindings/htcondor2/loose_functions.cpp, src/python-bindings/htcondor2_impl.cpp
The implementation of `dprintf_deconfig_tool()` was advised by TJ.
=> (HTCONDOR-3003)  Implement htcondor2.disable_debug().

docs/version-history/v23-version.hist, src/condor_starter.V6.1/starter.cpp
=> HTCONDOR-3156: Write machine and job ad as user in scratch directory

src/condor_tools/preen.cpp
=> HTCONDOR-3131 Fix memory leak in preen

docs/users-manual/file-transfer.rst
=> (HTCONDOR-3162)  Clarify S3 URL example.  Remove stray commmas and spaces.

docs/admin-manual/cm-configuration.rst
=> HTCONDOR-3165 Fix typo in manual -- higher prio factor is worse

src/condor_schedd.V6/job_transforms.cpp
Some users are relying on this syntax and we didn't give a warning about this removal. So we're giving some time to transition.
=> HTCONDOR-3118 Restore old syntax for submit transforms in the schedd

src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/qmgmt.h, src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/scheduler.h
=> HTCONDOR-3159 Add OCU counters to submitter ads

src/condor_tests/shadow_mem_usage-basic.run
=> HTCONDOR-3178 shadow memory test should use file xfer

docs/version-history/v23-version.hist, src/condor_procapi/procapi.cpp, src/condor_procapi/procapi.h, src/condor_procapi/procapi_killfamily.cpp
=> HTCONDOR-3179 Fixed bogus ImageSize value on Windows EP

src/condor_utils/credmon_interface.cpp
if we cannot talk to the credmon
=> HTCONDOR-3183 Fix stack corruption in credd

src/condor_utils/test_classad_funcs.cpp
=> HTCONDOR-3165 fix memory leak in test suite

src/condor_utils/classad_oldnew.cpp
=> HTCONDOR-3175 Do not preallocate 64k for classad serialization buffering

docs/version-history/v23-version.hist, src/condor_starter.V6.1/docker_proc.cpp
=> HTCONDOR-3185 docker uni post scripts env vars

src/condor_tests/test_guidance_commands.py
=> HTCONDOR-3165 On slow machine, test-guidance needs a little more time

docs/version-history/v23-version.hist, src/condor_tools/token_request.cpp
=> HTCONDOR-239 token request

docs/version-history/v23-version.hist
=> HTCONDOR-3101: Cleanup version history for release

docs/STYLE.md, docs/extensions/jira.py
=> HTCONDOR-3192: Add version history entry anchors

bindings/python/htcondor2/_schedd.py, docs/version-history/v24-version.hist, src/condor_daemon_client/dc_schedd.cpp, src/condor_daemon_client/dc_schedd.h, src/condor_schedd.V6/schedd.cpp, src/python-bindings/htcondor2/schedd.cpp, src/python-bindings/htcondor2_impl.cpp
=> HTCONDOR-3181 Add get_claims methods to dc_schedd and python bindings

src/condor_scripts/CondorPersonal.pm, src/condor_tests/ctest_driver.py
=> HTCONDOR-3171 Lower singularity test timeouts, in hopes of

src/classad/classad.cpp, src/classad/classad_version.cpp, src/classad/util.cpp, src/classad/xmlSource.cpp
=> HTCONDOR-3165 Remove "using std" from some classad sources

src/condor_status.V6/prettyPrint.cpp, src/condor_status.V6/prettyPrint.h, src/condor_status.V6/status.cpp, src/condor_utils/ad_printmask.cpp, src/condor_utils/ad_printmask.h, src/condor_utils/make_printmask.cpp
and the old print-format setup functions made obsolete thereby.
=> HTCONDOR-3193 Add missing print-format text blobs to condor_status

docs/admin-manual/configuration-macros.rst, docs/admin-manual/ep-policy-configuration.rst, docs/version-history/v24-version.hist, src/condor_chirp/condor_chirp.cpp, src/condor_starter.V6.1/jic_shadow.cpp
jobs that need chirp but don't use the default docker bridge network.
=> HTCONDOR-3197 Add support for DOCKER_NETWORK_NAME for docker universe

docs/version-history/v24-version.hist, src/condor_io/condor_auth_ssl.cpp, src/condor_io/condor_secman.cpp
=> HTCONDOR-3195 misc security fixes

docs/version-history/v24-version.hist, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h
=> HTCONDOR-3208 shell equal with interactive submit

src/condor_gridmanager/gridmanager_main.cpp, src/condor_schedd.V6/qmgmt.cpp, src/condor_shadow.V6.1/baseshadow.h, src/condor_startd.V6/Starter.cpp, src/condor_utils/read_user_log.h, src/condor_utils/single_provider_syndicate.cpp
=> HTCONDOR-3211 medium coverity fixes

docs/version-history/v24-version.hist, src/condor_tools/store_cred_main.cpp
=> HTCONDOR-3213 store password legacy

src/classad/classad/classad.h, src/classad/classad/classad_flat_map.h, src/condor_daemon_client/daemon.cpp, src/condor_daemon_client/daemon.h, src/condor_daemon_client/dc_schedd.cpp, src/condor_daemon_client/dc_schedd.h, src/condor_daemon_client/dc_shadow.cpp, src/condor_daemon_client/dc_shadow.h, src/condor_daemon_client/dc_startd.cpp, src/condor_daemon_client/dc_startd.h
This makes the objects more amenable to the default copy and move operations.
=> HTCONDOR-3165 Inline some Daemon client data members

src/classad/classad/classad.h
=> HTCONDOR-3165 Add classad move constructor

src/condor_includes/condor_attributes.h, src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_startd.V6/claim.cpp, src/condor_startd.V6/claim.h, src/condor_startd.V6/command.cpp, src/condor_tools/htcondor_cli/ocu.py
=> HTCONDOR-3205 advertise ocu startd

bindings/python/htcondor2/_schedd.py, src/python-bindings/common2/py_util.cpp, src/python-bindings/htcondor2/schedd.cpp, src/python-bindings/htcondor2_impl.cpp
=> HTCONDOR-3126 Add v2 python bindings QueryUserAds and QueryProjectAd

src/condor_schedd.V6/qmgmt.cpp, src/condor_tools/htcondor_cli/ocu.py
=> HTCONDOR-3218 add ocu willing attribute

src/condor_negotiator.V6/matchmaker.cpp, src/condor_negotiator.V6/matchmaker.h, src/condor_tests/test_starter_guidance.cpp
=> HTCONDOR-3211 coverity fixes

bindings/python/htcondor2/_collector.py, bindings/python/htcondor2/_schedd.py, docs/apis/python-bindings/api/version2/examples.rst, docs/man-pages/condor_qusers.rst, docs/version-history/v24-version.hist
=> (HTCONDOR-2911)  Document that locate() no longer works with slot names.

build/packaging/rpm/condor.spec
=> HTCONDOR-3196: Restore bash completions RPM dependency

docs/version-history/v24-version.hist, src/condor_tools/user_prio.cpp
=> HTCONDOR-3221 userprio without negotiator

src/condor_shadow.V6.1/baseshadow.cpp, src/condor_shadow.V6.1/baseshadow.h, src/condor_shadow.V6.1/pseudo_ops.cpp
This PR assumes that the server (shadow) side of the FTO always has/generates the same error message as the client side, and just runs through the same logic (currently split between starter and shadow) to invoke `improveReasonAttributes()` and handle the results.
=> (HTCONDOR-3161)  Report common files (almost) identically to input file errors.

docs/version-history/v24-version.hist, src/condor_procapi/procapi.cpp, src/condor_procapi/procapi.h, src/condor_procapi/procapi_killfamily.cpp, src/condor_startd.V6/claim.cpp, src/condor_startd.V6/claim.h
=> HTCONDOR-3224 Update MemoryUsage in STARTD more frequently on Windows

src/condor_schedd.V6/qmgmt.cpp, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-3229 Add count of owner claims and borrower claims to ocus in

src/condor_scripts/condor_upgrade_check
=> HTCONDOR-3209: Fix message issues in condor_upgrade_check

bindings/python/htcondor/personal.py, bindings/python/htcondor2/personal.py
=> HTCONDOR-3236 in htcondor personal, kill all daemons harder on shutdown

src/condor_shadow.V6.1/pseudo_ops.cpp
=> HTCONDOR-3237 fix shadow memory leak

src/condor_tests/test_fto_failure_propagation.py
=> HTCONDOR-3241 Robustify test_fto_failure_propagation test

docs/version-history/v23-version.hist, nmi_tools/glue/build/make-tarball-from-debs, nmi_tools/glue/build/make-tarball-from-rpms, nmi_tools/glue/build/make-tarball-links
=> HTCONDOR-3239: Normalize order of operations when making tarball

docs/version-history/v24-version.hist, src/condor_starter.V6.1/singularity.cpp
=> HTCONDOR-3243 starter nested scratch with singularity target dir bug

src/condor_scripts/condor_upgrade_check
=> HTCONDOR-3209: Add warning about v1 python API removal

src/condor_tests/test_singularity_sif.py
=> HTCONDOR-3243 Add test for singularity target dir

docs/version-history/v24-version.hist, src/condor_schedd.V6/schedd.cpp
=> HTCONDOR-3250 fix schedd keep claim idle crash

docs/automated-workflows/dagman-introduction.rst, docs/automated-workflows/dagman-reference.rst, docs/version-history/v25-version.hist, src/condor_dagman/dag.cpp, src/condor_dagman/node.cpp, src/condor_dagman/node.h, src/condor_dagman/script.cpp, src/condor_tests/test_dagman_script_macros.py
=> HTCONDOR-3245 dagman post script exit code list

src/condor_tests/CMakeLists.txt
=> HTCONDOR-3246 Disable test flakey on mac

src/condor_schedd.V6/schedd.cpp, src/condor_starter.V6.1/starter.cpp, src/condor_utils/condor_holdcodes.h
This ticket consolidates and updates the rules into one method for how the AP decides what to do when a job vacates an EP.
[See HTCONDOR-3251](https://opensciencegrid.atlassian.net/browse/HTCONDOR-3251)
=> HTCONDOR-3251 Use code+subcode and consolidate logic for hold-vs-vacate

src/condor_schedd.V6/dedicated_scheduler.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/scheduler.h
=> HTCONDOR-3247 hashtable upgrade

src/condor_tests/test_checkpoint_preen.py, src/condor_tests/test_fto_failure_propagation.py
=> HTCONDOR-3253 robustify test_fto_failure

src/condor_tests/test_drain_policies.py
Mb
We hope this will make the batlab happier when running many of these
=> HTCONDOR-3260 Lower WastedMemory in test_drain_policies from 650 to 150

src/condor_utils/submit_utils.cpp, src/condor_utils/test_transform_undo.cpp
=> HTCONDOR-3247 fix compiler warnings

docs/version-history/v25-version.hist, src/condor_starter.V6.1/singularity.cpp, src/condor_starter.V6.1/singularity.h
=> HTCONDOR-3265 correct set env vars for singularity with target_dir set

src/condor_tests/test_cgroup_oom.py
=> HTCONDOR-3275 add test

src/condor_scripts/annex/spark.fragment, src/condor_tools/htcondor_cli/annex_validate.py
A number of minor tweaks noticed by MattW.
=> (HTCONDOR-3277)  Update `htcondor annex`'s Spark support.

docs/admin-manual/configuration-macros.rst, docs/admin-manual/introduction-to-configuration.rst
=> HTCONDOR-3293 tokens docs

src/condor_daemon_client/daemon.cpp, src/condor_daemon_client/daemon.h, src/condor_daemon_client/dc_schedd.cpp, src/condor_daemon_client/dc_schedd.h, src/condor_daemon_core.V6/condor_daemon_core.h, src/condor_daemon_core.V6/daemon_core_main.cpp, src/condor_dagman/dagman_submit.cpp, src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/schedd_main.cpp, src/condor_schedd.V6/scheduler.h, src/condor_submit.V6/submit.cpp, src/condor_utils/condor_query.cpp, src/condor_utils/submit_utils.cpp, src/condor_utils/submit_utils.h, src/python-bindings/htcondor2/submit.cpp
=> HTCONDOR-3281 credd ad from schedd cherry pick

docs/version-history/v25-version.hist, src/condor_utils/docker-api.cpp
=> HTCONDOR-3280 Support docker uni jobs with non-default DOCKER_HOST env, such as for docker-in-docker

src/condor_daemon_client/daemon.cpp
=> HTCONDOR-3247 Fix warning about unused variable

src/condor_starter.V6.1/singularity.cpp
SINGULARITY_TEST_SANDBOX_TIMEOUT.
=> HTCONDOR-3307 the singularity startup exit_37 test should obey

src/condor_schedd.V6/schedd.cpp, src/condor_schedd.V6/scheduler.h
=> HTCONDOR-3312 Expire claimed/idle matches in the schedd

src/condor_scripts/condor_remote_cluster
Use new names for pre-release tarballs. Have curl follow redirects.
=> HTCONDOR-3316 bosco urls
